### ISSUE TITLE
multiple databases support

### ISSUE THREAD

**Issue by chriswep** [capacitor-community/sqlite#1]
As far as i see, the plugin only supports a single database, since it stores the database handle internally after opening the db. What about returning the handle and/or some kind of db instance with the query methods?

**Comment by jepiqueau** [comment]
@chriswep Look closely to the readme and the application provided as example ie https://github.com/jepiqueau/capacitor-apps/tree/master/IonicAngular/jeep-test-app and you will see that you can use multiple databases at once.  If the comment is to make query with join to multiple databases, you right so it is something that i could have a look at. Hope it's clarify

**Comment by chriswep** [comment]
@jepiqueau hmm, unless you mean that you can open a database, do a query, then open another db and do a query on that one, i don't see it. as far as i understand the README, opening a database does not return a handle or connection object but just sets the database internally. i can't see how multiple databases can be open at the same time this way

**Comment by jepiqueau** [comment]
@chriswep the databases are not open at the same time and you do not need it as the plugin open the db with the curent name before each command and close it after command completion. So i includes an example of how it works
``` 
  async testSQLitePluginMulti() {
    // Open First Database
    let result:any = await this._sqlite.open({database:"firstdb"});
    console.log("Open database : " + result.result.toString());
    let sqlcmd: string = `
    BEGIN TRANSACTION;
    CREATE TABLE IF NOT EXISTS users (
        id INTEGER PRIMARY KEY NOT NULL,
        email TEXT UNIQUE NOT NULL,
        name TEXT,
        age INTEGER
    );
    CREATE TABLE IF NOT EXISTS messages (
        id INTEGER PRIMARY KEY NOT NULL,
        title TEXT NOT NULL,
        body TEXT NOT NULL
    );
    PRAGMA user_version = 1;
    COMMIT TRANSACTION;
    `;
    var retExe: any = await this._sqlite.execute({statements:sqlcmd});
    console.log("retExe ",retExe)
    // Insert some Users
    sqlcmd = `
    BEGIN TRANSACTION;
    DELETE FROM users;
    INSERT INTO users (name,email,age) VALUES ("Whiteley","Whiteley;Bill.com",30);
    INSERT INTO users (name,email,age) VALUES ("Jones","Jones.com",44);
    COMMIT TRANSACTION;
    `;
    retExe = await this._sqlite.execute({statements:sqlcmd});
    // Select all Users
    sqlcmd = "SELECT * FROM users";
    var retSelect = await this._sqlite.query({statement:sqlcmd,values:[]});
    console.log('retSelect ',retSelect.values.length)
     for (let i:number =0; i< retSelect.values.length; i++) {
      console.log("results users: ",i,retSelect.values[i]);
    }
    // Open Second Database
    result = await this._sqlite.open({database:"seconddb"});
    console.log("Open database : " + result.result.toString());
    sqlcmd = `
    BEGIN TRANSACTION;
    CREATE TABLE IF NOT EXISTS contacts (
        id INTEGER PRIMARY KEY NOT NULL,
        email TEXT UNIQUE NOT NULL,
        name TEXT
    );
    PRAGMA user_version = 1;
    COMMIT TRANSACTION;
    `;
    var retExe: any = await this._sqlite.execute({statements:sqlcmd});
    // Insert some Contacts
    sqlcmd = `
    BEGIN TRANSACTION;
    DELETE FROM contacts;
    INSERT INTO contacts (name,email) VALUES ("Watson","Watson.com");
    INSERT INTO contacts (name,email) VALUES ("Churchill","Churchill.com");
    INSERT INTO contacts (name,email) VALUES ("Ferguson","Ferguson.com");
    COMMIT TRANSACTION;
    `;
    retExe = await this._sqlite.execute({statements:sqlcmd});
    // Select all Contact
    sqlcmd = "SELECT * FROM contacts";
    var retSelect = await this._sqlite.query({statement:sqlcmd,values:[]});
    console.log('retSelect ',retSelect.values.length)
     for (let i:number =0; i< retSelect.values.length; i++) {
      console.log("results contacts : ",i,retSelect.values[i]);
    }
    // Reopen the first store
    result = await this._sqlite.open({database:"firstdb"});
    // Insert a new User with SQL and Values
    sqlcmd = "INSERT INTO users (name,email,age) VALUES (?,?,?)";
    let values: Array<any>  = ["Simpson","Simpson@example.com",69];
    var retRun: any = await this._sqlite.run({statement:sqlcmd,values:values});
    // Select all Users
    sqlcmd = "SELECT * FROM users";
    var retSelect = await this._sqlite.query({statement:sqlcmd,values:[]});
    console.log('retSelect ',retSelect.values.length)
     for (let i:number =0; i< retSelect.values.length; i++) {
      console.log("results users: ",i,retSelect.values[i]);
    }
    // Insert some Messages
    const messages: Array<any> = [
      {title:"test post 1",content: "content test post 1"},
      {title:"test post 2",content: "content test post 2"}
    ]
    sqlcmd = `
    BEGIN TRANSACTION;
    DELETE FROM messages;
    INSERT INTO messages (title,body) VALUES ("${messages[0].title}","${messages[0].content}");
    INSERT INTO messages (title,body) VALUES ("${messages[1].title}","${messages[1].content}");
    COMMIT TRANSACTION;
    `;
    retExe = await this._sqlite.execute({statements:sqlcmd});
    // Select all Messages
    sqlcmd = "SELECT * FROM messages";
    var retSelect = await this._sqlite.query({statement:sqlcmd,values:[]});
    console.log('retSelect ',retSelect.values.length)
     for (let i:number =0; i< retSelect.values.length; i++) {
      console.log("results messages: ",i,retSelect.values[i]);
    }
    
  }

```
hope this clarify

**Comment by digaus** [comment]
@jepiqueau 
I think what @chriswep means is that it would be nicer if you would return a Typesricpt DB handle where you can call all other calls expect open.

-> 

 ```
    let db: CapDatabase = await this._sqlite.open({database:"firstdb"});
    let db2: CapDatabase = await this._sqlite.open({database:"seconddb"});
    db.execute(...)
    db2.execute(...)
    db2.query(...)
    db.query(...)
```
THis would make it nicer top work with.

**Comment by jepiqueau** [comment]
@digaus i understand your point and the one of @chriswep, but if you do that the plugin is just reduce to open a database and return a DB handle and that is it.

**Comment by digaus** [comment]
> @digaus i understand your point and the one of @chriswep, but if you do that the plugin is just reduce to open a database and return a DB handle and that is it.

Yes thats it but why is this bad? The functions would still be there but called with the DB handle?

**Comment by chriswep** [comment]
@jepiqueau @digaus maybe i'm missing something here, but isn't opening a sqlite database doing more than setting a pointer to a file in the underlying native sqlite implementation (like initialising indices, caches, metadata, etc.)? In most use cases those databases will need to be open at the same time, with a lot of parallel access going on. Even with no initialisation cost, this will likely fail due to parallelism - unless there is some kind of blocking mechanism in place (which in turn will slow everything down).

> if you do that the plugin is just reduce to open a database and return a DB handle and that is it.

again, maybe i'm missing something. but we still need all the db methods bridged to javascript on the handle (since we can't call the native methods). So we need a javascript db object/handle/connection that will allow us to do stuff with this db. Thats at least how the Cordova-sqlite plugin works.

**Comment by digaus** [comment]
> @jepiqueau @digaus maybe i'm missing something here, but isn't opening a sqlite database doing more than setting a pointer to a file in the underlying native sqlite implementation (like initialising indices, caches, metadata, etc.)? In most use cases those databases will need to be open at the same time, with a lot of parallel access going on. Even with no initialisation cost, this will likely fail due to parallelism - unless there is some kind of blocking mechanism in place (which in turn will slow everything down).
> 
> > if you do that the plugin is just reduce to open a database and return a DB handle and that is it.
> 
> again, maybe i'm missing something. but we still need all the db methods bridged to javascript on the handle (since we can't call the native methods). So we need a javascript db object/handle/connection that will allow us to do stuff with this db. Thats at least how the Cordova-sqlite plugin works.

At least for electron it should work by default:

https://github.com/kriasoft/node-sqlite#opening-multiple-databases

**Comment by jepiqueau** [comment]
@chriswep @digaus We could discuss this for ever. I didn't intent to replicate what  the Cordova plugin is doing. People can still work with the Cordova plugin as far as i know. To stay on the safe side, i decided to have only one database open at a time and even more the database is opened and closed after each sql statement execution completion. So you can have an application accessing multiple databases but only one after an other to avoid the parallelism issues and the complexity of blocking mechanism.

**Comment by chriswep** [comment]
>  i decided to have only one database open at a time and even more the database is opened and closed after each sql statement execution completion.

thanks for the clarification!

**Comment by chriswep** [comment]
@jepiqueau seeing this now is the kind of "official" sqlite community capacitor plugin i want to reopen this discussion to avoid potentially creating a second plugin for mostly the same purpose. i'm currently still using the Cordova plugin in capacitor however i want to get rid of it at some time.

I looked into the code a bit and it seems to me that this plugin indeed creates a new connection for each request/query/transaction. Can someone shed some light on the performance overhead for this? And apart from performance this also doesn't seem to be how a database (and also the underlying sqlite implementations) are supposed to work? 

If we want to use multiple databases there comes the issue of parallelism into play. If i see it correctly the plugin currently saves the database name and options in its internal state. So we would need to use `open` and `close` before and after each call to `execute` on this plugin. And if i don't overlook something this still wouldn't make 100% sure that parallel queries go to the correct database (or break another running operation) since they all operate on the same global `CapacitorSQLPlugin` object and its state.

I suggest to refactor this to return some kind of db-handle object when opening a database. I suppose this would involve separating some methods into a new class that handles the connection/db-handle in its state. Opening a database would then return an instance to this class. This way apps could have multiple database handles open that can be safely used in parallel. Also the plugin wouldn't need to open and close the database for each query/transaction.

For backwards compatibility, an instance of this db-handle class could be used internally by the plugin on default and only returned requested specifically.

**Comment by jepiqueau** [comment]
@chriswep I understand now that if we want to make ORM support with typeorm which seems to have the consensus of the community, we need  to have the db connection available and so the multiple support of databases. This requires a complete refactoring of the plugin which is quite a task but feasible. Would you be kind and some others to participate to this refactoring but before to start refactoring it would be better to have a complete specification of the refactoring process, would you like to write it as with your expertise in using the cordova plugin you know precisely what to do. You didn't convince me few months ago but since i got the request of ORM support i understood you were right. Tell me what are your thoughts

**Comment by chriswep** [comment]
if one of the goals is to have a TypeORM driver at the end we could start from there. There is already an abstract sqlite driver in TypeORM that all sqlite-based drivers extend: https://github.com/typeorm/typeorm/tree/master/src/driver/sqlite-abstract. It might make sense to take the Cordova driver as a template for a capacitor driver: https://github.com/typeorm/typeorm/tree/master/src/driver/cordova

For this to work the capacitor plugin needs to have some kind of `openDatabase` method that returns a connection object with the query method(s) and a close method.

If the latter is done, implementing the typeorm-driver is basically duplicating an existing sqlite driver and making a few minor modifications. As far as i see, TypeORM uses a single query method (which expects query and parameters). The other sqlite pass this to a single driver-method and look if the query starts with `INSERT` to determine what to return (insertId, array of rows, etc.). In a similar way the capacitor plugin can use its different query methods run/query/execute.

**Comment by jepiqueau** [comment]
@chriswep i start looking at this for Android but i didn't find a way to return a  kind of db-handle object from a createConnection method.
so what i could may be do is something like this
```
await this.sqlite.createConnection({database: "testNew", encrypted: false,
                                   mode: "no-encryption", version: 1});
await this.sqlite.open({database: "testNew"});
await this.sqlite.execute({database: "testNew", statements: statements});
await this.sqlite.runSQL({database: "testNew", statement: statement, values: values});
await this.sqlite.createConnection({database: "testEncrypted", encrypted: true,
                                   mode: "secret", version: 1});
await this.sqlite.open({database: "testEncrypted"});
await this.sqlite.execute({database: "testEncrypted", statements: statements});
await this.sqlite.selectSQL({database: "testNew", statement: statement, values: values});
await this.sqlite.runSQL({database: "testNew", statement: statement, values: values});
await this.sqlite.runSQL({database: "testEncrypted", statement: statement, values: values});
...
``` 
in the plugin, a dictionary handling the pair dbName, dbHandler

this will allow for multiple database connections
so the connection will be done once and not anymore for each request/execute/query/transaction
i am making the test in using `androidx.sqlite.db.xxx` so hopefully get less problems with database parallelism
What do you think about this or do you have any idea on passing kind of db-handle object, will you be ready to test a preliminary release on Android

**Comment by chriswep** [comment]
i'm not familiar enough with the system sqlite on android to speak into the db-handle issue. in the end it just comes down to what you save in the internal state to identify/access the correct database. if android-sqlite does not have db-handles and you just pass the same dbName to requests (i.e. it manages the open databases internally) then you just keep track of string. 

I think it would be a nice touch if the plugin would do some abstraction and return an instance like this after connecting:
```typescript
export interface ISQLiteDatabaseConnection {
    runSQL(statement: string, values?: any[]) => Promise<ISQLiteResult>;
}

class SQLiteDatabaseConnection implements ISQLiteDatabaseConnection {
    constructor(private dbName: string; private sqlite: SQLiteDriver) {}
    runSQL(statement: string, values?: any[]) {
        return this.sqlite({ database: this.dbName, statement, values});
    }
}

class CapacitorSQLite {
    createConnection({dbName, ...) {
         await this.sqlite.createConnection(...);
         return new SQLiteDatabaseConnection(dbName, this.sqlite);
    }
}
```

Then you could do:
```typescript
const db = await CapacitorSQLite.createConnection({ dbName: 'test', ...})
const response = await db.runSQL('SELECT ...');
```

**Comment by jepiqueau** [comment]
@chriswep 
```
const db = await CapacitorSQLite.createConnection({ dbName: 'test', ...})
const response = await db.runSQL('SELECT ...');
``` 
this is what i was trying to do and test but it doesn't work . i asked the question to the `capacitor team` of how `to pass a Native Object pointer to the typescript code` but i did not get the answer yet.

**Comment by jepiqueau** [comment]
@chriswep I will see if i can implement what you suggest in a `typescript wrapper service` to the `CapacitorSQLite plugin`

**Comment by jepiqueau** [comment]
@chriswep i have created a wrapper plugin for Angular that way (see below) and it is working well. Do you thing that will answer your request? 
so i create a class `sqliteConnection.ts`
```
export abstract class ISQLiteConnection {
    abstract open(): Promise<any>;
    abstract close(): Promise<any>;
    abstract execute(statements: string): Promise<any>;
}
export class SQLiteConnection implements ISQLiteConnection {
    constructor(private dbName:string, private sqlite:any) {}
    async open(): Promise<any> {
        const res: any = await this.sqlite.open(
                                            {database: this.dbName});
        return res;
    }
    async close(): Promise<any> {
        const res: any = await this.sqlite.close(
                                            {database: this.dbName});
        return res;
    }
    async execute(statements: string): Promise<any> {
        const res: any = await this.sqlite.execute(
                                            {database: this.dbName,
                                             statements: statements});
        return res;
    }
    // TODO other commands to run, query, ...
}
```

i then create a service `sqlite.service.ts`

```
import { Injectable } from '@angular/core';
import { SQLiteConnection } from './/sqliteConnection';

import { Plugins, Capacitor } from '@capacitor/core';
import 'capacitor-plugin-sqlite';
const { CapacitorSQLite } = Plugins;

@Injectable({
    providedIn: 'root'
})

export class SQLiteService {
    handlerPermissions: any;
    sqlite: any;
    isService: boolean = false;
    platform: string;

    constructor() {
    }
      /**
   * Plugin Initialization
   */
    initializePlugin(): Promise<boolean> {
        return new Promise (resolve => {
            this.platform = Capacitor.platform;
            console.log("*** platform " + this.platform)
            this.sqlite = CapacitorSQLite;
            if(this.platform === "android") {
                this.handlerPermissions = this.sqlite.addListener(
                    'androidPermissionsRequest', async (data:any) => { 
                    if (data.permissionGranted === 1) {
                      resolve(true);
                    } else {
                      console.log("Permission not granted");
                      resolve(false);
                    }      
                });
                try {
                    this.sqlite.requestPermissions();
                } catch (e) {
                    console.log("Error requesting permissions " + JSON.stringify(e));
                    resolve(false);
                }
            } else {
                resolve(true);
            }
        });
    }
    async echo(value: string): Promise<any> {
        return await this.sqlite.echo({value: value});
    }
    async createConnection(database:string, encrypted: boolean,
                           mode: string,
                           version: number): Promise<SQLiteConnection> {
        const res: any = await this.sqlite.createConnection({
                                database, encrypted, mode, version});
        if (res.result) {
            return new SQLiteConnection(database,this.sqlite);
        } else {
            return null
        }
    }
    async closeConnection(database:string): Promise<any> {
        return await this.sqlite.createConnection({database});
    }
}

```
and now call the service from a component 

```
import { Component, AfterViewInit } from '@angular/core';
import { SQLiteService } from '../services/sqlite.service';

@Component({
  selector: 'app-home',
  templateUrl: 'home.page.html',
  styleUrls: ['home.page.scss'],
})
export class HomePage implements AfterViewInit {
  sqlite: any;
  platform: string;
  handlerPermissions: any;
  initPlugin: boolean = false;

  constructor(private _sqlite: SQLiteService) {}

  async ngAfterViewInit() {
    // Initialize the CapacitorSQLite plugin
    this.initPlugin = await this._sqlite.initializePlugin();
    const result: boolean = await this.runTest();
    if(result) {
      console.log("$$$ runTest was successful");
    } else {
      console.log("$$$ runTest failed");
    }
  }


  async runTest(): Promise<boolean> {
    let result: any = await this._sqlite.echo("Hello World");
    console.log(" from Echo " + result.value);
    // initialize the connection
    const db = await this._sqlite
                .createConnection("testNew", false, "no-encryption", 1);
    let retB: any = await db.open();
    if (!retB.result) {
      return false;
    }
    // create tables
    const statements: string = `
    CREATE TABLE IF NOT EXISTS users (
        id INTEGER PRIMARY KEY NOT NULL,
        email TEXT UNIQUE NOT NULL,
        name TEXT,
        company TEXT,
        size FLOAT,
        age INTEGER,
        last_modified INTEGER DEFAULT (strftime('%s', 'now'))
    );
    CREATE INDEX IF NOT EXISTS users_index_name ON users (name);
    CREATE INDEX IF NOT EXISTS users_index_last_modified ON users (last_modified);
    CREATE TRIGGER IF NOT EXISTS users_trigger_last_modified
    AFTER UPDATE ON users
    FOR EACH ROW WHEN NEW.last_modified <= OLD.last_modified
    BEGIN
        UPDATE users SET last_modified= (strftime('%s', 'now')) WHERE id=OLD.id;
    END;
    PRAGMA user_version = 1;
    `;    
    retB = await db.execute(statements);
    if (retB.changes < 0) {
      return false;
    }
    retB = await this._sqlite.closeConnection("testNew"); 
    if(!retB.result) {
      return false; 
    } else {
      return true;
    }

  }
}
```

**Comment by jepiqueau** [comment]
@chriswep , @digaus I have published a first alpha release of the refactor `npm i @capacitor-community/sqlite@refactor` which basically do what @chriswep has described. It is only developed for Android platform and doesn't contain all the methods. But i think is enough for understanding the principle. i also published a Ionic/angular app demonstrating the use of the new plugin ` https://github.com/jepiqueau/angular-sqlite-app-refactor` If you could have a look and comment

**Comment by chriswep** [comment]
thanks @jepiqueau for pushing this forward. i wonder if `SQLiteConnection` is part of the plugin interface or if the user has to implement it themselves? if possible i think it would make sense to have that included in / returned from the plugin directly. don't know however how flexible you are with Capacitor plugins on the javascript side.

**Comment by jepiqueau** [comment]
@chriswep `SQLiteConnection` and `SQLiteDBConnection` are part of the javascript side of the plugin

```
import { Plugins, Capacitor } from '@capacitor/core';
import '@capacitor-community/sqlite';
import { SQLiteDBConnection, SQLiteConnection } from '@capacitor-community/sqlite';
const { CapacitorSQLite } = Plugins;
...
const sqlitePlugin: any = CapacitorSQLite;
this.sqlite = new SQLiteConnection(sqlitePlugin);
...
const db: SQLiteDBConnection = await this.sqlite.createConnection(
                                "testDB", true, "secret", 1);
...
    // open db testNew
    ret = await db.open();
    if (!ret.result) {
      return false;
    }

    // create tables in db
    ret = await db.execute(createSchema);
    if (ret.changes.changes < 0) {
      return false;
    }
    // add one user with statement and values              
    let sqlcmd: string = 
                "INSERT INTO users (name,email,age) VALUES (?,?,?)";
    let values: Array<any>  = ["Simpson","Simpson@example.com",69];
    ret = await db.run(sqlcmd,values);
    console.log()
    if(ret.changes.lastId !== 1) {
      return false;
    }
    // add one user with statement              
    sqlcmd = `INSERT INTO users (name,email,age) VALUES ` + 
                              `("Brown","Brown@example.com",15)`;
    ret = await db.run(sqlcmd);
    if(ret.changes.lastId !== 2) {
      return false;
    }
    // select all users in db
    ret = await db.query("SELECT * FROM users;");
    if(ret.values.length !== 2 || ret.values[0].name !== "Simpson" ||
                                  ret.values[1].name !== "Brown") {
...
```
Voilà, that simple as you requested

**Comment by jepiqueau** [comment]
@chriswep , @digaus  The refactor process is now ended with the new release 2.9.0-beta.1 of the plugin. if you could have a look and revert to me .  It has been a quite heavy process, but all the tests pass. you could see the usage in a Ionic/Angular app `https://github.com/jepiqueau/angular-sqlite-app-refactor` Hope you will find what you were looking for. After testing, you could close the issue.

**Comment by jepiqueau** [comment]
@chriswep as you did not comment i close the issue which is solved by the refactor.

**Comment by chriswep** [comment]
thanks @jepiqueau - i'll get back to this when i tackle the migration form cordova-sqlite

**Comment by jepiqueau** [comment]
thanks @chriswep
