### ISSUE TITLE
how to update any table or add new column and update in live mobile app without uninstall the app?

### ISSUE THREAD

**Issue by deepakjsr7979** [capacitor-community/sqlite#100]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jepiqueau** [comment]
@deepakjsr7979 Look at `addUpgradeStatement` and `https://github.com/capacitor-community/sqlite/blob/master/docs/UpgradeDatabaseVersion.md`

**Comment by jepiqueau** [comment]
@deepakjsr7979 Did you find your way. if yes could you please close the issue
