### ISSUE TITLE
specify database path to save sqlite into shared data containers (ios)

### ISSUE THREAD

**Issue by SBejga** [capacitor-community/sqlite#103]
First of all, thanks for this capacitor community project!

**Is your feature request related to a problem? Please describe.**
I am considering to split a big Ionic Cordova app into two smaller Ionic Apps and want to upgrade to capacitor as well.
The problem with two apps, they should share some data. I think about sharing a sqlite database. 

**Describe the solution you'd like**
In iOS sharing data between apps is not easy because of the sandbox environment. But as far as I understand reading the docs, there are application groups. And apps within an application group can share data. See https://developer.apple.com/documentation/foundation/filemanager/1412643-containerurl

With Android this should be easier, but I did not found the information if the current path of the sqlite is private.

I would suggest to make database folder path configurable, where to store the database.

**Additional context**
This feature is maybe interesting for other users, so I want to discuss this as a feature request. 
I will also try to contribute some code.

**Comment by jepiqueau** [comment]
@SBejga Hi, thanks for looking at using the plugin. This request is far too complex to achieve and will not keep the plugin simple and maintainable. The developers need something simple, easy to use and maintainable and respecting the device environment and rules. I will then decline this request. You are free to clone the plugin and develop the code you need for your own use.

**Comment by jepiqueau** [comment]
@SBejga i close this issue
