### ISSUE TITLE
reload of webview breaks connection handling

### ISSUE THREAD

**Issue by chriswep** [capacitor-community/sqlite#106]
If the webview of Capacitor is reloaded (e.g. via dev-server), the plugins looses its internal connection dict/state. `isConnection` returns `false` however `createConnection` fails because the connection still exists on the native side.

I suggest to not handle any state on the JS-side of the plugin (or alternatively to check native connection state on web-startup).

**Comment by jepiqueau** [comment]
@chriswep hi Chris, Which version of the plugin are you using 2.9.x or 3.0.0 ? Looking at this which i never thought about it, may be the best solution is to provide a command to delete all Native Connection as we need to keep the connection object on the JS-side. So the connections could be re-created from scratch.

**Comment by chriswep** [comment]
i'm using 3.0.0-beta-9, currently developing a typeORM plugin. yes, that's my current workaround to delete a connection before creating it. Its a hack though, since i have no way to determine if a connection exists on native or not (i.e. try .. catch .. ignore).

I could imagine that this could bite a lot of people, esp. while developing. `closeAllNativeConnections` could help - i would suggest to state in the README that this is needed during development if using a dev-server with reloading. I think a cleaner approach would be to take care that native state is pushed to js on startup. if i'm correct its "just" a list of db-names?

**Comment by chriswep** [comment]
This is addressed in https://github.com/capacitor-community/sqlite/commit/91cadf53e3a7e0cba01a911e3ca9b1a3eb39e2f6 - i found it difficult to wrap my head around the new `checkConnectionsConsistency` method, so here is my solution for reference. It might be useful for the README:

If using a dev-server with auto-reload, this should be executed before attempting any connections:
```
CapacitorSQLite.checkConnectionsConsistency({
     dbNames: [],
}).catch((e) => console.log(e));
```

If i understand correctly, this tells the native side: "i expect no connections to be open". The plugin then closes all open connections as specified. It throws an error though. @jepiqueau i would suggest to rather return a status from the method since the closing of connections is specified and intended behaviour, not an error.

**Comment by kurthybela** [comment]
Hi Chriswep,
where should i cann the closeAllNativeConnections or callthe checkConnectionsConsistency method? CheckConnectionsConsistency throws an error for me if i call it before creating or retrieving the connection.
thanks,
