### ISSUE TITLE
inconsistent db-name suffix handling between `copyFromAssets` and `createConnection`

### ISSUE THREAD

**Issue by chriswep** [capacitor-community/sqlite#107]
`copyFromAssets` removes an existing `.db` suffix and appends `SQLite.db`, `createConnection` appends it without removing the existing suffix:

```
// public/assets/databases/content.db
copyFromAssets(): contentSQLite.db
createConnection('content.db',..): content.dbSQLite.db
```

Apart from that, if i try to add the suffix myself, `copyFromAssets` then leaves it like that, `createConnection` appends a duplicate suffix.

I don't understand the need for the suffix, since it makes things hard for the developer (e.g. i also need access to the files outside of this plugin and having to transform strings in a certain way doesn't feel solid.) So my suggestion would be to only use the filenames provided by the user. If that is not desired, all methods should handle this consistently (i suggest adding ".SQLite" before the ".db").

i'm using 3.0.0-beta-9 and the connection wrapper.

**Comment by jepiqueau** [comment]
@chriswep Even if i understand your point, this one will be difficult to change for compatibility reason. When you use the `createConnection` method you just have to give the database name without extension. ie  `createConnection('content',..)` and it will work fine.

**Comment by chriswep** [comment]
ok, so the only valid way is to preload the files without "SQLite" but with ".db" in the name and set the database name without ".db". I can confirm that this works.

I suggest to document this more clearly. Probably it also wouldn't hurt to duplicate the name transformation from `copyFromAssets` to `createConnection` if the user provides a name that ends on ".db" (which was the intuitive way for me, esp. when preloading dis). It shouldn't break existing setups (and if, it can be document on the major release).
