### ISSUE TITLE
DATETIME strings are converted to numbers

### ISSUE THREAD

**Issue by chriswep** [capacitor-community/sqlite#108]
currently (3.0.0-beta-9) DATETIME strings are converted to numbers by the plugin. I assume this is due to the sqlite-affinities stated here: https://www.sqlite.org/datatype3.html. However SQLite affinities are different from data types. The same document also states that it is perfectly fine (and intended) to store DATETIME as strings. Concerning type conversion it states: 

> To "apply affinity" means to convert an operand to a particular storage class if and only if the conversion does not lose essential information. Numeric values can always be converted into TEXT. TEXT values can be converted into numeric values if the text content is a well-formed integer or real literal

In more concrete terms: `getColumnValue` in `UtilsSQLCipher` needs to look at the value as well, not only the column type. Otherwise it breaks a lot of applications with perfectly valid databases.

**Comment by jepiqueau** [comment]
@chriswep Thanks for the comment, i will have a look.

**Comment by jepiqueau** [comment]
@chriswep the plugin implement the types as described in `https://www.sqlite.org/datatype3.html`

**Comment by chriswep** [comment]
yes and no - did you have a look at the paragraph about type conversion? Datetime columns have a number affinity however that does not mean that they should be converted to numbers. Its is part of the specification that they can contain date time strings. A number conversion should only be done if the string contains "a well-formed integer or real literal".

**Comment by jepiqueau** [comment]
@chriswep The types tested and consistent with the plugin iOS, Android and Electron are only the five described in the sqlite documentation NULL, TEXT, REAL, BLOB, INTEGER.  In the first implementation of the iOS plugin, i coded the `getColumnValue` in the `UtilsSQLCipher` like you see it but i never test it and not implemented it in the Android and Electron part of the plugin neither in the `importFromJson` or `exportToJSON`. This part of the code should have been removed from the iOS plugin. If i look now at the cordova plugin it is not implemented either. By using only the five types you can define yourself if you want the date to be TEXT or INTEGER. As the documentation provided was not clear on this, i will clarify this.

**Comment by chriswep** [comment]
I'm not sure how to understand your updates in beta-10 (esp. README) concerning column types. The five types you mention are storage classes in SQLite not column types. Maybe you intended to use the five type affinities, which don't include `NULL` but `NUMERIC`. Those can be column types in SQLite, however they are not "the column types of SQLite", since all kinds of column types are accepted. In addition, SQLite allows all types of data to be inserted into each column - only doing non destructive conversions (like `"1"` > `1` or `1` => `1.0`, but not `"1 car"` => `1`). I would suggest the plugin shouldn't add a complexity on top of the default SQLite behaviour that makes it incompatible with both existing databases and application logic. In other words, i think the plugin should not transform data, at least not in a way that is incompatible with SQLite itself.

I assume the "restriction" of column types (and kind of data that can live there) is supposed to reduce complexity. However i think the plugin does not need to "support" column types at all but rather rely on the internal SQLite magic for that. Adding "supported" column types and doing special operations on them actually adds unnecessary complexity in my opinion. For me it is a core use case for the plugin to return the correct data out of the database and not do non-SQLite transformations. 

Maybe we agree on this anyway, since you mentioned to remove the iOS code related to `getColumnType` and `getColumnValue` - as far as i can see the android code works as expected. However i think the new additions to the README are misleading then.

**Comment by jepiqueau** [comment]
@chriswep When i will have a bit more time i will have a look what i could do following your lines
