### ISSUE TITLE
NULL values are returned as string

### ISSUE THREAD

**Issue by chriswep** [capacitor-community/sqlite#109]
Currently (3.0.0-beta-9) `NULL` values in the DB are returned as `"NULL"` (the string). They need to be returned as JS `null`. Among other reasons the current behaviour would prevent saving the string "NULL" to the database, even if one tried to work around this on the receiving end. I tried a quick change in `UtilsSQLCipher.swift` and changed `"NULL"` to `nil` in `getColumnValue` and that seemed to work well.

**Comment by jepiqueau** [comment]
@chriswep The "NULL" in `getColumnValue` is required for the importFromJson and exportToJson methods to work

**Comment by chriswep** [comment]
i haven't used (or looked at) the json import/export features. However returning the string "NULL" for null values is breaking core SQLite (or database in general) functionality, so i'd suggest refactoring to the json features to work with "real" null values?

**Comment by jepiqueau** [comment]
@chriswep solve in 3.0.0-beta.11
