### ISSUE TITLE
add an option to disable transactions for `run` and `execute`

### ISSUE THREAD

**Issue by chriswep** [capacitor-community/sqlite#111]
i couldn't use the `run` and `execute` methods in the TypeORM plugin since TypeORM manages transactions itself. I could make it work somehow by pushing everything through the `query` method however as far as i see i can't get `insertId` and `changes` values through that. and it may break other things?

So would it be possible to use those methods without transactions? Possibly by parameter or by dedicated methods.

**Comment by jepiqueau** [comment]
@chriswep this one i will have a look at it, i will add a parameter in the execute and run commands. this request has a value for all developers using the sqlite cordova plugin who will desire to migrate to the capacitor plugin.

**Comment by jepiqueau** [comment]
@chriswep to resume, i will provide fixes for issue #106, #107 and #111  and only for release 3.0.x of the plugin, hope you will understand

**Comment by jepiqueau** [comment]
@chriswep the fixes are available in release 3.0.0-beta.10 of the plugin. you can also look at `https://github.com/jepiqueau/angular-sqlite-app-starter` i added a test for issues #106,#107,#111. Hope this will help you for the TypeORM plugin.

**Comment by chriswep** [comment]
thanks @jepiqueau 

i tried it out and found the following bugs:

1) `transaction` is forced to true in those lines, effectively disabling the feature:
- https://github.com/capacitor-community/sqlite/blob/master/src/definitions.ts#L973
- https://github.com/capacitor-community/sqlite/blob/master/src/definitions.ts#L1010 

2) dateTypes are still treated as `SQLITE_FLOAT` here: https://github.com/capacitor-community/sqlite/blob/master/ios/Plugin/Utils/UtilsSQLCipher.swift#L486 - if the check is removed it works. I'm not sure if this is intended or if you consider this a bug. I'll write a more detailed comment in the corresponding ticket.

**Comment by jepiqueau** [comment]
@chriswep 
1. transaction is force to true if not given, so all the developers codes will still work. but if you enter false, it will run without transaction  see `https://github.com/jepiqueau/angular-sqlite-app-starter/blob/master/src/app/testissue111/testissue111.page.ts` lines 81, 95, ...
2. in sqlite3.h it is SQLITE_FLOAT with a value of 2 and not SQLITE_REAL. this is the reason i used SQLITE_FLOAT

**Comment by chriswep** [comment]
1. with `const trans = transaction ? transaction : true;` `trans` will always be truthy. What you want is `const trans = typeof transaction !== 'undefined' ? transaction : true;`. However i suppose a better style would be to provide a default value in the method definition. To make matters complete: In cases like this i name the variable such that `undefined` is equivalent to `false` to avoid this (e.g. `withoutTransaction`)
2. the issue here is not float or real, but that no (lossy) data conversion should happen here. I don't want to repeat the discussion started in #108, so we can go into more detail there if needed. In short: If a conversion is done, it needs to depend on the column value as well. Thats why in SQLite it's called type _affinity_. A quick fix would be to just remove the check for `dateTypes` in `getColumnType`, which then falls back to `sqlite3_column_type(stmt, index)` which should return the correct type for the data in the column.

**Comment by jepiqueau** [comment]
@chriswep solve in 3.0.0-beta.11. Hope you will now give me a break
