### ISSUE TITLE
Event Listeners for Import and Export Json

### ISSUE THREAD

**Issue by doctorstones** [capacitor-community/sqlite#112]
I'm currently developing an app with about 300.000 rows distribuited across 10-12 tables.
I've tried to import data downloading an huge json file and then calling the "import json" function.

This awesome plugin parses perfectly, but obviously a similar amount of data requires some time to be parsed: it requires between 2-5 minutes before the function returns the result.

I dont' think that the plugin could be more fast: it already uses transactions and so on. Perhaps it might be useful to report the status of current import, like the table that is currently importing or the successfully imported table, so that we can provide the user with a message updated in real time.

A solution could be the use of event listeners like described in https://capacitorjs.com/docs/plugins/android in the class ImportFromJson.java (at row 310 - I'm referring to android cause I'm only using it at the time of writing).

It's just my opinion and I don't know if it can be useful or there are technical issues that it hasn't been taken into account for.
if I can be useful, for the android part (the only one I can get my hands on) I could try to deepen and write the code

**Comment by jepiqueau** [comment]
@doctorstones Thanks for using the plugin , i never thought about using a so huge json file and i am pleased that it is working, i will have a look on finding a solution working for Android, iOS and Electron. Anyway if i found something it will only be available on release 3.+ of the plugin. Have you already done the move ?.

**Comment by jepiqueau** [comment]
@doctorstones Thanks for your proposal. Event listeners for import and export json have been implemented in release 3.0.0-beta.12. It would be nice if you can test it but you have first to move to capacitor3. You can have a look at `https://github.com/jepiqueau/angular-sqlite-app-starter` to help you for the move. The listeners have been implemented in the `testtypes.page.ts`.

**Comment by doctorstones** [comment]
@jepiqueau thank you so much for your commitment and work. I'm currently using capacitor 2 because v3 is still in beta, but I'm going to switch within a few weeks. I will try shortly and let you know, consider that I use ionic react and not angular.

**Comment by jepiqueau** [comment]
@doctorstones ok i will have a look to update `sqlite-react-hook` accordingly

**Comment by jepiqueau** [comment]
@doctorstones 
- `react-sqlite-hook` has been updated release `react-sqlite-hook 2.0.1` 
- a `testListeners` component has been added to demonstrate the use of listeners in `react-sqlite-app-starter@3.0.0-beta.1`
- using the @capacitor/toast like i did to notify the user, is certainly not the right way as there is no dismiss method and the `short` duration is too long especially in Android so the process is ended before all the toasts have been displayed. I use it just for quick test. Would be better to use a React Modal Component cumulating the messages received by the listeners

**Comment by jepiqueau** [comment]
@doctorstones 
- `modalJsonMessages` component has been added to `react-sqlite-app-starter@3.0.0-beta.2` and replace the toasts displayed
- `vue-sqlite-hook` has now been updated release `vue-sqlite-hook 2.0.1`
- `https://github.com/jepiqueau/vue-sqlite-app-starter 3.0.0-beta.1` has been updated by adding the following components  `JsonListenersTest` & `ModalJsonMessages`.

I will close the issue now, feel free to reopen it after your tests if required
