### ISSUE TITLE
ImportFromJson in Partial Mode without schema changes

### ISSUE THREAD

**Issue by doctorstones** [capacitor-community/sqlite#113]
In version 2.9.16, in the "importFromJson" method in Database.java (row 552) is mandatory to add a Schema Change before one can apply changes to data. 
But if I've launched a partial sync, I should be enabled to add only datas to tables, without importing also the schema.
In the code this is made not possible by the `if(changes!=- 1)` row, which should first verify if I'm importing in FULL or PARTIAL mode.

> public JSObject importFromJson(JsonSQLite jsonSQL) {
        Log.d(TAG, "importFromJson:  ");
        JSObject retObj = new JSObject();
        int changes = Integer.valueOf(-1);
        try {
            // create the database schema
            changes = fromJson.createDatabaseSchema(this, jsonSQL);
            if (changes != -1) {
                changes = fromJson.createDatabaseData(this, jsonSQL);
            }
        } catch (Exception e) {
            Log.e(TAG, "Error: importFromJson " + e.getMessage());
            changes = -1;
        } finally {
            retObj.put("changes", changes);
            return retObj;
        }
    }

In the code above, I expect to verify the type of Sync and then launch the schema and/OR data creation.
In Android, Line 559 of Database.java shoud be changed into `if (changes != -1 || jsonSQL.getMode().equals("partial") ) {`

I've found another bug in ImportFromJson.java at row 441. The code `.append(row.get(0))` doesn't control the type of the column, resulting in an update error when the ID of the column is a TEXT and not an INTEGER (es: `UPDATE table1 WHERE ID = HELLO`).
Instead, It should consider the type like the method "isIdExists" in UtilsJson.java (at rows 52/53).

**Comment by jepiqueau** [comment]
@doctorstones Thanks for this, i will have a look. I am putting all my workload on the 3.0.0 release right now.May be i will fix it in the 3.0.0 release.

**Comment by jepiqueau** [comment]
@doctorstones This has been fixed in @capacitor-community/sqlite@3.0.0-beta.13

**Comment by doctorstones** [comment]
@jepiqueau thank you for your fast reply. Do you Plan to fix this also in the older version? I'm asking just for knowledge

**Comment by jepiqueau** [comment]
@doctorstones Except if it takes too long to Ionic Capacitor team to release Capacitor 3. All my workload is now dedicated to move my 4 plugins to Capacitor 3 which is a huge challenge and take a lot more of my time that foreseen. Hope you will understand and thanks you to pointing me out these two bugs. If you find some others feel free to tell me. For me the 2.9.x which brought a big change in the sqlite plugin interface was just temporary waiting already for the Capacitor3.
