### ISSUE TITLE
no db returned is null

### ISSUE THREAD

**Issue by parthnayak7448** [capacitor-community/sqlite#114]
ionic 5 capacitor giving me this error

**Comment by jepiqueau** [comment]
@parthnayak7448 you have to give a bit more description to your issue. Which version of the plugin are you using? which platform? Did you look at the documentation and application starter `https://github.com/jepiqueau/angular-sqlite-app-starter`

**Comment by parthnayak7448** [comment]
Hey @jepiqueau 

Thanks for quick response just to update I resolve this issue. 

I will close the issue.
