### ISSUE TITLE
No clear way to store JSON in a column

### ISSUE THREAD

**Issue by micheal-w-wells** [capacitor-community/sqlite#115]
There are obviously many use cases where a dev would like to store JSON in a text column in sqlite.  I personally was not able to get it to work any way other than this:

`        ret = await db.execute('insert into ' + tablename + " (json) values ('" + escape(JSON.stringify(upsertConfig.json)) + "' );");`

This is less than ideal because to write and read the dev needs to stringify + escape and then visa versa which doesn't scale well for a lot of big json objects.

There's no way to tell from the docs if there's a better way to do it where the library assists with JSON other than the 'create db from json' examples which are not applicable.

Is there a better way to do it using the tool - or is what I posted above the only option?

**Comment by jepiqueau** [comment]
@micheal-w-wells Thanks for using the plugin. The json object should be converted in a string and store in a TEXT column. I do not understand what the escape function is doing.  So
``` 
ret = await db.execute('insert into ' + tablename + " (json) values ('" + JSON.stringify(upsertConfig.json) + "' );");
```
should work

**Comment by micheal-w-wells** [comment]
thanks @jepiqueau - I was using escape() and unescape() to deal with some of the data having single quotes.  I've tried the sqlite 'quote()' call without success.
