### ISSUE TITLE
How to use in ionic serve. 

### ISSUE THREAD

**Issue by parthnayak7448** [capacitor-community/sqlite#116]
**Describe the bug**
Is there any solutions to run the plugin in ionic serve. 

All the time now I have to test my changes in actual device which is time consuming. 

Codorva plugin was working fine in web too. 

Thanks is advance.

**Comment by jepiqueau** [comment]
@parthnayak7448 There is no web plugin implementation. In 2.9.x there is an electron implementation for this plugin . In 3.0.0-beta.x, the Electron implementation has not yet been converted.

**Comment by muuvmuuv** [comment]
Any plans for a web version?

**Comment by jepiqueau** [comment]
@muuvmuuv @parthnayak7448  this is done ` npm i --save @capcitor-community/sqlite@web` it will become latest when @capacitor/core@3.1.3 will be released

**Comment by jepiqueau** [comment]
@muuvmuuv @parthnayak7448  you need @capacitor/core@3.1.2.

**Comment by muuvmuuv** [comment]
@jepiqueau maybe this can improve the web version a lot just found it https://jlongster.com/future-sql-web

**Comment by jepiqueau** [comment]
@muuvmuuv thanks for this I will have a look
