### ISSUE TITLE
Unable to access JSON1 extension

### ISSUE THREAD

**Issue by micheal-w-wells** [capacitor-community/sqlite#117]
Hi!

I'm getting a 'not authorized' error when I try to load the json1 extension - which I see you compiled in.  Can you share how to use it?

EDIT:  If you can help point me in the right direction to add enabling it (or other extensions) to the tool (if thats not already possible) I MIGHT be able to help with a PR if i get it working

**Comment by jepiqueau** [comment]
@micheal-w-wells hi thanks for using the plug-in I do not know what do you mean by json1 extension. This plug-in has no extension may be you mix with the cordova plug-in . Json objects should be stringified with JSON.stringify (json) to be stored in a TEXT field

**Comment by micheal-w-wells** [comment]
Hi @jepiqueau , I'm talking about this:  https://sqlite.org/json1.html

You've got the flags set as far as I can tell for loadable extensions & this one in particular (json1) set here:  

https://github.com/capacitor-community/sqlite/blob/a1dcf544e8840d97f752de2580e0d4f2ccb16275/ios/Plugin.xcodeproj/project.pbxproj#L596

That gets sqlite compiled to allow for them - but there's a few other things that have to happen in order for loadable extensions to be enabled.  https://sqlite.org/c3ref/load_extension.html

The plugin is great so far - but there's LOADS of great use cases for json extensions, even if just accessed via db.execute / db.query.

**Comment by micheal-w-wells** [comment]
I'm going to take a second look at this weekend and see if i can figure it out.

**Comment by jepiqueau** [comment]
@micheal-w-wells ok take your time but put a clear spec and some example to help testing as I do not know anything about spatialite. Thanks in advance

**Comment by patdx** [comment]
@micheal-w-wells for your information, I am testing with `@capacitor-community/sqlite` version 3.1.3-3 on an iOS device.

It seems like the iOS version of the library used SQLCipher fork, [version 4.4.0+](https://github.com/capacitor-community/sqlite/blob/master/ios/Podfile#L17)

Which may already have [JSON support on by default (?)](https://www.zetetic.net/blog/2016/4/5/sqlcipher-340-release/)

In any case, I tried using [`json()` function and `json_array()`](https://www.sqlite.org/json1.html#jmini) function and it seemed to be parsing them and return results correctly:

![image](https://user-images.githubusercontent.com/353863/128846006-92a49a8b-f364-418c-b502-25a079ac3944.png)

**Comment by jepiqueau** [comment]
@patdx @micheal-w-wells can you please send me some examples of what you want to achieve with the Json1 extension so I can have of look on it and try

**Comment by jepiqueau** [comment]
@micheal-w-wells Can you give me the schema of the database where you store these json objects. Are you creating that table with standard sql queries. For the web i am using `sql.js` so i am not sure that the JSON1 extension is supported

**Comment by jepiqueau** [comment]
@micheal-w-wells Is it just a json object in memory and you use sql queries to get info from it or update it?

**Comment by jepiqueau** [comment]
@micheal-w-wells @patdx  i have done this
``` 
export const createSchema: string = `
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY NOT NULL,
    name TEXT,
    phone TEXT,
    last_modified INTEGER DEFAULT (strftime('%s', 'now'))
);
CREATE INDEX IF NOT EXISTS users_index_name ON users (name);
CREATE INDEX IF NOT EXISTS users_index_last_modified ON users (last_modified);
CREATE TRIGGER IF NOT EXISTS users_trigger_last_modified
AFTER UPDATE ON users
FOR EACH ROW WHEN NEW.last_modified <= OLD.last_modified
BEGIN
    UPDATE users SET last_modified= (strftime('%s', 'now')) WHERE id=OLD.id;
END;
PRAGMA user_version = 1;
`;    
export const twoUsers: string = `
INSERT INTO users (name,phone) VALUES ("Jones",json('{"cell":"+34712345678", "home":"+34498765432"}'));
INSERT INTO users (name,phone) VALUES ("Jeep",json('{"cell":"+33912345678", "home":"+33598765432"}'));
`;
```
and this in a angular page component
```
import { Component, AfterViewInit } from '@angular/core';
import { SQLiteService } from '../services/sqlite.service';
import { DetailService } from '../services/detail.service';

import { createSchema, twoUsers} from '../utils/test-json1-utils';
import { deleteDatabase } from '../utils/db-utils';
import { Dialog } from '@capacitor/dialog';
import { SQLiteDBConnection } from '@capacitor-community/sqlite';

@Component({
  selector: 'app-testjson1extension',
  templateUrl: 'testjson1extension.page.html',
  styleUrls: ['testjson1extension.page.scss']
})
export class TestJson1ExtensionPage implements AfterViewInit {
  detail: boolean = false;
  sqlite: any;
  platform: string;
  handlerPermissions: any;
  initPlugin: boolean = false;
  importListener: any;
  exportListener: any;

  constructor(private _sqlite: SQLiteService,
              private _detailService: DetailService) {}

  async ngAfterViewInit() {
    const showAlert = async (message: string) => {
      await Dialog.alert({
      title: 'Error Dialog',
      message: message,
      });
    };
    try {
      await this.runTest();
      document.querySelector('.sql-allsuccess').classList
      .remove('display');
      console.log("$$$ runTest was successful");
    } catch (err) {
      document.querySelector('.sql-allfailure').classList
      .remove('display');
      console.log(`$$$ runTest failed ${err.message}`);
      await showAlert(err.message);
    }
  }


  async runTest(): Promise<void> {
    try {
      let result: any = await this._sqlite.echo("Hello World");

       // initialize the connection
      let db: SQLiteDBConnection;
      if((await this._sqlite.isConnection("testJSON1.db")).result) {
        db = await this._sqlite.retrieveConnection("testJSON1");
      } else 
        db = await this._sqlite
                  .createConnection("testJSON1", false, "no-encryption", 1);
      // check if the databases exist 
      // and delete it for multiple successive tests
      await deleteDatabase(db);

      // open db testNew
      await db.open();

      // create tables in db
      let ret: any = await db.execute(createSchema,false);
      if (ret.changes.changes < 0) {
        return Promise.reject(new Error("Execute createSchema failed"));
      }

      // create synchronization table 
      ret = await db.createSyncTable();
      
      // set the synchronization date
      const syncDate: string = "2020-11-25T08:30:25.000Z";
      await db.setSyncDate(syncDate);

      // add first teachers in db
      ret = await db.execute(twoUsers);
      if (ret.changes.changes !== 2) {
        return Promise.reject(new Error("Execute 2 users failed"));
      }
      // select all users in db
      ret = await db.query("SELECT * FROM users;");
      if(ret.values.length !== 2 || ret.values[0].name !== "Jones" ||
                                    ret.values[1].name !== "Jeep") {
        return Promise.reject(new Error("Query 1 users failed"));
      }
      // select all users cell phone in db
      ret = await db.query("SELECT json_extract(users.phone, '$.cell') FROM users;");
      console.log(`ret.values ${JSON.stringify(ret.values)}`);
      console.log(`ret.values[0]  ${ret.values[0]["json_extract(users.phone, '$.cell')"]}}`);
      console.log(`ret.values[1]  ${ret.values[1]["json_extract(users.phone, '$.cell')"]}`);

      result = await this._sqlite.isConnection("testJSON1");
      if(result.result) {
        // close the connection testJSON1
        await this._sqlite.closeConnection("testJSON1");      
      }
    
      return Promise.resolve();
    } catch (err) {
      return Promise.reject(err);
    }
  }

}
```
and it works on iOS but i am surprised by the way to get the value
``` 
      console.log(`ret.values[0]  ${ret.values[0]["json_extract(users.phone, '$.cell')"]}}`);
```
i would have think from the doc 
```
ret.values[0].cell
```
Any ideas?

**Comment by jepiqueau** [comment]
@micheal-w-wells @patdx works also on Android

**Comment by jepiqueau** [comment]
@micheal-w-wells @patdx see `https://github.com/jepiqueau/angular-sqlite-app-starter` it works finr for iOs, Android and Web

**Comment by micheal-w-wells** [comment]
You're awesome dude, I'd say you can close this one.

**Comment by jepiqueau** [comment]
You are welcome

**Comment by jepiqueau** [comment]
You are welcome
