### ISSUE TITLE
Add some examples to docs

### ISSUE THREAD

**Issue by zim32** [capacitor-community/sqlite#118]
**Is your feature request related to a problem? Please describe.**
The problem is that it is very hard to get started and figure out how to use this plugin

**Describe the solution you'd like**
Provide some basic quick start examples hot to import plugin, connect to database and execute some simple staements.
I read examples for Vue and Angular, but it is hard to understand. 

And what is API_Connection_Wrapper_Documentation and API_DB_Connection_Wrapper_Documentation? 
Hot to use it and when?

**Comment by zim32** [comment]
F.e. in angular demo there is code

`this.sqlite = new SQLiteConnection(sqlitePlugin);`

But there is no SQLiteConnection interface in API documentation

**Comment by jepiqueau** [comment]
@zim32 thanks for looking at using the plug-in if you look at the Readme you have some links to starter apps 
- https://github.com/jepiqueau/angular-sqlite-app-starter
- https://github.com/jepiqueau/react-sqlite-app-starter
- https://github.com/jepiqueau/vue-sqlite-app-starter
There are also links to the API documentation

**Comment by jepiqueau** [comment]
@zim32 https://github.com/capacitor-community/sqlite/blob/2.9.x/docs/APIConnection.md

**Comment by jepiqueau** [comment]
@zim32 if you just start looking at the plug-in you should look at the 3.0.0-beta release which will become soon the official release. Everything you need to start is fully documented

**Comment by jepiqueau** [comment]
@zim32 Did you find your way. if yes can you close the issue
