### ISSUE TITLE
JS float numbers are rejected in run statements (iOS)

### ISSUE THREAD

**Issue by chriswep** [capacitor-community/sqlite#121]
Adding float values in a `run` statement from JS causes an error on iOS. Debugging the issue with Xcode showed those values end up as `Double` type on the native side. In https://github.com/capacitor-community/sqlite/blob/master/ios/Plugin/CapacitorSQLite.swift#L305 only `Float` is checked for. Adding an additional check for `Double` does fix the issue.

**Comment by jepiqueau** [comment]
@chriswep PR merged in release 3.0.0-beta.14. Thanks for your help
