### ISSUE TITLE
Error: "CapacitorSQLite.isSecretStored()" is not implemented on android

### ISSUE THREAD

**Issue by gabrielcursino** [capacitor-community/sqlite#123]
Hello!

I am trying to upgrade to Capacitor 3.0, but i am having problems with sqlite plugin

Some of my code:

```typescript
const isSecretStored = await this.sqlite?.isSecretStored();

if (!isSecretStored?.result) {
  await this.sqlite?.setEncryptionSecret(btoa(Math.random().toString()));
}

this.db = await this.sqlite?.createConnection(this.dbName, true, 'secret', version);

await this.db?.open();
```

If i run this code i get the error:

**Error: "CapacitorSQLite.isSecretStored()" is not implemented on android**

If i comment isSecretStored verification and setEncryptionSecret directly i get the error:

**Error: SetEncryptionSecret: State for: ion_financesSQLite.db not correct**

My GlobalSQLite.java (according to upgrade 3.0 process flow):

```java
package com.getcapacitor.community.database.sqlite.SQLite;

public class GlobalSQLite {
    public String secret = "";
}
```

the code was running perfectly on version 2.9.16.

Thanks for the plugin!

**Comment by jepiqueau** [comment]
@gabrielcursino Hi thanks for using the plugin. Which Framework are you using ? i assume it should be React or Vue. If it is the case, sorry i forgot to update the `react-sqlite-hook` and the `vue-sqlite-hook`. Normally with Angular it should work. You should set 
```
public class GlobalSQLite {
    public String secret = "";
}
```
only when you have successfully run `setEncryptionSecret` as it will re-encrypt the database using the secret in GlobalSQLite to open the encrypted database and the new secret given in `setEncryptionSecret`

**Comment by jepiqueau** [comment]
@gabrielcursino Sorry i was not awake this morning. Yes they have been implemented in `react-sqlite-hook` and the `vue-sqlite-hook`. So i do not understand. Which version of the plugin are you using? When you update your app to Capacitor 3 did you remove the android folder and run
```
npx cap add android
npm run build
npx cap sync
npm run build
npx cap copy
npx cap open android
```
Check also that the gradle is Version 7.0 otherwise upgrade it.

**Comment by gabrielcursino** [comment]
I am using Ionic Vue.

With version 2.9.16, i didn't use `vue-sqlite-hook`, but it worked perfectly.

With version 3.0.0-beta.14, i tested with `vue-sqlite-hook@2.0.2`, but persists the same errors

My Gradle version is **7.0.2**

And my Android Gradle Plugin Version is **4.2.1**

**Comment by jepiqueau** [comment]
@gabrielcursino Hi, thanks for your contribution and patience. This is fixed in the release `3.0.0-rc.1` of the plugin

**Comment by jepiqueau** [comment]
@gabrielcursino i also update `https://github.com/jepiqueau/vue-sqlite-app-starter.git`

**Comment by gabrielcursino** [comment]
Thank you! This is working fine now!

I am having some other problems, but it not related, i will open another issue

**Comment by jepiqueau** [comment]
Ok so I will close the issue
