### ISSUE TITLE
Double precision type numbers are read as floats

### ISSUE THREAD

**Issue by filpet95** [capacitor-community/sqlite#124]
**Describe the bug**
Double precision type numbers are read as floats.
According to SQLite documentation, REAL values are stored as an 8-byte IEEE floating point number.

**To Reproduce**

1. Create a table containing REAL column
2. Save a value which can be represented as a double precision value but not a float precision (e.g. 1015555132.0 )
3. Value is saved successfully as 8-byte IEEE floating point number
4. Select the row containing the value. Seems to return a float representation. In our example the returned value is 1015555136.

**Expected behavior**
Expected to return the double point precision value

**Desktop (please complete the following information):**

- OS: Tested on Android

**Additional context**
Found one potential place in the code where the error may occur (in android). 
SQLite/Database.java row 456:
row.put(colName, c.getFloat(c.getColumnIndex(colName)));
change to
row.put(colName, c.getDouble(c.getColumnIndex(colName)));

**Comment by jepiqueau** [comment]
@filpet95 Thanks for using the plugin, it seems that you are right, so i will fix it in the next release

**Comment by jepiqueau** [comment]
@filpet95 this is fixed in 3.0.0-rc.2 so I close the issue
