### ISSUE TITLE
Wrong values on insert and query

### ISSUE THREAD

**Issue by gabrielcursino** [capacitor-community/sqlite#125]
1- Can't insert null or undefined as foreign key, Error: Run: error code 19: FOREIGN KEY constraint failed

2- Sometimes query null values returns '...'

- OS: Android

**Comment by gabrielcursino** [comment]
Seems to be related to #120

**Comment by jepiqueau** [comment]
@gabrielcursino I do not understand your point 1. Can you share your table's schema and some data what is the purpose of having the foreign key null as it is a relationship between two tables.
For the point 2 i also need a case as i thought i solved it already

**Comment by gabrielcursino** [comment]
1-

For example:

```sql
...
wallet_id INTEGER,
...
FOREIGN KEY (wallet_id) REFERENCES wallet(id)
```

If i send `null` or `undefined`, occurs the error: `Error: Run: error code 19: FOREIGN KEY constraint failed`

2-

```
description TEXT,
units INTEGER,
```

if i insert `null` or `undefined` on fields that accept null like these above, sometimes select query returns me literal `"..."`

I didn't change the schema, with plugin version 2.9.16 these were working fine

**Comment by jepiqueau** [comment]
@gabrielcursino for 1- can you share the two table's shemas where you make the relationship with FOREIGN Key. I do not think i will make modifications as for me it is a non-sense. If it is not clearing explain the reason for it.
2- I will have a deeper look in it. 
I will be away (traveling) from the next 3 weeks having limited Internet access so keep an eye if there is a new release.

**Comment by gabrielcursino** [comment]
Please, check my test repository: https://github.com/gabrielcursino/capacitor-sqlite-test.

In this case, i need to insert a finance row without a wallet relationship, i tried with `null` or `undefined`, but it is not working as described on point 1.

I can't replicate point 2, i will check my official project to try to replicate on this repository

**Comment by jepiqueau** [comment]
@gabrielcursino I will have a look keep the test repsitory for a while as I am travelling and not sure when I can look at it. I will tell you when it will be solved

**Comment by gabrielcursino** [comment]
Ok, thanks!

**Comment by gabrielcursino** [comment]
I checked my project better, and the two problems are occuring only with `null`, `undefined` was accepted as foreign key and i didn't cause `...`

**Comment by jepiqueau** [comment]
@gabrielcursino remove the four null and insert into finance only the amount and it will work I would have to see the reason but it seems that the getArray () from capacitor is the problem it takes one null and after it return "..."

**Comment by parthnayak7448** [comment]
same problem in android null values are return as '...'

**Comment by jepiqueau** [comment]
@gabrielcursino @parthnayak7448 this is fix in 3.0.0 tell me if it is solved for you

**Comment by chriswep** [comment]
@jepiqueau i was researching this bug just now and i found (and reported) the bug in capacitor: https://github.com/ionic-team/capacitor/issues/4798 - may i kindly suggest to reconsider the fix you introduced here? changing `null` to `undefined` might work for some cases (didn't test) however it introduces potential new side effects.

**Comment by jepiqueau** [comment]
@chriswep it is a temporary fix in waiting that the ionic capacitor team came with a JSArray working with a set of null value. I am glad that you report it to them. I tried to do it from my phone last week as i was travelling  but it was rejected as i did not provide a case.

**Comment by chriswep** [comment]
@jepiqueau hm ok, it might work since you are only converting array values and `JSON.stringify` seems to convert `undefined` to `null` in arrays. however this is different for objects where it would remove `undefined` properties. so i agree that it should be only temporary. 

i assume you didn't leave the `console.log` lines there intentionally? might be good to remove them for the release.

**Comment by jepiqueau** [comment]
@chriswep yes you right I will have to do it I published an app showing the issue to @jcesarmobile hope it will fix this quickly
