### ISSUE TITLE
Capacitor 3.0.0  registerPlugin(CapacitorSQLite.class); fails

### ISSUE THREAD

**Issue by MonicaExplan** [capacitor-community/sqlite#126]
**Describe the bug**
registerPlugin(CapacitorSQLite.class); fails in Android MainActivity.java with Capacitor 3.0.0

**To Reproduce**
1. In My Android Studio project I sync the project with gradles files and I can see the package and the class CapacitorSQLite.class in com.getcapacitor.community.database.sqlite
2. import com.getcapacitor.community.database.sqlite.CapacitorSQLite;  in MainActivity.jva

I don't install vue-sqlite-hook cause I have senne example working without this installation

When I build the project I get this:
error: incompatible types: Class<CapacitorSQLite> cannot be converted to Class<? extends Plugin>
      registerPlugin(CapacitorSQLite.class); 

What I'm doing wrong?

Thanks
Monica

**Comment by jepiqueau** [comment]
@MonicaExplan normally in 3.0.0 you do not need to do anything but you have to remove the à droid and iOS from Tha app and add them again with npx cap add.check that the gradle has been updated to 7.0 if not do it in Android studio hope this clarify

**Comment by MonicaExplan** [comment]
@jepiqueau  thanks. It semmes to work fine. ALso other plugin like barcode scanner.
Now in Androis Studio I see my db but closed :-(
Why, if I don't close it?

My Vue code in App.Vue in setup()

onBeforeMount(async () => {
      try {
        const sqlite = new SQLiteConnection(CapacitorSQLite);
        // {"database":"plangei-consumer","encrypted":1,"mode":false,"version":"no-encryption"}
        const db = await sqlite.createConnection(
          "plangei-consumer",
          false,
          "no-encryption",
          1
        );
        const opened = await db.open();
        alert("db open = " , opened)
        database.value = db;

        console.log("database opened", db);
        databaseInitialized.value = true;
      } catch (e) {
        alert("Error Initializing the Database");
      }
    });

**Comment by jepiqueau** [comment]
@MonicaExplan the database exists but you cannot open it in Android Studio. Go to the device emulator and under the database folder of your application you will see the database. Save as to one folder of your PC or Mac. I use the app DBbrowser which is free to open it and look at schemas and data

**Comment by MonicaExplan** [comment]
Thanks a lot for suggestion. I partially solved without sharing database folder. 
While the app is running Db in Database Inspector is closed. When the app is stopped I can access the db in Database Inspector.

**Comment by jepiqueau** [comment]
@MonicaExplan ok thanks for the feedback good luck
