### ISSUE TITLE
On 2.9.x, add ability to use Library folder on iOS for addSQLiteSuffix

### ISSUE THREAD

**Issue by mtb3** [capacitor-community/sqlite#127]
I'm using version 2.9.x of the plugin and need to migrate / add the SQLite suffix to a DB that lives within the `Library/LocalDatabase` directory on iOS.

I noticed that the 3.x / master branch does appear to have this capability which came in this commit:

https://github.com/capacitor-community/sqlite/commit/0705e21241b91bf2c58e85f2d39afb600d7539a8#diff-b6db6d7e3708dbaf60f3ebbcef1f53db295f296f96680da334f64a3388df1677

Would it be feasible to port back this change to the 2.9.x branch?

**Comment by jepiqueau** [comment]
@mtb3 thanks for using the plug-in I apologize but I am not maintaining the 2.9.x concentrating on the move to 3. It is still in beta as I haven't transfer yet the electron part of the plug-in but the iOS and Android parts are in final state except for potential issues find by the developers that I will fix. Hope this clarify

**Comment by mtb3** [comment]
@jepiqueau Thank you for the input / response. I am considering moving to 3.x right away / very soon and will be exploring that direction.

If I decide to back-port the change myself to the 2.9x branch... then I may have a PR up... but I understand the focus on 3.x at this point.
