### ISSUE TITLE
Unable to use sqlite after refreshing the web view

### ISSUE THREAD

**Issue by Exocomp** [capacitor-community/sqlite#128]
**Describe the bug**
Unable to use sqlite after refreshing the web view.

**To Reproduce**

1. Using a capacitor 3.0 application the initial load everything functions correctly
2. On refresh of the webview I see inconsistent behavior with SQLiteConnection.

- Function isConnection returns false
- Function createConnection throws 'Connection sqlite-dbname already exists'.
- Function retrieveConnection throws 'Connection sqlite-dbname does not exist' 

As a result of this I'm not able to use sqlite after refreshing the web view.

**Expected behavior**
On refresh of the web view SQLiteConnection functions should be consistent.

**Smartphone (please complete the following information):**

- Device: iPhone7+
- OS: iOS v14.6
- Capacitor v3.0.0
- capacitor-community / sqlite v3.0.0-rc.1

**Comment by chriswep** [comment]
@Exocomp see this issue: https://github.com/capacitor-community/sqlite/issues/106

**Comment by Exocomp** [comment]
@chriswep thanks calling `CapacitorSQLite.checkConnectionsConsistency` prior to creating a new connection helped.

If that is the intended way to use it, putting it in the docs would be helpful so I'll leave it up to the developer to chime in and handle it as necessary.

Thanks again!

**Comment by jepiqueau** [comment]
@Exocomp you have to use
Const ret = await checkConnectionConsistency ()
If ret is false you have to reopen your connection (s) if ret is true you do not need to reopen the connection. Hope this clarify
