### ISSUE TITLE
Data is being reset after the app gets restarted (iOS, v3.0.0-rc.1)

### ISSUE THREAD

**Issue by lovetodream** [capacitor-community/sqlite#130]
**Describe the bug**
I've switched from https://github.com/storesafe/cordova-sqlite-storage to this plugin and the database was successfully migrated. But after closing the app (iOS) the data which was inserted and also able to query in the previous session is gone and I am back to the state I had before migrating. 
It seemed like the database would be migrated and overwritten again, but that can't be possible because it got deleted after the migration.
The logs aren't showing any errors.
Do I need to close the connection to the database to write the new data to the persistent file?
Maybe I am doing something wrong, the plugin is really hard to start with as mentioned in #118 

I am using version 3.0.0-rc.1 of this plugin.

**To Reproduce**

1. Open connection to database
2. Execute a few inserts
3. Close the app
4. Reopen and see, that the data is gone again

**Expected behavior**
The data should be persistent.

**Screenshots**

**Desktop (please complete the following information):**

- OS: macOS
- Browser -
- Version 11.4

**Smartphone (please complete the following information):**

- Device: iPhone XS & iPhone 12 mini
- OS: iOS
- Browser -
- Version 14.6

**Additional context**

**Comment by jepiqueau** [comment]
@lovetodream thanks for using the plug-in .you have to do the migration once and check that you can access the database an modify it when done you have to delete the databases as there are not automatically deleted.

**Comment by jepiqueau** [comment]
@lovetodream use the deleteOldDatabases method after having checked that the new databases with the SQLITE suffix have been created. After this your app will worked friendly. If not you can come back to me. I am currently travelling so I cannot answer easily but I will try to do so.

**Comment by lovetodream** [comment]
Ok, I had a look through my code and I just forgot to put the path into the `deleteOldDatabases` call. It works like a charm now. Thank you very much for the plugin and your help, I really appreciate it.
