### ISSUE TITLE
Upgrade statements not working

### ISSUE THREAD

**Issue by tfuetterer** [capacitor-community/sqlite#136]
**Describe the bug**
Hi,

I try to use the migration method addUpgradeStatement but I cant get this to work. I dont know if it is a bug or if I am only unable to correctly use the framework =)

I use the following Code to create the db and everything works fine: 

`if (!existingConn.existConn) {
      const db = await sqlite.createConnection(
        databaseName,
        false,
        "no-encryption",
        2
      );
      await db.open();

      await db.execute(create_v1);

      existingConn.setExistConn(true);

      return db;`

Then I add the upgrade statement as follows: 

`
if (!existingConn.existConn) {
      console.log("create upgrade statement");
      sqlite.addUpgradeStatement({
        database: databaseName,
        upgrade: [
          {
            fromVersion: 1,
            toVersion: 2,
            statement: create_v2,
            set: [],
          },
        ],
      });
      console.log("created upgrade statement");
      const db = await sqlite.createConnection(
        databaseName,
        false,
        "no-encryption",
        2
      );
      await db.open();

      await db.execute(create_v1);

      existingConn.setExistConn(true);

      return db;`

And the I get the error: Cannot read property 'fromVersion' of undefined.

![image](https://user-images.githubusercontent.com/16266856/122451653-b26ee700-cfa8-11eb-8532-f8a563af138a.png)

This confuses me a bit because I specified the fromVersion.

Another question is: Can I also add a upgrade statement from no db to version 1? So that I can manage the schema changes only through upgrade statements, as it is for example in Entity Framework. I cant find anything about that in the upgrade documentation. Maybe the documentation is not up to date because it uses the function openDB with I assume is createConnection, because I cant find anything about openDB and the parameters might match the createConnection method.

**Smartphone (please complete the following information):**

- Device: Samsung S20
- OS: Android

**Comment by jepiqueau** [comment]
@tfuetterer thanks for using the plug-in.  Yes the doc has to be updated. OpenDB has to be replaced by create connection. The process is demonstrated in the angular-sqlite-app-starter on the testupgradeversion component.
When you have created your version 1 and would like to upgrade to version 2, make sure to close the connection to version 1, create the upgrade statement with addUpgradeStatement (...) and then create a new connection on the version 2 it is at that time that the upgrade statement is used. And then do whatever with the version 2. Hope this clarify. No you cannot use upgradeStatement from no db to create version 1

**Comment by tfuetterer** [comment]
@jepiqueau Thank you for your quick response. Sorry I didn't see that, but now I get an idea of the process.

Now my idea was to build a function that gives me the connection, so I can use it all aroud the app. As from now I would think it will look like this:

`let db = await sqlite.createConnection(
        databaseName,
        false,
        "no-encryption",
        1
      );

      await db.open();

      await db.execute(create_v1);

      await db.close();

      await sqlite.closeConnection(databaseName);

      console.log("create upgrade statement");
      sqlite.addUpgradeStatement({
        database: databaseName,
        upgrade: [
          {
            fromVersion: 1,
            toVersion: 2,
            statement: create_v2,
            set: [],
          },
        ],
      });
      console.log("created upgrade statement");
      db = await sqlite.createConnection(
        databaseName,
        false,
        "no-encryption",
        2
      );
      await db.open();

      existingConn.setExistConn(true);

      return db;`

Do I need to do this process every time I want to get a connection, because that sounds like a lot of overhead, because in most cases, the database is on the latest version. Or do I manually need to track, on which version the database is and then upgrade it depending on the current version. What is, if the database is already on version 2 and I create the connection with version 1, as I would do in my example? I think Im still getting something wrong on that =)

Kind regards
Tobias

**Comment by jepiqueau** [comment]
@tfuetterer sqlite.upgradeSatet3ment (databaseName,1,2,create_v2, [])

**Comment by tfuetterer** [comment]
Thanks for the help again. With the react plugin this does not work. What works is:
`await sqlite.addUpgradeStatement(databaseName, {
        fromVersion: 2,
        toVersion: 3,
        statement: create_v3,
      });`

Just for reference if anybody else runs into the same issue.

Now I use the following code:

`let db = await sqlite.createConnection(
        databaseName,
        false,
        "no-encryption",
        1
      );

      await db.open();

      await db.execute(create_v1);

      await db.close();

      await sqlite.closeConnection(databaseName);

      console.log("create upgrade statement");
      await sqlite.addUpgradeStatement(databaseName, {
        fromVersion: 1,
        toVersion: 2,
        statement: create_v2,
      });
      await sqlite.addUpgradeStatement(databaseName, {
        fromVersion: 2,
        toVersion: 3,
        statement: create_v3,
      });
      console.log("created upgrade statement");
      db = await sqlite.createConnection(
        databaseName,
        false,
        "no-encryption",
        3
      );
      await db.open();

      existingConn.setExistConn(true);

      return db;`

I would assume that by doing this, if the database is not there at the start, it would get created with version 1 and then upgraded to version 2 and then to version 3. But I get the following error:

![image](https://user-images.githubusercontent.com/16266856/122561168-d2061e00-d041-11eb-861d-a62a34eedbab.png)

I think this is a total common scenario if the app grew over time with multiple upgrades and the app gets newly installed. Maybe I dont understand the concept, that you are using for migrations/upgrades. Im comming from .Net Entity Framework and maybe the idea of your upgrade process is completely different, so that I get things wrong.

Thanks in advance in hope of patience on your side with me ;)

**Comment by jepiqueau** [comment]
@tfuetter hi again you cannot have two addUpgradeStatement in a row without createConnection in between. It is the createConnection which is doing the upgrade and it can upgrade only from one version to a new one. I didn't know which framework you were using

**Comment by jepiqueau** [comment]
@tfuetterer you can look at react-sqlite-app-starter for React hope this clarify the process

**Comment by jepiqueau** [comment]
@tfuetterer any news, did it works?

**Comment by tfuetterer** [comment]
I figured out, that I need to track the current database version and which upgrade to execute by myself. lets say I am on version 2, but the latest version is 4, then I need to detect that and execute upgrade 3 and 4. It would be nice, if there was a solution, that would do that for me. for example I specify a list of upgrade statements an then just say that I want to upgrade to version x on connection creation and the framework would detect the current database version and which upgrade statements need to be executed. by now I do that myself and it perfectly works. thanks for your help!!

**Comment by jepiqueau** [comment]
@tfuetterer You may write a clear specification on what you would like the plugin to do. The plugin has been wriiten to work always on the latest version not intermediate ones. So for me if you are in version 4 you cannot work anymore on version 2 as the schemas and table data are overwritten.

**Comment by jepiqueau** [comment]
@tfuetterer I will let you close the issue

**Comment by tfuetterer** [comment]
Ok unfortunatly it doesnt work perfectly =) I deleted the database file for testing purposes and restart the app again and I get the following error:
![image](https://user-images.githubusercontent.com/16266856/122924271-e1e57100-d365-11eb-98ef-27dc74591310.png)

This createConnection worked perfectly fine when I first ran it. And as you see in the console, the sqlite object is not null as the error states.

Do you have any idea, what the error could come from? This is the code:

![image](https://user-images.githubusercontent.com/16266856/122924566-34bf2880-d366-11eb-8f5c-c5cecd8e60b7.png)

the sqlite object is not null and there is no database file, as it would be the case, when the user first installs the app. The database name is also set.

**Comment by tfuetterer** [comment]
> @tfuetterer You may write a clear specification on what you would like the plugin to do. The plugin has been wriiten to work always on the latest version not intermediate ones. So for me if you are in version 4 you cannot work anymore on version 2 as the schemas and table data are overwritten.

I think you get me wrong. I dont want to work on intermediate versions of the database. But lets say a user has installed the app and is on version 1. No I release an update that has database upgrades, now I want the user to get these upgrades from his current database version to the latest. and that might be a couple if the user did not update the app for a while

**Comment by tfuetterer** [comment]
And as I found out now, even if I delete the database on the device, uninstall the app and reinstall it, the createConnection methode seems to regenerate the database file with the data, that was in it before I deleted it. But also throws the error, from the second last post.

**Comment by tfuetterer** [comment]
When I delete unsinstall the app, rename the database and reinstall the app, I would expect, that a new db file with the new database name would be generated. but what happen instead is, that again the error occurs and a db file wit the old name and the data before the deletion is generated. Do you know why that happens? this is the console log:

![image](https://user-images.githubusercontent.com/16266856/122992983-0ada2600-d3a7-11eb-8a84-e644bb2ca790.png)

I would expect a file called databasenewSQLite.db gets generated, but instead I get a databaseSQLite.db with the old data.

**Comment by tfuetterer** [comment]
Now I deleted all data from within the android settings on the device and if I rerun the app the new db file gets generated and the error is gone. I thought, that uninstalling the app should also delete all data =) but as it seems it doesnt. So this might be a caching problem caused by android and I think deleting the db via the android studio device file exporer is not a good thing to do =) 

so I think there is no issue on your side and I will close this issue here. thank you for your support and your work for the community!

**Comment by jepiqueau** [comment]
@tfuetterer I am glad that you find the solution it seems the Android cache is causing some issues as someone else mentioned that this morning on an other issue. When I am back I will have a deeper look. Thanks again for using the plugin
