### ISSUE TITLE
Cannot install sqlite via CLI - Can't resolve dependency

### ISSUE THREAD

**Issue by rgbaman** [capacitor-community/sqlite#139]
When trying to install `@capacitor-community/sqlite` via the CLI, it throws an error saying the dependency cannot be resolved.

```
While resolving: MyApp@0.0.1
Found: @capacitor/core@3.0.0
node_modules/@capacitor/core
  @capacitor/core@"3.0.0" from the root project

Could not resolve dependency:
peer @capacitor/core@"^2.4.7" from @capacitor-community/sqlite@2.9.16
node_modules/@capacitor-community/sqlite
  @capacitor-community/sqlite@"*" from the root project

Fix the upstream dependency conflict, or retry
this command with --force, or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.
```

**To Reproduce**

1. Open an Ionic application
2. Navigate to your terminal and run `npm install @capacitor-community/sqlite`
3. Error outputs in terminal window

**Expected behavior**
SQLite node to install successfully.

**Environment:**

- Local machine (macOS).

**Additional context**
I could run `--force` which does install it but I'm concerned about breaking changes.

**Comment by jepiqueau** [comment]
@rgbaman you have to install the next version of the plug-in which is compatible with capacitor 3

**Comment by jepiqueau** [comment]
@rgbaman npm install --save @capacitor-community/sqlite@next as shown in the readme
