### ISSUE TITLE
Encrypted database with TypeORM

### ISSUE THREAD

**Issue by rkreutzer** [capacitor-community/sqlite#140]
Is there a way to use database encryption with the TypeORM driver?

The driver has the no-encryption statement hardcoded in the createConnection process. Is this because of a technical limitation?

**Comment by jepiqueau** [comment]
@rkreutzer @chriswep Chris can you answer that one

**Comment by chriswep** [comment]
@rkreutzer there is no technical limitation. you can easily make a PR at the TypeORM repo with the option added to the driver.

**Comment by chriswep** [comment]
@rkreutzer @jepiqueau this is now included in a PR i just submitted: https://github.com/typeorm/typeorm/pull/7868

**Comment by jepiqueau** [comment]
@chriswep thanks for answering this request

**Comment by rkreutzer** [comment]
Thanks. I started to look into it yesterday, but glad you did it.
