### ISSUE TITLE
iOS - sqlite3_total_changes EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by Snogo** [capacitor-community/sqlite#143]
I am just trying to port my app to **iOS**. on Android everything works fine
i am using capacitor-communit/sqlite@2.9.16  (I also tried 2.9.13) - iOs 12.1 - capacitor/ios 2.4.7 - capacitor/core 2.4.7 in a Vue project - ionic/vue 5.6.1 - vue 3.0.7

however when starting up and initializing the sqlite database I get the following error in line 167797 sqlite3.c:

return db->nTotalChange;  
**Thread 2: EXC_BAD_ACCESS (code=1, address=0x78)**

could it be a problem with too many threads or too many sqlite connections open?

this should be the code where the error arises:

```
const initVFGDB = async (): Promise<boolean>  => {
      const db = await sqlite
      .createConnection("vdb", false, "no-encryption", 1);
      
      let ret = await db.execute(createTablesNoEncryption);
      if (ret.changes.changes < 0) {
          return false;
      }

      ret = await db.execute(importAllAnimals);
      if (ret.changes.changes < 0) {
          return false;
      }

      ret = await db.execute(importAllTypes);
      if (ret.changes.changes < 0) {
          return false;
      }
      return true;
    }
```

**Comment by jepiqueau** [comment]
@Snogo Thanks for reporting an issue. Would be better that you move directly to 3.0.0-rc2 and capacitor/core3.0.2. It is fully operational for iOS and Android. It is not yet release at 3.0.0 due to Electron. So if you do not use Electron just use it. I will need to see how you implemented in Ionic/Vue Are you using the `vue-sqlite-hook`  What is the definition of sqlite in your example

**Comment by jepiqueau** [comment]
@Snogo Can you provide the database schema `createTablesNoEncryption` and the `importAllAnimals` and importAllTypes. Did you try with a smaller number of Animals and types?

**Comment by jepiqueau** [comment]
@Snogo Any news?

**Comment by Snogo** [comment]
@jepiqueau no. will let you know soon. will first try to port everything to 3.0.0-rc2 and then see

**Comment by jepiqueau** [comment]
@Snogo move to 3.0.0 or higher

**Comment by Snogo** [comment]
porting it now to 3.1.2-1 (and all other 3+ versions of ionic/core) and got the following error in main.ts

```
in src/main.ts:66:36

TS2554: Expected 1 arguments, but got 0.
    64 |   retrieveConnection, retrieveAllConnections, closeAllConnections,
    65 |     addUpgradeStatement, importFromJson, isJsonValid,
  > 66 |     copyFromAssets, isAvailable} = **useSQLite**();
```

can I already use it with the latest vue-sqlite-hook 2.0.2? or respectively do you know the problem here?

**Comment by jepiqueau** [comment]
@Snogo Delete Android and iOS folder of your app npm i --save-dev vue-sqlite-hook it should be version 2.0.4
then npx cap add android and ios then npx cap copy
and npx cap open it should work
the main.ts file should have

```
/* SQLite imports */
import { useSQLite } from 'vue-sqlite-hook/dist';
import { useState } from '@/composables/state';

const app = createApp(App)
  .use(IonicVue)
  .use(router);

/* SQLite Global Variables and Hook */
const [jsonListeners, setJsonListeners] = useState(false);
const [isModal, setIsModal] = useState(false);
const [message, setMessage] = useState("");
app.config.globalProperties.$isModalOpen = {isModal: isModal, setIsModal: setIsModal};
app.config.globalProperties.$isJsonListeners = {jsonListeners: jsonListeners, setJsonListeners: setJsonListeners};
app.config.globalProperties.$messageContent = {message: message, setMessage: setMessage};
  
const onProgressImport = async (progress: string) => {
  if(app.config.globalProperties.$isJsonListeners.jsonListeners.value) {
    if(!app.config.globalProperties.$isModalOpen.isModal.value) app.config.globalProperties.$isModalOpen.setIsModal(true);
    app.config.globalProperties.$messageContent.setMessage(
        app.config.globalProperties.$messageContent.message.value.concat(`${progress}\n`));
  }
}
const onProgressExport = async (progress: string) => {
  if(app.config.globalProperties.$isJsonListeners.jsonListeners.value) {
    if(!app.config.globalProperties.$isModalOpen.isModal.value) app.config.globalProperties.$isModalOpen.setIsModal(true);
    app.config.globalProperties.$messageContent.setMessage(
      app.config.globalProperties.$messageContent.message.value.concat(`${progress}\n`));
  }
}
  
// SQLite Hook  
const {echo, getPlatform, createConnection, closeConnection,
  retrieveConnection, retrieveAllConnections, closeAllConnections,
  isConnection, addUpgradeStatement, importFromJson, isJsonValid,
  isDatabase, getDatabaseList, addSQLiteSuffix, deleteOldDatabases,
  copyFromAssets, checkConnectionsConsistency, removeListeners,
  isSecretStored, setEncryptionSecret, changeEncryptionSecret,isAvailable} = useSQLite({
    onProgressImport,
    onProgressExport
  });
  
  // Singleton SQLite Hook  
  app.config.globalProperties.$sqlite = {echo: echo, getPlatform: getPlatform,
    createConnection: createConnection,
    closeConnection: closeConnection,
    retrieveConnection: retrieveConnection,
    retrieveAllConnections: retrieveAllConnections,
    closeAllConnections: closeAllConnections,
    isConnection: isConnection,
    isDatabase: isDatabase,
    getDatabaseList: getDatabaseList,
    addSQLiteSuffix: addSQLiteSuffix,
    deleteOldDatabases: deleteOldDatabases,
    addUpgradeStatement: addUpgradeStatement,
    importFromJson: importFromJson,
    isJsonValid: isJsonValid,
    copyFromAssets: copyFromAssets,
    checkConnectionsConsistency: checkConnectionsConsistency,
    removeListeners: removeListeners,
    isSecretStored: isSecretStored,
    setEncryptionSecret: setEncryptionSecret,
    changeEncryptionSecret: changeEncryptionSecret,
    isAvailable:isAvailable
  };
  
  //  Existing Connections Store
  const [existConn, setExistConn] = useState(false);
  app.config.globalProperties.$existingConn = {existConn: existConn, setExistConn: setExistConn};
    
router.isReady().then(() => {
  app.mount('#app');
});
```
Listeners have been added  
Hope this will help you

**Comment by jepiqueau** [comment]
@Snogo  Any news from your side? if it works on your side, can you close the issue

**Comment by Snogo** [comment]
@jepiqueau sorry. I was sick last week and will try it hopefully this week. will give you an update then and close the issue

**Comment by jepiqueau** [comment]
@Snogo Hope you are going better, take your time.

**Comment by jepiqueau** [comment]
@Snogo Any news?

**Comment by Snogo** [comment]
sorry. still on the backlog of other things which had priority. will do soon and let you know

**Comment by Snogo** [comment]
Dear @jepiqueau . sorry it took so long but with a colleague I know managed to Upgrade the project to Capacitor3 and we have the latest @capacitor-community/sqlite version (3.2.0-2)
we now face the problem however that although I check with different ways if a sqlite-connection exists (with **app.config.globalProperties.$existingConn** but also with the methods **iDBExists()** or **isConnection()**) 
it always says there is no connection and never retrieves it (with _retrieveConnection_)  and then the error rises _CreateConnection: Connection vdb already exists._ - sqlite3 seems to be more sensitive here
do I need to set the existingConn manually or how do i check if there is already a connection and get it?

I have this method:
const getConnection = async(): Promise<any> => {
    let db: SQLiteDBConnection;
    const {existConn} = app?.appContext.config.globalProperties.$existingConn;
    if(!existConn){
       db =  await sqlite.createConnection("vdb", false,"no-encryption",1);
    }else{
       db = await sqlite.retrieveConnection("vdb");
    }
    return db;
}

**Comment by jepiqueau** [comment]
@Snogo are you using `Live Reload` with capacitor ? Can you share your app on github ?

**Comment by Snogo** [comment]
@jepiqueau no but I will send you the clone via email. thank you very much

**Comment by jepiqueau** [comment]
@Snogo It is quite complex as you spend your time to create the same connection or retrieve it without closing it .
i will create a utils-connection.ts
```
import { SQLiteDBConnection, SQLiteHook } from "vue-sqlite-hook/dist";
export async function getMyConnection(sqlite: SQLiteHook, dbName: string): Promise<SQLiteDBConnection> {
    try {
        const isConn: any = await sqlite.isConnection(dbName);
        let db: SQLiteDBConnection;
        if(isConn.result) {
            db = await sqlite.retrieveConnection(dbName);
        } else {
            db = await sqlite
                    .createConnection(dbName, false, "no-encryption", 1);
        }
        return Promise.resolve(db);
    } catch (err) {
        return Promise.reject(err);
    }
}
export async function closeMyConnection(sqlite: SQLiteHook, dbName: string): Promise<void> {
    try {
        const isConn: any = await sqlite.isConnection(dbName);
        if(isConn.result) {
            await sqlite.closeConnection(dbName);
        }
        return Promise.resolve();
    } catch (err) {
        return Promise.reject(err);
    }
}
```
and do something like this  each time you need the connection ( create or retrieve) 
```
        // initialize the connection
        let db: SQLiteDBConnection;
        try {
          db = await getMyConnection(sqlite,"vfgdb");

          console.log("got DB connection");
          const ret = await db.isDBOpen();
            if (!ret.result) {
              // open db vfgdb
              await db.open();
            }
        } catch (err) {
          console.log(`error opening DB ${err}`);
          return false;
        }
```
you have also to take care with the try ...  catch ie
```
            try {
              const ret = await db.run(createNewSample, values);
              if(ret.changes != null && ret.changes.lastId != null) {
                const lastId = ret.changes.lastId;
                currentSample.value = addSample(
                  lastId,
                  loggedInUser,
                  cDateTimeformat,
                  "",
                  0,
                  0,
                  0,
                  0,
                  "",
                  "",
                  -1,
                  "",
                  -1,
                  -1,
                  0
                );
``` 
i start to modify the code but there are too much work
i will not use at all app.config.globalProperties.$existingConn
you can also simplify in the main.ts
```
  // Singleton SQLite Hook
  app.config.globalProperties.$sqlite = useSQLite({
    onProgressImport,
    onProgressExport
  });
```
hope this will help you to find the way

**Comment by jepiqueau** [comment]
@Snogo Well i thing there is apparently a bug in `@ionic/vue` and `@ionic/vue-router` above 5.6.13 which re-execute the previous pages when you leave one page. stick to 
```
    "@ionic/vue": "~5.6.13",
    "@ionic/vue-router": "~5.6.13",
```
Is that help ?

**Comment by jepiqueau** [comment]
@Snogo i have tried to modify your app without success It has to do with some logic of the app and the way of using Vue. As you are using only one database i will make a connection once and using it all along the app. The best will be to restart from scratch and have a look to `vue-sqlite-app` and `vue-sqlite-app-starter`. I do not thing it is related to the plugin, so there is nothing i can do much to help you sorry for this and good luck.

**Comment by jepiqueau** [comment]
@Snogo hope you find the way. i close the issue. Fell free to re-opens it if required
