### ISSUE TITLE
CapacitorSQLite.toJSON Android

### ISSUE THREAD

**Issue by medida** [capacitor-community/sqlite#144]
I have a completly clean and New ionic capacitor app

I have only added the basic items so i can test the database processes - Any help to get this working?

I am receiving this error: 
Uncaught (in promise): Error: "CapacitorSQLite.toJSON()" is not implemented on android
Error: "CapacitorSQLite.toJSON()" is not implemented on android

I installed the code using @next.

its running on the following versions:
  "@angular/common": "~12.0.1",
    "@angular/core": "^12.0.5",
    "@angular/forms": "~12.0.1",
    "@angular/platform-browser": "~12.0.1",
    "@angular/platform-browser-dynamic": "~12.0.1",
    "@angular/router": "~12.0.1",
    "@capacitor-community/sqlite": "^3.0.0-rc.2",
    "@capacitor/android": "^3.1.1",
    "@capacitor/app": "1.0.2",
    "@capacitor/core": "3.1.1",
    "@capacitor/haptics": "1.0.2",
    "@capacitor/keyboard": "1.0.2",
    "@capacitor/status-bar": "1.0.2",
    "@ionic/angular": "^5.5.2",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.11.4"

**Comment by jepiqueau** [comment]
@medida Thanks for using the plugin. I saw this error which has been introduced by Capacitor 3. CapacitorSQLite has no `toJSON()` method. it should not impact the app using the CapacitorSQLite methods which should normally works. I am working on trying to identify the reason for that error. I have to build up a case for the capacitor team.

**Comment by medida** [comment]
@jepiqueau thank you- the plugin seems to be working so far... its taking me far too long as i am trying to update an existing app process from cordova to capacitor ).

Thanks for the plugin.

**Comment by jepiqueau** [comment]
@medida the error has been reported to the Ionic Capacitor team with a simple plug-in just having an echo method and a simple app using this plug-in . I am waiting for their reaction. Good luck for your hard work. It would have been nice to have a wrapper cordova to capacitor sqlite plug-in. I thought about it but it seems to be quite a work and on top I never use myself the cordova plug-in this is the reason why I didn't developed it. But once can do that it would certainly good for the community of developer.

**Comment by medida** [comment]
I'm trying to move away from the cordova plugins and swap to capacitor ones where possible :)

**Comment by medida** [comment]
@jepiqueau i have managed to get rid of the Error: "CapacitorSQLite.toJSON()" 

I replaced all the single quaotes in your SQLite.service.ts file with ' ( proper single quotes - as yours were the backward versions on my PC )
