### ISSUE TITLE
Open prepopulated encrypted database

### ISSUE THREAD

**Issue by massimeddu** [capacitor-community/sqlite#148]
Hi,

I've an encrypted database (encrypted with SQLCiper) on my assets directory, and I'd like to open it, but I'm not able to do that.

I've tried to following snippet:

```typescript
await this.sqlite.copyFromAssets();
await this.sqlite.setEncryptionSecret('<s3cretKey>');
this.db = await this.sqlite.createConnection('EncryptedDB', true, 'secret', 1);
this.db.open()
```

and

```typescript
await this.sqlite.copyFromAssets();
this.db = await this.sqlite.createConnection('EncryptedDB', true, 'secret', 1);
await this.sqlite.setEncryptionSecret('<s3cretKey>');
this.db.open()
```

but I'm getting the following error (tested on Android): `Msg: Unhandled Promise rejection: SetEncryptionSecret: State for: EncryptedDBSQLite.db not correct ; Zone: <root> ; Task: null ; Value: Error: SetEncryptionSecret: State for: EncryptedDBSQLite.db not correct Error: SetEncryptionSecret: State for: EncryptedDBSQLite.db not correct`

Do you know how to solve this issue?

Thank you.

**Comment by jepiqueau** [comment]
@massimeddu First thanks for using the plugin. I assume the database on the asset folder has been encrypted with the passphrase `'<s3cretKey>'`. I assume there are no other databases in android device application databases folder  so can you test this
```
await this.sqlite.setEncryptionSecret('<s3cretKey>');
await this.sqlite.copyFromAssets();
this.db = await this.sqlite.createConnection('EncryptedDB', true, 'secret', 1);
this.db.open()
```
This should work. if not you need to share a reproduction example on github so i can try reproducing your error.

**Comment by massimeddu** [comment]
Please have a look at the example project: https://github.com/massimeddu/encryped-test

DB connection is implemented here: https://github.com/massimeddu/encryped-test/blob/ed373611e31196c5fbd503cdf27675e1cda06e6a/src/app/search/search.page.ts#L16

Thank you

**Comment by jepiqueau** [comment]
@massimeddu Well it seems that the encrypted database in your asset folder (`encryptedSQLite.db`) has not been encrypted with the passphrase `<secretKey>` . You have to use the passphrase which has been used to encrypt `encryptedSQLite.db` in sqlite.setEncryptionSecret

**Comment by massimeddu** [comment]
@jepiqueau thank you very much for reviewing my example repository. I've encrypted the database using SQLCipher with the following procedure:

```
$ ./sqlcipher plaintext.db
sqlite> ATTACH DATABASE encryptedSQLite.db' AS encrypted KEY '<secretKey>';
sqlite> SELECT sqlcipher_export('encrypted');
sqlite> DETACH DATABASE encryptedSQLite;
```

and I'm actually able to query the encrypted db using the following commands:

```
sqlcipher plaintext.db
sqlite> ATTACH DATABASE encryptedSQLite.db' AS encrypted KEY '<secretKey>';
sqlite> SELECT sqlcipher_export('encrypted');
sqlite> DETACH DATABASE encryptedSQLite;
```

```
sqlcipher encryptedSQLite.db                             
SQLCipher version 3.15.2 2016-11-28 19:13:37
Enter ".help" for instructions
Enter SQL statements terminated with a ";"
sqlite> PRAGMA key='<secretKey>';
sqlite> SELECT * FROM words;
1|test
3|
sqlite> 

```

Should I encode the DB using a different procedure?

Thanks again for your help.

**Comment by jepiqueau** [comment]
@massimeddu  seems that the encryptedSQLite.db in the assets/databases folder is not correct.
i started again from the dbSQLite.db
run `sqlcipher dbSQLite.db` 
```
sqlite> .tables
words
sqlite> ATTACH DATABASE 'encryptedSQLite.db' AS encrypted KEY '<secretKey>';
sqlite> SELECT sqlcipher_export('encrypted');

sqlite> DETACH DATABASE encrypted;
sqlite> 

```
copy the `encryptedSQLite.db` into the `assets/databases` folder
do 
```
npm run build
npx cap copy
npx cap open android
```  
and it works like a charm

the `ngOnInit` is
```
  async ngOnInit(): Promise<void> {
    await this.sqlite.setEncryptionSecret('<secretKey>');
    await this.sqlite.copyFromAssets();
    const db = await this.sqlite.createConnection('encrypted', true, 'secret', 1);
    db.open();
    const res = await db.query('SELECT * FROM words;');
    console.log('RESULT', res.values[0].word);
  }

```
if it works on your site after having recreate the encryptedSQLite.db please close the issue

**Comment by massimeddu** [comment]
Thank you very much @jepiqueau , now I'm able to access to the encrypted db.

What I had to do was to upgrade the sqlciher to the latest version to encrypt the file, and to wipe the app cache into the device. Then it start to work properly.

I'm closing this issue.

Thank you!

**Comment by jepiqueau** [comment]
@massimeddu I am please that you find the reason. You are not the first one to get issue with the android cache since capacitor3
