### ISSUE TITLE
copyFromAssets fails on Android 6

### ISSUE THREAD

**Issue by chriswep** [capacitor-community/sqlite#151]
I see an issue with `copyFromAssets` in my production error logs:
`Error: CopyFromAssets: copy failed : copy failed : `

Up until now those are coming exclusively from Android 6.0 devices and at a rate that suggests a general incompatibility somewhere not an individual user issue. Unfortunately i can't test this, since i don't have an android device with that version and the Android emulator can't update the webview (it's stuck an on old chrome version that can't run the app).

**Comment by jepiqueau** [comment]
@chriswep i do not have an android 6 device, so it will be hard to reproduce the issue, i will look back at the command to see if there is something special not valid for API 23

**Comment by jepiqueau** [comment]
@chriswep i tested the `angular-sqlite-app-starter` tag refactor which is base on capacitor/core@2.4.7 and @capacitor-community/sqlite@2.9.15 on my Samsung Note 3 device having Lolippop and API 21 and the CopyFromAsset test works successfully unfortunately i cannot test the version based on capacitor/core@3.1.1 and @capacitor-community/sqlite@3.1.2-1 as it required API 23 for storing the encryption passphrase.

**Comment by jepiqueau** [comment]
@chriswep looking at the code of copyFromAssetsToDatabase in UtilsFile it is identical in both versions. The error  is due either the receiving databases folder or the public/assets/databases folder do not exist.

**Comment by jepiqueau** [comment]
@chriswep i found the reason. if there was not any databases created before the copyFromAsset is run the folder databases doesn't exist. I will provide a fix in the next release.

**Comment by jepiqueau** [comment]
@chriswep this is fix in 3.1.2. Can you revert to when someone with an Android 6.0 device has test it

**Comment by jepiqueau** [comment]
@chriswep the bug with null value contrary to the changelog of @capacitor/core3.1.2 is still there.

**Comment by jepiqueau** [comment]
@chriswep i set back the fix for null value in 3.1.3-1

**Comment by chriswep** [comment]
@jepiqueau you left two `console.log` in `src/definitions.ts` in the recent commits (i'll put it here since it slightly refers to your comments above and i don't want to open a ticket just for this)

thanks for the fix. i'll let you know if there are any new errors.
