### ISSUE TITLE
copyFromAssets only takes files with SQLite.db suffix on iOS (contrary to Android)

### ISSUE THREAD

**Issue by chriswep** [capacitor-community/sqlite#152]
Since this change in 3.0.0 in https://github.com/capacitor-community/sqlite/commit/84d78e349a1c671cd3c51dcf61df00b0bb6d2856#diff-5cac6efd9a5f78a555d58eff74def9e5c2312ce00c433ec22efc904c1cfedd2aR187 `copyFromAssets` fails on iOS for files that only have the `.db` suffix, not `SQLite.db` - contrary to Android which still accepts `.db` files. 

In any case this should be consistent in both iOS and Android, and the expected suffix should be documented. 

I assume the change for iOS was not intended since the method `getFileList` is used in multiple places. In any case, i would suggest staying with the previous (and android) behaviour of not having to add `SQLite` to the preload-dbs.

**Comment by chriswep** [comment]
thanks @jepiqueau 

i think you accidentally included your sql.js development into the fix? generally concerning sql.js: nothing against it in principle, however it adds huge dependencies to the project (localforage, sql.js). this will significantly increase build sizes and startup time, which is crucial in the context of mobile apps. i would suggest to find a way to make this optional.

**Comment by jepiqueau** [comment]
@chriswep Yes i start looking at it but it is not easy to find the proper setup. i saw that the have it in the cordova sqlite plugin. I was reluctant to do it as i had the electron part in 2.9.x. But the difficulty to get the @capacitor-community/electron working with other plugins push me to  start looking at sql.js. I will certainly take into account your remark. Any idea on how to evaluate the size of the build and how the web part impact the native part?

**Comment by chriswep** [comment]
looking at the sql.js demo page, it pulls in a 429.5 KB wasm file (1.18 MB uncompressed). i would say that is far too much to include by default for a special use case - esp on mobile devices. running sqlite in the browser and persisting via localforage can have it's use cases however i'd suspect it is not a common one. concerning electron - wouldn't native sqlite be available there through node?

**Comment by jepiqueau** [comment]
@chriswep I remove the Web implementation in 3.1.3-3 I will look at it in a different way so the native app in mobile device will not suffer from this. Thanks for your comments

**Comment by jepiqueau** [comment]
@chriswep i did not hear from you, so i assume this is fixed so i will close the issue
