### ISSUE TITLE
Connection exists and doesn't exist at the same time

### ISSUE THREAD

**Issue by ajmas** [capacitor-community/sqlite#153]
**Describe the bug**

I am currently developing an app using Quasar (vue based framework) and I am targeting Android as the platform. At the moment I am deploying to the emulator via Android Studio. 4.2.2, on macOS. Using `vue-sqlite-hook` 2.0.2

If I do a clean start the everything works as expected. The issue I am running into is when I do code modification which results in a hot reload. In this situation the database connection appears to exists and not exist at the same time.

The code:

```js
  const sqlite = app?.config.globalProperties.$sqlite;
  const connectionName = 'myConnection';

  const res = await sqlite.echo('Hello from echo');
  if (res.value !== 'Hello from echo') {
    console.log('Echo not returning "Hello from echo"');
    throw new Error('echo not returning');
  }

  let database;
  try {
    database = await sqlite.retrieveConnection(connectionName);
  } catch (error) {
    console.log('retrieveConnection error', error);
  }

  try {
    database = await sqlite.createConnection(connectionName);
  } catch (error) {
    console.log('createConnection error', error);
  }

  if (!database) {
    throw new Error('unable to create or retrieve connection');
  } 
```

**Expected behavior**

My expectation is for the `retrieveConnection()` call to retrieve the connection, even during a hot reload, to facilitate development.

**Screenshots**

<img width="683" alt="Screenshot 2021-08-03 at 18 51 59" src="https://user-images.githubusercontent.com/682269/128096388-2aeb4b93-7d71-4bf0-b0de-1e2f0622d623.png">

**Smartphone (please complete the following information):**

- Device: Emulated Android tablet
- OS: Android 11.0 x86
- Browser n/a
- Sqlite Version 3.0.0-rc.2

**Additional context**

**Comment by ajmas** [comment]
After some exploring simply closing the database after a  retrieve failure resolve the issue:

```js
      let database;
      try {
        database = await sqlite.retrieveConnection(connectionName);
      } catch (error) {
        console.log('retrieveConnection error', error);
      }

      try {
        if (!database) {
          await sqlite.closeConnection(connectionName);
        }
      } catch (error) {
        console.log('closeConnection error', error);
      }

      try {
        if (!database) {
          database = await sqlite.createConnection(connectionName);
        }
      } catch (error) {
        console.log('createConnection error', error);
      }

      if (!database) {
        throw new Error('unable to create or retrieve connection');
      }
```

**Comment by jepiqueau** [comment]
@ajmas first thanks for using the plugin, you should use `checkConnectionsConsistency` before retrieving the connection
```
let database;
try {
      // Check Connections Consistency
      ret= await this._sqlite.checkConnectionsConsistency();
      if(!ret.result) {
         database = await sqlite.createConnection(connectionName);
      } else {
         database = await sqlite.retrieveConnection(connectionName);
      }
} catch (error) {
      throw new Error(' your message ');
}
```
hope this help

**Comment by ajmas** [comment]
I am trying to use this code with typescript, but running into issue:

> sqlite.checkConnectionsConsistency is not a function

BTW assigning the type `SQLiteConnection` to the sqlite object, I notice that the 2nd, 3rd and 4th parameters are not marked at optional and I am being told there are necessary, despite the example usage in `vue-sqlite-app-starter`. Is that normal? If `sqlite` is typed as `any` I don't need to provide the other parameters


Versions:

- "@capacitor-community/sqlite": "^3.0.0-rc.2"
- "vue-sqlite-hook": "^2.0.4"

**Comment by jepiqueau** [comment]
@ajmas upgrade to the latest of @capacitor-community/sqlite. For the question is difficult to understand can you share your code

**Comment by jepiqueau** [comment]
@ajmas look carefully at the definition of the hook and at the global variable $sqlite checkConnectionsConsistency should be defined on both. I do not understand if you use the hook why do you need to use SQLiteConnection type

**Comment by ajmas** [comment]
@jepiqueau Well for the type I was trying to understand the right type to use, since `vue-sqlite-app-starter` doesn't explicitly indicate the type to use, so I made a best guess best on the Typescript definitions, based on API usage in the sample project. Which is the right type?

**Comment by jepiqueau** [comment]
@ajmas it is may be a problem of android cache. so the best way is to remove the apps and data from you android device or simulator. Delete the folder android from your app. when done  do
```bash
npm run build
npx cap add android
npx cap sync
npm run build
npx cap copy
npx cap open android
```
to come back on the type question you can do the following in the `main.ts` 
```
// SQLite Hook  
const {echo, getPlatform, createConnection, closeConnection,
  retrieveConnection, retrieveAllConnections, closeAllConnections,
  isConnection, addUpgradeStatement, importFromJson, isJsonValid,
  isDatabase, getDatabaseList, addSQLiteSuffix, deleteOldDatabases,
  copyFromAssets, checkConnectionsConsistency, removeListeners,
  isSecretStored, setEncryptionSecret, changeEncryptionSecret,isAvailable} = useSQLite({
    onProgressImport,
    onProgressExport
  });
  
  
  
``` 
and the way to use the sqlite hook in a component is
```
...
import { useSQLite, SQLiteHook} from 'vue-sqlite-hook/dist';
...
        const app = getCurrentInstance()
        const sqlite = app?.appContext.config.globalProperties.$sqlite;
       ... 
       let database;
       try {
           // Check Connections Consistency
           ret= await sqlite.checkConnectionsConsistency();
           if(!ret.result) {
              database = await sqlite.createConnection(connectionName);
           } else {
              database = await sqlite.retrieveConnection(connectionName);
           }
      } catch (error) {
       throw new Error(' your message ');
     }
  const hook: SQLiteHook = {echo: echo, getPlatform: getPlatform,
    createConnection: createConnection,
    closeConnection: closeConnection,
    retrieveConnection: retrieveConnection,
    retrieveAllConnections: retrieveAllConnections,
    closeAllConnections: closeAllConnections,
    isConnection: isConnection,
    isDatabase: isDatabase,
    getDatabaseList: getDatabaseList,
    addSQLiteSuffix: addSQLiteSuffix,
    deleteOldDatabases: deleteOldDatabases,
    addUpgradeStatement: addUpgradeStatement,
    importFromJson: importFromJson,
    isJsonValid: isJsonValid,
    copyFromAssets: copyFromAssets,
    checkConnectionsConsistency: checkConnectionsConsistency,
    removeListeners: removeListeners,
    isSecretStored: isSecretStored,
    setEncryptionSecret: setEncryptionSecret,
    changeEncryptionSecret: changeEncryptionSecret,
    isAvailable:isAvailable
  };
  // Singleton SQLite Hook  
  app.config.globalProperties.$sqlite = hook;

```
and in the component 
```
...
import { SQLiteDBConnection, SQLiteHook } from 'vue-sqlite-hook/dist';
...
async setup() {
...
        const app = getCurrentInstance()
        const sqlite: SQLiteHook = app?.appContext.config.globalProperties.$sqlite;
...
}
``` 
if all this does not work you have to share your app on github so i can have a look.
Hope this will help you and close the issue

**Comment by jepiqueau** [comment]
@ajmas Did you try? is it working ? if yes feel free to close the issue

**Comment by ajmas** [comment]
@jepiqueau I only just got around to trying it and ran into the same issues.

What I did, noting that 

  - removed the src-capacitor/android file
  - ran: `quasar dev -m capacitor -T android`
  - modified the `minSdkVersion` version to be 23 in the `variables.gradle` file
  - launch the application from Android studio
  - connected the debugger from Chrome and saw in the logs:

```
Error during DB init TypeError: sqlite.checkConnectionsConsistency is not a function
    at DatabaseService.eval (webpack-internal:///./src/api/services/DatabaseService.ts:67)
    at step (webpack-internal:///./src/api/services/DatabaseService.ts:33)
    at Object.eval [as next] (webpack-internal:///./src/api/services/DatabaseService.ts:14)
    at fulfilled (webpack-internal:///./src/api/services/DatabaseService.ts:5)
```

Beyond having `sqlite.getPlatform()` give me 'android' as a value, I am not sure what other information I give you.

Displaying `sqlite.checkConnectionsConsistency`, shows me it is undefined.

Looking in the Java source I do see the following, which indicates the issue is most likely at the JS layer:

```java
    public Boolean checkConnectionsConsistency(JSArray dbNames) throws Exception {
```

Just to provide the code I am using to create the sqlite object in the first place, which is essentially taken from the starter app you created:

```ts
import { boot } from 'quasar/wrappers';
import { useSQLite } from 'vue-sqlite-hook/dist';
import { useState } from 'src/composables/state';

export default boot(({ app }) => {
  const appConfig = app.config.globalProperties.$appConfig;
  const mode: string = appConfig.mode;

  if (appConfig.mode !== 'capacitor') {
    console.log(`Sqlite not supported for mode ${mode}`);
    return;
  }

  // SQLite Hook
  // eslint-disable-next-line @typescript-eslint/unbound-method
  const {
    echo, getPlatform, createConnection, closeConnection,
    retrieveConnection, retrieveAllConnections, closeAllConnections,
    addUpgradeStatement, importFromJson, isJsonValid,
    copyFromAssets, isAvailable
  } = useSQLite({});

  // Existing Connections
  // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
  const [existConn, setExistConn] = useState(false);

  app.config.globalProperties.$sqlite = {
    echo: echo,
    getPlatform: getPlatform,
    createConnection: createConnection,
    closeConnection: closeConnection,
    retrieveConnection: retrieveConnection,
    retrieveAllConnections: retrieveAllConnections,
    closeAllConnections: closeAllConnections,
    addUpgradeStatement: addUpgradeStatement,
    importFromJson: importFromJson,
    isJsonValid: isJsonValid,
    copyFromAssets: copyFromAssets,
    isAvailable: isAvailable
  };

  // Existing Connections Store
  app.config.globalProperties.$existingConn = {
    existConn: existConn,
    setExistConn: setExistConn
  };
});
```

**Comment by ajmas** [comment]
Ugh, just seen why I am not seeing it: it was not in the object put into the the `$sqlite` object. 

I replaced the above code with:

```js
  app.config.globalProperties.$sqlite = useSQLite({});
```

I am not sure why you decompose the object in the example to create a new object with the same keys here: https://github.com/jepiqueau/vue-sqlite-app-starter/blob/main/src/main.ts

**Comment by jepiqueau** [comment]
@ajmas Yeah, you right, we could simplify the code as you suggested which will avoid the error you add. Thanks for this, i will update the app-starter.
For typeOrm, you do not need to create a ticket, this is part of the doc TypeORM_Usage.md. So i will close the issue
