### ISSUE TITLE
New function-parameter for not safing secret

### ISSUE THREAD

**Issue by ChefKochNut** [capacitor-community/sqlite#154]
For an app i want to use an encrypted sqlite DB. The secret for accessing said db i wanted to safe as credentials with NativeBiometric Plugin behind a fingerprint. So everytime a user opens the app and if the db already exists a fingerprint is required to retrieve the secret and open the db.

The problem i have right now: Running setEncryptionSecret() sets a secret for the db i am connecting to, encrypts my db and safes it into sharedpreferences (in android case). To open a db running createConnection() with mode ="secret" is already enough to open up my db because the secret is stored in sharedpreferences.

I would like to only open the db if the user provides the secret and not because it is stored in sharedpreferences.
The idea i came up with would be adding another parameter to the setEncryptionSecret- function (true = safe to sharedpreferences/ falso = not safing to sharedpreferences).
@edit additionally an additional mode/parameter for the createConnection- function to privde the secret would be required too?

What i tried was deleting /shared_prefs/sqlite_encrypted_shared_prefs.xml. So far i wasnt really succesfull with this and came to the idea of writing a feature request :)

I hope i could explain my problem understandable.
Also i hope i didnt oversee this certain option or missunderstood anything.

Thanks in advance for any answer or help :)

**Comment by jepiqueau** [comment]
@ChefKochNut  First thanks for using the plugin. The preliminary releases of this plugin, a passphrase was asked each time a user want to access the db. Developers were asking to have it stored in the app  to not have to provide the passphrase on clear each time. After this, see issue#88, they were asking that each user can set up its own passphrase once and having stored it in a safe area. This has a big impact on the plugin. May be the way to do it is to have a capacitor plugin which deal with the biometric and when the user entered the app is recognized your app generate a new passphrase  and  keep the old passphrase  somewhere in a keystore and then you go through the  `changeEncryptionSecret` of the sqlite plugin. This is quite a tedious process if you have several encrypted databases in your app but it you have one it take the time to change the passphrase of the encrypted database and each time you want to create a connection to the database it is done has it is in the plugin right now.
This is just an idea, but with this your database is well protected has the passphrase is only valid during the connection time to the app. Hope this will be helpful

**Comment by AntiGuide** [comment]
Hi @jepiqueau thank you for the fast response. I'm on the team with @ChefKochNut . Our goal here is to protect our closed app even if the phone is unlocked. We found out that at least in Android you use the MasterKey to protect the key for the DB. The newer MasterKey.Builder has a function to force a user authentication in the app:
https://developer.android.com/reference/androidx/security/crypto/MasterKey.Builder#setUserAuthenticationRequired(boolean)
I don't know if there is a counterpart in iOS tough. It would be interesting to expose this functionality in the framework.
Great job with the library by the way :wink:

**Comment by jepiqueau** [comment]
@ChefKochNut @AntiGuide  Biometric to secure Keychain(iOS) or MasterKey(Android) has been implemented in release 3.4.0-2. Can you please test it and revert to me

**Comment by ChefKochNut** [comment]
@jepiqueau wow thanks! A lovely surprise on this sunny wednesday morning :-) Im gonna upgrade and check it out as soon as i got some time free for it. Hopefully this week. Latest next!
Thanks again!

**Comment by ChefKochNut** [comment]
Hi @jepiqueau ! sorry for the delayed answer. Got busy with some other tasks and just had the time to try it out.

So i upgraded to version 3.4.1 and added the settings to capacitor.config described in [here](https://github.com/capacitor-community/sqlite/blob/master/docs/Biometric-Authentication.md).
I get asked for fingerprint and all works pretty fine. Thanks! :)

The current error i am facing though is the following:
**In my case right now no DB exists yet**
calling createConnection() to create my DB leads to the error:
- Uncaught (in promise) Error: Open: Attempt to invoke interface method 'java.lang.String android.content.SharedPreferences.getString(java.lang.String, java.lang.String)' on a null object reference
FYI: In this case i didnt use setEncryptionSecret(). When i try to use it before i get almost the same message: 
- Uncaught (in promise) Error: SetEncryptionSecret: Attempt to invoke virtual method 'void com.getcapacitor.community.database.sqlite.SQLite.UtilsSecret.setEncryptionSecret(java.lang.String)' on a null object reference

Could you explain in detail how to use it? Or is it just a small mistake I am doing? 
Thank you very much in advance already!

**Comment by jepiqueau** [comment]
@ChefKochNut Can you share your code?

**Comment by ChefKochNut** [comment]
@jepiqueau some parts for sure, yes. I just cut out some unnecessary parts.

My custom function "initDb()" does the following:
`
const initDb = async (): Promise<void> => {
  if (!isPlatform("capacitor")) return;

  await CapacitorSQLite.checkConnectionsConsistency({ dbNames: ["DBNAME"] });
  const sqliteConnection = new SQLiteConnection(CapacitorSQLite);

  if (!(await sqliteConnection.isDatabase(DBNAME)).result) {
    const secret = "geheim";
    await sqliteConnection.setEncryptionSecret(secret);
    await createDBConnection(true, "DBNAME", sqliteConnection);
    return;
  }

  const connection = await createDBConnection(false, "DBNAME", sqliteConnection);
};
`

The function "createDBConnection()" looks like this:
`
    const createDBConnection = async (newDB: boolean, dbName: string, sqliteConnection: SQLiteConnection): Promise<Connection> => {
        return await createConnection({
            database: dbName,
            driver: sqliteConnection,
            mode: "secret",
            type: "capacitor",
            version: 1,
            entities: [],
            logging: ["error", "query", "schema"],
            synchronize: newDB,
        });
    };
`

In my main.ts i call initDb and then mount my app:
`
initDb().then(() => {
    router.isReady().then(() => {
        app.mount('#app');
    });
});
`

I hope this helps? If you need more just ask. Just gotta check out first if i can show you :)

**Comment by jepiqueau** [comment]
@ChefKochNut Can you try
```
await CapacitorSQLite.checkConnectionsConsistency({ dbNames: [] });

```

**Comment by ChefKochNut** [comment]
@jepiqueau i did. Result of it is false

**Comment by jepiqueau** [comment]
@ChefKochNut Yes that normal has there is no connection yet returning true means that your connection is there and consistent

**Comment by ChefKochNut** [comment]
@jepiqueau alright. But my general workflow is fine so far? In detail i mean:
when no db exist using first setEncryptionSecret to set a secret and then createConnection function to create a new db. We were not sure if we even need setEncryptionSecret when we use biometrics.
Or would you recommend another approach or something?

**Comment by jepiqueau** [comment]
@ChefKochNut If you do not use encrypted database you do not need to use neither setEncryptionSecret or biometrics. If you use encrypted database you must setEncryptionSecret first before creating any database and then you can also use biometrics.

**Comment by ChefKochNut** [comment]
@jepiqueau so should be fine then. No db exists. I want to create one with encryption so i call **_SetEncryptionSecret_** first before i call **_createConnection_**.
Maybe it makes a difference because i call the **_createConnection_** function from typeorm?

**Comment by jepiqueau** [comment]
@ChefKochNut should be fine tell me if it works and close the issue if it is

**Comment by ChefKochNut** [comment]
@jepiqueau i still get the error

`Uncaught (in promise) Error: SetEncryptionSecret: Attempt to invoke virtual method 'void com.getcapacitor.community.database.sqlite.SQLite.UtilsSecret.setEncryptionSecret(java.lang.String)' on a null object reference`

when calling _setEncryptionSecret_ function.

sorry if it didnt come through in my last message

**Comment by jepiqueau** [comment]
@ChefKochNut can you make a small app that you can share so i can have a look on my own. May be it is due to the typeOrm driver

**Comment by ChefKochNut** [comment]
@jepiqueau here you go: https://github.com/ChefKochNut/testapp

**Comment by jepiqueau** [comment]
@ChefKochNut i clone it update the JDK to version 11 and it works fine

**Comment by jepiqueau** [comment]
@ChefKochNut To be more compliant with the latest release of typeOrm i have done this
```
import { User } from "@/models/User";
//import { createConnection } from "typeorm";
import { DataSource } from "typeorm";
import { CapacitorSQLite, SQLiteConnection } from "@capacitor-community/sqlite";
import { isPlatform } from "@ionic/vue";

const DBNAME = "testDB";

const useDb = () => {
    const createDBConnection = async (newDB: boolean, dbName: string, sqliteConnection: SQLiteConnection) => {
        const AppDataSource = new DataSource({
            database: dbName,
            driver: sqliteConnection,
            mode: "secret",
            type: "capacitor",
            version: 1,
            entities: [User],
            logging: ["error", "query", "schema"],
            synchronize: newDB,
        });
        AppDataSource.initialize()
         .then(()=> {
            return Promise.resolve();
         })
         .catch((error) => {
             console.log(error)
             return Promise.reject(`Error createDBConnection: ${error}`)
         });
    /*    return await createConnection({
            database: dbName,
            driver: sqliteConnection,
            mode: "secret",
            type: "capacitor",
            version: 1,
            entities: [User],
            logging: ["error", "query", "schema"],
            synchronize: newDB,
        });
    */
    };

...

```
and it still working fine
I cannot do more so tell me when it works on your side

**Comment by ChefKochNut** [comment]
@jepiqueau thanks a lot already for all the help! Might not be able today to try anything more since its almost the weekend. But i will get back at you as soon as i found out. From what you are writing i recon its a version problem for sure.

**Comment by jepiqueau** [comment]
@ChefKochNut  Ok, good luck and have a good weekend

**Comment by ChefKochNut** [comment]
@jepiqueau you too!
