### ISSUE TITLE
Question: What is the preferred way to maintain multiple parallel requests to sqlite 

### ISSUE THREAD

**Issue by NicolasHofmairT23** [capacitor-community/sqlite#157]
My main question is: 
What is the difference between **sqlite.createConnection()** and **db.open()**

Why is both needed? 
When doing `sqlite.closeConnection(...)`, makes this `db.close()` unneeded?

When I do something like this it does not work (kinda understand why, because same instance)
```
// Function 1 (slow)
const db = sqlite.createConnection('mydb');
db.open();
// async work...

// Function 2 (fast)
const db2 = sqlite.retrieveConnection('mydb');
db2.open()
db2.close();
...
// Function 1 (again after some time)
db.query(...) // ERROR, because db2.close();
// 
```
So what is best practice here?
- one connection, open it with db.open() but never close? (is this an issue?)

**Comment by jepiqueau** [comment]
@NicolasHofmairT23 First thanks to use the plugin. Internally the connection are store in a `Map<string, SQLiteDBConnection>` with the key being the database name. so your constants db et db2 are pointing to the same SQLiteDBConnection, so when you close db2 means that you have close the SQLiteDBConnection so if you use the db.query(...) it is normal that you get the message that the database is close.
- `sqlite.createConnection` is creating a pointer to a new SQLiteDBConnection, store it in the `Map<string, SQLiteDBConnection>` and return it to the interface .
- `db.open` is opening the database referenced in the SQLiteDBConnection
- `db.close` is closing the database referenced in the SQLiteDBConnection
- `sqlite.closeConnection` is closing the database referenced in the SQLiteDBConnection if the database is opened and removing the pointer to that SQLiteDBConnection in the `Map<string, SQLiteDBConnection>`

You can decide in YOUR_APP to close the database and keep the `Connection` opened to reused it later, or to close the connection.
You will see that the db.close() in the web interface which is coming, is used to store the in-memory database to a `localforage` store.

When using `dev-live-reload` you must check the connection consistency, this can be done by using `checkConnectionsConsistency`

ie
```js
      let db;
      if (
        !(await sqliteConnection.isConnection("MY_DB")).result ||
        !(await sqliteConnection.checkConnectionsConsistency()).result
      ) {
        console.log("in Teams createConnection");
        // Create a connection to the MY_DB db
        db = await sqliteConnection.createConnection("MY_DB", false);
        // Open the MY_DB db
        await db.open();
      } else {
        // Get existing db connection
        console.log("in Teams retrieveConnection");
        db = await sqliteConnection.retrieveConnection("MY_DB");
      }

```
Hope this will be helpful.

**Comment by micheal-w-wells** [comment]
Something that helped us deal with different threads wanting to open and close connections was to introduce a promise queue, have the receiving end handle opening or retrieving the connection, and then all the components that want to use the db can call a method that adds it to the queue and get a regular promise.

**Comment by NicolasHofmairT23** [comment]
```ts
const retrieveOrCreate = async (name: string): Promise<SQLiteDBConnection> => {
    const isConnection = await sqlite.isConnection(name);
    const consistencyCheckWithDeleteSideeffect = await sqlite.checkConnectionsConsistency();
    if (!isConnection.result || !consistencyCheckWithDeleteSideeffect) {
        return await sqlite.createConnection(name);
    }
    return await sqlite.retrieveConnection(name);
};

export const getDatabaseConnection = async (name = 'dbname'): Promise<SQLiteDBConnection> => {
    const connection = await retrieveOrCreate(name);
    const isOpen = await connection.isDBOpen();
    if (!isOpen.result) {
       await connection.open();
    }
    return connection;
};
```

I am using this approach now. Everytime I need to use sqlite I do `const db = await getDatabaseConnection();`
Until now this seems to work good. I hope leaving the connection open will not be an issue.
You think this implementation is solid?

**Comment by jepiqueau** [comment]
@NicolasHofmairT23 Seems good to me you can leave the connection opened and close the db and open the db when you wish and close the connection before to leave the component or the app. On the Web plug-in it is the mechanism to close the db which will store the db to local forage.
