### ISSUE TITLE
Encrypted electron database

### ISSUE THREAD

**Issue by filpet95** [capacitor-community/sqlite#162]
If I have understood correctly, today electron is finally supported again, but without encrypted database. 

In my project, the encryption of the database is quite important for a release on desktop and mac. Is this in the scope of this project or is it on hold?
If it's in the scope, what is the plan to solve the issue and would you need some help somewhere?

Thanks for your dedication for this project!

**Comment by jepiqueau** [comment]
@filpet95  They were some issue with the package for Windows with the previous implementation see issue#135. This is why a come back to the use of pure `sqlite3`.
It has been a tremendous work to have it working back on Electron. You should appreciate it.
The error came from the dependencies of @journeyapps/sqlcipher. I do not have a grip on that package. I understand your view point but i cannot release something which is not working for all OS. I will see later if it will be possible to use it successfully. I let in the code commented all the code lines required for encryption for encryption. if you are in a hurry you can uncomment these lines and install `@journeyapps/sqlcipher` instead of `sqlite3` in the electron folder of your app. I assume it should work. if you try, tell me the status.
My next plan is to provide a Web version using `sql.js` and `localeforage` for database persistency.

**Comment by filpet95** [comment]
Alright, sounds great!
At the moment I have unfortunately not the time to focus on electron platform of my application, but this will be my first prio as soon I get the time. 
Keep up the great work and I'll keep in touch!

**Comment by filpet95** [comment]
Hi, hope that all is well. 
I have finally freed some time to put on this project. I have made a fork and implemented a version that enables encrypted databases on all platforms. Have tested it on iOS/Android/Win/mac. 

I have changed back the dependency from sqlite3 to @journeyapps/sqlcipher. To make it compile at all platforms, the user need to install the dependency in their electron project and disable the automatic electron-rebuild for that specific package.
 
I have been thinking of a generic way of making the key storage secure on electron as well. It is a hard task as it should be protected from both admin users browsing the files and malicious software reading them. There are some options that may work in a somewhat semi-secure (e.g. electron safeStorage or Atom's keytar, links below) way but from my view there are no perfect solutions. Hence, I believe that enforcing a safety solution for all projects using the plugin is not the way of going forward, so I also implemented the possibility to let the application itself take the responsibility of storing the secret keys.

The way the implementation is intended to work is following:
1. App is started.
2. App retrieve the secret key by its own preffered method.
3. App sends the secret key to the sqlite plugin using the method setRAMEncryptionSecret.
4. When the plugin opens an encrypted database, it checks if a RAM encryption secret is set. If it is, it will use this key, otherwise it will use the secret set with the method where the plugin is responsible to store the secret.
Note that this way also has its cavecats, e.g. by sending keys over the capacitor tunnel. But no solution is perfect.

So, as a summary this fork yields the following options:
1. Encrypted database for all platforms
2. In electron, the setEncryptionSecret etc is not implemented, however the user can write a static key for all builds in the JS file (insecure, not recommended)
3. Yields possibility for app to be responsible to store the secret key for all platforms to avoid storing it in plain text in files.

I have not created a pull request yet as the changes will break users builds in electron as the dependency changed from sqlite3 to @journeyapps/sqlcipher. You can find the implementation in my fork: https://github.com/filpet95/sqlite/tree/feature/encrypted-electron 
Please test it on all platforms as well to make sure it works on different devices. And PM me with feedback or if something doesnt work!

For atom's node-keytar see: https://github.com/atom/node-keytar
For the new safeStorage in electron see: https://www.electronjs.org/docs/latest/api/safe-storage

**Comment by jepiqueau** [comment]
@filpet95 i am quite busy on other thing right now. When i have time i will have a look at what you did. Did you test it on Mac and Windows and create a package and run it without error? The reason why i removed it is one developer could not make the package on Windows. On Mac it was working fine.

**Comment by filpet95** [comment]
Yes, everything works fine on both mac/windows given that you install the dependency in your electron project and disable the automatic electron-rebuild for that specific package.

**Comment by jepiqueau** [comment]
@filpet95 Starting to look at it. Have you made modifications only on the Electron part of the plugin.

**Comment by filpet95** [comment]
Super. I have made changes for all platforms to make possibility for app to be responsible to store the secret key to avoid storing it in plain text in files.

**Comment by jepiqueau** [comment]
@filpet95 for Android and iOS platform the `setEncryptionSecret` was not storing the secret in plain text files. This will add to the complexity of the review as some changes have been made since then

**Comment by filpet95** [comment]
Yes, I understand that. However, this will enable the same behaviour for all platforms if the user builds to electron.
An other solution would be to store the secret in a safe keystore in win/mac but this would  probably impose more dependencies. I also believe that enabling an option of letting a plugin user select his/her own storage of their secret keys is a good idea to prevent the plugin enforcing a security solution of an application.

However, please note that I believe this solution is not bullet proof either as the key will be exposed as a variable in the javascript code. This means that if someone really tries he/she will be able to edit the javascript code and get over the key by printing it to an accessible file. However, this is also a risk in the already existing solution so I don't believe there is so much added risk to this approach.

**Comment by filpet95** [comment]
For instance, the electron application will be packaged in an .asar file. Someone could unpack the .asar file, identify the location where the keymanagement is occuring, write it to a public file, repack the .asar file and replace the original file with the corrupted one. 
In my eyes, the only way to avoid this is to create a NAPI addon which decrypts the database with a key hidden in the compiled code. This would add quite some complexity to the plugin but should be possible. 

However, I havn't tested my theory and I'm happy if someone proved me wrong about this!

**Comment by beligatclement** [comment]
I would also have been interested in the return of this feature. Would it be possible for you @filpet95 to isolate the changes made on the electron part to facilitate the implementation of your fix in the project ?

PS : I can test it on iOS / Android / MacOS / Windows / Linux

**Comment by jepiqueau** [comment]
This feature is back in 5.0.0 so i close the issue
