### ISSUE TITLE
full importFromJson. Error: restoreDB: backup-myDbName_SQLite.db does not exist

### ISSUE THREAD

**Issue by MonicaExplan** [capacitor-community/sqlite#164]
Hi

I'm on Andorid and I'm importing from json full a new verion over another version previously  imported from Json
Both json file are only for schema
May Db is populated with data and I have to upgrade it to a new schema version. In the new json schema file the only changes: I remove one table. 

On await sqlite.importFromJson(JSON.stringify(dbToImport)) I get this error:
E/com.getcapacitor.community.database.sqlite.SQLite.UtilsFile: Error: restoreDB: backup-myDbName_SQLite.db does not exist

"@ionic-native/core": "^5.32.0",
"@capacitor/cli": "^3.0.2",
"@capacitor-community/sqlite": "^3.0.0-rc.1",

Can you help me in solving this issue, please?

Thanks
Monica

**Comment by khashashin** [comment]
> @MonicaExplan Hi, I do not really follow what you said. If it is a full import it should contain all the schema and all the data. So you should be more specific . the error message seems to indicate that when you open the database the version is not correct.
> have you change the version number (ie to 2 if it was 1 in the first import) in your new full import and you create the connection with version set to 2. Show me your code

So if I'll only create Database schema without Data (`values: []`) using `JSObject res = db.importFromJson(jsonSQL);`  I've to use `partial` method?

**Comment by khashashin** [comment]
Well, I've tested `importFromJson` using partial, still no success :(

**Comment by khashashin** [comment]
I found my issue. The problem was that I've defined foreign key `module_id` but di not created that field it self as column. Then I've followed all processes in the Debugger and the error where thrown in `ImportFromJson.java` in line: 114 `catch (Exception e)`

```
} catch (IllegalStateException e) {
    throw e;
} catch (android.database.SQLException e) {
    throw e;
} catch (Exception e) {
    throw e;
} finally {
    if (db != null && db.inTransaction()) db.endTransaction();
    return changes;
}
```

But this error wasn't shown in the console. It would be maybe better if all this error would shown in the Logcat

**Comment by jepiqueau** [comment]
@khashashin I was not working this afternoon, so i only see your message now.  Normally all messages should be throw . So i will have to figure out this. Can you share your code so i can replicate easily what you do. Usually you start by a full import containing schemas and table data and after you use partial import for adding shemas or adding schemas and data. I you want to change the version number of your database you have to use a full import with all schemas and table data and make sure to set up the version in the new json object. Are your schemas and data coming from a remote server or is it a json object stored in the assets folder?

**Comment by jepiqueau** [comment]
@khashashin the first import is always a full,

**Comment by khashashin** [comment]
Hi @jepiqueau thanks for the reply. You can try importing the following JSON, and it will give an error about the foreign key, and this error is not displayed in the console:

```
{
    "database": "test_study_db",
    "version": 1,
    "encrypted": false,
    "mode": "full",
    "tables": [
        {
            "name": "modules",
            "schema": [
                {"column": "id", "value": "INTEGER PRIMARY KEY NOT NULL"},
                {"column": "name", "value": "TEXT NOT NULL"},
                {"column": "color", "value": "TEXT NOT NULL"},
                {"column": "room", "value": "TEXT"},
                {"column": "tag", "value": "TEXT"},
                {"column": "event", "value": "TEXT"},
                {"column": "home_work", "value": "TEXT"},
                {"column": "last_modified", "value": "INTEGER DEFAULT (strftime('%s', 'now'))"}
            ],
        },
        {
            "name": "module_date",
            "schema": [
                {"column": "id", "value": "INTEGER PRIMARY KEY NOT NULL"},
                {"column": "date_time", "value": "TEXT NOT NULL"},
                {"column": "last_modified", "value": "INTEGER DEFAULT (strftime('%s', 'now'))"},
                {
                    "foreignkey": "module_id",
                    "value": "REFERENCES modules(id)"
                }
            ],
        }
    ]
}
```

**Comment by jepiqueau** [comment]
@khashashin i will do that tomorrow

**Comment by jepiqueau** [comment]
@khashashin this is fix in v3.2.0-9

**Comment by jepiqueau** [comment]
@MonicaExplan Hi, if i did not hear from you i will close the issue

**Comment by jepiqueau** [comment]
@MonicaExplan I am still trying to understand the scenario
```
- you create a first version of your database with a `full` import containing only the schema of the database
- you fill the data either by 
      - one or several `partial` imports
      - by using standard statements  using `execute`, `executeSet` and/or `run` methods
```
Now you would like to update the version of your database where one table is removed by an importFromJson and keeping your data
``` 
- first you have to exportToJson  in `full` mode to get the json object
- from that returned json object you have to 
        - change the version
        - remove the table from the json object (this will remove the schema, indexes, triggers, values)
- check the validity of the modified json object with `isJsonValid`
- finally make a new importFromJson with mode `full` of the modified json object
```

Did that make sense to you?

**Comment by MonicaExplan** [comment]
@jepiqueau 
Hi, sorry for my late answer but Iwasn't connected in the last days.
About scenario

- **YES (I get the json from a json file on server with "version": 1,"encrypted": false,"mode": "full",)** you create a first version of your database with a `full` import containing only the schema of the database
- **YES** you fill the data either by 
      - **YES (only one partial import with dummy data, I get the json with data from a json file on server)** one or several `partial` imports
      - by using standard statements  using `execute`, `executeSet` and/or `run` methods


**YES** Now you would like to update the version of your database where one table is removed by an importFromJson **NO (I'll have new data)** and keeping your data

- **NO** first you have to exportToJson  in `full` mode to get the json object
- **NO** from that returned json object you have to 
        - change the version
        - remove the table from the json object (this will remove the schema, indexes, triggers, values)
- **NO** check the validity of the modified json object with `isJsonValid`

Yoy suggest these steps, instead I simply get a new json schema from a new file from the server with 
    "version": 2,
    "encrypted": false,
    "mode": "full", 
Then I check check the validity of the json object with `isJsonValid`, and then make a new importFromJson with mode `full`, Then I will reload all the data 


- **YES** finally make a new importFromJson with mode `full` of the modified json object


Differently from your scenario I get the DB schema with mode "full" always from the server (I don't manipuletd an exported JSON DB). Is this case correct?

Thanks
Monica

**Comment by jepiqueau** [comment]
@MonicaExplan Thanks for replying. If you get the database from a server it is correct to do a `full` import from the server to upgrade the version . This `full` import can contain the schema and the table data or the schema only. In the last case you must do one or several `partial` imports to load the new data. Do not forget to modify the `syncDate` after this. If you follow this does it work or have you still an issue?

**Comment by MonicaExplan** [comment]
@jepiqueau 
Thanks for suggestions.
I'm already doing all you write in your previous response (iValida, data, syncDate, ...) but the error is on importFromJSON when mode= full and version = 2

**I explain my app.**
- I get file db1.json
- import full mode, only schema, version = 1
- I get file db1_dati.json
- import partial mode, only data, version =1
- sync Date or syn Table
All right. The db exists and works. Then: 
- I get file db2.json
- import (full mode, only schema, version = 2) **and here I get the error**

I have tested also this case: 
**TEST1**: check the json, in file db2.json, is correct
I'm sure the json in file db2.json is correct because I drop db, and importing file db2.json with version = 1 and all is ok: imported! 
**TEST2**: make the db schema version = 2 as it was the first version installed on the device. 
I drop db from device by your API. Then I get file db2.json with version = 2 and it seems to try upgrade DB and not to create a new DB!!! I get the error! Does it seem caching some information about dropped DB or not accepting version =2 as the first one DB version??...

It seems have some problem with version =2... 

Thanks

**Comment by jepiqueau** [comment]
@MonicaExplan can you share your db1.json, db1_dati.json and db2.json or is it to confidential data?

**Comment by MonicaExplan** [comment]
@jepiqueau 

Here the content of my test file
Thanks

-------------------------------------- db1.json
{
    "database": "consumer_plangei_",
    "version": 1,
    "encrypted": false,
    "mode": "full",
    "tables":[
    	{
            "name": "compat",
            "schema": [
              { "column": "id", "value": "INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL" },
              { "column": "dbVer", "value": "INTEGER NOT NULL" },
              { "column": "minAppBuildVer", "value": "INTEGER NOT NULL" },
              { "column": "maxAppBuildVer", "value": "INTEGER NOT NULL" },
              { "column": "last_modified", "value": "INTEGER DEFAULT (strftime('%s', 'now'))" }   
            ],
            "indexes": [
                {"name": "index_compat_on_last_modified","value": "last_modified DESC"}
            ]
        },
        {
            "name": "sites",
            "schema": [
              { "column": "id", "value": "INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL" },
              { "column": "syncId", "value": "TEXT UNIQUE" },
              { "column": "code", "value": "TEXT NOT NULL" },
              { "column": "title", "value": "TEXT NOT NULL" },
              { "column": "recordType", "value": "INTEGER DEFAULT 0 NOT NULL" },
              { "column": "editable", "value": "INTEGER DEFAULT 0 NOT NULL" },
              { "column": "deletable", "value": "INTEGER DEFAULT 0 NOT NULL" },
              { "column": "last_modified", "value": "INTEGER DEFAULT (strftime('%s', 'now'))" }   
            ],
            "indexes": [
                {"name": "index_site_on_last_modified","value": "last_modified DESC"}
            ]
        },
        {
            "name": "tickets",
            "schema": [
                { "column": "id", "value": "INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL" },
                { "column": "syncId", "value": "TEXT UNIQUE" },
                { "column": "num", "value": "TEXT UNIQUE NOT NULL" },
                { "column": "siteId", "value": "TEXT NOT NULL" },
                { "column": "title", "value": "TEXT NOT NULL" },
                { "column": "desc", "value": "TEXT" },
                { "column": "img", "value": "TEXT" },
                { "column": "recordType", "value": "INTEGER DEFAULT 0 NOT NULL" },
                { "column": "editable", "value": "INTEGER DEFAULT 0 NOT NULL" },
                { "column": "deletable", "value": "INTEGER DEFAULT 0 NOT NULL" },
                { "column": "last_modified", "value":"INTEGER DEFAULT (strftime('%s', 'now'))" },
                {
                    "foreignkey": "siteId",
                    "value": "REFERENCES sites(id)"
                }
            ],
            "indexes": [
                {"name": "index_ticket_on_siteId","value": "siteId"},
                {"name": "index_ticket_on_last_modified","value": "last_modified DESC"},
                {"name": "index_ticket_on_title_desc", "value": "title ASC, desc"}
            ]
        }
    ]
}

-------------------------------------- db1_dati.json
{
    "database": "consumer_plangei_",
    "version": 1,
    "encrypted": false,
    "mode": "partial",
    "tables":[
        {
            "name": "sites",
            "values": [
                [1,"1","AA","location1 da store",0,0,0,1587310030], 
                [2,"2","BB","location2 da store",0,0,0,1587310030 ],
                [4,"4","DD","location4 da store",0,0,0,1587310030 ], 
                [3,"3","CC","location3",0,0,0,1587310030],
                [5,"5","EE","location no tickets ",0,0,0,1587310030]

            ]
        },
        {
            "name": "tickets",
            "values": [
                [1,"1","t1",2,"Ticket one","I m the Ticket one and I like it","https://europanglass.it/wp-content/uploads/2015/09/vetro-rotto-156393-300x225.jpg",0,0,0, 1587310030],
                [2,"2","t2",4,"Ticket two","Im the Ticket two and I like it","https://millepiani.com/wp-content/uploads/2018/12/allarme-ascenore.jpeg",0,0,0, 1587310030],
                [3,"3","t3",2,"Ticket three","I m the Ticket three and I like it","https://thumbs.dreamstime.com/z/porta-di-legno-rotta-28815944.jpg",0,0,0, 1587310030],
                [4,"4","t4",2,"Ticket four","I m the Ticket four and I like it","https://plangei.it/wp-content/uploads/2020/03/Logo-2.png",0,0,0, 1587310030],
                [5,"5","t5",4,"Ticket one","I m the Ticket one and I like it","https://europanglass.it/wp-content/uploads/2015/09/vetro-rotto-156393-300x225.jpg",0,0,0, 1587310030],
                [6,"6","t6",2,"Ticket two","Im the Ticket two and I like it","https://millepiani.com/wp-content/uploads/2018/12/allarme-ascenore.jpeg",0,0,0, 1587310030],
                [7,"7","t7",2,"Ticket three","I m the Ticket three and I like it","https://thumbs.dreamstime.com/z/porta-di-legno-rotta-28815944.jpg",0,0,0, 1587310030],
                [8,"8","t8",2,"Ticket four","I m the Ticket four and I like it","https://plangei.it/wp-content/uploads/2020/03/Logo-2.png",0,0,0, 1587310030],
                [9,"9","t9",4,"Ticket one","I m the Ticket one and I like it","https://europanglass.it/wp-content/uploads/2015/09/vetro-rotto-156393-300x225.jpg",0,0,0, 1587310030],
                [10,"10","t10",2,"Ticket two","Im the Ticket two and I like it","https://millepiani.com/wp-content/uploads/2018/12/allarme-ascenore.jpeg",0,0,0, 1587310030],
                [11,"11","t11",3,"Ticket three","I m the Ticket three and I like it","https://thumbs.dreamstime.com/z/porta-di-legno-rotta-28815944.jpg",0,0,0, 1587310030],
                [12,"12","t12",3,"Ticket four","I m the Ticket four and I like it","https://plangei.it/wp-content/uploads/2020/03/Logo-2.png",0,0,0, 1587310030],
                [13,"13","t13",3,"Ticket one","I m the Ticket one and I like it","https://europanglass.it/wp-content/uploads/2015/09/vetro-rotto-156393-300x225.jpg",0,0,0, 1587310030],
                [14,"14","t14",3,"Ticket two","Im the Ticket two and I like it","https://millepiani.com/wp-content/uploads/2018/12/allarme-ascenore.jpeg",0,0,0, 1587310030],
                [15,"15","t15",3,"Ticket three","I m the Ticket three and I like it","https://thumbs.dreamstime.com/z/porta-di-legno-rotta-28815944.jpg",0,0,0, 1587310030],
                [16,"16","t16",3,"Ticket four","I m the Ticket four and I like it","https://plangei.it/wp-content/uploads/2020/03/Logo-2.png",0,0,0, 1587310030],
                [17,"17","t17",3,"Ticket one","I m the Ticket one and I like it","https://europanglass.it/wp-content/uploads/2015/09/vetro-rotto-156393-300x225.jpg",0,0,0, 1587310030],
                [18,"18","t18",3,"Ticket two","Im the Ticket two and I like it","https://millepiani.com/wp-content/uploads/2018/12/allarme-ascenore.jpeg",0,0,0, 1587310030],
                [19,"19","t19",1,"Ticket three","I m the Ticket three and I like it","https://thumbs.dreamstime.com/z/porta-di-legno-rotta-28815944.jpg",0,0,0, 1587310030],
                [20,"20","t20",1,"Ticket four","I m the Ticket four and I like it","https://plangei.it/wp-content/uploads/2020/03/Logo-2.png",0,0,0, 1587310030],
                [21,"21","t21",3,"Ticket one","I m the Ticket one and I like it","https://europanglass.it/wp-content/uploads/2015/09/vetro-rotto-156393-300x225.jpg",0,0,0, 1587310030],
                [22,"22","t22",1,"Ticket two","Im the Ticket two and I like it","https://millepiani.com/wp-content/uploads/2018/12/allarme-ascenore.jpeg",0,0,0, 1587310030],
                [23,"23","t23",3,"Ticket three","I m the Ticket three and I like it","https://thumbs.dreamstime.com/z/porta-di-legno-rotta-28815944.jpg",0,0,0, 1587310030],
                [24,"24","t24",1,"Ticket four","I m the Ticket four and I like it","https://plangei.it/wp-content/uploads/2020/03/Logo-2.png",0,0,0, 1587310030],
                [25,"25","t25",1,"Ticket one","I m the Ticket one and I like it","https://europanglass.it/wp-content/uploads/2015/09/vetro-rotto-156393-300x225.jpg",0,0,0, 1587310030],
                [26,"26","t26",3,"Ticket two","Im the Ticket two and I like it","https://millepiani.com/wp-content/uploads/2018/12/allarme-ascenore.jpeg",0,0,0, 1587310030],
                [27,"27","t27",4,"Ticket three","I m the Ticket three and I like it","https://thumbs.dreamstime.com/z/porta-di-legno-rotta-28815944.jpg",0,0,0, 1587310030],
                [28,"28","t28",1,"Ticket four","I m the Ticket four and I like it","https://plangei.it/wp-content/uploads/2020/03/Logo-2.png",0,0,0, 1587310030],
                [29,"29","t29",4,"Ticket one","I m the Ticket one and I like it","https://europanglass.it/wp-content/uploads/2015/09/vetro-rotto-156393-300x225.jpg",0,0,0, 1587310030],
                [30,"30","t30",1,"Ticket two","Im the Ticket two and I like it","https://millepiani.com/wp-content/uploads/2018/12/allarme-ascenore.jpeg",0,0,0, 1587310030],
                [31,"31","t31",1,"Ticket three","I m the Ticket three and I like it","https://thumbs.dreamstime.com/z/porta-di-legno-rotta-28815944.jpg",0,0,0, 1587310030],
                [32,"32","t32",4,"Ticket four","I m the Ticket four and I like it","https://plangei.it/wp-content/uploads/2020/03/Logo-2.png",0,0,0, 1587310030]
            ]
        }
    ]
}

-------------------------------------- db2.json
{
    "database": "consumer_plangei_",
    "version": 2,
    "encrypted": false,
    "mode": "full",
    "tables":[
        {
            "name": "sites",
            "schema": [
              { "column": "id", "value": "INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL" },
              { "column": "syncId", "value": "TEXT UNIQUE" },
              { "column": "code", "value": "TEXT NOT NULL" },
              { "column": "title", "value": "TEXT NOT NULL" },
              { "column": "recordType", "value": "INTEGER DEFAULT 0 NOT NULL" },
              { "column": "editable", "value": "INTEGER DEFAULT 0 NOT NULL" },
              { "column": "deletable", "value": "INTEGER DEFAULT 0 NOT NULL" },
              { "column": "last_modified", "value": "INTEGER DEFAULT (strftime('%s', 'now'))" }   
            ],
            "indexes": [
                {"name": "index_site_on_last_modified","value": "last_modified DESC"}
            ]
        },
        {
            "name": "tickets",
            "schema": [
                { "column": "id", "value": "INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL" },
                { "column": "syncId", "value": "TEXT UNIQUE" },
                { "column": "num", "value": "TEXT UNIQUE NOT NULL" },
                { "column": "siteId", "value": "TEXT NOT NULL" },
                { "column": "title", "value": "TEXT NOT NULL" },
                { "column": "desc", "value": "TEXT" },
                { "column": "img", "value": "TEXT" },
                { "column": "recordType", "value": "INTEGER DEFAULT 0 NOT NULL" },
                { "column": "editable", "value": "INTEGER DEFAULT 0 NOT NULL" },
                { "column": "deletable", "value": "INTEGER DEFAULT 0 NOT NULL" },
                { "column": "last_modified", "value":"INTEGER DEFAULT (strftime('%s', 'now'))" },
                {
                    "foreignkey": "siteId",
                    "value": "REFERENCES sites(id)"
                }
            ],
            "indexes": [
                {"name": "index_ticket_on_siteId","value": "siteId"},
                {"name": "index_ticket_on_last_modified","value": "last_modified DESC"},
                {"name": "index_ticket_on_title_desc", "value": "title ASC, desc"}
            ]
        }
    ]
}

**Comment by jepiqueau** [comment]
@MonicaExplan In a meantime i test this
```js
  async runTest(): Promise<void> {
    try {
      let result: any = await this._sqlite.echo("Hello World");

      // ************************************************
      // Import Full Version 1 Schema Issue#164
      // ************************************************
      // test Json object validity
      result = await this._sqlite
                            .isJsonValid(JSON.stringify(schemaVersion1));
      console.log(`>>>> after isJsonValid ${result.result}`)      
      if(!result.result) {
        return Promise.reject(new Error("IsJson failed"));
      }
      // full import
      result = await this._sqlite
                          .importFromJson(JSON.stringify(schemaVersion1));    
      if(result.changes.changes === -1 ) return Promise.reject(new Error("ImportFromJson 'full' failed"));

      // ************************************************
      // Create Sync Table and Date
      // ************************************************

      // create the connection to the database
      console.log("create SYNC Table and Date")
      let db = await this._sqlite
                        .createConnection("db-issue164", false,
                                          "no-encryption", 1);
      if(db === null) return Promise.reject(new Error("CreateConnection db-issue164 failed"));

      // open db testNew
      await db.open();

      // create synchronization table 
      result = await db.createSyncTable();
      if (result.changes.changes < 0) return Promise.reject(new Error("CreateSyncTable failed"));


      let syncDate: string = await db.getSyncDate();
      if(syncDate.length === 0) return Promise.reject(new Error("GetSyncDate failed"));

      // close the connection
      await this._sqlite.closeConnection("db-issue164"); 
      console.log("closeConnection Version 1")

      // ************************************************
      // Import Partial Version 1 Table data Issue#164
      // ************************************************

      // test Json object validity
      result = await this._sqlite
                            .isJsonValid(JSON.stringify(dataVersion1));
      console.log(`>>>> after isJsonValid ${result.result}`)      
      if(!result.result) {
        return Promise.reject(new Error("IsJson failed"));
      }
      // partial import
      result = await this._sqlite
                          .importFromJson(JSON.stringify(dataVersion1));    
      if(result.changes.changes === -1 ) return Promise.reject(new Error("ImportFromJson 'full' failed"));
      db = await this._sqlite
      .createConnection("db-issue164", false,
                        "no-encryption", 1);
      if(db === null) return Promise.reject(new Error("CreateConnection db-issue164 failed"));

      // open db testNew
      await db.open();

      // select all tables in db
      let query: string = "SELECT name FROM sqlite_master WHERE "
      query += "type='table' AND name NOT LIKE 'sync_table' "
      query += "AND name NOT LIKE '_temp_%' "
      query += "AND name NOT LIKE 'sqlite_%' "
      query += "ORDER BY rootpage DESC;";

      let ret = await db.query(query);
      if(ret.values.length !== 3 || ret.values[0].name !== "images" ||
                                    ret.values[1].name !== "messages" ||
                                    ret.values[2].name !== "users") {
        return Promise.reject(new Error("Query Tables Version1 failed"));
      }
      
      // close the connection
      await this._sqlite.closeConnection("db-issue164"); 

      // ************************************************
      // Import Full Version 2 Schema Issue#164
      // ************************************************
      // test Json object validity
      result = await this._sqlite
                            .isJsonValid(JSON.stringify(schemaVersion2));
      console.log(`>>>> after isJsonValid ${result.result}`)      
      if(!result.result) {
        return Promise.reject(new Error("IsJson failed"));
      }
      // full import
      result = await this._sqlite
                          .importFromJson(JSON.stringify(schemaVersion2));    
      if(result.changes.changes === -1 ) return Promise.reject(new Error("ImportFromJson 'full' failed"));

      db = await this._sqlite
          .createConnection("db-issue164", false,
                        "no-encryption", 2);
      if(db === null) return Promise.reject(new Error("CreateConnection db-issue164 failed"));

      // open db testNew
      await db.open();

      // create synchronization table 
      result = await db.createSyncTable();
      if (result.changes.changes < 0) return Promise.reject(new Error("CreateSyncTable failed"));


      syncDate = await db.getSyncDate();
      if(syncDate.length === 0) return Promise.reject(new Error("GetSyncDate failed"));

      // close the connection
      await this._sqlite.closeConnection("db-issue164"); 
      console.log("closeConnection Version 2")

      // ************************************************
      // Import Partial Version 2 Table data Issue#164
      // ************************************************

      // test Json object validity
      result = await this._sqlite
                            .isJsonValid(JSON.stringify(dataVersion2));
      console.log(`>>>> after isJsonValid ${result.result}`)      
      if(!result.result) {
        return Promise.reject(new Error("IsJson failed"));
      }
      // partial import
      result = await this._sqlite
                          .importFromJson(JSON.stringify(dataVersion2));    
      if(result.changes.changes === -1 ) return Promise.reject(new Error("ImportFromJson 'full' failed"));
      db = await this._sqlite
      .createConnection("db-issue164", false,
                        "no-encryption", 2);
      if(db === null) return Promise.reject(new Error("CreateConnection db-issue164 failed"));

      // open db testNew
      await db.open();

      // select all tables in db
      query = "SELECT name FROM sqlite_master WHERE "
      query += "type='table' AND name NOT LIKE 'sync_table' "
      query += "AND name NOT LIKE '_temp_%' "
      query += "AND name NOT LIKE 'sqlite_%' "
      query += "ORDER BY rootpage DESC;";

      ret = await db.query(query);
      if(ret.values.length !== 2 || ret.values[0].name !== "messages" ||
                                    ret.values[1].name !== "users") {
        return Promise.reject(new Error("Query Tables Version2 failed"));
      }
      
      // close the connection
      await this._sqlite.closeConnection("db-issue164"); 


    } catch (err) {
      return Promise.reject(err);
    }
  

  }

```
with 
```js
export const schemaVersion1: any = {
  database : "db-issue164",
  version : 1,
  encrypted : false,
  mode : "full",
  tables :[
      {
          name: "users",
          schema: [
              {column:"id", value: "INTEGER PRIMARY KEY NOT NULL"},
              {column:"email", value:"TEXT UNIQUE NOT NULL"},
              {column:"name", value:"TEXT"},
              {column:"age", value:"REAL"},
              {column:"last_modified", value:"INTEGER"}
          ],
          indexes: [
              {name: "index_user_on_name",value: "name"},
              {name: "index_user_on_last_modified",value: "last_modified DESC"},
              {name: "index_user_on_email_name", value: "email ASC, name", mode: "UNIQUE"}
          ],
      },
      {
        name: "messages",
        schema: [
          {column:"id", value: "INTEGER PRIMARY KEY NOT NULL"},
          {column:"title", value:"TEXT NOT NULL"},
          {column:"body", value:"TEXT NOT NULL"},
          {column:"last_modified", value:"INTEGER"}
        ],
      },
      {
        name: "images",
        schema: [
          {column:"id", value: "INTEGER PRIMARY KEY NOT NULL"},
          {column:"name", value:"TEXT UNIQUE NOT NULL"},
          {column:"type", value:"TEXT NOT NULL"},
          {column:"size", value:"INTEGER"},
          {column:"img", value:"BLOB"},
          {column:"last_modified", value:"INTEGER"}
        ],
      }

  ]

}

export const dataVersion1: any = {
  database : "db-issue164",
  version : 1,
  encrypted : false,
  mode : "partial",
  tables :[
      {
          name: "users",
          values: [
              [1,"Whiteley.com","Whiteley",30.5,1582536810],
              [2,"Jones.com","Jones",44.2,1582812800],
              [3,"Simpson@example.com","Simpson",69,1583570630],
              [4,"Brown@example.com","Brown",15,1590383895]
          ]
      },
      {
        name: "messages",
        values: [
            [1,"test post 1","content test post 1",1587310030],
            [2,"test post 2","content test post 2",1590388125]
        ]
      },
      {
        name: "images",
        values: [
          [1,"feather","png",null,Images[1],1582536810],
          [2,"meowth","png",null,Images[0],1590151132]
        ]
      }

  ]

}
export const schemaVersion2: any = {
  database : "db-issue164",
  version : 2,
  encrypted : false,
  mode : "full",
  tables :[
      {
          name: "users",
          schema: [
              {column:"id", value: "INTEGER PRIMARY KEY NOT NULL"},
              {column:"email", value:"TEXT UNIQUE NOT NULL"},
              {column:"name", value:"TEXT"},
              {column:"age", value:"REAL"},
              {column:"country", value:"TEXT"},
              {column:"last_modified", value:"INTEGER"}
          ],
          indexes: [
              {name: "index_user_on_name",value: "name"},
              {name: "index_user_on_last_modified",value: "last_modified DESC"},
              {name: "index_user_on_email_name", value: "email ASC, name", mode: "UNIQUE"}
          ],
      },
      {
        name: "messages",
        schema: [
          {column:"id", value: "INTEGER PRIMARY KEY NOT NULL"},
          {column:"title", value:"TEXT NOT NULL"},
          {column:"body", value:"TEXT NOT NULL"},
          {column:"last_modified", value:"INTEGER"}
        ],
      },
  ]

}
export const dataVersion2: any = {
  database : "db-issue164",
  version : 2,
  encrypted : false,
  mode : "partial",
  tables :[
      {
          name: "users",
          values: [
              [1,"Whiteley.com","Whiteley",30.5,"United of Kingdom",1582536810],
              [2,"Jones.com","Jones",44.2,"Australia",1582812800],
              [3,"Simpson@example.com","Simpson",69,"South Africa",1583570630],
              [4,"Brown@example.com","Brown",15,"United States", 1590383895],
              [5,"Jeep@example.com","Jeep",70,"France", 1590383980]
          ]
      },
      {
        name: "messages",
        values: [
            [1,"test post 1","content test post 1",1587310030],
            [2,"test post 2","content test post 2",1590388125],
            [3,"test post 3","content test post 3",1590389355],
        ]
      },
  ]

}
```
and it works fine on iOS, i will test for Android

**Comment by jepiqueau** [comment]
@MonicaExplan Ok it failed on Android so i will have a look closely to the code. Thanks for pointing this to me

**Comment by MonicaExplan** [comment]
Thank you very much

bye
Monica

**Comment by jepiqueau** [comment]
@MonicaExplan This has been fixed in release v3.2.0-11

**Comment by MonicaExplan** [comment]
@jepiqueau 
Thank you very much. It's working fine.
I've tested this latest version with  "@capacitor/core": "^3.0.2" and all is ok

Thanks
Monica

**Comment by jepiqueau** [comment]
@MonicaExplan I am pleased that it is now working good luck for your development
