### ISSUE TITLE
Improve description of createSyncTable and getSyncDate

### ISSUE THREAD

**Issue by khashashin** [capacitor-community/sqlite#165]
**Is your feature request related to a problem? Please describe.**
I've lost a lot of time by resolving an issue of missing tables. To be honest I'm still not sure if those methods are related to that but after I've called those methods running SQLite query did work. So if those methods doing something important the description like "Creating a Synchronisation table" is not enough in my opinion. And I didn't found any usable information about these methods.

I've imported following JSON using 

```
let jsonOBJ: any = await this.http
  .get('https://json.khas.dev/study-summon/test_database-scheme')
  .toPromise();
await this.dbService.isJsonValid(JSON.stringify(jsonOBJ));
await this.dbService.importFromJson(JSON.stringify(jsonOBJ));
```

Then I've checked if the Tables exists using SQLite Browser. They where created.

Then I've ran the query to insert values in to the created Database:

```
async createDBConnection() {
  let db: SQLiteDBConnection;
  await this.dbService
    .retrieveConnection(DATABASE_NAME)
    .then((_db) => (db = _db));
  db.open();

  return db;
}
let m = {
  33,
  'Test Module',
  '#000fff',
  null,
  null,
  null,
  'Last Homework'
}
async create() {
    let db = await this.createDBConnection();
    let VALUES = `(${m.id},"${m.name}","${m.color}","${m.room}","${m.tag}","${m.event}","${m.homeWork}")`;
    let sqlQuery = `INSERT INTO modules (id,name,color,room,tag,event,home_work) VALUES ${VALUES};`;
    let querySet = await db.run(sqlQuery);

    if (!querySet.changes.changes) return null;
    else {
      console.log('>>>>>>>>>>>>>>>>>>> create: ', JSON.stringify(querySet));
    }
  }

```
After that I got error that the Table `modules` is not exists

**Describe the solution you'd like**
Make clear description of these methods and describe what is the purpose of them.

**Describe alternatives you've considered**
Call `db.createSyncTable()` and `db.getSyncDate()` to be able to insert, delete, update values in your Database.

**Comment by jepiqueau** [comment]
@khashashin did you read the doc ImportExportJson.md

**Comment by khashashin** [comment]
Thx for pointing to this docs. So if I understood it correctly the synchronization date is important think and the database is not usable if you not call `db.createSyncTable()` before trying to insert any data in to your Database. In other words, inserting data in to Database relies somehow to table `sync_table` which is not exists if you don't call  `db.createSyncTable()` after importing data using ` db.importFromJson()`. Am I right?

**Comment by jepiqueau** [comment]
@khashashin yes you are see in angular-sqlite-app-starter the import json examples

**Comment by khashashin** [comment]
@jepiqueau Okay, thanks for clarifying.
