### ISSUE TITLE
Get DB Version

### ISSUE THREAD

**Issue by MonicaExplan** [capacitor-community/sqlite#166]
Hi 
I'm searching for a method to get the version of DB installed on the device but I can't find it.

Is there a method or a propery to get the version od the DB? If yes, this version number corresponds to the "version" contained in json whem importing?

Thanks
Monica

**Comment by jepiqueau** [comment]
@MonicaExplan There is no method, i may add one, you can get the version by this query statement
```
const stmt = "PRAGMA user_version;";
const ret = db.query(stmt);
const version = ret.value[0]["user_version"]
```
this  should work too

**Comment by jepiqueau** [comment]
@MonicaExplan the method db.getVersion() has been added in 3.2.0

**Comment by MonicaExplan** [comment]
@jepiqueau 
Oh thank you!! And I'm sorry: I haven't seen this method it in the API docs. Sorry

**Comment by jepiqueau** [comment]
@MonicaExplan it was not existing I add it on your request thanks for asking it will benefit to everyone

**Comment by MonicaExplan** [comment]
Hi
this new method is notexactly what I need. Maybe I have not explained my resuest in the right mode.
I need to get DB version = "version" attribute in the json file I import
I have tested with a value of "version" attribute in the json = 451 but getVersion() return 2... 

thanks

**Comment by MonicaExplan** [comment]
All is ok. The getVersion() retry the exact value of my "version" attribute in json DB schema.
Thanks
