### ISSUE TITLE
Ability to add views with JSON format

### ISSUE THREAD

**Issue by amiral84** [capacitor-community/sqlite#167]
As far as I have checked documentation and inspecting code, I don't find any support for creating views with JSON format. Could there be a feature to add views that are type of `JSONView[]` just like `JSONTable[]`?

**Comment by jepiqueau** [comment]
@amiral84 thanks for using the plugin. I do not know what do you mean by `JSONView[]` and to which SQLite element they will be connected to. So you have to be more explicit and give an example of what you try to achieve.

**Comment by amiral84** [comment]
I mean views that are used in every SQL, SQLite, PostgreSQL, MySQL, MSSQL, etc. they all support it. Views are combination of data from different tables and it is very basic concept in SQL.
`
{
  "database": "foo-db",
  "version": 1,
  "encrypted": false,
  "mode": "full",
  "tables": [
    {
      "name": "foo",
      "schema": [
        { "column": "id", "value": "INTEGER PRIMARY KEY NOT NULL" },
        { "column": "foo", "value": "TEXT NOT NULL" },
        { "column": "bar", "value": "TEXT NOT NULL" },
      ]
    },
    {
      "name": "bar",
      "schema": [
        { "column": "id", "value": "INTEGER PRIMARY KEY NOT NULL" },
        { "column": "foo_bar", "value": "TEXT NOT NULL" },
        { "column": "bar_foo", "value": "TEXT NOT NULL" },
      ]
    }
  ]
}
`
As you can see above a table is created and you can then take this json file and import it to SQLite in your code. Now this SQLite repository doesn't support "views" because it is not yet implemented but in official SQLite it is supported. So I was thinking the ability to add views, just like above and here's an example that I was thinking:
`
{
  "database": "foo-db",
  "version": 1,
  "encrypted": false,
  "mode": "full",
  "tables": [
    {
      "name": "foo",
      "schema": [
        { "column": "id", "value": "INTEGER PRIMARY KEY NOT NULL" },
        { "column": "foo", "value": "TEXT NOT NULL" },
        { "column": "bar", "value": "TEXT NOT NULL" },
      ]
    },
    {
      "name": "bar",
      "schema": [
        { "column": "id", "value": "INTEGER PRIMARY KEY NOT NULL" },
        { "column": "foo_bar", "value": "TEXT NOT NULL" },
        { "column": "bar_foo", "value": "TEXT NOT NULL" },
      ]
    }
  ],
 "views": [
    {"value": "SELECT f.bar, b.foo_bar FROM foo f INNER JOIN bar b on f.id = b.id"}
  ]
}
`

**Comment by jepiqueau** [comment]
@amiral84 Thanks for your example, it is definitively something that i should add to my planning except if you want to make a PR and do it yourself. In that case it should be valid for all platforms except the Web. This should be implemented in the Stencil component `jeep-sqlite` so i prefer to do it myself.

**Comment by jepiqueau** [comment]
@amiral84 Tell me if you decide to do a PR otherwise i will put in on my list of todos.

**Comment by amiral84** [comment]
I think it would be better if you do it since if it is have to be added to `jeep-sqlite`. Awesome that we will get this kind of feature. It would be also nice to have SQL procedures as well, but I think it would be better to do different PR for SQL procedures.

**Comment by jepiqueau** [comment]
@amiral84 Ok so you will have to be patient as i am currently working on the `capacitor-data-storage-sqlite`

**Comment by amiral84** [comment]
Take as much time as you need :)

**Comment by jepiqueau** [comment]
@amiral84 This feature has been added in release `3.2.2-1` of the plugin. Feel free to close the issue when tested in your site. This is a great add-on

**Comment by jepiqueau** [comment]
@amiral84 It is now available so i close the issue. Thanks for asking this enhancement

**Comment by amiral84** [comment]
Thank you so much for this update. I will test and if I find something that should be addressed I will let you know :)
