### ISSUE TITLE
Help with locating database location when using capacitor-community/sqlite plugin with electron

### ISSUE THREAD

**Issue by ogadepoju** [capacitor-community/sqlite#168]
I'm new to ionic framework, in I'm tasked to develop an application that works on Android, iOS and desktop.
Of which I see ionic as the best tool for carrying out the project.
The Android part of the project is completed as it is up and running, but when building for desktop, using electron, I needed to save user login locally on the system, but I can't find the location of the database on my computer.
Note: after so many readings, I realised the database is located inside user/databases/APP_Name.
But I still can't find this location on my PC.
Kindly help asap  on how best to handle the issue
below are snapshot of my electron  package.json file 
![Screenshot (363)](https://user-images.githubusercontent.com/38212389/132100484-76bf2dee-9cfa-4a77-8b87-850798cbe3e7.png)

App package.json file: 
{
  "name": "newApp",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "https://ionicframework.com/",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "~12.1.1",
    "@angular/compiler": "~12.1.1",
    "@angular/core": "~12.1.1",
    "@angular/flex-layout": "^2.0.0-beta.10-4905443",
    "@angular/forms": "~12.1.1",
    "@angular/platform-browser": "~12.1.1",
    "@angular/platform-browser-dynamic": "~12.1.1",
    "@angular/router": "~12.1.1",
    "@capacitor-community/electron": "^4.0.3",
    "@capacitor-community/sqlite": "^3.2.0",
    "@capacitor/android": "3.1.2",
    "@capacitor/app": "1.0.2",
    "@capacitor/core": "3.1.2",
    "@capacitor/electron": "2.4.9",
    "@capacitor/haptics": "1.0.2",
    "@capacitor/keyboard": "1.0.2",
    "@capacitor/status-bar": "1.0.2",
    "@fullcalendar/angular": "^4.4.5-beta",
    "@ionic-native/core": "^5.35.0",
    "@ionic-native/document-viewer": "^5.35.0",
    "@ionic-native/downloader": "^5.35.0",
    "@ionic-native/file": "^5.35.0",
    "@ionic-native/file-opener": "^5.35.0",
    "@ionic-native/file-path": "^5.35.0",
    "@ionic-native/file-transfer": "^5.35.0",
    "@ionic-native/http": "^5.35.0",
    "@ionic-native/in-app-browser": "^5.35.0",
    "@ionic-native/native-storage": "^5.35.0",
    "@ionic-native/sqlite": "^5.36.0",
    "@ionic-native/sqlite-porter": "^5.35.0",
    "@ionic-native/status-bar": "^5.35.0",
    "@ionic/angular": "^5.5.2",
    "@ionic/storage": "^2.1.3",
    "cordova-plugin-advanced-http": "^3.2.0",
    "cordova-plugin-document-viewer": "^1.0.0",
    "cordova-plugin-file": "^6.0.2",
    "cordova-plugin-file-opener2": "^3.0.5",
    "cordova-plugin-file-transfer": "^1.7.1",
    "cordova-plugin-filepath": "^1.6.0",
    "cordova-plugin-inappbrowser": "^5.0.0",
    "cordova-plugin-nativestorage": "^2.3.2",
    "cordova-plugin-statusbar": "^2.4.3",
    "cordova-sqlite-storage": "^6.0.0",
    "electron-packager": "^15.3.0",
    "electron-winstaller": "^5.0.0",
    "integrator-cordova-plugin-downloader": "^1.1.0",
    "rxjs": "^6.6.7",
    "sqlite3": "^5.0.0",
    "tslib": "^2.2.0",
    "uk.co.workingedge.cordova.plugin.sqliteporter": "^1.1.1",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~12.1.1",
    "@angular-eslint/builder": "~12.0.0",
    "@angular-eslint/eslint-plugin": "~12.0.0",
    "@angular-eslint/eslint-plugin-template": "~12.0.0",
    "@angular-eslint/template-parser": "~12.0.0",
    "@angular/cli": "~12.1.1",
    "@angular/compiler": "~12.1.1",
    "@angular/compiler-cli": "~12.1.1",
    "@angular/language-service": "~12.0.1",
    "@capacitor/cli": "3.1.2",
    "@ionic/angular-toolkit": "^4.0.0",
    "@types/jasmine": "~3.6.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "@types/sqlite3": "^3.1.7",
    "@typescript-eslint/eslint-plugin": "4.16.1",
    "@typescript-eslint/parser": "4.16.1",
    "electron": "^13.1.7",
    "eslint": "^7.6.0",
    "eslint-plugin-import": "2.22.1",
    "eslint-plugin-jsdoc": "30.7.6",
    "eslint-plugin-prefer-arrow": "1.2.2",
    "jasmine-core": "~3.8.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~6.3.2",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "typescript": "~4.2.4"
  },
  "description": "An Ionic project"
}

code for creating the database:

![Screenshot (365)](https://user-images.githubusercontent.com/38212389/132100774-70097342-69d1-44a7-afac-ccd7f25e2d63.png)

Your help will be greatly appreciated. 
Thank you.

**Comment by digaus** [comment]
Are you using windows?

Then type user this path in the explorer -> `%USERPROFILE%/Databases`

**Comment by ogadepoju** [comment]
Thanks,
I've been able to find the solution to the issue by removing some unnecessary dependencies from my package.json and running npm run build.
