### ISSUE TITLE
Error: Cannot Find Module

### ISSUE THREAD

**Issue by ogadepoju** [capacitor-community/sqlite#169]
@jepiqueau 
Good day, 
I'm working on a project which utilises capacitor-community/sqlite for storing user login locally and it works well on my system, but when i did electron-pack and sent the packed folder to run on a different system, i was faced with an error stating:

Unhandled Promise Rejection
Error: Cannot find module 'C:/ebookevans/electron/node_modules/@capacitor-community/sqlite/electron/dist/plugin.js'
Require stack:
- C:/Users/USER/Desktop/dist/win-unpacked/resources/app.asar/build/src/rt/electron-plugins.js
- C:/Users/USER/Desktop/dist/win-unpacked/resources/app.asar/node_modules/@capacitor-community/electron/dist/core/index.js
- C:/Users/USER/Desktop/dist/win-unpacked/resources/app.asar/build/src/index.js
- 
    at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Object.<anonymous> (C:/Users/USER/Desktop/dist/win-unpacked/resources/app.asar/build/src/rt/electron-plugins.js:3:34) 

![error](https://user-images.githubusercontent.com/38212389/132547091-e5489a72-f251-464b-b0f3-9b23a4caa05d.JPG)

Things i've done;
I've done npm run build inside my app folder and also inside electron folder and it's still not working.
Urgent response will be greatly appreciated.

Thank you

**Comment by jepiqueau** [comment]
@ogadepoju I am not really a specialist in electron can you try to run electron:make instead and tell me if it works

**Comment by jepiqueau** [comment]
@ogadepoju  I  ask the developer `@Mike S (IT-MikeS)` of @capacitor-community/electron to help me on this

**Comment by ogadepoju** [comment]
Okay thank you @jepiqueau, 
I'll be expecting @IT-MikeS response/help on this issue.

Thank you.

**Comment by jepiqueau** [comment]
@ogadepoju Did you try to run electron:make in the electron folder

**Comment by jepiqueau** [comment]
@digaus Can you help on this one ?

**Comment by digaus** [comment]
@ogadepoju @jepiqueau 

There is still an open issue for this: 

https://github.com/capacitor-community/electron/issues/135#issuecomment-912738532

Supposed to be fixed in the next electron release

**Comment by ogadepoju** [comment]
> @ogadepoju Did you try to run electron:make in the electron folder

Yes @jepiqueau  i did, but and it run well on my pc but once i once i send it to any pc, i had same issue

**Comment by ogadepoju** [comment]
> @ogadepoju @jepiqueau
> 
> There is still an open issue for this:
> 
> [capacitor-community/electron#135 (comment)](https://github.com/capacitor-community/electron/issues/135#issuecomment-912738532)
> 
> Supposed to be fixed in the next release

When is the next release please ?

**Comment by digaus** [comment]
> > @ogadepoju @jepiqueau
> > There is still an open issue for this:
> > [capacitor-community/electron#135 (comment)](https://github.com/capacitor-community/electron/issues/135#issuecomment-912738532)
> > Supposed to be fixed in the next release
> 
> When is the next release please ?

This is something I do not know. I think when @IT-MikeS finds the time he will do a release :)

**Comment by ogadepoju** [comment]
> > > @ogadepoju @jepiqueau
> > > There is still an open issue for this:
> > > [capacitor-community/electron#135 (comment)](https://github.com/capacitor-community/electron/issues/135#issuecomment-912738532)
> > > Supposed to be fixed in the next release
> > 
> > 
> > When is the next release please ?
> 
> This is something I do not know. I think when @IT-MikeS finds the time he will do a release :)

Thank you @digaus  for the response. I hope the release is out ASAP as i'm greatly behind schedule and i'm stuck presently.

**Comment by ogadepoju** [comment]
@IT-MikeS @digaus kindly make release out, i'm still waiting.

**Comment by jepiqueau** [comment]
@ogadepoju @digaus @IT-MikeS  you have to be patient these guys work so hard to make it happens. Do not forget that you are using a new technology which is just out of the box. One month earlier you could not use it to make your app. So you have your schedule but it should be aligned with the technology schedule. What you can be sure it will come

**Comment by IT-MikeS** [comment]
Thank you @digaus for fielding the answers, all very spot on! 

Thank you to @jepiqueau as well, you're very right about lacking time that I wish I had!

The fixes will be out soon, and I am trying to get through stuff as quick as I can but life does happen so things get delayed, however thank you for using the project to you all and I hope you like the next release!

**Comment by CosminCraciun** [comment]
I had this issue fixed in my project. Found the absolute path in `electron/src/rt/electron-plugins.js`

Replaced:

> const CapacitorCommunitySqlite = require('......\node_modules\\@capacitor-community\\sqlite\\electron\\dist\\plugin.js')

with

> import * as CapacitorCommunitySqlite from '@capacitor-community/sqlite/electron/dist/plugin';

**Comment by peakcool** [comment]
@CosminCraciun yes, I have also encountered this problem, it seems that the fixes mentioned by @IT-MikeS  did not work, but your method will work

The following are related issues:

https://github.com/capacitor-community/electron/pull/151

https://github.com/capacitor-community/electron/issues/135

**Comment by ogadepoju** [comment]
@CosminCraciun  solution worked just fine.
Many thanks
