### ISSUE TITLE
Spatialite integration

### ISSUE THREAD

**Issue by KartanoDev** [capacitor-community/sqlite#171]
Hello!

We are trying to load a sqlite database that have tables with GEOMETRY field.

Is there any way to load this field with spatialite module or transform it to other that capacitor sqlite plugin can read it?

Let me know if you need more information about it, and sorry for the inconveniences.

Thanks, Kartano.

**Comment by jepiqueau** [comment]
@KartanoDev thanks for using the plugin i already answer that one issue#45. If you can provide a wrapper specification from spatialite to capacitor sqlite plugin and give me tables schema and data with GEOMETRY field. this wrapper should use capacitor sqlite to store and make the link to spatialite.

**Comment by KartanoDev** [comment]
Hello @jepiqueau, we don't have any  wrapper specification from spatialite to capacitor sqlite plugin.

This is the schema for one of the tables:

![image](https://user-images.githubusercontent.com/80762651/133603060-835f3c26-008c-4cf9-a8ae-b2e6f86e42d3.png)

**Comment by jepiqueau** [comment]
@KartanoDev Can you give me an example of data  corresponding to that schema and how is the GEOMETRY data type?

**Comment by jepiqueau** [comment]
@KartanoDev is the Geopoly sqlite3 extension (https://www.sqlite.org/geopoly.html) can be used? is it the same?

**Comment by KartanoDev** [comment]
@jepiqueau I need to transform this GEOMETRY field to AsGeoJson like this:

![image](https://user-images.githubusercontent.com/80762651/133763336-c7ab36d1-107a-495e-bc79-5efe89f05f2c.png)

**Comment by jepiqueau** [comment]
@KartanoDev Is it something that you would like to do or not. How to you get the Geometry data from? which software. you have to give me a bit of your scenario so i can understand. Is spatialite an app install on Windows or Mac ...

**Comment by jepiqueau** [comment]
@KartanoDev What is the tool you are using to  show me the data

**Comment by KartanoDev** [comment]
@jepiqueau We want to display data on a map. For this we need to have transform GEOMETRY field to AsGeoJson type like:

"{"type":"Point","coordinates":[-72.98352140181473,41.25610730677585]}"

To transform this we are using spatialite_gui in Windows:

https://www.gaia-gis.it/fossil/spatialite_gui/index

**Comment by jepiqueau** [comment]
@KartanoDev for me the complete scenario step by step is not clear Could you describe it
it seems somehow that you first enter all your GEOMETRY in `spatialite_gui` so if it is the case where do you use sqlite and why would you like to store GEOMETRY, we could store AsGeoJson type using the sqlite Json1 extension?

**Comment by jepiqueau** [comment]
@KartanoDev No news from you so i close the issue
