### ISSUE TITLE
isStoreOpen is set asynchronously in CapacitorSQLiteWeb constructor, which makes a rapid subsequent call to createConnection fail

### ISSUE THREAD

**Issue by sidquisaad** [capacitor-community/sqlite#172]
**Describe the bug**
The constructor of class `CapacitorSQLiteWeb` initializes member `isStoreOpen` by calling async function `isStoreOpen()` provided by jeep-sqlite. The call is made asynchronously, so the constructor continues execution and returns an instance. Immediately calling `createConnection()` on said instance may fail if the Promise from before is not yet settled at the time of the call.

**To Reproduce**

1. Instantiate a `CapacitorSQLiteWeb` object
2. Immediately call `createConnection()` on the instantiated object.
(See my rudimentary debugging in the screenshots).

**Expected behavior**
The member variable should be set synchronously.

**Screenshots**
- Several `console.log()` statements were placed on lines 18, 26, and 50 for debugging purposes.
![image](https://user-images.githubusercontent.com/25284407/133886092-887c63d0-8fa9-4667-83ea-379c31968e0c.png)
- The order of calls is shown here. Notice how B is still false and only then the Promise resolves (A1 lines).
![image](https://user-images.githubusercontent.com/25284407/133886201-fa44f810-4cc9-42fe-8833-6adf703c3141.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Chrome / Firefox
- Version 93.0.4577.82 / 91.0.2 

**Additional context**
This may affect other methods of the `CapacitorSQLiteWeb` class.
- A quick workaround during my debugging, I had the value explicitly checked and set inside the `createConnection()` method
![image](https://user-images.githubusercontent.com/25284407/133886313-820f8191-934d-4c45-816f-ae1cdf1854ec.png)
- And as expected now it works correctly
![image](https://user-images.githubusercontent.com/25284407/133886331-ca51ad58-5e3d-4f75-a4b6-be97860a77ab.png)

**Comment by jepiqueau** [comment]
@sidquisaad thanks for using the plug-in and for your comments.which version of the plug-in and jeep-sqlite are you using? I will have a look tomorrow.

**Comment by sidquisaad** [comment]
@jepiqueau Thank you. I'm using @capacitor-community/sqlite 3.2.2 and jeep-sqlite v1.2.1.

**Comment by jepiqueau** [comment]
@sidquisaad Sorry to come back a bit late, i was busy on `@capacitor-community/photoviewer` Which framework are you using for the app ?.  In the app when you initialize the plugin and the platform is web do you have 
```
          await customElements.whenDefined('jeep-sqlite');

```
something like this in angular
```
  initializeApp() {
    this.platform.ready().then(async () => {
      this.sqlite.initializePlugin().then(async (ret) => {
        this.initPlugin = ret;
        const p: string = this.sqlite.platform;
        console.log(`plaform ${p}`);
        if( p === "web") {
          this.isWeb = true;
          await customElements.whenDefined('jeep-sqlite');
          const jeepSqliteEl = document.querySelector('jeep-sqlite');
          if(jeepSqliteEl != null) {
            console.log(`isStoreOpen ${await jeepSqliteEl.isStoreOpen()}`)
            console.log(`$$ jeepSqliteEl is defined}`);
          } else {
            console.log('$$ jeepSqliteEl is null');
          }
        }
        try {
          console.log(`going to create a connection`)
          const db = await this.sqlite.createConnection("db_issue9",false,"no-encryption", 1);
          console.log(`db ${JSON.stringify(db)}`)
          await db.open();
          console.log(`after db.open`)
          let query = `
          CREATE TABLE IF NOT EXISTS test (
            id INTEGER PRIMARY KEY NOT NULL,
            name TEXT NOT NULL
          );
          `
          console.log(`query ${query}`)
          const res: any = await db.execute(query);
          console.log(`res: ${JSON.stringify(res)}`)
          await db.close();
...

```

**Comment by jepiqueau** [comment]
@sidquisaad any progress on your side?

**Comment by sidquisaad** [comment]
Hello @jepiqueau. I'm so sorry about the late reply, I've been busy on another project.
So, I'm using Vue 3. In the code you provided, I have a few remarks:
- `this.platform.ready()`, I'm not finding any alternative for this in Vue. I'm instead using a listener on `DOMContentLoaded`
- `this.sqlite.initializePlugin()` I do not recognize this function from any of the docs or sample apps, am I missing something ?

My application init flow is as follows:

```
// main.ts
window.addEventListener('DOMContentLoaded', () => {
	if (Capacitor.getPlatform() === 'web') {
                /* MARK_1 */
		const jeepSqlite = document.createElement('jeep-sqlite');
		document.body.appendChild(jeepSqlite);
		import('jeep-sqlite/loader').then(module => {
			const { defineCustomElements, applyPolyfills } = module;
			applyPolyfills().then(() => {
				defineCustomElements(window);
			});
		});
	}

	CapacitorSQLite.checkConnectionsConsistency({
		dbNames: [], // i.e. "i expect no connections to be open"
	}).catch((e) => {
		console.debug(e);
	});

	const app = createApp(App)
		.use(IonicVue)
		.use(router);

	app.component('main-layout', MainLayout);

	router.isReady().then(() => {
		app.mount('#app');
	});
});
```

```
// App.vue
...
onMounted(async () => {
      ...
      try {
	      const sqlite = new SQLiteConnection(CapacitorSQLite);
      
	      if (Capacitor.getPlatform() === "web") await customElements.whenDefined("jeep-sqlite");
      
	      await createConnection({
		      type: "capacitor",
		      driver: sqlite,
		      database: process.env.VUE_APP_DB_NAME,
		      version: process.env.VUE_APP_DB_VERSION,
		      entities: entities,
		      migrations: migrations,
		      migrationsTransactionMode: "all",
		      synchronize: false,
		      migrationsRun: true,
	      });
      } catch (e) {
	      console.error(e);
	      return await handleDBError();
      }
      ...
      // isLoading is just a flag that delays the mounting of other components until the App is properly initialized.
      isLoading.value = false;
});
```

This still yields the same error. I have tried moving `await customElements.whenDefined("jeep-sqlite")` from App.vue and putting it where it says `/* MARK_1 */`, but the page never load.

**Comment by jepiqueau** [comment]
@sidquisaad This will come in the next release, i didn't publish it yet as i have to make the modification to the vue and react hooks and also the angular service and update all the application. The two methods added are `initWebStore` as requested and `saveToStore` to save the database on request without closing the connection. if you look at the `https://github.com/capacitor-community/sqlite`you will see the modifications. you will have also to update `jeep-sqlite` to  1.3.0. May be you could do some testing by amending the code directly in your app. to call it
```
...
      if(platform === "web") {
        await customElements.whenDefined('jeep-sqlite');
        const jeepSqliteEl = document.querySelector('jeep-sqlite');
        if(jeepSqliteEl != null) {
          await sqliteConnection.initWebStore()
...
```

**Comment by jepiqueau** [comment]
@sidquisaad I have updated @capacitor-community-sqlite to 3.2.3-1 and test it with `https://github.com/jepiqueau/vue-test-issue172`. Have a look and transpose it for your app which seems to use the TypeOrm driver. Tell me if it is  ok and thanks for pointing out this. Your proposed workaround was working but i prefer like you suggest to create an `initWebStore` method. i also took the opportunity to create a `saveToStore` method allowing to store the database not waiting for the `closeConnection` in case of browser deleting the cache

**Comment by sidquisaad** [comment]
@jepiqueau  dude you're awesome. Thank you very much. I'll check this out over the weekend and come back here with the results. Thank you so much.

**Comment by jepiqueau** [comment]
@sidquisaad 👍

**Comment by sidquisaad** [comment]
@jepiqueau I have just pulled in the new version for `@capacitor-community-sqlite` and `jeep-sqlite`, made the changes to the code to use `initWebStore()` when `platform` is web. I run a couple tests and it works flawlessly now. 

Thank you so much for your prompt replies and interaction, and please keep up the good work. I will now close the issue as it is resolved.
