### ISSUE TITLE
Vue Ionic Capacitor: java.lang.ClassCastException: class com.getcapacitor.community.database.sqlite.CapacitorSQLite cannot be cast to com.getcapacitor.Plugin

### ISSUE THREAD

**Issue by accron-1** [capacitor-community/sqlite#174]
**Describe the bug**
I using the plugin in a Vue Ionic Capacitor project.
After doing an upgrade of all the plugins from v2 -> v3, I get the following error in Android Studio on startup:
`java.lang.ClassCastException: class com.getcapacitor.community.database.sqlite.CapacitorSQLite cannot be cast to com.getcapacitor.Plugin`

**To Reproduce**
Package setup:
```json
"dependencies": {
    "@capacitor-community/sqlite": "3.2.0",
    "@capacitor/android": "^3.0.0-beta.0",
    "@capacitor/app": "^1.0.3",
    "@capacitor/cli": "^3.0.0",
    "@capacitor/core": "^3.0.0",
    "@capacitor/share": "^1.0.4",
    "@capacitor/splash-screen": "^1.1.2"
  }
```

**Expected behavior**
No errors

**Desktop (please complete the following information):**
- OS: Ubuntu 21.04

**Smartphone (please complete the following information):**
- Device: Android Emulator

**Additional context**
My `MainActivity.java` is 'empty':
```java
package com.doublecheckpro;
import com.getcapacitor.BridgeActivity;
public class MainActivity extends BridgeActivity {}
```

I do the import in my JS as such:
```javascript
import { CapacitorSQLite } from '@capacitor-community/sqlite'
```
I looked at the sample projects and see a different way of importing:
```javascript
import { useStorageSQLite } from 'vue-data-storage-sqlite-hook/dist'
```
but that gives me a compile error.

**Comment by jepiqueau** [comment]
@accron-1  your package.json should be updated as follow
``` 
"dependencies": {
    "@capacitor-community/sqlite": "^3.2.2",
    "@capacitor/android": "^3.2.2",
    "@capacitor/core": "^3.2.2",
...
}

"devDependencies": {
    "@capacitor/cli": "^3.2.2",
    "vue-sqlite-hook": "^2.1.0"
}
```
when done remove the android folder from your app and do the following
```
npm run build
npx cap add android
npx cap copy
npx cap open android
```
you have nothing to add in the MainActivity.java file

You can use or not the `vue-sqlite-hook `
if you use it do 
```
import { useSQLite} from 'vue-sqlite-hook/dist';

```
and not 
```
import { useStorageSQLite } from 'vue-data-storage-sqlite-hook/dist'
```
which is for the capacitor-data-storage-sqlite plugin
hope this will clarify

**Comment by accron-1** [comment]
Thank you for the quick reply!

I think the error is fixed, but I can't seem to get the storage permission to trigger as before.

Is the old way of doing it still correct?
```javascript
import { CapacitorSQLite } from '@capacitor-community/sqlite'
...
const handlerPermissions = CapacitorSQLite.addListener(
        'androidPermissionsRequest', async (data) => {
          if (data.permissionGranted === 1) {
             //do something
          }
      });
CapacitorSQLite.requestPermissions();
```

**Comment by jepiqueau** [comment]
@accron-1 this feature has been removed as it was not required and a lot of developers complain about it

**Comment by accron-1** [comment]
`db.open()` now gives me:
`Open: No available connection for database xyz
    at Object.cap.fromNative`
which used to work.

In the example projects I see `sqlite.retrieveConnection("testNew")`.

Have the APIs changed? What's the correct way of doing it now?

**Comment by accron-1** [comment]
I've looked at the Vue projects, and they seem very React-like, with hooks all over the place...

Regardless, in one file file I find this usage of `useSQLite()`:
https://github.com/jepiqueau/vue-sqlite-app-starter/blob/73d8afa9a41f71486ea1c7098915cca94535c326/src/App.vue#L53

In another version:
https://github.com/jepiqueau/vue-sqlite-app-starter/blob/255041b29ef835be6d1e2013b1c791a80620dc98/src/main.ts#L33

If I do the last one I get the error:
`Cannot destructure property 'onProgressImport' of 'undefined' as it is undefined.
    at useSQLite (useSQLite.js?046f:10)`

But I would it expect to work given the example above. Also, given the names of `onProgressImport()/Export` I assume they shouldn't not needed for connecting to the db.
I haven't tried the first one as I'm not importing/exporting anything.

Please advice.

**Comment by accron-1** [comment]
So I had to look at the Vue sample + plugin source code in a couple of different repos to figure out how it's supposed to work. I got this:

```javascript
import { useSQLite } from 'vue-sqlite-hook/dist';
...
const db = await useSQLite({}).createConnection('mydb');
if(db) {
       await db.open();
	try {
		await db.execute(`CREATE TABLE IF NOT EXISTS Test (
		              id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
		              name TEXT UNIQUE NOT NULL`);
		
		const res = await db.query('SELECT * FROM Test');
		//do something with 'res'
  	}
  	catch(e) {
  		
  	}
}
```

If this correct, a constructive suggestion: the `README` of each repo should not only show how to install the plugin, but also a `Get started` section with code like above or similar.
It shouldn't be required to clone the repos to dig into the projects and library source code to figure this all out. The `README` should have enough info to create, connect and query a db, without looking in other places.

Either way, thank you for your great work, and help, as always!!

**Comment by jepiqueau** [comment]
@accron-1 Did you had a look to `https://github.com/capacitor-community/sqlite/blob/master/docs/Ionic-Vue-Usage.md` i think it is all explained. I was forced to split the developer on several documents otherwise the readme would have been far too long, but there is a link in the Readme under the chapter `Documentation` on `Framework's usage`. May be you missed it. Anyhow i am glad that you find the solution by yourself and that all this frustration will disappear on the use of the plugin. Feel free to close the issue

**Comment by accron-1** [comment]
I didn't see it initially. I think it's a good example of more complex usage, but I think that something very short and simple in the `README` that you can just copy and paste and immediately get started with would be very useful.

Also, those examples have `useSQLite()`, which I don't think is correct based on the source code and my tests:
https://github.com/jepiqueau/vue-sqlite-hook/blob/a790ee0b7feb75375d54f5a76ef624d13d9bfb5c/src/useSQLite.ts#L204
(FWIW I think it makes more sense to send no params instead of an empty `{}`)

Thank you!

**Comment by jepiqueau** [comment]
@accron-1 i took into account your comment and you can now `@capacitor-community/sqlite@3.2.3-1` use  useSQLite() if you do not want to use the import/export progress listeners. I also updated all the `Ionic-Vue-Usage.md` documentation. Hope this clarify. Anyhow thanks for the comments
