### ISSUE TITLE
All functions give the same "Attempt to invoke virtual method '...' on a null object reference" error after attempting to encrypt db

### ISSUE THREAD

**Issue by AlessandroGandolfi** [capacitor-community/sqlite#175]
I tried to follow the docs to encrypt the db I was using since some weeks for an Angular Ionic app I'm developing but they are too much confusing honestly.
What I understood from the Angular usage docs and adapted to my case I had to:
- initialize the plugin
- check if database already existed with isDatabase() and if it didn’t:
             - create the connection with mode ‘no-encryption’ to the db
             - close it
             - set the secret with setEncryptionSecret() (this one is very poorly documented and not in the usage doc, if the GlobalSQLite.java method of changing passphrase is deprecated why is it still the first paragraph about encryption in the doc???)
             - create the connection with mode 'encryption' to the db
             - close it
- create the connection with mode 'secret' to the db
- open the db

Since the first time I tried to follow these steps, every method of the plugin I try to use gives the same error (screenshot attached):
"Attempt to invoke virtual method '...' on a null object reference" with the method/function signature instead of the 3 dots.

In the Android Studio console there are also problems about some keyset/keystore errors before the error I'm reporting (screenshots attached). They seem to be involved with the EncryptedSharedPreferences used for the setEncryptionSecret() method.

In GlobalSQLite.java I also commented the newsecret line and set secret to an empty string, as written in the comment above those lines.

Kinda offtopic: isDatabase() should be used without connection as written in the docs but in the implementation in the Angular usage page it throws 'no connection open' for whatever reason.

1. create (and use without any problems) a db without encryption
2. try to follow the steps documented in the docs, same as listed above

Expected behavior:
Not having the same error for every function I try to use in my code.

Screenshots:
Chrome inspect error (also present on Android Studio):
![chrome inspect error](https://user-images.githubusercontent.com/20190108/134169207-8a6ad35c-0c9b-44ab-85c8-86f63b07e9ba.PNG)
Android Studio error before the null object reference error:
![android console first part](https://user-images.githubusercontent.com/20190108/134169211-5c5c0e4a-ffdb-4480-b3b4-0214864b3868.PNG)
![android console second part](https://user-images.githubusercontent.com/20190108/134169214-744b9ac2-68dd-4490-bea2-2f3203d466c2.PNG)
Part of the code (in this case isDatabase()  is causing the error but I tried using other methods and the same thing happens):
![code causing the error](https://user-images.githubusercontent.com/20190108/134170811-a8f4f254-188c-4c12-89f9-896ea6d9c5cd.PNG)
Implementation of setEncryptionSecret() (the rest of the service is the same as in Angular usage, everything worked before trying to encrypt the db anyway):
![set encryption secret implementation](https://user-images.githubusercontent.com/20190108/134171141-e222ee0b-e6cd-47a2-b909-3eefc9610ace.PNG)

Desktop:
- OS: Windows 10
- Browser Chrome

Smartphone:
- Device: OnePlus 6
- OS: Android 11
- Browser: stock browser

Additional context:
I already tried everything at this link ( https://githubmemory.com/repo/capacitor-community/sqlite/issues/150 ) but nothing worked.

**Comment by jepiqueau** [comment]
@AlessandroGandolfi first look at `angular-sqlite-app-starter` you will find 

- in the `home.page.ts` the way to set the secret phrase
```
    if(this.native) {
      const secretPhrase = 'abbey clammy gird night test';
      const isSet = await this.sqlite.isSecretStored()
      if(!isSet.result) {
        await this.sqlite.setEncryptionSecret(secretPhrase);
      }
    }

```

- in `test2dbs.page.ts`an example to directly encrypt a database 
```
      if((await this._sqlite.isConnection("testSet")).result) {
        db1 = await this._sqlite.retrieveConnection("testSet");
      } else {
        
        db1 = await this._sqlite
                  .createConnection("testSet", true, "secret", 1);
      }
```

- in `testencryption.page.ts` an example of first create a database no-encrypted and encrypt it later

- and the new service in sqlite.service.ts

to understand it clone the app and run it after this when it works compare to what you have 

the GlobalSQLite.java was for those using the plugin before we introduce the `setEncryptionSecret` method

Hope this will clarify and if you still think that the documentation is not good enough feel free to comment or make PR

**Comment by AlessandroGandolfi** [comment]
@jepiqueau I tried running "npm install" after "git remote rm origin" but the installation failed. 
![error npm install starter app](https://user-images.githubusercontent.com/20190108/134214606-94f282d4-4c15-438d-898b-cb0000499514.PNG)

I also tried to change my code to be more similar to yours but the errors are the same but this time the "null object reference" is on the isSecretStored() call.
![changed code](https://user-images.githubusercontent.com/20190108/134214624-7f97f4b4-727d-4139-abc5-f2efb52f6d0c.PNG)

**Comment by AlessandroGandolfi** [comment]
With the same code as the last comment I tried to compile from Android Studio again after deleting cache, data and uninstalling the previous app and it worked. I don't know how, I already did that multiple times in the last hours, but maybe what I (and my PC) needed was just a little break. Thanks for the support @jepiqueau .

For someone that might end up here, allowBackup is set to false in my AndroidManifest.xml, I honestly don't know if it did change anything but if you're hopeless like I was today you could try that. It probably can affect the app keeping old data before the encryption and giving some kind of error after.

**Comment by jepiqueau** [comment]
@AlessandroGandolfi yes some cache problems were reported on Android when upgrading @capacitor/android. Sorry i should have warn you on this. But i am busy with the `@capacitor-community/photoviewer`. and it is difficult to swap my brain. I am please that you find out and that it is working now .
