### ISSUE TITLE
Issue trying to access JSON1 extension

### ISSUE THREAD

**Issue by adrirrFOS** [capacitor-community/sqlite#176]
Hi, I need to store some json fields and I would like to make use of json1 extension. I've been unsuccessful so far. Wondering if it really works with this plugin and if it does, can I have some guidance regarding how to load/use it please?

I am following the `angular-sql-app-starter example` and replaced some fields with a json content and the data is stored ok. I would like to be able to select using `json_each` for example

```SELECT DISTINCT user.name
  FROM user, json_each(user.phone)
 WHERE json_each.value LIKE '704-%';```


Package.json
```
    "@capacitor-community/sqlite": "^3.2.2",
    "jeep-sqlite": "^1.2.1",
```
thank you.

**Comment by jepiqueau** [comment]
@adrirrFOS the Json1 extension is loaded so you should not worry about the load.
Have you try the query
``` 

SELECT DISTINCT users.name FROM users,
            json_each(users.phone) WHERE json_each.value LIKE '704-%'';
```
this should work. See `angular-sqlite-app-starter`  `testjson1extension.page.ts` line 107

**Comment by adrirrFOS** [comment]
thank you
