### ISSUE TITLE
Error on trigger definition when importing JSON schema 

### ISSUE THREAD

**Issue by MonicaExplan** [capacitor-community/sqlite#177]
Hi

I'm trying to import a json file with this new trigger:"triggers": [
              {
              "name": "trigger_after_update_recordType_tickets",
              "timeevent": "AFTER UPDATE",
              "logic":"BEGIN SELECT CASE WHEN NEW.recordType = 3 THEN UPDATE images SET recordType = 3 WHERE ticketId=OLD.id END; END"
              }
]
But I get an error

Beside if I import the json with this below trigger json, all is ok
            "triggers": [
              {
                "name": "trigger_after_update_recordType_tickets",
                "timeevent": "AFTER UPDATE",
                "logic":"BEGIN UPDATE images SET recordType = 3; END;"
              }
	    ]

It seems that fails the WHERE clause ( WHERE ticketId=OLD.id END) in update images statment.

Could you hel p me to solve this error. What am I failing?
Thanks in advance
Monica

**Comment by jepiqueau** [comment]
@MonicaExplan can you share the json object so i can go for testing

**Comment by MonicaExplan** [comment]
Here is the content of my json file containing only DB schema


{
    "database": "consumer_plangei_",
    "version":418,
    "encrypted": false,
    "mode": "full",
    "tables":[
   
        {
            "name": "tickets",
            "schema": [
                { "column": "id", "value": "INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL" },
                { "column": "syncId", "value": "TEXT UNIQUE" },
                { "column": "num", "value": "TEXT UNIQUE NOT NULL" },
                { "column": "siteId", "value": "TEXT NOT NULL" },
                { "column": "title", "value": "TEXT NOT NULL" },
                { "column": "desc", "value": "TEXT" },
                { "column": "recordType", "value": "INTEGER DEFAULT 0 NOT NULL" },
                { "column": "editable", "value": "INTEGER DEFAULT 0 NOT NULL" },
                { "column": "deletable", "value": "INTEGER DEFAULT 0 NOT NULL" },
                { "column": "last_modified", "value":"INTEGER DEFAULT (strftime('%s', 'now'))" },
                { "foreignkey": "siteId","value": "REFERENCES sites(id) ON DELETE CASCADE" }
            ],
            "indexes": [
                {"name": "index_ticket_on_siteId","value": "siteId"},
                {"name": "index_ticket_on_last_modified","value": "last_modified DESC"},
                {"name": "index_ticket_on_title_desc", "value": "title ASC, desc"}
            ],
            "triggers": [
                {
                "name": "trigger_after_update_recordType_tickets",
                "timeevent": "AFTER UPDATE",
                "logic":"BEGIN SELECT CASE WHEN NEW.recordType = 3 THEN UPDATE images SET recordType = 3 WHERE ticketId=OLD.id END; END"
                }
            ]
        },
        {
          "name": "images",
          "schema": [
            { "column": "id", "value": "INTEGER PRIMARY KEY NOT NULL" },
            { "column": "syncId", "value": "TEXT UNIQUE" },
            { "column": "name", "value": "TEXT" },
            { "column": "format", "value": "TEXT" },
            { "column": "exif", "value": "TEXT" },
            { "column": "webPath", "value": "TEXT NOT NULL"},
            { "column": "path", "value": "TEXT NOT NULL"},
            { "column": "ticketId", "value": "INTEGER NOT NULL" },
            { "column": "recordType", "value": "INTEGER DEFAULT 0 NOT NULL" },
            { "column": "editable", "value": "INTEGER DEFAULT 0 NOT NULL" },
            { "column": "deletable", "value": "INTEGER DEFAULT 0 NOT NULL" },
            { "column": "last_modified", "value": "INTEGER DEFAULT (strftime('%s', 'now'))" },
            { "foreignkey": "ticketId", "value": "REFERENCES tickets(id) ON DELETE CASCADE" }
          ],
          "indexes": [
            {"name": "index_images_on_ticketId","value": "ticketId"},
            { "name": "index_images_on_last_modified", "value": "last_modified DESC" }
          ]
        }
    ]
}

**Comment by jepiqueau** [comment]
@MonicaExplan i will have a look i forgot to ask you which platform?

**Comment by MonicaExplan** [comment]
Oh no, I forgot to detail my project. Sorry.

"@capacitor/core": "^3.0.2",
"@capacitor-community/sqlite": "^3.2.0",
"@capacitor/android": "^3.0.2",
"@capacitor/app": "^1.0.3",

I'm testing on Android 

Thanks a lot

**Comment by jepiqueau** [comment]
@MonicaExplan Can you give the triggers SQLite statement corresponding that you want to execute( not the json one) it seems the trigger definition is not correct

**Comment by MonicaExplan** [comment]
here is my trigger, correctly created on the DB by DBBrowser for SQLite

CREATE TRIGGER trigger_after_update_recordType_tickets
AFTER UPDATE ON tickets 
WHEN NEW.recordType = 3 
BEGIN UPDATE images SET recordType = 3 WHERE ticketId=OLD.id;  END

Thanks

**Comment by jepiqueau** [comment]
@MonicaExplan  Now that you provide the right tested trigger in DBBrowser it works
so your json object should be
```json
{
  "database": "consumer_plangei_",
  "version":418,
  "encrypted": false,
  "mode": "full",
  "tables":[
  
      {
          "name": "tickets",
          "schema": [
              { "column": "id", "value": "INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL" },
              { "column": "syncId", "value": "TEXT UNIQUE" },
              { "column": "num", "value": "TEXT UNIQUE NOT NULL" },
              { "column": "siteId", "value": "TEXT NOT NULL" },
              { "column": "title", "value": "TEXT NOT NULL" },
              { "column": "desc", "value": "TEXT" },
              { "column": "recordType", "value": "INTEGER DEFAULT 0 NOT NULL" },
              { "column": "editable", "value": "INTEGER DEFAULT 0 NOT NULL" },
              { "column": "deletable", "value": "INTEGER DEFAULT 0 NOT NULL" },
              { "column": "last_modified", "value":"INTEGER DEFAULT (strftime('%s', 'now'))" }
          ],
          "indexes": [
              {"name": "index_ticket_on_last_modified","value": "last_modified DESC"},
              {"name": "index_ticket_on_title_desc", "value": "title ASC, desc"}
          ],
          "triggers": [
            {
            "name": "trigger_after_update_recordType_tickets",
            "timeevent": "AFTER UPDATE",
            "logic":"WHEN NEW.recordType = 3 BEGIN UPDATE images SET recordType = 3 WHERE ticketId=OLD.id; END;"
            }
        ]
    },
      {
        "name": "images",
        "schema": [
          { "column": "id", "value": "INTEGER PRIMARY KEY NOT NULL" },
          { "column": "syncId", "value": "TEXT UNIQUE" },
          { "column": "name", "value": "TEXT" },
          { "column": "format", "value": "TEXT" },
          { "column": "exif", "value": "TEXT" },
          { "column": "webPath", "value": "TEXT NOT NULL"},
          { "column": "path", "value": "TEXT NOT NULL"},
          { "column": "ticketId", "value": "INTEGER NOT NULL" },
          { "column": "recordType", "value": "INTEGER DEFAULT 0 NOT NULL" },
          { "column": "editable", "value": "INTEGER DEFAULT 0 NOT NULL" },
          { "column": "deletable", "value": "INTEGER DEFAULT 0 NOT NULL" },
          { "column": "last_modified", "value": "INTEGER DEFAULT (strftime('%s', 'now'))" },
          { "foreignkey": "ticketId", "value": "REFERENCES tickets(id) ON DELETE CASCADE" }
        ],
        "indexes": [
          {"name": "index_images_on_ticketId","value": "ticketId"},
          { "name": "index_images_on_last_modified", "value": "last_modified DESC" }
        ]
      }
  ]
};
```
When tested on your side please close the issue. trigger syntax is not as easy. I am pleased that it was not a bug this time.
look at `https://github.com/jepiqueau/vue-sqlite-app-starter/blob/main/src/components/JsonImportIssue177.vue`

**Comment by MonicaExplan** [comment]
@jepiqueau 
Hi
thanks for you help, I was lost in the logic.

Have a nice day
Monica
