### ISSUE TITLE
Foreign Key with combined columns

### ISSUE THREAD

**Issue by MonicaExplan** [capacitor-community/sqlite#179]
Hello,

is it possible, in import from json, use a FOREIGN KEY with combined columns?

And if it's possible, how is the syntax? One of this ipotesi?
(as DB schema below in this messagge)
Ipotesi 1
{ constraint: 'FK_ticketId, ticketSyncId', value: 'FOREIGN KEY (ticketId, ticketSyncId) REFERENCES tickets(id, syncId) ON DELETE CASCADE'},
Ipotesi 2
 { "foreignkey": "ticketId, ticketSyncId", "value": "REFERENCES tickets(id, ticketSyncId) ON DELETE CASCADE" } 

My Environment:
Android and Ios
"@capacitor/core": "^3.0.2",
"@capacitor-community/sqlite": "^3.2.0",

My use case is as follow:
        {
            "name": "tickets",
            "schema": [
                { "column": "id", "value": "INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL" },
                { "column": "syncId", "value": "TEXT UNIQUE" },
                { "column": "num", "value": "TEXT UNIQUE" },
                { "column": "siteId", "value": "TEXT NOT NULL" },
                { "column": "title", "value": "TEXT NOT NULL" },
                { "column": "desc", "value": "TEXT" },
                { "column": "recordType", "value": "INTEGER DEFAULT 0 NOT NULL" },
                { "column": "editable", "value": "INTEGER DEFAULT 0 NOT NULL" },
                { "column": "deletable", "value": "INTEGER DEFAULT 0 NOT NULL" },
                { "column": "last_modified", "value":"INTEGER DEFAULT (strftime('%s', 'now'))" },
                { "foreignkey": "siteId","value": "REFERENCES sites(id) ON DELETE CASCADE" }
            ],
            "indexes": [
                {"name": "index_ticket_on_siteId","value": "siteId"},
                {"name": "index_ticket_on_last_modified","value": "last_modified DESC"},
                {"name": "index_ticket_on_title_desc", "value": "title ASC, desc"}
            ],
            "triggers": [
              {
              "name": "trigger_after_update_recordType_tickets",
              "timeevent": "AFTER UPDATE",
              "logic":"WHEN NEW.recordType = 3 BEGIN UPDATE images SET recordType = 3 WHERE ticketId=OLD.id; END;"
              }
            ]
        },
        {
          "name": "images",
          "schema": [
            { "column": "id", "value": "INTEGER PRIMARY KEY NOT NULL" },
            { "column": "syncId", "value": "TEXT UNIQUE" },
            { "column": "name", "value": "TEXT" },
            { "column": "format", "value": "TEXT" },
            { "column": "exif", "value": "TEXT" },
            { "column": "webPath", "value": "TEXT NOT NULL"},
            { "column": "path", "value": "TEXT NOT NULL"},
            { "column": "ticketId", "value": "TEXT NOT NULL" },
            { "column": "ticketSyncId", "value": "TEXT NOT NULL" },
            { "column": "recordType", "value": "INTEGER DEFAULT 0 NOT NULL" },
            { "column": "editable", "value": "INTEGER DEFAULT 0 NOT NULL" },
            { "column": "deletable", "value": "INTEGER DEFAULT 0 NOT NULL" },
            { "column": "last_modified", "value": "INTEGER DEFAULT (strftime('%s', 'now'))" }
          ],
          "indexes": [
            {"name": "index_images_on_ticketId_ticketSyncId","value": "ticketId, ticketSyncId", "mode": "UNIQUE"},
            { "name": "index_images_on_last_modified", "value": "last_modified DESC" }
          ]
        }

Thanks a lot
Monica

**Comment by jepiqueau** [comment]
@MonicaExplan Did you try in DB-Browser what you are asking and did it works ? As ticketsId is a primary key and ticketSyncId is UNIQUE i do not understand why do you want to combine them  working with one or the other will work too but may be i am wrong. I think before to create an issue check that what you want to achieve is SQLite correct.

**Comment by MonicaExplan** [comment]
Hi @jepiqueau 
I'm sorry if you are thinking that I did not think before opening this issue.
In DB-Browser the froeign key was correctly created and used.
Maybe my example wasn't suited for this case, simply was the json code I can copy and paste instead to write a new one. I'm sorry for this.

**Comment by jepiqueau** [comment]
@MonicaExplan I did not want to be rude but i am busy on something else and having a quick look on what you sent i did not really pick-up the thing. So please give me the database schema  with and the  foreign key that you want to have so i can construct it quickly in DB-Browser so i will understand it and so look to what is wrong in the json format. 
All modifications in this part of the code is quite tedious and should be done without anything else in mind. Hope you will understand

**Comment by MonicaExplan** [comment]
@jepiqueau 
do not worry, all is ok. I understand your needs
enjoy

**Comment by jepiqueau** [comment]
@MonicaExplan i am expecting the two-tables that you want to make into relations
Can this help you
```
CREATE TABLE album(
  albumartist TEXT,
  albumname TEXT,
  albumcover BINARY,
  PRIMARY KEY(albumartist, albumname)
);

CREATE TABLE song(
  songid     INTEGER,
  songartist TEXT,
  songalbum TEXT,
  songname   TEXT,
  FOREIGN KEY(songartist, songalbum) REFERENCES album(albumartist, albumname)
);
```

**Comment by jepiqueau** [comment]
@MonicaExplan the corresponding JSON Object is
```
{
    database: 'db-issue179',
    version: 1,
    encrypted: false,
    mode: 'full',
    tables: [
      {
        name: 'album',
        schema: [
          { column: 'albumartist', value: 'TEXT NOT NULL' },
          { column: 'albumname', value: 'TEXT NOT NULL' },
          { column: 'albumcover', value: 'BINARY' },
          { column: 'last_modified', value: 'INTEGER' },
          { constraint: 'PK_albumartist_albumname', value: 'PRIMARY KEY (albumartist,albumname)'},
        ],
        indexes: [
          { name: 'index_album_on_albumartist_albumname', value: 'albumartist,albumname' },
          { name: 'index_album_on_last_modified', value: 'last_modified DESC' },
        ],
      },
      {
        name: 'song',
        schema: [
          { column: 'songid', value: 'INTEGER PRIMARY KEY NOT NULL' },
          { column: 'songartist', value: 'TEXT NOT NULL' },
          { column: 'songalbum', value: 'TEXT NOT NULL' },
          { column: 'songname', value: 'TEXT NOT NULL' },
          { column: 'last_modified', value: 'INTEGER' },
          {
            foreignkey: 'songartist,songalbum',
            value: 'REFERENCES album(albumartist,albumname)',
          },
        ],
        indexes: [
            { name: 'index_song_on_songartist_songalbum', value: 'songartist,songalbum' },
            {
            name: 'index_song_on_last_modified',
            value: 'last_modified DESC',
          },
        ],
      },
    ],
  };
```

**Comment by MonicaExplan** [comment]
@jepiqueau 
thanks
Monica

**Comment by jepiqueau** [comment]
@MonicaExplan did you succeed to do what you try to do now?

**Comment by MonicaExplan** [comment]
@jepiqueau yes, I did
thanks
