### ISSUE TITLE
uuid as Primary key: insert stament lastId is not the PK?

### ISSUE THREAD

**Issue by MonicaExplan** [capacitor-community/sqlite#180]
Ho

I'm using uuid as primary key. My table is
{
          "name": "testuuid",
          "schema": [
              { "column": "id", "value": "TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6))))" },
              { "column": "title", "value": "TEXT NOT NULL" },
              { "column": "desc", "value": "TEXT" },
          ]
}

Insert statment is ok, but I get {"changes":{"changes":1,"lastId":36}}
In DB Browser I can see this record:
2923482c-f54e-4dca-a8bb-6eb5355adb1c | test 2 uuid | desc uuid test

I'm expecting to have something like this:
{"changes":{"changes":1,"lastId":"2923482c-f54e-4dca-a8bb-6eb5355adb1c"}}
So, my doubt: is last id the PK just entered? It seems no....

Thanks for explanation about lastId
Monica

**Comment by jepiqueau** [comment]
@MonicaExplan the `lastId` returned correspond to the sqlite command `SELECT last_insert_rowid()` which is returning the internal id of the last row as an  integer and not the column `id`. if you want to have your id you must do `SELECT id FROM messages WHERE ROWID = last_insert_rowid()` so for the plugin 
```
    changes = YOUR INSERT command using db.run
    sqlcmd = "SELECT id FROM messages WHERE ROWID = ?";
    values = [changes.changes.lastId];
    res = await db.query(sqlcmd,values);

```
this should give you the expected result

**Comment by MonicaExplan** [comment]
thanks a lot
Monica
