### ISSUE TITLE
Plugin for Android stuck at executing CREATE TABLE statements

### ISSUE THREAD

**Issue by ranjithrd** [capacitor-community/sqlite#184]
**Describe the bug**

The plugin on Android is stuck on a call for `await db.execute(`CREATE TABLE....`)`. 

**To Reproduce**

1. Create any Ionic React project
2. Add this package using the instructions provided in README and in the Ionic-React.md doc
3. Use a `CREATE TABLE` statement 

**Expected behavior**

The statement shouldn't have taken more than a second or so. or, see iOS screenshot below

**Screenshots**

Some problems with my installation right now make it impossible for me to share the debug output. But I'm attaching expected behaviour (iOS) and actual behaviour (Android)

Expected Behaviour, working on iOS
<img width="399" alt="Screenshot 2021-10-13 at 12 20 51 AM" src="https://user-images.githubusercontent.com/32879598/137013157-f57c8159-6844-441c-9c17-e35a18793007.png">

Actual Behaviour, Android
![WhatsApp Image 2021-10-13 at 00 21 02](https://user-images.githubusercontent.com/32879598/137013345-50717506-a64a-468f-b12d-5fd4c2ec0b3e.jpeg)

**Code**

`App.tsx`
```js
import { useSQLite } from "react-sqlite-hook/dist"
import { useState } from "react"

// Singleton SQLite Hook
export let sqlite: any
// Existing Connections Store
export let existingConn: any
const App: React.FC = () => {
	const [existConn, setExistConn] = useState(false)
	existingConn = { existConn: existConn, setExistConn: setExistConn }
	const {
		echo,
		getPlatform,
		createConnection,
		closeConnection,
		isConnection,
		retrieveConnection,
		retrieveAllConnections,
		closeAllConnections,
		addUpgradeStatement,
		importFromJson,
		isJsonValid,
		copyFromAssets,
		isAvailable,
	} = useSQLite({})
	sqlite = {
		echo: echo,
		getPlatform: getPlatform,
		createConnection: createConnection,
		closeConnection: closeConnection,
		isConnection: isConnection,
		retrieveConnection: retrieveConnection,
		retrieveAllConnections: retrieveAllConnections,
		closeAllConnections: closeAllConnections,
		addUpgradeStatement: addUpgradeStatement,
		importFromJson: importFromJson,
		isJsonValid: isJsonValid,
		copyFromAssets: copyFromAssets,
		isAvailable: isAvailable,
	}

     return ...

}
```

`Page.tsx`
```js
import ...
import { sqlite } from "../App"

function Page() {
	const [res, setRes] = useState({})

	useEffect(() => {
		;(async () => {
			try {
				let db
				const connectionName = "steward"
				try {
					db = await sqlite.retrieveConnection(connectionName)
				} catch (error) {
					console.log("retrieveConnection error", error)
				}

				try {
					if (!db) {
						await sqlite.closeConnection(connectionName)
					}
				} catch (error) {
					console.log("closeConnection error", error)
				}

				try {
					if (!db) {
						setRes("creating connection on next line")
						db = await sqlite.createConnection(connectionName)
						setRes("created connection")
					}
				} catch (error) {
					console.log("createConnection error", error)
				}

				if (!db) {
					throw new Error("unable to create or retrieve connection")
				}

				setRes("opening db on next line")
				await db.open()
				setRes("opened db")

				setRes("executing create statements on next line") // HERE IS WHERE IT'S STUCK
				await db.execute(`
        DROP TABLE chores;
        DROP TABLE items;

        CREATE TABLE IF NOT EXISTS chores (
          id INTEGER PRIMARY KEY,
          name TEXT,
          next_due DATE,
          completed BOOLEAN,
          repeats BOOLEAN,
          frequency INT
        );
        
        CREATE TABLE IF NOT EXISTS items (
          id INTEGER PRIMARY KEY,
          name TEXT,
          image TEXT,
          next_buy DATE,
          buy_from TEXT,
          supplied BOOLEAN
        );
        `)
				setRes("executed create statements")

				setRes("executing insert on next line")
				await db.execute(
					"INSERT INTO chores VALUES(null, 'Clean room 2', '2021-12-11', false, false, 1)"
				)
				setRes("executed insert")

				setRes("selecting from table")
				setRes(await db.query("SELECT * FROM chores;"))
			} catch (e) {
				console.error(e)
			}
		})()
	}, [])

       return ...
}
```

**Desktop (please complete the following information):**

- OS: MacOS
- Version 11

**Smartphone (please complete the following information):**

- Device: RealMe GT Master Edition
- OS: Android (ColourOS)
- Version: 11

**Additional context**

The code for instantiating the database is from #153 with very little modification.

This is a debug APK build, through Android studio and `ionic capacitor build android`. I couldn't use emulators unfortunately. I'll try my best to check emulators or other debug builds, but I'd like to know if there's anything wrong with the code that I'm using.

Note: I'm 100% sure that this is a mistake on my end, but there doesn't seem to be a platform that I know of where I can ask this other than here on issues. Besides, I think posting this here might help other folks who might get stuck in a similar situation. 

Thank you so much for your work on the package. I hope I can get this resolved ASAP.

**Comment by jepiqueau** [comment]
@ranjithrd can you share your package.json file. you should look at `https://github.com/jepiqueau/react-sqlite-app-starter` which is an updated app to help you starting.
the execute is wrong
```
INSERT INTO chores VALUES(null, 'Clean room 2', '2021-12-11', false, false, 1)
```
replace with
```
INSERT INTO chores(name,next_due,completed,repeats,frequency) VALUES ('Clean room 2', '2021-12-11', false, false, 1);

```
and add AUTOINCREMENT  in   `id INTEGER PRIMARY KEY,`

this should work

**Comment by jepiqueau** [comment]
@ranjithrd Hi, you cannot Drop a table if it does not exist so make the following modifications
```
                    DROP TABLE IF EXISTS chores;
                    DROP TABLE IF EXISTS items;
```
and it should work

**Comment by jepiqueau** [comment]
@ranjithrd Look at `https://github.com/jepiqueau/react-sqlite-app-starter` i have added a test for this issue and it works fine. So i do not know what is going on on your app. Can you share it ?

**Comment by ranjithrd** [comment]
@jepiqueau 
Sure, here you go.
https://github.com/ranjithrd/ion-test

**Comment by ranjithrd** [comment]
@jepiqueau 
Hey Jean, sorry for not responding earlier. 
I tried this approach, and I'm very, very, very happy to say it worked. 

Thank you so much for helping me out and maintaining this package. 
Closing this issue. Thanks again.
