### ISSUE TITLE
importing zipped files using copyFromAssets method

### ISSUE THREAD

**Issue by psantos9** [capacitor-community/sqlite#191]
**Is your feature request related to a problem? Please describe.**
When including large pre-existing database files in the application, it would be interesting to be able to store them in a compressed format (zip, for instance).
Currently the **copyFromAssets** method doesn't allow to import compressed database files.

**Describe the solution you'd like**
1. In the *assets/databases/databases.json* to be able to include *.db* and *.zip* filenames.
2. All *.db* entries contained in each described *.zip* (may be multiple) are imported by the **copyFromAssets** method.

**Describe alternatives you've considered**
Currently could not find an alternative, the db files must be included in the assets uncompressed.

**Comment by jepiqueau** [comment]
@psantos9 this is a good suggestion I will have a look if I can find a solution.

**Comment by jepiqueau** [comment]
@psantos9 What should we do if a .db entry contained in a .zip already exists on the database default folder. Do we erase it or do we send an error message as this .db could have been modified from a previous run of the app. Usually the copyFromAssets should only be run once at the first app run. Can you make some suggestions

**Comment by psantos9** [comment]
@jepiqueau My suggestion would be to implement the same behaviour as for the unzipped files (overwrite existing -  without throwing error). Thank you very much for looking into this request!

**Comment by jepiqueau** [comment]
@psantos9 i got it already preliminary working for iOS, i think i will add an optional parameter overwrite set by default to `true` but keeping the possibility to not overwrite them (overwrite parameter set to `false`) if they have been already unzipped and and the already existing on disk. What is your targeted platform?

**Comment by psantos9** [comment]
@jepiqueau I'm targeting android. I think your solution is perfect

**Comment by jepiqueau** [comment]
@psantos9 this is fixed in v3.2.5-2, test it and revert to me

**Comment by jepiqueau** [comment]
@psantos9 Did you had time to test it? Is it working as you wish ?

**Comment by jepiqueau** [comment]
@psantos9 As i do not get any comments from you i will close the issue. I spent quite some times to develop this. i think you were in a hurry to get it.
