### ISSUE TITLE
sqllite.ImportFromJson not working

### ISSUE THREAD

**Issue by DanielvdSpoel** [capacitor-community/sqlite#192]
**Describe the bug**
When importing json it doens't create the route table. When we try to collect things it give the error that the routes table doesn't excist

**To Reproduce**

Use this json object:
`
const JSONSchema = {
    database: 'storage',
    version: 1,
    encrypted: false,
    mode: 'full',
    tables: [
        {
            name: 'routes',
            schema: [
                { column: 'id', value: 'TEXT NOT NULL'},
                { column: 'name', value: 'TEXT NOT NULL' },
                { column: 'date', value: 'TEXT NOT NULL' },
                { constraint: 'routes_pk', value: 'PRIMARY KEY (id)'},
            ],
            indexes: [
                { name: 'routes_id_uindex', value: 'id' },
                { name: 'routes_id_uindex', value: 'name' },
            ],
        },
        {
            name: 'route_points',
            schema: [
                { column: 'id', value: 'INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL' },
                { column: 'route_id', value: 'TEXT NOT NULL' },
                { column: 'accuracy', value: 'REAL' },
                { column: 'altitude', value: 'REAL' },
                { column: 'altitudeAccuracy', value: 'REAL' },
                { column: 'heading', value: 'REAL' },
                { column: 'latitude', value: 'REAL' },
                { column: 'longitude', value: 'REAL' },
                { column: 'speed', value: 'REAL' },
                { column: 'TIMESTAMP', value: 'INTEGER' },
                {
                    foreignkey: 'route_id',
                    value: 'REFERENCES routes ON DELETE CASCADE',
                },
            ],
            indexes: [
                { name: 'route_points_id_uindex', value: 'id' },
            ],
        },
    ],
};
`
and import it like this:
`const tableQuery = `SELECT name FROM sqlite_master WHERE type='table' AND name='routes';`
    const tableResult = await db.query(tableQuery);
    if (tableResult.values.length === 0) {
      await console.log('table bestaat niet')
      const result = await sqlite.isJsonValid(JSON.stringify(JSONSchema));
      await console.log(result)
      if(!result.result) {
        throw new Error(`isJsonValid: "schemaToImport179" is not valid`);
      }
      const resJson = await sqlite.importFromJson(JSON.stringify(JSONSchema));
      await console.log(resJson)
      if(resJson.changes && resJson.changes.changes && resJson.changes.changes < 0) {
        throw new Error(`importFromJson: "full" failed`);
      }`

**Expected behavior**
Create the routes table

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Chrome

**Comment by jepiqueau** [comment]
@DanielvdSpoel Hi, Did you make some progress? keep me in the loop.

**Comment by DanielvdSpoel** [comment]
@jepiqueau Project is currently on hold for 2 weeks (we have exams on school) I hopefully will have time next week to make some progress

**Comment by jepiqueau** [comment]
@DanielvdSpoel Any progress on your side ?  without answer from you i will close the issue

**Comment by DanielvdSpoel** [comment]
@jepiqueau So sorry that I didn't respond, the code you send fixed everything. Thank you verry much for you help!
