### ISSUE TITLE
silence CapacitorSQLite debug messages in xcode debugger output window

### ISSUE THREAD

**Issue by mjgoeke** [capacitor-community/sqlite#194]
When running my capacitor app from within xcode, I rely on the debug output to see useful messages.
CapacitorSQLite is spamming the window with messages like
⚡️  To Native ->  CapacitorSQLite executeSet 114296743
⚡️  TO JS {"changes":{"changes":0,"lastId":3329}}

I'm unfamiliar with Xcode, so it's likely there's something I'm just missing, but nothing so far I've tried has worked.

Filtering the log in Xcode doesn't support regex, nor exclusion filters as far as I can tell.
Searching this repository I can't find the logging taking place, so I can't see if there's a flag to toggle.
Searching closed issues on this repo I find no one asking about this.

I'd like a solution that can disable, or filter out the messages CapacitorSQLite is emitting.

I'm on XCode 13.0

Thank you!

**Comment by jepiqueau** [comment]
@mjgoeke hi thanks for this comment but as you can see ⚡️ in the message means that it is coming from @capacitor/core and @capacitor/ios, so there is nothing i can do. This is the message passing in and out through the bridge.

**Comment by mjgoeke** [comment]
ok, thanks! I'll keep digging elsewhere

**Comment by jepiqueau** [comment]
@mjgoeke if you find something keep me aware thanks
