### ISSUE TITLE
Cannot find module jszip

### ISSUE THREAD

**Issue by berengere13** [capacitor-community/sqlite#197]
**Describe the bug**
I try to create msi with my stack angular / ionic / @capacitor-community/electron and the dependencies sqlite. 

**To Reproduce**

1. Run script "electron-builder build -c ./electron-builder.config.json -p always"
2. Generate the msi
3. Install the msi
4. Launch the app
5. A pop up error is open with error : 
6. Unhandled Promise Rejection
"vError: Cannot find module 'jszip'
Require stack:
- C:/Users/XXXXXXX/AppData/Local/Programs/APP_NAME/resources/app/node_modules/@capacitor-community/sqlite/electron/dist/plugin.js
- C:/Users/XXXXXXX/AppData/Local/Programs/APP_NAME/resources/app/build/src/rt/electron-plugins.js
- C:/Users/XXXXXXX/AppData/Local/Programs/APP_NAME/resources/app/node_modules/@capacitor-community/electron/dist/core/index.js
- C:/Users/XXXXXXX/AppData/Local/Programs/APP_NAME/resources/app/build/src/index.js
- 
    at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Object.<anonymous> (C:/Users/XXXXXXX/AppData/Local/Programs/APP_NAME/resources/app/node_modules/@capacitor-community/sqlite/electron/dist/plugin.js:9:18) "

**Expected behavior**
The applications runs well.

Extract of package.json form electron : 
"
  "dependencies": {
    "@capacitor-community/electron": "^4.0.3",
    "@capacitor-community/sqlite": "^3.2.5",
    "chokidar": "~3.5.2",
    "electron-context-menu": "^3.1.1",
    "electron-is-dev": "~2.0.0",
    "electron-serve": "~1.1.0",
    "electron-unhandled": "~3.0.2",
    "electron-updater": "~4.3.9",
    "electron-window-state": "~5.0.3",
    "sqlite3": "5.0.0"
  },
"

**Comment by jepiqueau** [comment]
@berengere13 Can you tell me how you did generate the msi ? You must add to your electron package.json file `    "jszip": "^3.7.1",`  or `npm install --save jszip` Sorry i forgot to add this to the readme.

**Comment by jepiqueau** [comment]
@berengere13 this has been fixed in release 3.3.1
