### ISSUE TITLE
feat: support databases without SQLite suffix

### ISSUE THREAD

**Issue by robingenz** [capacitor-community/sqlite#201]
Hi jepiqueau, 
again thank you for this great plugin.
I am currently trying to migrate from `cordova-sqlite-storage` to this plugin and wonder why it is necessary to rename the databases. 
I would like to continue using the databases with the previous name.

**Is your feature request related to a problem? Please describe.**

I would like to access databases that do not have the `SQLite.db` suffix.
Example 1: I want to access a database that is created by another plugin and whose name I cannot change. The name does not have the `SQLite.db` suffix.
Example 2: I want to be able to access an existing database without having to migrate it first.

**Describe the solution you'd like**

I would like to pass the full name of a database to the method [createConnection(...)](https://github.com/capacitor-community/sqlite/blob/master/docs/API.md#createconnection) and similar methods without the `SQLite.db` suffix being appended by the plugin.

**Describe alternatives you've considered**

Unfortunately, I can't think of an alternative solution.

**Additional context**

**Comment by jepiqueau** [comment]
@robingenz Hi, sorry but this is how it has been implemented and it will require to go through all the pieces of code for each part of the plugin iOS, Android, Electron and Web. The location of the databases to be used with the capacitor plugin is the `documents` and then you cannot define your own path folder. It will involve also to modify the React and Vue hooks and as well the driver to 'TypeOrm' .So this is too much work sorry for this

**Comment by robingenz** [comment]
@jepiqueau Thank you for your answer!
Okay, I understand that! 
I can offer you to do the Android and iOS part.
But yes, that would be a lot of breaking changes.
For example, the `isDatabase` method would then no longer be able to distinguish between databases of this plugin and foreign databases.

**Comment by jepiqueau** [comment]
@robingenz i think it will be better to add a new connection method for non-compliant databases where the path and the name is given. in that case it will have a no impact on the actual plugin.This will solve the Example1 but must be used only for a small number of databases and will be done only for non encrypted database. For the Example 2 i would suggest that the migration is done first.

**Comment by jepiqueau** [comment]
@robingenz in the Example1 Do you intent do modify the database coming from the other plugin or just make read-only queries? My understanding would be not to modify in this plugin the database from another plugin

**Comment by robingenz** [comment]
Yes, at the moment I just want to read.

**Comment by jepiqueau** [comment]
@robingenz For me it make sense, so i will have a look this way
- add a non conformed createconnection  no encryption giving the path to the db
- add a non conformed open in read-only mode
- add a non conformed isDatabase
and then using standard db query method
Is this approach correct for you need? It is quite a work but will have minimal impact.
I have to answer some questions relative to some of my others plugins first

**Comment by robingenz** [comment]
Yes, this approach seems correct. 👍 
This feature has time, you have already helped me a lot with the other issue. Thank you again! Great work!

**Comment by jepiqueau** [comment]
@robingenz this has been fixed in 3.3.3-1 following the approach mentioned above. There are some news methods:
`getNCDatabasePath`, `createNCConnection`, `closeNCConnection`, `isNCConnection`, `isNCDatabase` and `retrieveNCConnection` Hope this will help you to migrate from `cordova-sqlite-storage` plugin.

**Comment by robingenz** [comment]
Hi @jepiqueau, thank you very much!
I will let you know if I run into any problems.

**Comment by hicham-barhoumi** [comment]
I have a similar issue, we trying to migrate from codova plugin, we have to put the database in a custom shared folder in developpement mode so we can access it with an SQL tool(ex:SQLPrime) to check data and do dev and tester stufs. but the "createNCConnection/open" does not use openOrCreateDatabase of SQLiteDatabase so the database do not get created. It is a key feature for us. Any idea if this ll be implemented in this plugin ?

**Comment by jepiqueau** [comment]
@hicham-barhoumi if you want to migrate from cordova i assume that the database that you want to access is already existing so you can use createNCConnection to access it and this should work. So may be i did not understand your point

**Comment by hicham-barhoumi** [comment]
@jepiqueau it does not exist until the app is loaded after a fresh install, or for some reason the devlopper delete it in the developpement process. So the idea is to create the database "if not exitst" like the "openOrCreateDatabase" of the database driver do

**Comment by hicham-barhoumi** [comment]
and in the "ncDB" mode there is some limitation in the execute and run methods

**Comment by hicham-barhoumi** [comment]
and in the "ncDB" mode there is some limitation in the execute and run methods of the plugin

**Comment by hicham-barhoumi** [comment]
@jepiqueau it does not exist until the app is loaded after a fresh install, or for some reason the devlopper delete it in the developpement process. So the idea is to create the database "if not exitst" like the "openOrCreateDatabase" of the database driver do. and in the "ncDB" mode there is some limitation in the execute and run methods of the plugin.

I have tested the 3.3.2 version and it works fine with a database name "/storage/emulated/0/CustomFolder/data.db"

**Comment by jepiqueau** [comment]
@hicham-barhoumi it iis not really how the plugin works. Tne non conform features have been developed for existing cordova databases where the name was kept as these databases were shared with others plugins otherwise the advice it to use the standard way with the sqlite prefix. Now if you find some limitations in using the run and execute commands you have to be more specific about these limitations

**Comment by hicham-barhoumi** [comment]
May be I was not clear enough, here an example of code that does not work on this plugin(I use TypeOrm)
```typescript

const databaseConnectionBase: CapacitorConnectionOptions = {
  synchronize: true,
  type: 'capacitor',
  driver: new SQLiteConnection(CapacitorSQLite),
  // what is important for me is only the path, the name can be anything with any prefix or suffix
  database: '/storage/emulated/0/Whatever.db',
  // Or this
  database: '/storage/emulated/0/Android/data/com.toto.app/files/WhateverSQLite.db',
  migrationsTransactionMode: 'none',
  logging: ['error'],
  entities: [
    Entity,
  ]
};
// clear old connection
CapacitorSQLite.checkConnectionsConsistency({
  dbNames: []
}).catch(() => { });
const dataSource = new DataSource(databaseConnectionBase);
// create the db if it does not exist and initialize the ORM
await dataSource.initialize();
```
Our main goal is to have access to database file with another App, and if we don't give the full path(ex: `/storage/emulated/0/Android/data/com.toto.app/files/`) in dbname it will be stored in `/data/data/fr.xelians.wms.mobile/databases` by default witch is protected by the system and not accecible

And even the database already created when typeorm initialize I run into an error 
`Query: database /storage/emulated/0/Whatever not opened` (from [CapacitorSQLite.java:821](https://github.com/capacitor-community/sqlite/blob/5ce56eefd31b6ee6c700271a6071a4d86d15f000/android/src/main/java/com/getcapacitor/community/database/sqlite/CapacitorSQLite.java#L821))
