### ISSUE TITLE
Reloading iOS WebView via Safari inspector throws "Connection already exists"

### ISSUE THREAD

**Issue by muuvmuuv** [capacitor-community/sqlite#202]
**Describe the bug**

Running an Ionic Angular app in Xcode and reloading the WebView through the Safari Inspector throws this error, even with previous "isConnection" check.

```
[Error] DatabaseService Error: [Database] Fatal [22x0]
Error: CreateConnection: Connection entergon already exists
CapacitorException — index.js:85
(anonyme Funktion) — user-script:2:406
Globaler Code — localhost:1
	error
	handleError (main.js:11281)
	error (main.js:33419)
	errorExtended (main.js:33435)
	(anonyme Funktion) (main.js:23367)
	generatorResume
	asyncGeneratorStep (polyfills.js:38506)
	_throw (polyfills.js:38532)
	onInvoke (vendor.js:37134)
	(anonyme Funktion) (polyfills.js:34405)
	(anonyme Funktion) (polyfills.js:35563)
	onInvokeTask (vendor.js:37121)
	(anonyme Funktion) (polyfills.js:34450)
	drainMicroTaskQueue (polyfills.js:34865)
	promiseReactionJob
```

**To Reproduce**

1. Run Xcode app
2. Open Safari and inspect localhost
3. Press reload

**Expected behavior**

Retrieve active connection or savely create a new one.

**Screenshots**

<img width="509" alt="Bildschirmfoto 2021-12-13 um 15 19 30" src="https://user-images.githubusercontent.com/11534760/145828920-2bfbe1be-07d1-456c-885a-fb16f99eed2d.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

- Device: [e.g. iPhone6] iPad
- OS: [e.g. iOS8.1] latest
- Browser [e.g. stock browser, safari] Safari
- Version [e.g. 22] latest

**Additional context**

**Comment by jepiqueau** [comment]
@muuvmuuv something like this
```
    const ret = await sqlite.checkConnectionsConsistency();
    const isConn = (await sqlite.isConnection("YOUR_DATABASE")).result;
    var db: SQLiteDBConnection
    if (ret.result && isConn) {
      db = await sqlite.retrieveConnection("YOUR_DATABASE");
    } else {
      db = await sqlite.createConnection("YOUR_DATABASE", false, "no-encryption", 1);
    }
```

**Comment by muuvmuuv** [comment]
@jepiqueau good catch. I missed this one. Will try that tomorrow at work, thanks. 

Fyi its quite hard to understand the examples with all the if else codes, I think a more simple and reduced example would reduce the clutter. I could share our Angular DatabaseService when we finished the migration, it is a good example from an enterprise state (I think haha).

**Comment by jepiqueau** [comment]
@muuvmuuv you are welcome, it is difficult to write development code and good related examples which suit all needs. so if you can help improving the doc as a user point of view having made the migration it will be a plus for the all developer community. Thanks to provide your feedback

**Comment by muuvmuuv** [comment]
I can't test it right now, because my Xcode isnt working anymore :D I will keep you updated if the issue still persists after you suggestion.
