### ISSUE TITLE
have isJsonValid report what the issue is when the response is false.

### ISSUE THREAD

**Issue by cparkinsonMYCM** [capacitor-community/sqlite#203]
**Is your feature request related to a problem? Please describe.**
`isJsonValid` simply says that my json is not valid, but there is no clear reason for why it is invalid.
There are a few issues that have been opened in the past on the same topic, rather than spend time yourself; add in to the `isJsonValid` method response the reason for it reporting that the JSON is invalid.

**Describe the solution you'd like**
have `isJsonValid` return where the validation failed, a little context, literally any information.
![image](https://user-images.githubusercontent.com/47317809/145852468-bb77f6f0-0a29-479e-b701-96d75ad793a4.png)
I can't gleam any information from that to resolve the issue myself and save you the time...

**Comment by jepiqueau** [comment]
@cparkinsonMYCM can you share your Jones object

**Comment by jepiqueau** [comment]
@cparkinsonMYCM i mean your json object, did you look at the example provided in the docs or applications?

**Comment by cparkinsonMYCM** [comment]
I cannot, but that's kind of the point.
I needed the information for why it's invalid, rather than share the schema.

What I've ended up doing was reading through the `JsonSQLite.java`, `JsonTable.java`, and `JsonIndex.java` files, parsing it manually.
The issue was in my Indexes, turns out that `objValue.equals("UNIQUE")` causes it to be invalid.
Even though SQLite syntax **_is not_** case sensitive, the validation **_is_** and so my indexes with `mode: "unique"` failed validation.

**Comment by jepiqueau** [comment]
@cparkinsonMYCM ok i will have a look and make it case incentive

**Comment by jepiqueau** [comment]
@cparkinsonMYCM this will be fixed in the next release.

**Comment by jepiqueau** [comment]
@cparkinsonMYCM this has been fixed in 3.3.3-1 Thanks again for helping in the debugging process.

**Comment by jepiqueau** [comment]
@cparkinsonMYCM i assume that i can close the issue. feel free to re-open it if necessary
