### ISSUE TITLE
Simulate iOS devices in Chrome browser Error

### ISSUE THREAD

**Issue by wilhantian** [capacitor-community/sqlite#205]
**Describe the bug**
Simulate iOS devices in Chrome browser, can`t open database:

**To Reproduce**

1. In Chrome F12, Toggle device toolbar
2. Click on Dimensions: iPhone
3. createConnection and open database is wrong

- Browser: Chrome 96.0.4664.110
- Version: "@capacitor-community/sqlite": "^3.3.2"

```
Uncaught (in promise) Open: undefined
```

p.s. Simulate Android/Other devices in Chrome browser can run successfully

**Comment by jepiqueau** [comment]
@wilhantian When you simulate iOS devices in Chrome you are running the browser part of the plugin not the iOS part of the plugin so you should use the `jeep-sqlite` stencil component companion.

**Comment by jepiqueau** [comment]
@wilhantian Anything new from your side  otherwise i will close the issue
