### ISSUE TITLE
Get DB Path or file URI

### ISSUE THREAD

**Issue by adamtec** [capacitor-community/sqlite#208]
**Is your feature request related to a problem? Please describe.**

I would like to be able to export a __conformed__ SQLite database (e.g. using the Share API). I haven't found any easy way to get the full directory/path or file URI for a given DB name. 

**Describe the solution you'd like**

If it doesn't exist already, provide a method to retrieve either the directory and path -OR- file URI for a given DB name. This would be similar to Filesystem plugin and would allow to leverage the Share API.

**Describe alternatives you've considered**

To export as JSON or CSV instead.

**Additional context**

I really appreciate this plugin!!

**Comment by jepiqueau** [comment]
@adamtec thanks for using the plugin and thanks for your query. I will have a look at the Share API to understand your query. Can you explain how do you want to use it so i can well understand your query. From my side create a new method to get the database path is not a problem.  What about security issue. On iOS, the database location will certainly be changed As today the location is backup on the cloud.

**Comment by jepiqueau** [comment]
@chriswep can you also give me your opinion on this before i start looking at it thanks in advance

**Comment by jepiqueau** [comment]
@adamtec if you do not give me more explanation i will close the issue. I look for sharing a db to a iPhone simulator and i can share a db only `On my iPhone` sub-folder not on a full given path.

**Comment by adamtec** [comment]
Sorry for delay- I've been traveling. For an application that I am working on, users connect to BLE devices that broadcast sensor measurements. The user is able to create recordings of this measurement data. I am currently saving each of these recordings as a separate sqlite DB. I also currently allow exporting the recording (sqlite tables) as a CSV file for later, offline post-processing. This requires parsing the entire DB record to create a CSV. It would be preferable to be able to export the entire sqlite DB as another option.  

```javascript

import { Share } from '@capacitor/share';
import {  CapacitorSQLite } from '@capacitor-community/sqlite';

const sqlite = new SQLiteConnection(CapacitorSQLite);
const db =  await sqlite.createConnection('record-1234', false, "no-encryption", 1);
await db.open()

// ... Perform some transactions
// ... User requests to export record DB

const dbUri = await db.getUri() // <- This would be new method

// Use Share API to export 
await Share.share({ title: 'Share Record', url: uri, dialogTitle: 'Share Record' });

```

**Comment by jepiqueau** [comment]
@adamtec OK it is for an export not an import what about the security of your database.

**Comment by adamtec** [comment]
The databases that I would expose would be for user created, unencrypted DBs (intended to be shared). I would not expose the core encrypted DB used to store app state, etc.

**Comment by jepiqueau** [comment]
@adamtec this is fix in 3.3.3-4

**Comment by jepiqueau** [comment]
@adamtec the way to use it
```js
                // Use Share API to export
                const url = `file://${(await db.getUrl()).url}`;
                console.log(`shareUrl: ${url}`)
                await Share.share({ title: 'Share Record', url: url, dialogTitle: 'Share Record' });
```

**Comment by jepiqueau** [comment]
@adamtec it works on iOS not on Android

**Comment by jepiqueau** [comment]
@adamtec the Share plugin in ANDROID allows to look at folder starting with `/storage/emulated/0` or `/data/data/YOUR_APPLICATION/cache` so it cannot find the root that contains the path `/data/data/YOUR_APPLICATION/databases/YOURDBSQLite.db` so there is nothing i can do

**Comment by adamtec** [comment]
Hey @jepiqueau, thank you so much for adding this feature. iOS is my main focus so this works great! Perhaps, I can follow up with Capacitor/Ionic to see if Share API root path can be extended.

**Comment by jepiqueau** [comment]
@adamtec yes if you could raise an issue that will help as i will be travelling tomorrow keep me aware

**Comment by jepiqueau** [comment]
@adamtec i integrate `file://`directly in the returned url:
```js
               // Use Share API to export
                const url = (await db.getUrl()).url;
                console.log(`&&& shareUrl: ${url}`)
                await Share.share({ title: 'Share Record', url: url, dialogTitle: 'Share Record' });
```
in fact on Android it is not an error of the Share plugin. In the file_paths.xml you cannot address the `databases` folder. To make it working i would have to move the databases from the `databases` folder to the `files/databases` folder. May be i will go for this but it is quite some changes.
