### ISSUE TITLE
Error during database version upgrade on Android 

### ISSUE THREAD

**Issue by dewald-els** [capacitor-community/sqlite#209]
**Describe the bug**

**To Reproduce**

1. Build project using `ionic build --prod`
2. Sync capacitor plugins using `npx cap sync android`
3. Copy build output to android `npx cap copy android`
4. Run in android emulator `ionic capacitor run android --external`
5. Choose AVD
6. Receive error when trying to open database

**Expected behavior**
Should load the app without any errors. Confirmed that it is working on iOS both physical device and iOS simulator.

**Screenshots**
![image](https://user-images.githubusercontent.com/10051247/147879255-93e8a401-e38c-4166-853a-5560bebe67ab.png)

**Smartphone (please complete the following information):**

- Device: Android AVD
- OS: Android 12

**Additional context**
I have tested that it is currently working on iOS both my iPhone 12  Mini with iOS 15 and an iOS simulator.

**Comment by dewald-els** [comment]
Here is a link to my repo:
[https://github.com/dewald-els/ion-tracker](https://github.com/dewald-els/ion-tracker)

**Comment by jepiqueau** [comment]
@dewald-els thanks for using the plugin and thanks for providing a repo i will have a look

**Comment by dewald-els** [comment]
I don’t know much about Java or Android but let me know if I can help with anything at all

**Comment by dewald-els** [comment]
@jepiqueau  I found the point of the error: It's happening in the open method in the `CapacitorSQLitePlugin.java` file on line 248
**See below:**
![image](https://user-images.githubusercontent.com/10051247/147884378-935cb47a-e0ff-4d14-9888-6cb74a0e230d.png)

**Comment by dewald-els** [comment]
@jepiqueau  Can confirm this is the source of the problem. Did a fix this side and made a pull request :)

**Comment by jepiqueau** [comment]
@dewald-els i merged your PR in release 3.3.3-3 of the plugin. Thanks for participating to the debugging process feel free to close the issue

**Comment by dewald-els** [comment]
merged your PR in release 3.3.3-3
