### ISSUE TITLE
SQLiteDBConnection delete method in Typescript

### ISSUE THREAD

**Issue by doctorstones** [capacitor-community/sqlite#213]
**Describe the bug**
In Typescript definition file "sqlite/dist/esm/definitions.d.ts" on the class SQLiteDBConnection there is method 
```
delete(): Promise<void>;
```
which seems not to be related to anything in the Android Plugin.

**To Reproduce**

1. Go to file;
2. Search for line 1080;
3. See delete() method;
4. Open Android definitions;
5. Search the delete() method;

**Expected behavior**
The delete method should be present in Android Plugin or should be deleted from definitions.
There should be an easy method to delete all referencies to Database by an App.

**Comment by jepiqueau** [comment]
@doctorstones 
if you look at `src/definitions.ts` line 1549 you find async delete() which is calling `await this.sqlite.deleteDatabase({ database: this.dbName });`
now if you look in  Android `CapacitorSQLitePlugin.java` line 792 `public void deleteDatabase(PluginCall call) {` which call `implementation.deleteDatabase(dbName);` which is in `CapacitorSQLite.java`
in `CapacitorSQLite.java` line 662 `public void deleteDatabase(String dbName) throws Exception {` which call in line 667 `db.deleteDB(dbName + "SQLite.db");` 
in `SQLite/Database.java` in line 533 `public void deleteDB(String dbName) throws Exception {` which call in line 545 `Boolean ret = _uFile.deleteDatabase(_context, dbName);` 
then in `UtilsFile.java` in line 48 `public Boolean deleteDatabase(Context context, String dbName) {` which call `context.deleteDatabase(dbName);` 
So the method is well present in the Android plugin

**Comment by doctorstones** [comment]
@jepiqueau You are right, I apologize. 
This was my mistake, due to updating the library. 
Following the update, many of the features throw Exceptions, which are only resolved by reinstalling the entire Android folder.

**Comment by jepiqueau** [comment]
@doctorstones 👍 No problem. Good luck with your development
