### ISSUE TITLE
Use with knex.

### ISSUE THREAD

**Issue by IbrohimMirxoshimov** [capacitor-community/sqlite#217]
How can I use capacitor sqlite with knex.

I saw how to use it with TypeORM. But I couldn’t find a way to do this with a knex. I didn't know how to make a special dialect.

The old project was written with knex and I was copying it to the capacitor.

**Comment by jepiqueau** [comment]
@IbrohimMirxoshimov thanks for looking at the plugin. There is no driver for `knex` available. One should be looking at  this. Is it for Web or for Native apps

**Comment by IbrohimMirxoshimov** [comment]
@jepiqueau Hi. 

I am developing this app in the browser 

But we need this app for Windows, Android and iOS.

I tried to do something to solve but all failed with knex. 

I knew it can possible to use knex only query builder. https://github.com/knex/knex/issues/983#issuecomment-141758489

But this also I couldn't use in browser. Knex required many nodejs packages os, stream, fs, path. I installed all of this and added webpack config. But finally i got error process is undefined))

Just, I wanted to develop with brawser this project, Becouse it is easy). If are there any solution i will try

**Comment by jepiqueau** [comment]
@IbrohimMirxoshimov I looked into this, i let a message on [tgriesser/knex](https://github.com/tgriesser/knex) but i did not get any answer. I think ones as to develop a new `client` in knex for `capacitorsqlite` I do not know enough knex to do this and it a bit out of my scope of capacitor developer. I got enough work to maintain existing plugins. For typeOrm it is someone else who develop it. May be you should raise an issue to knex for having them developing this new client.

**Comment by IbrohimMirxoshimov** [comment]
@jepiqueau Sorry for the late reply.

I will try to do what you say. So far I haven’t found a good solution yet. Thanks for your answers
