### ISSUE TITLE
Possible to update database schema with importFromJSON()?

### ISSUE THREAD

**Issue by martinkreitl** [capacitor-community/sqlite#218]
**Is your feature request related to a problem? Please describe.**

We built an app with your plugin and it is already in the app stores.
Users can input values based on the current schema. 
Now, we would like to make an update of the schema (e.g. add columns) and keep the existing values. 

So far, we used an startupJSONv2 to create the initial database and import the schema from that.
Now, we would like to use a different startupJSONv2 with more columns. So we are trying to make the database updatable. 

We tried the addUpgradeStatement. But we could not make it work and would rather like to work with an imported JSON not SQL strings. So we tried the importFromJSON function with "partial" mode. But it does not seem to work with just a change in schemas. Is that correct?

**Describe the solution you'd like**

Is it possible to use importFromJSON in order to update the schema? The "full" mode changed the schema successfully but obviously deleted all data. We are not certain if "partial" mode can update existing schemas. Maybe a third mode could do that?

I can provide you some code, if you need that for clarification.

Thank you very very much for creating and supporting this plugin, btw!

Best regards 
Martin

**Comment by jepiqueau** [comment]
@martinkreitl It has to be done through the addUpgradeStatement. Assuming that the users of your app have got their own data means that you may do it with a full export  and your app  will have to manage the transfer of the existing data from the export json object in a new json object with your new schema and then you will make a full import of the new json object with a new version

**Comment by martinkreitl** [comment]
@jepiqueau Thanks for your fast feedback so far!
Yes, users can record their own data with the app. For security, no API call will be made and all data should stay on the phone. 
So, when I do the full export, constructing new json object and full import. Do I even need the addUpgradeStatement?
Does the addUpgradeStatement work with a json object in general? I tried once and it failed.

**Comment by jepiqueau** [comment]
@martinkreitl as i said it should be done with addUpgradeStatement, look at the provided documentation `UpgradeDatabaseVersion.md `and example `angular-sqlite-app-starter`
```
      await this._sqlite.addUpgradeStatement("YOUR_DATABASE",
      1, 2, YOUR_NEW_SCHEMA , YOUR_SET_OF_DATA); 
       const db = await this._sqlite
                  .createConnection("YOUR_DATABASE", false,
                  "no-encryption", 2);
         await db.open();
```
the `addUpgradeStatement` does not work with a json object but with a set of SCHEMA statements and for the DATA a set of SQLite statements and values. 

Now if you want to do it with json object follow the process i described to you earlier

Do not mix the two processes
Hope this is clear

**Comment by martinkreitl** [comment]
@jepiqueau Sounds good! Thanks a lot.

**Comment by jepiqueau** [comment]
@martinkreitl Tell me if you are facing problems. Good luck, i do not see any reason why it should not work

**Comment by jepiqueau** [comment]
@martinkreitl i will close the issue feel free to reopen it if require
