### ISSUE TITLE
ExecuteSet: lastId equals -1 when changes is 0

### ISSUE THREAD

**Issue by koen20** [capacitor-community/sqlite#221]
**Describe the bug**
When I try to run executeSet on Android when there are no changes I get an error. If there are changes when inserting  the method runs successfully. If I try to run the same code on iOS I do not get an error.
Error:
`Error: ExecuteSet: lastId equals -1`

Result on android:
`{"changes":{"lastId":-1,"changes":0}}`
Result on iOS:
`{"changes":{"lastId":0,"changes":0}}`

**To Reproduce**

1. Insert items with executeSet
2. Insert the same items with executeSet

**Expected behavior**
When running executeSet with the same items I do not expect to get an error.

**Desktop (please complete the following information):**

- OS: macOS
- Version: 11.6.3

**Smartphone (please complete the following information):**

- Device: Oneplus 6
- OS: Android 11 **(Custom rom, Lineage OS)**
- Browser: Chrome

**Comment by jepiqueau** [comment]
@koen20 Can you share your executeSet statements ?

**Comment by koen20** [comment]
@jepiqueau I used the same query as #220 . I also used a where clause so there are no changes when inserting.

**Comment by jepiqueau** [comment]
@koen20  it could not be the same as @bkostjens mention that it was working on android and not on iOS which i can confirm. If i look at the code when lastId = -1 an Error message `lastId equals -1` is returned. 
So can you show me your code as i do not know how you get `{"changes":{"lastId":0,"changes":-1}}`

**Comment by bkostjens** [comment]
When you comment outline 381 in  Database.java:

`throw new Exception("lastId equals -1");`

the problem is solved. Basically similar problem as on iOS. In Android the lastID is set to -1 as default value in executeSet and it looks like it is not set to 0 when there are no changes, but will still have the value -1 which causes it to throw.

**Comment by jepiqueau** [comment]
@bkostjens 
line 381 of Database. java
``` 
throw new Exception("lastId equals -1");
``` 
which is catch by lines 533-535 of `CapacitorSQLite.java`
```
                } catch (Exception e) {
                    throw new Exception(e.getMessage());
                }
```
which is catch by lines 653-657 in `CapacitorSQLitePlugin.java`
```
        } catch (Exception e) {
            String msg = "ExecuteSet: " + e.getMessage();
            rHandler.retChanges(call, retRes, msg);
            return;
        }
```
with the retRes object initialize line 618 in `CapacitorSQLitePlugin.java`
```
retRes.put("changes", Integer.valueOf(-1));
```
so in javascript it is returned
res = {changes: {changes:-1}, message:"Error: ExecuteSet: lastId equals -1"}

so i do not see how you can get 
```
{"changes":{"lastId":0,"changes":-1}}
```

**Comment by bkostjens** [comment]
I'll double check to see what the exact debug output is, however: basically android has the same issue as iOS: when not updating or inserting any records while calling executeSet you'll get an error (error differs per platform).

**Comment by jepiqueau** [comment]
@bkostjens I am waiting your feedback before releasing the new version fixing the issue#220 that i can reproduced and fixed but i could not reproduce yours

**Comment by bkostjens** [comment]
#220 was created by me, #221 by a collegae of mine (@koen20). I'll provide more feedback in here about the Android problem asap. Thanks so far for your quick responses!

**Comment by bkostjens** [comment]
Ok, I logged the exact messages:

```
2022-02-08 11:43:04.682 6589-6660/xxx V/com.getcapacitor.community.database.sqlite.RetHandler: *** ERROR ExecuteSet: lastId equals -1
2022-02-08 11:43:04.682 6589-6660/xxx D/Capacitor: Sending plugin error: {"save":false,"callbackId":"47769535","pluginId":"CapacitorSQLite","methodName":"executeSet","success":false,"error":{"message":"ExecuteSet: lastId equals -1"}}
2022-02-08 11:43:04.717 6589-6589/xxx E/Capacitor/Console: File: webpack-internal:///./src/services/SyncService.ts - Line 153 - Msg: Error: ExecuteSet: lastId equals -1```

When looking trough the source code it seems caused by the lastId being set to -1 initially, and it will never get updated as there are no changes. Maybe set it to 0 initially will fix this?

**Comment by koen20** [comment]
I just noticed that I included the wrong result for Android. It should have been
{"changes":{"lastId":-1,"changes":0}}

Sorry about that.

**Comment by jepiqueau** [comment]
@koen20 This should have been fixed in 3.4.0-1 Can you test and revert to me

**Comment by bkostjens** [comment]
Seems to work fine now, but I'm not able to test on a real device at this moment. Maybe wait for @koen20 to verify this as well.

**Comment by koen20** [comment]
I tested it on a real device and it works. Thanks
