### ISSUE TITLE
Update command doesn't work

### ISSUE THREAD

**Issue by fr3shn3ss** [capacitor-community/sqlite#223]
**Describe the bug**

Update command doesn't work on sqlite@2.9.7 using CapacitorSQLite.execute() while INSERT works just fine. Table was created using importFromJson()

Result ==> {
 "changes": {
  "changes": -1
 }
} 

**To Reproduce**

  const statement = `UPDATE importedBulkScan SET jsonData_='testtest' WHERE itemId = 4;`;
        const r = await CapacitorSQLite.execute({
          statements: statement,
          database: this.dbName,
        });

**Expected behavior**
Should update the item but the following command won't show any change

const statement = `SELECT * FROM importedBulkScan;`;
    const r = await CapacitorSQLite.query({
      statement,
      values: [],
      database: this.dbName,
    });

**Smartphone (please complete the following information):**

- Device: [e.g. iPhone6] Galaxy S10
- OS: [e.g. iOS8.1] Android 10

**Comment by jepiqueau** [comment]
@fr3shn3ss thank for using the plugin but the release 2.9.7 is not maintained anymore. So upgrade to the latest release and tell me if you still have the issue

**Comment by fr3shn3ss** [comment]
Thanks. I found the issue. 

This version requires "last_modified" as one of the columns. 

Sample Schema 

[
        { column: "id", value: "INTEGER PRIMARY KEY AUTOINCREMENT" },
        { column: "jsonData", value: "TEXT NOT NULL" },
        {
          column: "last_modified",
          value: "INTEGER DEFAULT (strftime('%s', 'now'))",
        },
      ];

**Comment by jepiqueau** [comment]
@fr3shn3ss i am glad that you find the reason. I still encourage you to move to the latest version which is strongest and maintain
