### ISSUE TITLE
Export encrypted data

### ISSUE THREAD

**Issue by handsatwork85** [capacitor-community/sqlite#227]
Hi everyone!

I would like to add this plugin to my project, so I am testing with [angular-sqlite-app-starter]. 
The main idea is export and import JSON (between devices) with encrypted data/values using a passphrase.
Is that possible?

I mean when I export data from an encrypted database using exportToJson() that is not encrypted as I test in angular-sqlite-app-starter. I am doing something wrong or that is normal behavior?

I checked it on android 10.

**Comment by jepiqueau** [comment]
@handsatwork85 No that is to day the normal behavior. I never thought about the way you want to use it. The import/export was more to use between a remote server and a device.
How you will pass the JSON Object between devices?

**Comment by handsatwork85** [comment]
@jepiqueau 

The present project use CryptoJS.AES.encrypt and SQLite to de/encrypt data. It exports a JSON with encrypted values cause they are medic personal info and more. I suppose is due to legal things .... On this way, when you update or change your phone to another, you can import your data, either locally from your device or from a server, where the personal info (values) is not readable.  

Don't know if that is the best way, yet I want to keep this behavior. Don't know if it is possible to export the entire database file. (It is a small DB) Another way would be encrypt json before send it to the server.

I guess I will continue as it is actually. 

Thanks !!

**Comment by jepiqueau** [comment]
@handsatwork85 how  the passphrase is defined and where the passphrase to encrypt/decrypt is stored during the process? The solution if it is a small database could be to share it as a file this can be easily done the problem will be how to import it as a file i have to think about it

**Comment by jepiqueau** [comment]
@handsatwork85 the database is encrypted with an application passphrase on device A when imported in device B the application passphrase of the device B should be the same that the one in A otherwise it will be not workable in device B

**Comment by handsatwork85** [comment]
> @handsatwork85 the database is encrypted with an application passphrase on device A when imported in device B the application passphrase of the device B should be the same that the one in A otherwise it will be not workable in device B

Sure. That is the idea. And if you forgot your pass you will lose your data.

At the present, the passphrase is requested and stored in angular store.

**Comment by jepiqueau** [comment]
@handsatwork85 As i did not have news from your side, i close the issue.
