### ISSUE TITLE
TypeORM with Angular - Data is not saved across browser refresh

### ISSUE THREAD

**Issue by harikvpy** [capacitor-community/sqlite#228]
I don't think this is really a bug. Perhaps more to do with some mistakes in my code.

As the title says, I'm trying to integrate TypeORM with an Ionic/Angular project and I encounter this problem of data not being persisted across sessions. I can create tables and query them, but upon browser refresh it's all gone. As if data is being saved to a memory database rather than a persistent storage such as IndexedDB.

My code is pretty much entirely borrowed from the samples in this repo. Anyway this is what I do:

1. Copied the sqlite.service.ts from the angular starter project. Call its initializePlugin() method and setup the webstore.
```
  async initializeDB() {
    await this.sqlite.initializePlugin();
    // const p = this.sqlite.platform;
    // console.log(`plaform ${p}`);
    const platform = Capacitor.getPlatform();
    if (platform === 'web') {
      await customElements.whenDefined('jeep-sqlite');
      const jeepSqliteEl = document.querySelector('jeep-sqlite');
      if (jeepSqliteEl != null) {
        await this.sqlite.initWebStore();
        console.log(`isStoreOpen ${await jeepSqliteEl.isStoreOpen()}`);
        console.log(`$$ jeepSqliteEl is defined $$`);
      } else {
        console.log('$$ jeepSqliteEl is null');
        throw Error('jeepSqliteEl is null');
      }
    }
  }
```
2. Initialize TypeORM based on the code in the Vue sample.
```
  private async createConnection(): Promise<Connection> {
    // when using Capacitor, you might want to close existing connections,
    // otherwise new connections will fail when using dev-live-reload
    // see https://github.com/capacitor-community/sqlite/issues/106
    CapacitorSQLite.checkConnectionsConsistency({
      dbNames: ['test'], // i.e. "i expect no connections to be open"
    }).catch((e) => {
      // the plugin throws an error when closing connections. we can ignore
      // that since it is expected behaviour
      console.log(e);
      return null;
    });

    // create a SQLite Connection Wrapper
    const sqliteConnection = new SQLiteConnection(CapacitorSQLite);

    // copy preloaded dbs (optional, not TypeORM related):
    // the preloaded dbs must have the `YOUR_DB_NAME.db` format (i.e. including
    // the `.db` suffix, NOT including the internal `SQLITE` suffix from the plugin)
    // await sqliteConnection.copyFromAssets();

    let dbOptions: ConnectionOptions;

    // eslint-disable-next-line prefer-const
    dbOptions = {
      logging: ['error', 'query', 'schema'],
      type: 'capacitor',
      driver: sqliteConnection, // pass the connection wrapper here
      database: 'test', // database name without the `.db` suffix,
      mode: 'no-encryption',
      synchronize: true,
      entities: [User],
    };
    // create the TypeORM connection
    return await createConnection(dbOptions);
  }
```
3. I have an OrmService which has initialize() which I call during application startup:
```
  async initialize() {
    try {
      await this.initializeDB();
      await getConnection();
    } catch (ex) {
      console.log('Connection not established, creating connection', ex);
      await this.createConnection();
      console.log('Connection created!');
    }
    //await this.createMockData();
    console.log('All users:', JSON.stringify(await User.find(), null, 2));
  }
```

What am I missing?

My expectation of the sqlite plugin is that this app when run on the web, it would use `jeep-sqlite` and on a physical device it would use the actual on-device sqlite databases. Pls correct me if this assumption is wrong and if the TypeORM plugin only works with device (I'm yet to test that).

My test repo is [here](https://github.com/harikvpy/ionic-sqlite).

Thanks in advance.

**UPDATE**
Versions:
- @capacitor-community/sqlite v3.4.0-2
- jeep-sqlite v1.3.5
- Ionic v6
- Angular 13

Hari

**Comment by harikvpy** [comment]
To add, data can be saved and read across browser refresh when it's done with SQL statements using the SQLiteService methods.

**Comment by harikvpy** [comment]
@jepiqueau Thanks for the quick response! When using TypeORM, you don't really get access to the DB to close it. Do you? There isn't an autoSave option either in CapacitorConnectionOptions. Anyway, isn't the TypeORM driver supposed to do that when you issue an Entity.save()?

**Comment by jepiqueau** [comment]
@harikvpy do just this and it works fine
```
  async initialize() {
    try {
      await this.initializeDB();
      await getConnection();
    } catch (ex) {
      console.log('Connection not established, creating connection', ex);
      await this.createConnection();
      console.log('Connection created!');
    }
    await this.createMockData();
    await this.sqlite.saveToStore('test');

    console.log('All users:', JSON.stringify(await User.find(), null, 2));
  }
```

**Comment by jepiqueau** [comment]
@harikvpy you have to use ` await this.sqlite.saveToStore('test');` only if it is a web platform and after a number of transactions at your convenience.
For native platforms you do not need to do anything

**Comment by jepiqueau** [comment]
@harikvpy so do this 
```
    if( this.sqlite.platform === 'web') {
      await this.sqlite.saveToStore('test');
    }
```
do you want me to merge the fork i did

**Comment by jepiqueau** [comment]
@harikvpy The driver to TypeOrm was made by ones prior i develop the web version of the plugin and works well for native apps and also works well with the web in-memory.

**Comment by harikvpy** [comment]
> @harikvpy so do this
> 
> ```
>     if( this.sqlite.platform === 'web') {
>       await this.sqlite.saveToStore('test');
>     }
> ```
> 
> do you want me to merge the fork i did

Oh no..I can handle it :) But appreciate the offer!

**Comment by jepiqueau** [comment]
@harikvpy it has been done like this as normally the web part is just used to speed up the development prior to go native and you can work in-memory for fast queries. Each time you do a saveToStore it save the whole db memory erasing the store so it will be really slowing down the app if you do it after each transaction. Hope this clarify.

**Comment by jepiqueau** [comment]
@harikvpy Have an happy development from now on.

**Comment by harikvpy** [comment]
> @harikvpy it has been done like this as normally the web part is just used to speed up the development prior to go native and you can work in-memory for fast queries. Each time you do a saveToStore it save the whole db memory erasing the store so it will be really slowing down the app if you do it after each transaction. Hope this clarify.

It's clear. Thanks. I'll close it now.

**Comment by harikvpy** [comment]
Just to complete the loop on this conversation -- the native sql.js driver's `SqljsConnectionOptions` has the autoSave option:
```
    /**
     * Enables the autoSave mechanism which either saves to location
     * or calls autoSaveCallback every time a change to the database is made.
     */
    readonly autoSave?: boolean;
```
Perhaps you can think of supporting this as an extra (there's a comment about possible deprecation there, may be there are other avenues to provide this) option that the user can use as per their discretion. If the user is willing to put up with lower performance for better data consistency, they have a choice.

I expected this behavior as I first integrated TypeORM with sql.js (repo [here](https://github.com/harikvpy/ionic-typeorm)) before I jumped into your plugin.

Thanks again.
Best

**Comment by jepiqueau** [comment]
@harikvpy fix in jeep-sqlite 1.3.6 add a property autoSave
```
    <jeep-sqlite autoSave="true"></jeep-sqlite>
```
tell me if it works now

**Comment by jepiqueau** [comment]
@harikvpy does not seems to work with typeorm

**Comment by jepiqueau** [comment]
@harikvpy an alternative is to create an entitySave function in your service like:
```
  private async entitySave(entity: any, dbName: string) {
    await entity.save();
    await this.sqlite.saveToStore(dbName);
  }
```
and then replace `await newUser.save();`  with `await this.entitySave(newUser, 'test');`
Voilà this all i can suggest

**Comment by harikvpy** [comment]
Thanks. I just forked the jeep-sqlite code and was about to see if it can be tweaked. I guess that wont be necessary now as you've done that part already. I'll follow the last suggestion for now.

**Comment by harikvpy** [comment]
BTW, my idea for tweaking jeep-sqlite was to issue a saveToStore() if one of the execute methods return with changes > 0. Not sure if this makes sense.

**Comment by harikvpy** [comment]
> Thanks. I just forked the jeep-sqlite code and was about to see if it can be tweaked. I guess that wont be necessary now as you've done that part already. I'll follow the last suggestion for now.

Hmm..now that I think a little bit more about this. Why/how does autoSave work for sql.js driver with TypeORM?

**Comment by jepiqueau** [comment]
@harikvpy It would have to be implemented into the capacitor driver and this would be difficult as the capacitor driver does not know if it is a native app or a web app which is calling to create the connection.

**Comment by harikvpy** [comment]
I get it. I went through the TypeORM source and realize that your jeep-sqlite is a secondary driver -- a driver within the CapacitorSQLiteDriver.

Further to this, since I didn't want to have a separate save() method or extend BaseEntity class, I came up with a stop-gap method. I monkey patched the `execute`, `excuteSet` & `query` methods of `SQLiteDBConnection` object returned by `createConnection` and the SQL statement in them is anything other than SELECT, I trigger a timer the handler for which calls the `saveToStore`. This mechanism is only activated on 'web' and it suits me fine as I need it only for dev. (Changes in `orm.service.ts`).

The monkey patching code is not pretty and I don't want to spend too much time making it so as this is purely for my dev env. You can consider adopting a similar approach to implementing the `autoSave` property that you have introduced. But this has to be clearly documented with the necessary caveats.

Another approach could be for you to trigger an event from these data-changing-methods and the client code can trap this event to implement their own autoSave feature. This way you avoid making your code 'dirty' and push the responsibility to the user of your library.

Ideally of course, the CapacitorDriver would've to be modified to implement a `flush()` method like in `SqljsDriver` and then trigger a call into your DatabaseDriver from there, if it implements it.

**Comment by Sadi-1992** [comment]
Has anyone else had the experience that saveToStore increases the memory used with each call, even if there were no changes to the DB? It seems to me that it does not overwrite the localForage, but simply adds the DB again and again.
