### ISSUE TITLE
How to handle Transactions with this plugin

### ISSUE THREAD

**Issue by Sampath-Lokuge** [capacitor-community/sqlite#230]
Hi,

I would like to do this workflow under 1 transaction. Can you tell me how to do that? Thanks.

```
 async createExpense(expense: ExpenseModel): Promise<void> {
    const query = `
          CREATE TABLE IF NOT EXISTS Expenses (
            ExpenseId GUID PRIMARY KEY NOT NULL,
            Name TEXT NOT NULL,
            Amount TEXT NOT NULL,
            Date TEXT NOT NULL,
            Vat TEXT NULL,
            ExpenseType TEXT NOT NULL,
            Image BLOB NULL
          );`;

    const res = await this.sqliteDbConnection.execute(query);

    const sqlQuery = `INSERT INTO Expenses (ExpenseId,Name,Amount,Date,Vat,ExpenseType,Image) 
      VALUES (?,?,?,?,?,?,?)`;

    const sqlValues = [
      Guid.create(),
      expense?.name,
      expense?.amount,
      expense?.date,
      expense?.vat,
      expense?.expenseType,
      expense?.image,
    ];

    const ret = await this.sqliteDbConnection.run(sqlQuery, sqlValues, false);
}

```

**Comment by jepiqueau** [comment]
@Sampath-Lokuge each execute, executeSet or run is done automatically with transaction .

**Comment by Sampath-Lokuge** [comment]
Hi @jepiqueau 

My question here is like so. i.e. how can I achieve the same thing with your plugin? I can understand each and every above operation are having its own transaction level. But How can I do a series of operations under 1 transaction like so:

 ```
db.transaction(function(tx) {
    tx.executeSql('CREATE TABLE IF NOT EXISTS DemoTable (name, score)');
    tx.executeSql('INSERT INTO DemoTable VALUES (?,?)', ['Alice', 101]);
    tx.executeSql('INSERT INTO DemoTable VALUES (?,?)', ['Betty', 202]);
  }, function(error) {
    console.log('Transaction ERROR: ' + error.message);
  }, function() {
    console.log('Populated database OK');
  });
```

**Comment by jepiqueau** [comment]
@Sampath-Lokuge  
db.transaction does not exist so
you can manage the transaction yourself by using sqlite statements and do this
```
      try {

        let ret: any = await db.execute("BEGIN TRANSACTION;",false);
        // create table in db
        ret = await db.execute(createSchemaIssue230,false);
        if (ret.changes.changes < 0) {
          await db.execute("ROLLBACK;",false);
          return Promise.reject(new Error("Execute createSchema failed"));
        }
        // do some INSERT
        let sqlcmd: string = 
        "INSERT INTO DemoTable VALUES (?,?)";
        let values: Array<any>  = ["Alice",101];
        ret = await db.run(sqlcmd,values,false);
        console.log(`INSERT1 ret.changes: ${JSON.stringify(ret.changes)}`);
        if(ret.changes.lastId === -1) {
          await db.execute("ROLLBACK;",false);
          return Promise.reject(new Error("Run 1 users with statement & values failed"));
        }
        values  = ["Betty",202];
        ret = await db.run(sqlcmd,values,false);
        console.log(`INSERT2 ret.changes: ${JSON.stringify(ret.changes)}`);
        if(ret.changes.lastId === -1) {
          await db.execute("ROLLBACK;",false);
          return Promise.reject(new Error("Run 1 users with statement & values failed"));
        }
        await db.execute("COMMIT;",false);
        await this._sqlite.closeConnection("testIssue230"); 
        return Promise.resolve();
      } catch (err) {
        await db.execute("ROLLBACK;",false);
        return Promise.reject(err);
      }

```

**Comment by Sampath-Lokuge** [comment]
Yes, it seems a bit ugly. But I think this is the only way right now with this plugin. We would like to have a more out-of-the-box/robust approach if we'll have this plugin in the future version like so where I have mentioned in my previous comment. But I'll try it that way for now.

I would like to ask another question here. I can see that you have closed the connection like so ` await this._sqlite.closeConnection("testIssue230"); ` . Since this is a transaction we need to close it manually.

But do I need to close the connection for each and every none transaction use case too?

I opened the connection very beginning and then use that everywhere like so:

_service1.ts_

```
async configureSqliteDatabase(): Promise<void> {
    const sqliteConnection = new SQLiteConnection(CapacitorSQLite);

    const checkConnectionsConsistency = await sqliteConnection.checkConnectionsConsistency();
    const isConnection = (await sqliteConnection.isConnection('MyDatabase'))?.result;

    if (checkConnectionsConsistency?.result && isConnection) {
      this.sqliteDbConnection = await sqliteConnection.retrieveConnection('MyDatabase');
    } else {
      this.sqliteDbConnection = await sqliteConnection.createConnection(
        'MyDatabase',
        false,
        'no-encryption',
        1
      );
    }

    await this.sqliteDbConnection.open();

    this.setSqliteDbConnection(this.sqliteDbConnection); 
  }
```

This is an `Observable` and I use it everywhere: `this.setSqliteDbConnection(this.sqliteDbConnection); ` on other serverices.

_service2.ts_
```

 private initialize(): void {
    this.sqliteService.sqliteDbConnectionChanged$.subscribe((res) => {
      this.sqliteDbConnection = res;
    });
  }

sync createExpense(expense: ExpenseModel): Promise<void> {
const sqlQuery = `INSERT INTO Expenses (ExpenseId,Name,Amount,Date,Vat,ExpenseType,Image) 
      VALUES (?,?,?,?,?,?,?)`;

    const sqlValues = [
      Guid.create().toString(),
      expense?.name,
      expense?.amount,
      expense?.date,
      expense?.vat,
      expense?.expenseType,
      expense?.image,
    ];

    await this.sqliteDbConnection.run(sqlQuery, sqlValues, false);
}
```

Please let me know your thoughts here for better usage of connection. Thanks for your support.

**Comment by jepiqueau** [comment]
@Sampath-Lokuge No you do not need to close the connection after each transaction you do it when you want. Here it is because i cut and paste the code from my test so as i did not have anything to do after the test so it is why i clause it.
it would be nice to have a db.transaction(function tx)  like you mentioned but for this i would have to understand how to run a javascript function in swift and java which i do not know for the time being. So hope you will understand

**Comment by Sampath-Lokuge** [comment]
Hi, @jepiqueau 

Ok sure. Thanks a lot for support and great plugin too!

**Comment by jepiqueau** [comment]
@Sampath-Lokuge  i add a method db.transaction  in 3.4.0 as follow
```
    const createSchemaIssue230 = `
       CREATE TABLE IF NOT EXISTS DemoTable (
       name TEXT,
       score INTEGER
   );
   `
   const transaction: any = [
        {statement : createSchemaIssue230},
        {statement: "INSERT INTO DemoTable VALUES (?,?)",
              values: ["Alice",101]},
        {statement: "INSERT INTO DemoTable VALUES (?,?)",
              values: ["Betty",202]}
    ]
    await db.executeTransaction(transaction);
```

Voilà

**Comment by Sampath-Lokuge** [comment]
Hi @jepiqueau 

This is awesome. I'll try it with my offline first app. Thanks a lot.

One question. I cannot see any `Open collective` or `Bye me a coffee` page for this project. Any reason for that? We would love to give something for your great effort here,

**Comment by jepiqueau** [comment]
Hi @Sampath-Lokuge I start this project after my retirement to keep my brain active. Even it it takes me more time than foreseen, i still enjoy to do it. This is a free open-source plugin like the others i am owning.   🍻

**Comment by Sampath-Lokuge** [comment]
Hi @jepiqueau 

Ok sure. Thanks a lot for doing a great job for the free and open-source world. Keep up the good work!

**Comment by mjgoeke** [comment]
I've put together some pieces that give me what I want of transactions.
I'm working with corporate to get it open sourced.

Essentially it wraps a `SQLiteDBConnection`. Read methods don't require a txnId, writes do.
The transaction method takes a descriptive identifier for the txn (for tracing/troubleshooting purposes) and a set of `actions` which it passes the txnId to, and you're expected to call e.g. `executeSet` `execute` `run` etc passing in that txnId.

I use async-lock to ensure executing code from other txns cannot bleed over.

Here's the actual code block as an example:
``` ts
  async txn(description: string, actions: (txnId: string) => Promise<void>): Promise<void> {
    //generate a unique but identifiable txnId
    const txnId = `${description} ${Math.floor(Math.random() * 4294967296).toString(16)}`; //hex
    await lock.acquire(this.txnLock, async () => {
      try {
        this.txnId = txnId;
        await this.run(txnId, 'BEGIN TRANSACTION;');
        await actions(txnId);
        await this.run(txnId, 'COMMIT TRANSACTION;');
        await this.flush();
      } catch (error) {
        await this.run(txnId, 'ROLLBACK TRANSACTION;');
        throw error;
      } finally {
        this.txnId = undefined;
      }
    });
  }

  async executeSet(txnId: string, set: capSQLiteSet[]): Promise<capSQLiteChanges> {
    if (txnId !== this.txnId) throw new Error(`executeSet: transaction doesn't match, txn in progress: ${this.txnId}, attempted txn: ${this.txnId}`);
    return this.db.executeSet(set, false);
  }

  async execute(txnId: string, statements: string): Promise<capSQLiteChanges> { return this.executeSet(txnId, [{ statement: statements, values: [] }]); }

  async run(txnId: string, statement: string, values?: unknown[]): Promise<capSQLiteChanges> { return this.executeSet(txnId, [{ statement, values: values ?? [] }]); }

```

(ignore the flush piece - it's only really necessary on the web platform)

I named the class `LockedSQLiteDBConnection`
hope this is helpful to someone.

If I can get it open sourced soon I'll let you know.

**Comment by jepiqueau** [comment]
@mjgoeke interesting. I do not think it is necessary since i created a db.transaction method which let you run several sql statements in the same transaction. If you disagree please explain.

**Comment by mjgoeke** [comment]
sure - the transaction method allows you to run a transaction from *one point*   *in code* - not a span - not a starting at one point, adding to, and then committing or rolling back at a different point.
The method you've added looks like I could just use `executeSet` instead.
(Please correct me if I'm wrong on this!)

What if I want code in between the sql statements in a transaction? For example

Say I recalculate values for a part of a larger system.  Within the transaction I update the data in the tables, and then hand this over to some verification step that queries the db and ensures everything is consistent (doesn't break code-based rules we have about calculations across the whole system), and it also writes to another table noting the result of the verification.  

The transactional scope I've written allows sql writes and reads to be interleaved with processing, and if anything fails along the way the entire transaction will be rolled back.  The entire transaction with all the work is atomic.

It's a powerful construct to be able to interleave reads, writes, and processing within the same transactional unit, and be able to reason about the entirety of the the transaction either succeeding or failing - it's all or nothing, no partial state.

Contrast that to a "transaction" method that can only be called from one point in code.  I can't expand the *transactional scope* to include a *scoped span* of code.

When you have this scoped span, and it may be added to you can then pass the transaction around and allow other pieces of code to contribute to the larger, atomic block.
Within a transactional scope code can delegate to bits of code in different classes, with different responsibilities, etc.
You could fake this sort of transactional scope by queuing a set of sql writes to run in one transaction... but then you wouldn't have *consistent reads* - if you query to read data with queued but not-yet-written writes then parts of the system would be pulling stale data.

Transactional scopes that allow you to *start* them at one point in code, add to the scope from other points in code, read a consistent (but not yet committed) state, and then atomically commit or roll back are extremely valuable for building _reliable_ systems.

Sorry it's a bit rambling - I hope this helps paint a picture of the value of transactional scopes that can span swatches of code.


``` mermaid
flowchart TD
    R(Recalculate)
    V(Verify Consistency across Larger Set)
    DB1[(DB)]
    DB2[(DB)]

    R-.->|write|DB1-.->|read|R
    V-.->|write|DB2-.->|read<br><div>reads are consistent with uncommitted changes<br> in Recalculate step</div>|V

    subgraph transaction
        R
        V
        DB1
        DB2
    end

    b(begin transaction) --> transaction --> c(commit transaction) & r(...or... rollback transaction on error)
    
```

**Comment by jepiqueau** [comment]
@mjgoeke sorry i did not pick up the idea which is now developed. Seems more than of interest. How can we proceed from there and can you provide a full example

**Comment by mjgoeke** [comment]
Reworking this plugin to support transactions how SQLite treats them is a bit above my level of expertise.
What I built was simply a small library that provided an abstraction layer over the top of what this plugin `capacitor-community/sqlite` already provides.

Expanding this plugin to match more directly the API that SQLite exposes would be a broader undertaking and whoever does it would need to take some time to wrap their head around the differences.
SQLite's description of how they expose transactions can be found here https://www.sqlite.org/lang_transaction.html

Reading there now, it looks like I should perhaps be opening separate connections... thus far I've really only opened and shared one.

The key would be to mirror (as faithfully as possible) the API that SQLite provides, into this plugin.

I suggest that would be a much larger scoped feature than this individual Issue.
If my time were more available to contribute to this plugin I would give it a shot and do my best to put together a PR.
**As things currently stand with me, sadly, I cannot commit to that undertaking.**

As I mentioned above I'm pushing to be able to open source the npm package I described in my first comment. It's working well as a stopgap for me currently. Perhaps it could help others too.

**Comment by jepiqueau** [comment]
@mjgoeke I come back on this, as may be i will have a look 
what is the definition for 
```  
      await actions(txnId);
``` 
and also  for 
```
        await this.flush();
```
have you made your work open source already

**Comment by lajith111** [comment]
@jepiqueau i planning to port corodova to this plugin.

Please let me know how this can achived in this plugin

**Comment by michaelgoeke** [comment]
> @mjgoeke I come back on this, as may be i will have a look what is the definition for
> 
> ```
>       await actions(txnId);
> ```
> 
> and also for
> 
> ```
>         await this.flush();
> ```
> 
> have you made your work open source already

this.flush() was basically just
``` ts
if (Capacitor.getPlatform() === 'web') await this._sqliteConnection.saveToStore(this.dbName);
```

`actions` are a passed in parameter. the usage is something like
```ts

const db = new LockedSQLiteDBConnection(...);

await db.txn('some description here', /* this is actions */ async txnId => {
  await db.query('select ...');
  await db.executeSet([...//set of sql inserts here//]);
  if (_whoops_failure) throw Error('something went wrong - this will rollback the txn');
  //otherwise it implicitly commits the txn
});
```

**Comment by jepiqueau** [comment]
@mjgoeke look at the new documentation transactions.md i do not follow the same process so there is no de.acions, db.flush, lockedSQLConnection methods.

**Comment by michaelgoeke** [comment]
> @mjgoeke look at the new documentation transactions.md i do not follow the same process so there is no de.acions, db.flush, lockedSQLConnection methods.

Gotcha.
In this case the example at https://github.com/capacitor-community/sqlite/blob/master/docs/SQLiteTransaction.md#for-batch-of-commands is the closest one.
The main would be to write a wrapper which does all the _transactional_ pieces for you, and have `actions` passed in and executed within the method.

end result:
``` ts
const testTransactionManage = async (db: SQLiteDBConnection) => {
  if (db !== null) {
    await db.beginTransaction();
    const isTransAct = await db.isTransactionActive();
    if(!isTransAct) {
      throw new Error('db Transaction not Active');
    }
    try {

      await actions(db); //note if the `db.run/execute/executeSet` methods aren't wrapped the caller needs to remember to pass `false` for the last parameter within their 'actions' code... this is the last "leaky abstraction" part of having actions passed in as an IoC pattern... would be best to wrap db and provide methods that don't even include the 'transaction' property.

      // Commit Transaction
      await db.commitTransaction()
      if (platform === 'web') await sqliteServ.saveToStore(dbName);
    } catch (err) {
      // Rollback Transaction
      await db.rollbackTransaction()
      throw err; //rethrow for caller to handle
    }
  }
}
```


editing and commenting the original code would look more like this:
``` ts
const testTransactionManage = async (db: SQLiteDBConnection) => {
  setLog(prevLog => prevLog + '### Start Transaction Manage ###\n');
  if (db !== null) {
    await db.beginTransaction();
    const isTransAct = await db.isTransactionActive();
    if(!isTransAct) {
      throw new Error('db Transaction not Active');
    }
    try {
      // run command
      await actions(db); //note if the `db.run/execute/executeSet` methods aren't wrapped the caller needs to remember to pass `false` for the last parameter within their 'actions' code... this is the last "leaky abstraction" part of having actions passed in as an IoC pattern
//this all goes away, it's expected the caller includes the 'actions' specifics
/*      let insertQuery = 'INSERT INTO DemoTable (name, score) VALUES (?, ?);';
      let bindValues = ["Betty", 152];
      let ret = await db.run(insertQuery, bindValues, false);
      console.log(`>>> run ret 2: ${JSON.stringify(ret)}`)
      // execute command
      const statements = `
        INSERT INTO DemoTable (name, score) VALUES ('Aimie',115);
        INSERT INTO DemoTable (name, score) VALUES ('Test1',330);
        INSERT INTO DemoTable (name, score) VALUES ('George',223);
      `;
      ret = await db.execute(statements,false);
      console.log(`>>> execute ret 2: ${JSON.stringify(ret)}`)

      // executeSet command
      ret = await db.executeSet(setScores1,false);
      console.log(`>>> executeSet 2 ret: ${JSON.stringify(ret)}`)

*/
      // Commit Transaction
      await db.commitTransaction()
      if (platform === 'web') {
        await sqliteServ.saveToStore(dbName);
      }
      setLog(prevLog => prevLog + '### Commit Test Transaction Manage ###\n');
    } catch (err) {
      console.log(`in catch : ${err}`)
      // Rollback Transaction
      await db.rollbackTransaction()
      setLog(prevLog => prevLog + '### RollBack Test Transaction Manage ###\n');

    }/* finally {
      let selectQuery = "SELECT * /* all columns */ FROM Demotable;";
      const retQuery = await db.query(selectQuery);
      console.log(`>>> query All retQuery2: ${JSON.stringify(retQuery)}`)
      setLog(prevLog => prevLog + '### End Test Transaction Manage ###\n');
    }*/
  }
}
```

**Comment by jepiqueau** [comment]
@mjgoeke what is the difference with executeTransaction which is already a wrapper ? In your case what is the action?

**Comment by michaelgoeke** [comment]
```ts
//given `_db`

async function myCode {
  await transactionWithCODE(_db, async db => {
    try {
        await db.run('INSERT INTO DemoTable (name, score) VALUES (?, ?);', ["Betty",152] , false);
        //run lots of other code that only happens if we needed to insert
    } catch (e) {
        //fall back to just updating the single row
        await db.run('UPDATE DemoTable set score = ? where name = ?;', [152, "Betty"] , false);
    }
  });
}  

const transactionWithCODE = async (db: SQLiteDBConnection, actions: (db: SQLiteDBConnection) => Promise<any>) => {
  if (db !== null) {
    await db.beginTransaction();
    const isTransAct = await db.isTransactionActive();
    if(!isTransAct) {
      throw new Error('db Transaction not Active');
    }
    try {
      await actions(db); //note - this code could throw - it would be caught by and user try/catch stuff before landing here

      // Commit Transaction
      await db.commitTransaction()
      if (platform === 'web') await sqliteServ.saveToStore(dbName);
    } catch (err) {
      // Rollback Transaction
      await db.rollbackTransaction()
      throw err; //rethrow for caller to handle
    }
  }
}
```

the wrapper I mentioned is unimportant, but it'd just expose a wrapper around _db that exposes the run/execute/executeSet calls WITHOUT the last transaction parameter and always passes false (so the user can't accidentally screw up and start and commit another txn within the current one)

**Comment by jepiqueau** [comment]
@mjgoeke i am still not with you. What is the function await actions(db) can you define it

**Comment by michaelgoeke** [comment]
@jepiqueau 
In the method `transactionWithCODE` it's the second parameter.
Instead of passing **data** we pass a user supplied **function or lambda expression** that is then executed within the wrapper function `transactionWithCODE`.
see the function definition line - the parameter is right there:
`const transactionWithCODE = async (db: SQLiteDBConnection, actions: (db: SQLiteDBConnection) => Promise<any>) => {
`

actions can be whatever the user passes (it's a lambda expression or function).
In the example above it's this part (bolded below):

> async function myCode {
>   //example 'action' - it's the async function that's the second parameter into `transactionWithCODE`
>   await transactionWithCODE(_db, ***async db => {
>     try {
>         await db.run('INSERT INTO DemoTable (name, score) VALUES (?, ?);', ["Betty",152] , false);
>         //run lots of other code that only happens if we needed to insert
>     } catch (e) {
>         //fall back to just updating the single row
>         await db.run('UPDATE DemoTable set score = ? where name = ?;', [152, "Betty"] , false);
>     }
>   }***);
> }
