### ISSUE TITLE
importFromJson result shows incorrect changes

### ISSUE THREAD

**Issue by petterbergman** [capacitor-community/sqlite#231]
**Describe the bug**
When using importFromJson a SECOND time with the same data, number if changes shows as double, even though it should show 0 as nothing has changed.

**To Reproduce**
Using testimportjson from angular-sql-app-starter as baseline, call importFromJson on the following data TWICE:

export const partialImport999: any = {
    database : "db-from-json",
    version : 1,
    encrypted : false,
    mode : "partial",
    tables :[
        {
            name: "users",
            values: [
                [1,"Whiteley.com","Whiteley",30.5,1582536810]
            ]
        },
    ]
};

Using code like:
      // partial import 1
      result = await this._sqlite
                        .importFromJson(JSON.stringify(partialImport999));
      if(result.changes.changes !== 1 ) return Promise.reject(new Error("1st ImportFromJson 'partial' partialImport999 failed because changes = " + result.changes.changes));
      // partial import 1
      result = await this._sqlite
          .importFromJson(JSON.stringify(partialImport999));
      if(result.changes.changes !== 0 ) return Promise.reject(new Error("2nd ImportFromJson 'partial' partialImport999 failed because changes = " + result.changes.changes));

First call yields 1 change as expected.

Second call yields 2 changes (although no records have been imported)

last_modified is does not equal original value

**Expected behavior**
Second call to importFromJson should yield 0 changes (as there should be none)

last_modified should not be different from original value

**Screenshots**

**Desktop (please complete the following information):**

- OS: macOS (web and iOS simulator)
- Browser Chrome
- Version 98.0.4758.109 

**Smartphone (please complete the following information):**

- Device: Simulator
- OS: iOS 15.2
- Browser Chrome
- Version 98.0.4758.109 

**Additional context**
I've made a test in angular-sql-app-starter and I'll be happy to check it in or share it in any other form.

**Comment by jepiqueau** [comment]
@petterbergman Thanks for using the plugin can you share the `full import` where you created the table schema as this one is a `partial import`

**Comment by jepiqueau** [comment]
@petterbergman Well in fact it is a normal behavior. At a time you create the table with the `full or partial` import, the software create a trigger `_trigger_last_modified` on the last modified field to make sure that when you will do an export all the data imported from one or more `partial` imports will be exported. The software does not look at the data if they are the same or not. so this is why the `last_modified` field has changed and so the change number returned is correct. So this is not a bug

**Comment by petterbergman** [comment]
The missing full import:

export const dataToImport999: any = {
    database : "db-from-json",
    version : 1,
    encrypted : false,
    mode : "full",
    tables :[
        {
            name: "users",
            schema: [
                {column:"id", value: "INTEGER PRIMARY KEY NOT NULL"},
                {column:"email", value:"TEXT UNIQUE NOT NULL"},
                {column:"name", value:"TEXT"},
                {column:"age", value:"REAL"},
                {column:"last_modified", value:"INTEGER"}
            ],
            indexes: [
                {name: "index_user_on_name",value: "name"},
                {name: "index_user_on_last_modified",value: "last_modified DESC"},
                {name: "index_user_on_email_name", value: "email ASC, name", mode: "unique"}
            ]
        },
    ]
};

So maybe I'm not quite understanding how last_modified will help at all in syncing data from an external source.

The documentation on importFromJson doesn't mention any trigger and it isn't clear how the user should be using last_modified and/or setSyncDate to keep their data in sync with an external source. Perhaps you can clarify and we can update the documentation.

I've got several tables on a server that I try to keep in sync with my device database. I use full import to create an empty database. Then I pull the server for each table's data and use partial importFromJson to update the device database. Now, if I pull the server a second time, how do I know which records to pull?

**Comment by jepiqueau** [comment]
@petterbergman after each import 'partial` you setSyncDate now when you want to pull from the server a second time you geSyncDate and pull data from the server from that date

**Comment by petterbergman** [comment]
Correct me if I'm wrong, but setSyncDate simply sets one datetime in the database. If that's the case, then doing what you propose will require the app to pull from all tables and assume all transactions will commit in a single pull, without the option to pull each table separately. If the data is large, and requires foreign keys, this will often not be possible.

Is there any way to use importFromJson without having the triggers created? If so, I can create my own sync strategy (it's not difficult to keep a list of per-table sync datetimes), while still leveraging the ease of importFromJson to setup the schema and initial data.

BTW, thanks for all your hard work creating and maintain this plugin. It's essential for our community and it's a game changer for Ionic/Capacitor app creation.

**Comment by jepiqueau** [comment]
@petterbergman i do not really follow you. A lot of developers are using it for pulling from a server and pushing back to the server without any question about this process. I will have a look on how to do this for you by using a parameter isJsonTrigger (default true) in the capacitor.config.ts that you could set to false. This means that you will be on your own to manage your import strategy. No errors coming from this decision will be look at by me. The import/export process works as is from more than two years without issues. Hope you will understand.

**Comment by petterbergman** [comment]
Totally understandable. My preference would simply to track last synced date per table, as opposed to a single sync date and I don't see the setSyncDate doing that.

Looking at the plugin code, It wouldn't be difficult to turn off the triggers with a simple flag in the JSON (such as in ImportFromJson.swift line 224). However, if I'm the only user requiring such a flag, it wouldn't be too hard for me to simply create my own createTableSchema method and apply the statements manually.

Thus, if I'm the only user who prefer not using triggers, I'll go ahead and create my own method to generate the statements.

**Comment by jepiqueau** [comment]
@petterbergman Well you cannot really do it at the table level as a table's data can be dependent of other table's data so they all have to be synched in one transaction. I will modified the code to create a trigger only if a `last_modified` column exists in the schema. Not having this column will imply that there is no creation of a `sync table` and you can only use the mode `full` for importing/exporting from/to the remote server database which is ok for small databases but not for large. For me it would be better to create the right json object to import (avoiding to send data which already exist and are not modified)

**Comment by petterbergman** [comment]
@jepiqueau I think there's no need to change anything in the plugin code. I think it's more important to add a section to ImportExportJson.md to describe how to use these methods. For me, I have legacy server code and design I have to support, so doing it per table is my best option. It's easily done with SQL statements and for users like me who wants to do it differently than the recommended (plugin supported) method, it makes more sense to keep that code local.

**Comment by jepiqueau** [comment]
@petterbergman OK in your case it make sense to do it locally in your app with SQL statements. In that case you do not need to define a column last_modified and to create a sync table. Good luck for your development

**Comment by jepiqueau** [comment]
@petterbergman this has been fixed in 3.4.2 the trigger has to be changed see doc ImportExportJson.md and a method has been added in the update to only update if there is a changé of data
