### ISSUE TITLE
Problem cloning project to another computer

### ISSUE THREAD

**Issue by gassssty** [capacitor-community/sqlite#232]
Hi guys! 

I have a small problem and I'm trying to clone a project (using gitlab), on another computer; and when I try to execute some of the Capacitor SQL Lite functions (like 'importFromJson' or 'isJsonValid'), I get an error that the stringify JSON object is not right.
It only happens when I try to clone, because on the computer where I created the whole project, it works perfectly.

Attached is a screenshot of what I get in the log.

I'm using IONIC (Angular framework) and I'm trying to run the app with Android Studio.

Do you know what it could be?

Thanks and best regards! :D

![image](https://user-images.githubusercontent.com/83598997/157015637-f6965294-4827-4bc8-b3a3-04a715244499.png)

**Comment by gassssty** [comment]
P.S.: I have checked the versions if they are the same, and they are exact... so that error is discarded.

**Comment by gassssty** [comment]
And more images:
![image](https://user-images.githubusercontent.com/83598997/157017264-cf556725-707e-4f95-ab4e-10157ad09bf3.png)

The code:
![image](https://user-images.githubusercontent.com/83598997/157017438-fb0fed0d-97d5-4634-b56f-1426b012ddb8.png)

The alert in the device:
![image](https://user-images.githubusercontent.com/83598997/157017370-3d0e05bc-8d9f-4fbc-b949-04897db2a447.png)

**Comment by jepiqueau** [comment]
@gassssty OK i understand

**Comment by jepiqueau** [comment]
@gassssty i can't do too much on this, which platform are you using? Is it Electron ?

**Comment by gassssty** [comment]
Is Ionic. But it's okay. I fixed it creating another project, and copying all to the new and it works!!

Thanks btw!! :D

**Comment by jepiqueau** [comment]
@gassssty OK 👌 then i close the issue
