### ISSUE TITLE
No handling of changeEncryptionSecret (android)

### ISSUE THREAD

**Issue by CSVerbeek** [capacitor-community/sqlite#233]
**Describe the bug**
In the function changeEncryptionSecret the call is not always handled. This is the case when biometricAuth is false. The promise returned will never be resolved or rejected.

**To Reproduce**
changeEncryptionSecret without biometricAuth

**Expected behavior**
Should be resolved like in the onSuccess of the BiometricListener.

**Screenshots**

**Smartphone (please complete the following information):**

- OS: [android]

**Additional context**
Solution: Use the same code in the else block as in the onSuccess of the listener
```
                if (biometricAuth) {
                    BiometricListener listener = new BiometricListener() {
                        @Override
                        public void onSuccess(BiometricPrompt.AuthenticationResult result) {
                            try {
                                // change encryption secret
                                uSecret.changeEncryptionSecret(passphrase, oldPassphrase);
                                rHandler.retResult(call, null, null);
                                return;
                            } catch (Exception e) {
                                String input = e.getMessage();
                                Log.e("MY_APP_TAG", input);
                                Toast.makeText(context, input, Toast.LENGTH_LONG).show();
                                rHandler.retResult(call, null, e.getMessage());
                            }
                        }

                        @Override
                        public void onFailed() {
                            String input = "Error in authenticating biometric";
                            Log.e("MY_APP_TAG", input);
                            Toast.makeText(context, input, Toast.LENGTH_LONG).show();
                            rHandler.retResult(call, null, input);
                        }
                    };

                    UtilsBiometric uBiom = new UtilsBiometric(context, biometricManager, listener);
                    if (uBiom.checkBiometricIsAvailable()) {
                        uBiom.showBiometricDialog(biometricTitle, biometricSubTitle);
                    } else {
                        throw new Exception("Biometric features are currently unavailable.");
                    }
                } else {
                    // change encryption secret
                    uSecret.changeEncryptionSecret(passphrase, oldPassphrase);
                    // PROBLEM IS HERE: Should resolve or reject with retHandler.retResult !!!!!!!!!!!!!!!!!
                }
```

**Comment by jepiqueau** [comment]
@CSVerbeek i will have a look but i will be away for the next 5 days. Normally you do not need it as it is in a try ... catch and then the reHandler is in the CapacitorSQLitePlugin. java file if it catch an error. In your did you make the call in a try ... catch

**Comment by CSVerbeek** [comment]
If there is an error to catch, then yes the retHandler will be used. If there is no error this is not the case. The promise returned in typescript code will never resolve.

**Comment by jepiqueau** [comment]
@CSVerbeek have you run angular-sqlite-app-starter and did you have an issue running it?.

**Comment by CSVerbeek** [comment]
@jepiqueau No I used the method in my own application and encountered the issue. After some research I found this is the issue.

**Comment by jepiqueau** [comment]
@CSVerbeek can you share your code? As i said i am now leaving so i will look at your code end of n'est week

**Comment by jepiqueau** [comment]
@CSVerbeek end of next week

**Comment by CSVerbeek** [comment]
@jepiqueau The only relevant code to share is:
```
await this.sqlite.changeEncryptionSecret(passphrase, oldpassphrase);
```
This is still working fine in version 3.3.3. In later versions it stopped working.

**Comment by jepiqueau** [comment]
@CSVerbeek i will have a look when i am back

**Comment by jepiqueau** [comment]
@CSVerbeek 3.4.2-1 has been published when tested if there is no more issues can you please close the issue

**Comment by jepiqueau** [comment]
@CSVerbeek Did you test it?

**Comment by CSVerbeek** [comment]
> @CSVerbeek Did you test it?

@jepiqueau Sorry. I got the flu and then I was busy with catching up with work. I didn't have time to test it yet.

**Comment by jepiqueau** [comment]
@CSVerbeek hope you feel better. Tell me when done

**Comment by CSVerbeek** [comment]
@jepiqueau Thanks for implementing. It works. I'll close the issue.

**Comment by jepiqueau** [comment]
@CSVerbeek 👍
