### ISSUE TITLE
Remove all the console messages

### ISSUE THREAD

**Issue by Sampath-Lokuge** [capacitor-community/sqlite#236]
Hi,

Please remove all the console messages on this plugin. Because it'll directly effect to degrade the performance of native apps. And also security risk too. i.e. can see the table names and etc. Thanks!

![c1](https://user-images.githubusercontent.com/5206526/159167983-f9df9621-ed21-4790-a224-d5ac0d415eff.png)

**Comment by jepiqueau** [comment]
@Sampath-Lokuge which platform?

**Comment by Sampath-Lokuge** [comment]
Sorry, I was not able to mention that. Here it is:

```
Ionic:

   Ionic CLI                     : 6.16.3 (C:\Users\Sampath\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.0.11
   @angular-devkit/build-angular : 13.0.1
   @angular-devkit/schematics    : 13.0.1
   @angular/cli                  : 13.0.1
   @ionic/angular-toolkit        : 5.0.0

Capacitor:

   Capacitor CLI      : 3.4.0
   @capacitor/android : 3.4.1
   @capacitor/core    : 3.4.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.3
   native-run  : 1.5.0

System:

   NodeJS : v14.16.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.12
   OS     : Windows 10
```

**Comment by jepiqueau** [comment]
@Sampath-Lokuge this is the messages coming from capacitor itself nothing to do with the plugin

**Comment by Sampath-Lokuge** [comment]
Ok sure. I have mentioned that to the Capacitor team. We'll see that: https://github.com/ionic-team/capacitor/issues/5517

**Comment by jepiqueau** [comment]
@Sampath-Lokuge 👍sorry there is nothing i can do keep me in the loop

**Comment by Sampath-Lokuge** [comment]
Ok sure. Please keep this issue open until they'll give any feedback there. Thanks!

**Comment by jepiqueau** [comment]
@Sampath-Lokuge ok

**Comment by Sampath-Lokuge** [comment]
Nice. It has an option here: https://capacitorjs.com/docs/v2/apis/console

**Comment by jepiqueau** [comment]
@Sampath-Lokuge thanks for the info i didn't know

**Comment by Sampath-Lokuge** [comment]
Sure!
