### ISSUE TITLE
Feat: Delete use case with Local to Server Sync

### ISSUE THREAD

**Issue by Sampath-Lokuge** [capacitor-community/sqlite#237]
Hi,

I would like to have your feedback/advice about building a better Sync workflow with my Ionic/Angular offline first app. Here is my workflow.

My client's requirement is like so:

> If it is connected, then as needed (when saving a form), if not, then synchronize when status changes to connected.
> 
> I think the synchronization needs to happen automatically. If its the first time, we should probably show a dialog telling the user it could take some time and show some form of progress or spinner.
> 
> After the initial synchronization, Instead of the Cloud Sync button, we use the network plugin to detect connectivity and perform synchronization of data that hasn't yet been synchronized.
> 
> So a flag on the tables to determine whether it has been synchronized and a flag in settings whether the initial migration has taken place.

Please let me know how to handle this kind of workflow with SQLite Data sync APIs? 

I have already developed the SQLite on local databases and etc. I think we need to have an MS SQL server on the serverside no?

So how can I send SQLite sync data to the API?

I have 3 use cases:

1. If the user is online then I need to save those data on both server/API and Locally. I cannot see any issue here and I can handle this use case since it is an online use case

I use GUID for PK on all the tables.

2. Let's say the user works on an offline use case after the above online situation. So how can I determine the newly added/modified/deleted records locally using your Sync APIs to send them back to Server API/DB after the user is online again?

3. Let's say the user will use a new device use case. i.e. lost his old device and etc. So at that time, I need to send his old data back to the local SQLite database after he'll log in to the app. Any advice here too?

Please let me know a better workflow for handling the above use cases. If you'll propose a better workflow than what my client said above I can discuss it with him. Please let me know. Thanks in advance.

**Comment by Sampath-Lokuge** [comment]
Thanks a lot for the feedback. Sure, I'll go through your doc and will let you know if I'll have more questions.

One question here: Can you tell me how to handle the Delete use case with Local to Server Sync. i.e `Export to Json`

I fully delete the record from the table right now. So then how the server knows about that deleted record on partial mode?

**Comment by jepiqueau** [comment]
@Sampath-Lokuge that the good point. Nobody ask for it before so i will have to have a look at it

**Comment by Sampath-Lokuge** [comment]
Ok sure. Please let me know your thoughts/workaround and etc. after you'll see that. Thanks!

**Comment by Sampath-Lokuge** [comment]
Hi @jepiqueau 

Do you have any solution/workaround to handle the below use case? Thanks!

> One question here: Can you tell me how to handle the Delete use case with Local to Server Sync. i.e Export to Json
> 
> I fully delete the record from the table right now. So then how the server knows about that deleted record on partial mode?

**Comment by jepiqueau** [comment]
@Sampath-Lokuge this has to be developed.

**Comment by Sampath-Lokuge** [comment]
Ok sure. Please let us know after you'll develop it. Thanks!

**Comment by jepiqueau** [comment]
@Sampath-Lokuge i am working on. I have nearly the iOS part working still have an issue when deleting an item which are others items reference to it in an other table. A new column sql_deleted equal to 0 or 1 will be added and if there is a sync table the DELETE statement will be change to UPDATE statement with the column sql_deleted set to 1

**Comment by Sampath-Lokuge** [comment]
This is great news. Please let us know after you'll fully complete this for both native platforms. Good luck!

**Comment by jepiqueau** [comment]
@Sampath-Lokuge This has been implemented in 3.4.3-2 for Web, iOS and Android. You can have a look to ([solidjs-vite-sqlite-app](https://github.com/jepiqueau/capacitor-solid-sqlite)) which i have used for implementation and testing.

**Comment by Sampath-Lokuge** [comment]
Hi @jepiqueau 

Actually, I'm an Ionic/Angular developer only. So I hope you'll do the same for the Ionic/Angular repo too. Thanks!

**Comment by jepiqueau** [comment]
@Sampath-Lokuge This has been implemented in 3.4.3-3 for Electron. I will close the issue

**Comment by jepiqueau** [comment]
@Sampath-Lokuge You can now find a Ionic/Angular app implementing the change [angular-sqlite-synchronize-app](https://github.com/jepiqueau/angular-sqlite-synchronize-app). Hope you will enjoy it

**Comment by Sampath-Lokuge** [comment]
Great! I'll see that. Thanks!
