### ISSUE TITLE
Insert of floating point / decimal value on iOS throws UtilsSQLCipherError.bindFailed and inserts null value

### ISSUE THREAD

**Issue by mpkasp** [capacitor-community/sqlite#239]
**Describe the bug**
Insert of floating point / decimal value on iOS throws UtilsSQLCipherError.bindFailed and inserts null value; works fine on websql, and Android.

**To Reproduce**

I have a typeorm object like this:
```typescript
@Entity({name: 'food'})
export class Food {
  @Column({nullable: true})
  name: string = '';

  @Column({nullable: true, type: 'decimal'})
  servingSize: number = null;

  @Column({nullable: true, type: 'decimal'})
  fatPerGram: number = null;
...
```

and if I insert fatPerGram at 0.5, I get an error from UtilsSQLCipherError.bindFailed. iOS stack trace shown in screenshot

**Expected behavior**
0.5 gets inserted into database

Actual: NULL gets inserted into database

**Screenshots**
<img width="1468" alt="Screen Shot 2022-03-23 at 10 30 38 PM" src="https://user-images.githubusercontent.com/5695263/159830171-5a8c954d-2837-4721-a4b5-84582ddfe047.png">

**Desktop (please complete the following information):**

- OS: iOS 15.3.1
- Browser [e.g. chrome, safari]: Capacitor Core 3.3.3 webview (safar?)

**Smartphone (please complete the following information):**

- Device: [e.g. iPhone6] iPhone 8
- OS: [e.g. iOS8.1] iOS 15.3.1

**Additional context**

Running "@capacitor-community/sqlite": "^3.4.2-1"
Integers, strings are inserting fine
Works fine on websql and android

**Comment by jepiqueau** [comment]
@mpkasp Was it working in 3.4.1?

**Comment by mpkasp** [comment]
I tried reverting and running an `ionic cap sync`. Looks like it still breaks in the same place
<img width="1468" alt="Screen Shot 2022-03-24 at 8 24 28 PM" src="https://user-images.githubusercontent.com/5695263/160030949-553bf2a1-9e3f-4cce-8523-0c97db1929e6.png">

**Comment by mpkasp** [comment]
So seems the `value` is coming in to swift as a Float type from the plugin despite calling it type: 'double' in typeorm. Not sure the intricacies of this plugin but checking for a Float type in the binding call and casting it to double to bind to double seems to fix my issue:

```swift
class func bind( handle: OpaquePointer?, value: Any?, idx: Int)
    throws {
        if value == nil {
            sqlite3_bind_null(handle, Int32(idx))
        } else if (value as? NSNull) != nil {
            sqlite3_bind_null(handle, Int32(idx))
        } else if let value = value as? Double {
            sqlite3_bind_double(handle, Int32(idx), value)
        } else if let value = value as? Float {
            sqlite3_bind_double(handle, Int32(idx), Double(value))
        }
...
```

**Comment by jepiqueau** [comment]
@mpkasp I could not reproduce the error, may be something coming from the typeOrm driver for this plugin. any how i will add what you suggest.

**Comment by jepiqueau** [comment]
@mpkasp Have you tested the new release 3.4.2-2?

**Comment by mpkasp** [comment]
Tested and works for me now, thank you @jepiqueau !
