### ISSUE TITLE
Error: echo "Not implemented on web."

### ISSUE THREAD

**Issue by tobiasmuecksch** [capacitor-community/sqlite#241]
**Describe the bug**
When I try to call `echo` on a `SQLiteConnection` instance an exception `Not implemented on web.`  is thrown in Safari.

Of course, I have added the wasm file to my angular assets folder.

**To Reproduce**
Demo Repo: https://github.com/tobiasmuecksch/capacitor-sqlite-angular

1. Create blank ionic angular starter
2. install dependencies
3. copy the wasm to the `src/assets` folder
4. execute the following code (in a component, service or what ever you like).

```typescript

const connection = new SQLiteConnection(CapacitorSQLite);
const result = await connection.echo('test');

console.log('result');
```

I have looked at the angular usage example [here](https://github.com/capacitor-community/sqlite/blob/master/docs/Ionic-Angular-Usage.md) and in the echo method it does not check if native is true.

![Bildschirmfoto 2022-03-25 um 10 45 08](https://user-images.githubusercontent.com/1294854/160097245-e9bd9c80-0910-4e8c-9c7a-c7494ad6be05.png)

Therefore I assume that echo should also be available on web. In the [supported methods section of the documentation](https://github.com/capacitor-community/sqlite#supported-methods) the echo method is not mentioned at all. 

**Expected behavior**
I'd expect the echo method to work, or the documentation and the usage example to clearly state, that echo is not available on web.

**Comment by tobiasmuecksch** [comment]
I'm having the same problem with `isJsonValid`.

```typescript
const isValid = await CapacitorSQLite.isJsonValid({ jsonstring: productSchemaJson });
```

It also throws an exception which says, that this would not be available for web, but  in the [supported methods section of the documentation](https://github.com/capacitor-community/sqlite#supported-methods) it clearly states, that this is available on web.

**Comment by tobiasmuecksch** [comment]
I have created a demo repository:

https://github.com/tobiasmuecksch/capacitor-sqlite-angular

**Comment by jepiqueau** [comment]
@tobiasmuecksch  you must edit your main.ts file
```
import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from './app/app.module';
import { environment } from './environments/environment';
import { defineCustomElements as jeepSqlite} from 'jeep-sqlite/loader';

if (environment.production) {
  enableProdMode();
}
jeepSqlite(window);
platformBrowserDynamic().bootstrapModule(AppModule)
  .catch(err => console.log(err));

``` 
now `jeep-sqlite` can be used in your app it is requested to have the web part of the plugin
and update the `app.component.html` file
```
<ion-app>
  <ion-router-outlet></ion-router-outlet>
  <jeep-sqlite *ngIf="isWeb"></jeep-sqlite>
</ion-app>

```
somehow you have to have a variable `isWeb `in your `app.component.ts`

and also something like this to initialize the webStore

```
        if( platform === "web") {
          this.isWeb = true;
          await customElements.whenDefined('jeep-sqlite');
          const jeepSqliteEl = document.querySelector('jeep-sqlite');
          if(jeepSqliteEl != null) {
            await this.sqlite.initWebStore();

            console.log(`isStoreOpen ${await jeepSqliteEl.isStoreOpen()}`)
            console.log(`$$ jeepSqliteEl is defined}`);
          } else {
            console.log('$$ jeepSqliteEl is null');
          }
        }

```

**Comment by tobiasmuecksch** [comment]
It worked. Thanks!

I'd recommend to add this information here: https://github.com/capacitor-community/sqlite#web

**Comment by jepiqueau** [comment]
@tobiasmuecksch happy that it works. Have a good app development
