### ISSUE TITLE
bug: `deleteDatabase()` does not work

### ISSUE THREAD

**Issue by tobiasmuecksch** [capacitor-community/sqlite#247]
**Describe the bug**
I wanted to delete a database called `product-db` but it didn't work.
[The documentation](https://github.com/capacitor-community/sqlite/blob/master/docs/API.md#deletedatabase) is not very informative about deleting databases.

At first I saw this error:
```
 DeleteDatabase: No available connection for product-db
``` 

I was a little confused, why I need a connection for that, but I created a connection. The connection itself does not offer any deletion method. There only is a method to delete "old databases". 

So I **opened a connection** to the database and retried to call the `.deleteDatabase()` method on the CapacitorSQLite Object.
The **promise returned void**, but the database is still present 😱  **It wasn't deleted.** 

**To Reproduce**

1. Create a Database
2. Restart the app
3. try to delete a database before opening a connection
4. See the error
5. open a connection to the database which you want to delete
6. retry to delete the database
7. there is no error, but the database is still there

**Code**

```typescript
await CapacitorSQLite.deleteDatabase({ database: 'product-db' });
```

**Expected behavior**
The database should disappear.

If a connection is necessary, this information should be added [to the documentation here](https://github.com/capacitor-community/sqlite/blob/master/docs/API.md#deletedatabase).

Additionally; if a connection is really necessary,  I'd propose to move the method into that Connection-object for better comprehensibility.

The code would look like this then:

```typescript
const dbConnection = await this.sqliteConnection.retrieveConnection(databasename);

await dbConnection.deleteDatabase(); // we don't need to specify the databasename, it's already in the connection
```

**Additional context**
I'm testing on safari with `jeep-sqlite`.

**Comment by tobiasmuecksch** [comment]
I tested it on iOS, and it doesn't work there too.

**Comment by jepiqueau** [comment]
@tobiasmuecksch for me it works fine.
``` 
const dbConnection = await this.sqliteConnection.createConnection("product-db", false, "no-encryption", 1);
await dbConnection.open();
await dbConnection.delete();
await this.sqliteConnection..closeConnection("product-db");
``` 
So i close the issue

**Comment by tobiasmuecksch** [comment]
You are right. It works with this code.

The problem is, that this method is not documented in the DB Connection Wrapper documentation.

https://github.com/capacitor-community/sqlite/blob/master/docs/APIConnection.md
