### ISSUE TITLE
saving database to storage - ANDROID

### ISSUE THREAD

**Issue by dodo-sofranko** [capacitor-community/sqlite#248]
**Describe the bug**
HI, at first, thanks for your work.
I am new to IONIC, and I am not sure how to save created sql database to storage of android. 
I sucessfully created database and imported data from json api. 
Also loading data from database works correctly, but is stored only for one session.
Somewhere I read that db.close() should store data automatically or I neet something more? 
Thanks for advance.

**Comment by jepiqueau** [comment]
@dodo-sofranko Are you talking Web app or Android App? in Android the database is automatically created under the  `data/data/YOUR_PACKAGE/databases`. and it is there when you re-open the app except if you have delete it. You are mixing with the Web plugin where here you need to `db.close()` or `db.saveToStore()`to save the in-memory database to the store

**Comment by dodo-sofranko** [comment]
@jepiqueau thanks for confirmation that it should work this way. I finally found typo which caused that.
Thanks again for your work
