### ISSUE TITLE
Help: Handle BLOB images with Export To JSON workflow

### ISSUE THREAD

**Issue by Sampath-Lokuge** [capacitor-community/sqlite#251]
Hi,

I store images like so on the Sqlite table and all are working fine.

`  Image BLOB NULL,`

But I have an issue with the `Export To JSON` workflow. i.e. since that blob size is around 4MB I cannot use it to send API due to its huge size. I use Firebase Storage for the images on online-only apps. But since this is an offline-first app how to handle this kind of issue? Thanks! 

**Note:** Here I need to send a lot of such records to the API at once. That is a huge load on the API. And this is from a mobile device too. i.e. Ionic/Angular native app

![blo](https://user-images.githubusercontent.com/5206526/162666712-860e3549-c488-410c-92cf-84ca4322c184.png)

**Comment by jepiqueau** [comment]
@Sampath-Lokuge No idea except to split your export in several partial exports.

**Comment by Sampath-Lokuge** [comment]
Ok sure, I'll use 1 backend API call per record. Since my app regularly/automatically uploads the records to the API/Database where it'll have very less records per session.  Thanks!

**Comment by jepiqueau** [comment]
@Sampath-Lokuge 👌
