### ISSUE TITLE
How to enable failed sync data for next `exportToJson` workflow

### ISSUE THREAD

**Issue by Sampath-Lokuge** [capacitor-community/sqlite#252]
Hi,

I have used `exportToJson` workflow like so and all are working fine. i.e. I need `partial` use case here. But I have a question here. Let's say the API update fails for a 1 record. Then how can I inform the `exportToJson` workflow to show that record on that table again for the next `exportToJson()` workflow too? 

Now if I'll use the below code then it doesn't show any previous failed once. I would like to know how have you handled these things on this plugin behind the scene too. I can't see where you put any update on the ` last_modified` filed on each and every record too. Please let me know. Thanks! 

```
  async exportToJson(): Promise<capSQLiteJson> {
    try {
      const exportToJson = await this.sqliteDbConnection.exportToJson('partial');

      this.sqliteDbConnection.setSyncDate(new Date().toISOString());

      return exportToJson;
    } catch (error) {
      console.error(`exportToJson`, error);
    }
  }
```

**Comment by jepiqueau** [comment]
@Sampath-Lokuge It is certainly interesting to put all this questions on the table. You should also propose  some process solutions to answer these questions. If what is on the table is not good enough for your needs you can still write your own synchronization process by using in your app standard SQL queries. I cannot look on any directions. If the API failed to update a record, the transaction is rollback meaning that the database is not updated. so the export will not export the data which have been rollback. I do really follow what you said

**Comment by Sampath-Lokuge** [comment]
I think where I have not given clear information here. Here API means backend API where I need to send this exported data. i.e. not the plugin's API.

My question is this. If I'll need to enable one record for the next `exportToJson()` cycle due to some issue on the backend API failer then how can I do that? Now I cannot see any way to do that. Can you tell me how have you set it all done after running this `this.sqliteDbConnection.setSyncDate(new Date().toISOString());`?

**Comment by Sampath-Lokuge** [comment]
Hi @jepiqueau 

Do we have any way/method to inform `exportToJson()` where we have an issue with one record and please regenerate that record again for the next `exportToJson()` workflow? Your thoughts? Thanks!

**Comment by jepiqueau** [comment]
@Sampath-Lokuge exportToJson is browsing the database fully or partially  with standard SQL queries and lords the query results in a Json object. So i do not understand how you can have a problem with one record. You should give example. If you have a problem with one record meaning that the database data are wrong you could mak
- a partial import for that record to update it 
- use a standard sql query to update the record
May be i did not understand the question please illustrate

**Comment by Sampath-Lokuge** [comment]
My question here is not about that workflow. 

If I'll need to enable one record for the next `exportToJson()` cycle due to some issue on the backend API failer due to no internet or else then how can I do that? Now I cannot see any way to do that.

**e.g.** 

`exportToJson()` will give 5 records to send backend API of mine. Here all the records are fine and no issues there. Lets' say due to an internet failure where an app cannot send all the 5 records to the production Database. i.e. send 4 and cannot send `id=5` record to the production db. Since I have already set the `SyncDate` after the `exportToJson()`  workflow I'll not able to get that record again if I'll run the `exportToJson()`.  

So my question here is how to get that `id=5` record again if I'll run the `exportToJson()`  again?

**Comment by jepiqueau** [comment]
@Sampath-Lokuge now i understand your question. Your app has to manage to wait the success from your backend before to set the syncDate

**Comment by Sampath-Lokuge** [comment]
I think that will not solve my issue hence I need to do this only for 1 or 2 records. i.e. not for all.

What about this kind of workflow here?

Hence I'll need to do this only for a few known records what if I'll update the `last_modified` date of that record a few hours ahead of the SyncDate? Then I think that record will available for the next `exportToJson()` workflow no?

**Comment by jepiqueau** [comment]
@Sampath-Lokuge Well you can do this it will make the job you do not need to wait hours, you can create a delay function
```
export const delay = async (delay: number, message: string): Promise<void> => {
        return new Promise (resolve => {
          setTimeout(() => {
            const s = "*".repeat(message.length)
            console.log(`*****************${s}`);
            console.log(`Simulate a delay ${message}`);
            console.log(`*****************${s}`);
            resolve();
          }, delay * 1000);
        });
      }
```
 await delay(2, 'before updating last_modified on few records');
and now you call your function to update the last_modified on few records
Voilà
