### ISSUE TITLE
createSyncTable: No last_modified column in tables

### ISSUE THREAD

**Issue by CosminCraciun** [capacitor-community/sqlite#253]
**Describe the bug**
Android and Electron fails when calling db.createSyncTable() on an empty database.

> Error: Uncaught (in promise): Error: Error invoking remote method 'CapacitorSQLite-createSyncTable': createSyncTable: No last_modified column in tables
Error: Error invoking remote method 'CapacitorSQLite-createSyncTable': createSyncTable: No last_modified column in tables

Seems to be related to commit https://github.com/capacitor-community/sqlite/commit/5176a13e2366942ff54b0f70fa18e6fd1b0aa241

Web not affected.

**To Reproduce**

1. Have the app in an empty state, with no database existing.
2. Create database
3. Call `createSyncTable`

**Expected behavior**
It used to work fine in the past. I expected the sync table to be created.

Is there some change I'm missing? I have checked the release notes and it just mentions a fix on `createSyncTable`. Maybe I'm missing something from the documentation

**Comment by jepiqueau** [comment]
@CosminCraciun thanks but this is the normal behaviour. To create the sync table you must have the database created with tables having a last_modified colum.  This is mandatory i am currently implementing a sql-deleted  column for synchronisation and i will use this to decide if it is a pure SQLite DELETE (no synchronisation) or an UPDATE  with the sql_deleted set to 1. 
So change your app accordingly

**Comment by CosminCraciun** [comment]
I understand. 
One thing to mention: the error is not thrown in the Web version

Thanks for the quick reply
