### ISSUE TITLE
bug: `npx cap sync @capacitor-community/electron` breaks configuration

### ISSUE THREAD

**Issue by tobiasmuecksch** [capacitor-community/sqlite#255]
**Describe the bug**
As we already discussed in [this issue](https://github.com/capacitor-community/sqlite/issues/242) it is necessary to add some configuration to the `electron/capacitor.config.ts` file.

The problem is, that whenever I run `npx cap sync @capacitor-community/electron` it removes the `plugin` section completely. I am using this command frequently, and I wonder how to fix that?  

**To Reproduce**

1. clone repo: https://github.com/tobiasmuecksch/capacitor-sqlite-angular2. 
2. take a look at the file `electron/capacitor.config.ts` and see, that the plugin config is there. 
3. run `npx cap sync @capacitor-community/electron`. 
4. now look at the file `electron/capacitor.config.ts` again, and you will see that the plugin config is gone.

**Expected behavior**
The config should not be removed.

**Comment by jepiqueau** [comment]
@tobiasmuecksch You must put 
```
  plugins: {
    CapacitorSQLite: {
      electronWindowsLocation: 'CapacitorDatabases',
      electronMacLocation: 'CapacitorDatabases',
      electronLinuxLocation: 'CapacitorDatabases'
    }
  }
```
in the `capacitor.config.ts` file of your app then this file will be automatically copied to the electron folder when you use the standard process
```
npx cap sync @capacitor-community/electron
npm run build
npx cap copy @capacitor-community/electron
npx cap open @capacitor-community/electron
```
Look at the different app starter
Voilà Good development

**Comment by tobiasmuecksch** [comment]
Well, that's embarrassing. I haven't even realized that this file synchronized from the app's root folder to electron.

Thanks!

**Comment by jepiqueau** [comment]
@tobiasmuecksch 👍may be if you have sometimes you could make a PR to improve the documentation so others could benefit from all these discussions  and have a better and easy start. For myself i try to concentrate on development and fixes

**Comment by tobiasmuecksch** [comment]
@jepiqueau Sure. I'm already thinking about how the documentation could be improved 😊

**Comment by jepiqueau** [comment]
@tobiasmuecksch 👍👏
