### ISSUE TITLE
Bug: ExportToJson: return Obj is not a JsonSQLite Obj - prod build only

### ISSUE THREAD

**Issue by Sampath-Lokuge** [capacitor-community/sqlite#256]
Hi,

I set Syncdate like so:
```

  setSynchronizationDate(): Promise<void> {
    return this.sqliteDbConnection.setSyncDate(new Date().toISOString());
  }
```
I set `last_modified` like so:

` last_modified INTEGER NOT NULL,`

```
createExpense(expense: ExpenseModel): Promise<capSQLiteChanges> {
    const sqlQuery = `INSERT INTO Expenses (
      ExpenseId,
      CreatedDate,
      last_modified,
      UserId) 
      VALUES (?,?,?,?,?,?,?,?,?,?,?)`;

    const sqlValues = [
      expense?.id,
      expense?.createdDate,
      dayjs().unix(),
      expense?.userId,
    ];

    return this.sqliteDbConnection.run(sqlQuery, sqlValues, false);
  }

```

But still, it says like so:

```
exportToJson Error: ExportToJson: ExportToJson ExportToJson: return Obj is not a JsonSQLite Obj
    at Object.cap.fromNative (VM3:411:32)
    at <anonymous>:1:18
```

My workflow:

1. init

```
  async initializeSynchronizationProcess(): Promise<void> {
    await this.sqliteDbConnection.createSyncTable();

    this.sqliteDbConnection.setSyncDate(new Date().toISOString())
  }
```

The above will run only once for the app life

2. Each and every transaction where I update the `last_modified` like so on the above. i.e. ` dayjs().unix(),`

3. At the end of the `exportToJson` where I update the Sync date like so:

` this.sqliteDbConnection.setSyncDate(new Date().toISOString())`

So please let me know why the above error then? I use `partial` and this is an Ionic/Angular Native app. Thanks!

**P.S. 1:**

I have used this too `last_modified INTEGER DEFAULT (strftime('%s', 'now')),` But same above issue.

```
createExpensesTable(): Promise<capSQLiteChanges> {
    const query = `
          CREATE TABLE IF NOT EXISTS Expenses (
            ExpenseId TEXT PRIMARY KEY NOT NULL,
            Name TEXT NULL,
            Amount REAL NULL,
            Date INTEGER NULL,
            VatId TEXT NULL,
            ExpenseTypeId TEXT NULL,
            Image BLOB NULL,
            ExpenseTemplateId TEXT NULL,
            CreatedDate INTEGER NOT NULL,
            UserId TEXT NOT NULL,
            last_modified INTEGER DEFAULT (strftime('%s', 'now')),
            FOREIGN KEY(VatId) REFERENCES Vats(VatId),
            FOREIGN KEY(ExpenseTypeId) REFERENCES ExpenseTypes(ExpenseTypeId),
            FOREIGN KEY(ExpenseTemplateId) REFERENCES ExpenseTemplates(ExpenseTemplateId)
          );`;

    return this.sqliteDbConnection.execute(query);
  }
```

**P.S. 2**

I have done further research/testing on this and I was able to see this issue only happens on the `--prod` build. i.e. no issues on development mode like so: `ionic cap run android -l --host=0.0.0.0`

The problem is on this workflow:

```
ionic build --prod

npx cap sync android

npx cap open android
```

And no issues on `full` mode. Only with `partial` mode. This is an `Ionic/Angular native app`. 

It seems this is a major BUG. Please let me know your thoughts.

**Comment by Sampath-Lokuge** [comment]
Any feedback here?

**Comment by jepiqueau** [comment]
@Sampath-Lokuge i did not look at it yet. I was and still is working on the implementation of the delete process whick take me a lot of time

**Comment by Sampath-Lokuge** [comment]
Hi @jepiqueau
 
Ok sure. It would be great if you'll find out some time to see this issue hence this is an issue of an already existing feature. i.e. delete workflow is a completely brand new feature. So on our side where we are completely blocked right now due to we cannot send our SQLite data to the API. So we'll highly appreciate it if you'll provide us with some advice/solutions here. Thanks in advance!

**Comment by jepiqueau** [comment]
@Sampath-Lokuge can you share your code

**Comment by jepiqueau** [comment]
@Sampath-Lokuge if i do 
```ionic build --prod``` 
or
```ng build --configuration production```
i got the following error at build time
```
Schema validation failed with the following errors:
  Data path "" must NOT have additional properties(extractCss).
```

**Comment by jepiqueau** [comment]
@Sampath-Lokuge You must not update the last_modified yourself. 
A trigger can manage this for you . 
This trigger is automatically created when you use an importFromJson which is not your case so when you create the Schema of your database add the creation of this trigger for each table:
```
CREATE TRIGGER IF NOT EXISTS YOURTABLENAME_trigger_last_modified
AFTER UPDATE ON YOURTABLENAME
FOR EACH ROW WHEN NEW.last_modified < OLD.last_modified
BEGIN
    UPDATE YOURTABLENAME SET last_modified= (strftime('%s', 'now')) WHERE id=OLD.id;
END;
```

**Comment by jepiqueau** [comment]
@Sampath-Lokuge Your createExpense function is wrong you must have the same number of times ? than you have the number of given values

**Comment by Sampath-Lokuge** [comment]
Hi @jepiqueau 

All are working perfectly fine on all the use cases now. Thanks a lot.

It would be great if you'll update the doc with these things hence I was not able to find out these details anywhere on the doc.

**Comment by jepiqueau** [comment]
@Sampath-Lokuge Sorry i come back on work.
i had change createExpense like this
```
  async createExpense(expense: ExpenseModel): Promise<capSQLiteChanges> {
    const sqlQuery = `INSERT INTO Expenses (
      ExpenseId,
      Name,
      Amount,
      Date,
      VatId,
      ExpenseTypeId,
      Image,
      ExpenseTemplateId,
      CreatedDate,
      UserId)
      VALUES (?,?,?,?,?,?,?,?,?,?)`;

    const sqlValues = [
      expense.id,
      expense.name ? expense.name : null,
      expense.amount ? expense.amount : null,
      expense.date ? expense.date : null,
      expense.vatId ? expense.vatId : null,
      expense.typeId ? expense.typeId : null,
      expense.image ? expense.image : null,
      expense.templateId ? expense.templateId : null,
      expense.createdDate,
      expense.userId,
    ];
    try {
      const res =  await this.sqliteDbConnection.run(sqlQuery, sqlValues, false);
      return Promise.resolve(res);
    } catch (err ) {
      return Promise.reject(err);
    }
  }
```
and add the trigger and it is working fine.
Ok that this is working for you know
in fact i will modify the error message when the partial export does not return anything which in that case it was returning the message return Obj is not aJsonSQLite Obj

**Comment by Sampath-Lokuge** [comment]
> i will modify the error message when the partial export does not return anything which in that case it was returning the message return Obj is not aJsonSQLite Obj

Yes, that is true. We would like to have a more meaningful error message in the context of the use case here.

**Comment by jepiqueau** [comment]
@Sampath-Lokuge you can have a look at [ionic-sqlite-256](https://github.com/jepiqueau/ionic-sqlite-256)

**Comment by Sampath-Lokuge** [comment]
Sorry, I didn't get that. Is this for what?

**Comment by jepiqueau** [comment]
@Sampath-Lokuge this is the app i develop to see the issue and where it was coming from

**Comment by Sampath-Lokuge** [comment]
Ok sure. All are working fine now on my app too. Thanks a lot!
