### ISSUE TITLE
bug: Simultaneous write operations broken on `web` and `electron`

### ISSUE THREAD

**Issue by tobiasmuecksch** [capacitor-community/sqlite#258]
**Describe the bug**
I'm working on a chat app. That means, that my app receives events asynchronously. For example such an event could be a new message.

It happens pretty often, that multiple messages are received at the same time, which means that the app tries to add multiple messages at the same time to the database. On `Android` that works perfectly fine. But on `iOS` `web` and `electron` it doesn't work as expected at all.

On `iOS` and `web` only one of the multiple messages are saved. The other datasets are discarded without any error.

On `electron` the following exception is thrown:

<img width="526" alt="Bildschirmfoto 2022-04-17 um 13 09 49" src="https://user-images.githubusercontent.com/1294854/163711873-963c7a6c-3566-49bc-97ca-065912d24d31.png">

**To Reproduce**
The following code **does not work** as expected (on web and electron):

```typescript
 async addDataToTestDB() {
    // Since I'm not using await here, these operations are called simultaneously.
    this.insertData('id1', 'Bob');
    this.insertData('id2', 'Lina');
    this.insertData('id3', 'Maria');
  }

  async insertData(id: string, name: string) {
    const dbConnection = await this.sqlite.openDB('test-db');
    const result = await dbConnection.run('REPLACE INTO test(id, name) VALUES(?,?)', [id, name]);

    // The following line is only necessary on web platform
    await this.sqlite.saveToStore('test-db');
  }
```

But if I actively take care that there are no simultaneous db queries, the bug does not appear.

```typescript
 async addDataToTestDB() {
    await this.insertData('id1', 'Bob');
    await this.insertData('id2', 'Lina');
    await this.insertData('id3', 'Maria');
  }
```

**Expected behavior**
Simultaneous database write actions should work.

**Desktop (please complete the following information):**

- OS: macOS 12.3.1
- Browser: Safari
- Version: 15.4

**Demo code**

1. clone repo: git@github.com:tobiasmuecksch/capacitor-sqlite-angular.git
2. test `web`: `npm run start`
3. test `electron`: `npm run electron:start`

Click buttons in this order (while looking at the js console):

1. "Create Tables"
2. "Insert some data"
3. "print select all to console"
4. "drop database"

**Comment by jepiqueau** [comment]
@tobiasmuecksch you must do it with the await to make sure that the transaction is completed  or add them to a queue that you execute within the same transaction

**Comment by jepiqueau** [comment]
@tobiasmuecksch when you insertion an item avoid to open each time the db test if it is open and if not open it that slow down the process

**Comment by tobiasmuecksch** [comment]
> @tobiasmuecksch when you insertion an item avoid to open each time the db test if it is open and if not open it that slow down the process

@jepiqueau Thanks for the hint. In fact my `openDB` method checks if there already is a connection, and re-uses it.

**Comment by tobiasmuecksch** [comment]
> @tobiasmuecksch you must do it with the await to make sure that the transaction is completed or add them to a queue that you execute within the same transaction

Hm. That's not how I'd expect a database to work. No database I have ever worked with, required the developer to take care of execution locks and/or queues.

As I already explained, data is added to the database as a reaction to asynchronous events which are triggered by the sever via web-socket. Therefore `await` does not have any effect inside an event callback.

If I understand you right, I have to implement a query-queue for the platforms `web` and `electron`. 

But why doesn't the plugin implement a queue for these platforms under the hood? It would make the plugin way easier to use and make it act more like a real database.

**Comment by jepiqueau** [comment]
@tobiasmuecksch can you test  executing this statement
```
PRAGMA journal_mode=WAL
```
after the db.open()
This must solve the issue

**Comment by tobiasmuecksch** [comment]
I just tried that, and the following exception occurred:

```
[Error] ERROR – Error: Uncaught (in promise): Execute: ExecuteSQL: ExecuteSQL: Execute: cannot change into wal mode from within a transaction
```

**Comment by jepiqueau** [comment]
@tobiasmuecksch just do your execute command with transaction to false

**Comment by tobiasmuecksch** [comment]
Allright; I got rid of the exception with a little workaround. 

<details>
<summary>Screenshot: Workaround Code</summary>
<img width="951" alt="Bildschirmfoto 2022-04-19 um 09 20 34" src="https://user-images.githubusercontent.com/1294854/163947954-301c1a49-fa60-4847-974e-c74aca4c847b.png">
</details>

On line 89 I'm querying and printing the `journal_mode` to make sure that it really is applied. And it seems to be successfully changed.
But the problem of described in this issue is still there 😢

**Comment by tobiasmuecksch** [comment]
> @tobiasmuecksch just do your execute command with transaction to false

Ah, you are right. I overlooked that there is a `transaction` parameter on this method. I changed my code accordingly. The problem is still the same :(

<details>
<summary>Screenshot corrected code<summary>

<img width="924" alt="Bildschirmfoto 2022-04-19 um 09 27 11" src="https://user-images.githubusercontent.com/1294854/163949276-2f2a2e6d-45a9-4b64-8cb6-d7aec8f6d67e.png">

</details>

**Comment by tobiasmuecksch** [comment]
@jepiqueau I've done some research and found out that there is a `wal2` mode.

Soruce: https://stackoverflow.com/a/54475279/1646019

I'm still testing it, but it seems to fix the issue. 

If this really fixes the issue. Can you make it the default mode for all connections?

**Comment by tobiasmuecksch** [comment]
On android, setting the `journal_mode` to `wal2` fails with this error:

```
ERROR Error: Uncaught (in promise): Error: Execute: unknown error: Queries cannot be performed using execSQL(), use query() instead.
```

**Comment by tobiasmuecksch** [comment]
On `electron` changing to `wal2` does not fix the exception

![](https://user-images.githubusercontent.com/1294854/163711873-963c7a6c-3566-49bc-97ca-065912d24d31.png)

**Comment by jepiqueau** [comment]
@tobiasmuecksch 
```
        await this.db.open();
        if (this.platform !== 'android') {
          await this.db.execute(`PRAGMA journal_mode=WAL;`,false);
        }

```

**Comment by tobiasmuecksch** [comment]
@jepiqueau as I already said, `WAL` does not fix the problem. Only `WAL2` does fix this problem for `ios` and `web`. `electron` automatically sets `WAL` instead of `WAL2`. So I still need a solution for `electron`.

What do you think about, making `wal2` the default pragma on `iOS` and `web` ?

**Comment by tobiasmuecksch** [comment]
@jepiqueau No need to hurry 😉 

All right. I do understand. Since it's not possible to run simultaneous write operations anyways, what do you think about implementing a queue into the plugin? We could add a configuration variable with which developers can turn it off, if they want to.

**Comment by phal0r** [comment]
@tobiasmuecksch @jepiqueau I stumbled upon the second error in this thread and I think this is still a unresolved bug, right?

> I did some research, and if I understand https://github.com/mattn/go-sqlite3/issues/709#issuecomment-485295884 correctly, it could be that the plugin misinterprets the response of sqlite as an error, although no error has occurred.

Setting the PRAGMA throws, although it's not an actual error.

**Comment by tobiasmuecksch** [comment]
Yes this is still an issue. I circumvented it, by writing my own Queue in order to always execute SQL statements and queries in sequence instead of parallel.

I would advice you, to do the same.

**Comment by jepiqueau** [comment]
@tobiasmuecksch could you share your que ingénieur implementation or make a PR to jeep-sqlite and @capacitor-community/sqlite electron so every developer can benefit from this.

**Comment by phal0r** [comment]
@jepiqueau @tobiasmuecksch Queueing was the initial issue here. But you guys discusssed a second issue, which is a seperate bug:

> I did some research, and if I understand https://github.com/mattn/go-sqlite3/issues/709#issuecomment-485295884 correctly, it could be that the plugin misinterprets the response of sqlite as an error, although no error has occurred.

When executing this sql, it throws an error, although no error has happened. This should be fixed independently of queueing.

**Comment by jepiqueau** [comment]
@tobiasmuecksch if you update to @capacitor-community/sqlite@4.1.0-8 and upgrade in the electron folder of your app  sqlite3 to 5.1.0 it works fine with WAL2. You can have a look at [test with Wal2 & readonly](https://github.com/jepiqueau/angular-sqlite-app-starter/blob/master/src/app/test/testreadonly/testreadonly.page.ts) hope this help

**Comment by tobiasmuecksch** [comment]
@jepiqueau Thanks. I will test that and close the issue if the problem is fixed

**Comment by tobiasmuecksch** [comment]
@jepiqueau I'm still having the same issues :-(

**Comment by jepiqueau** [comment]
@tobiasmuecksch you must provide me a repro app on github as i never experiences this problem

**Comment by jepiqueau** [comment]
@tobiasmuecksch any progress on this? I am still waiting some code to reproduce the error

**Comment by tobiasmuecksch** [comment]
@jepiqueau I haven't had the time yet, to update the repro app. I will do that asap.

**Comment by tobiasmuecksch** [comment]
@jepiqueau I have updated the repro app to the latest version of `sqlite3@5.1.2` and to `@capacitor-community/sqlite@4.2.0`.

Additionally I have added a statement to set the `journal_mode` to `WAL2`. The issue is still there.

(See changes regarding WAL2 here: https://github.com/tobiasmuecksch/capacitor-sqlite-angular/commit/37b44a761910f012deedb019f5718faab71c4df5#diff-f076088e0454292ba7d4c88f1eb19181a115deb2a35a4b265da42abf9344a7b6R137)

**How to reproduce:**

1. clone repo: git@github.com:tobiasmuecksch/capacitor-sqlite-angular.git
2. test `electron`: `npm run electron:start`

Click buttons in this order (while looking at the js console):

1. "Create Tables"
2. "Insert some data"
3. "print select all to console"
4. "drop database"

**Comment by jepiqueau** [comment]
@tobiasmuecksch i test it it works fine for iOS, Android and Web but not for Electron. To make it working in Electron seems the you must put the transaction to false in the db.run

**Comment by jepiqueau** [comment]
@tobiasmuecksch i think i may have find the reason but i cannot this this morning run electron:start both on Windows and MAC i got the following error : Error: Cannot find module 'node:fs/promises' and i have no glue of what it is. when i git clone your project last evening it was working fine and reproducing the error with Wal  in Electron. Now even if i re-clone it today i got always Error: Cannot find module 'node:fs/promises' . Any idea? I put a release 4.2.2-1 but i am enable to test it. Any idea about this. Can you upgrade to 4.2.2-1 on your side and tell me if it works

**Comment by tobiasmuecksch** [comment]
@jepiqueau thank you for your effort. I'm currently out of office. I will test it on Saturday, and let you know whether I'm experiencing the same issues. Maybe I can find a solution.

**Comment by jepiqueau** [comment]
@tobiasmuecksch i update to "electron": "^15.5.7" and it is working back 
in 4.2.2-1 i implement BEGIN CONCURRENT instead of BEGIN TRANSACTION  when the journal_mode start with wal. But i get a syntax error near CONCURRENT meaning that for me it has not be implemented in node sqlite3. On top of this when we change to `wal2` instead of `wal` it does not work too the journal_mode return is `delete`. again it does not seem to be implemented. So i do not think i can do something for your case i spent a full day on it and i do not have a solution

**Comment by tobiasmuecksch** [comment]
@jepiqueau Thank you so much for your effort. According to this issue https://github.com/TryGhost/node-sqlite3/issues/408 this seems not to be implemented for sqlite3.

The author of the follow comment, recommends to switch to `better-sqlite3`. Are there any reasons, you decided to use `sqlite3` instead of `better-sqlite3`?
https://github.com/TryGhost/node-sqlite3/issues/408#issuecomment-354013490

**Comment by jepiqueau** [comment]
@tobiasmuecksch At the time in Electron i was using `@journeyapps/sqlcipher` to give the ability to encrypt the database which is based on sqlite3.  Finally i fall back to `sqlite3` when developers had some problems to create a Windows executable.
In fact i look this morning at the Web part `jeep-sqlite` based on sql.js the mode Wal2 does not exist too. and when setting to mode WAL i got `cannot start a transaction within a transaction` if i do not keep the await in front of the db.run the only way to have it working with no await is to select transaction false.
Moving to `better-sqlite3` could be feasible but it is quite a work and would necessary before starting to test in a simple case that it is working with the WAL mode or WAL2 mode.

**Comment by tobiasmuecksch** [comment]
Okay. I think we should add a warning to the readme for example that WAL/WAL2 is not officially supported by this plugin. 

For now I'm thinking about a clean way to add a queue mechanism to this plugin. Can you imagine to add that to the plugin, or do you want to keep this out of the plugin?
I could make a proposal / merge request for that.

**Comment by jepiqueau** [comment]
@tobiasmuecksch i want googling through a lot of docs this morning and i could not find a way. I will stop on this. For me the queing will make the the execution of each transaction one after other which is similar to what the async is doing. 
In that case i do not really understand what the `wal` mode differs from the `delete` mode.
There is may be something that i do not understand .
if you develop a queue mechanism for the Electron part of this plugin and you have a PR ready with an example that i can test i will merge it but i will have to implement it in the jeep-sqlite plugin too.
For the time being i will stop working on this as it took me some day work. i am sorry to not have found solution for this

**Comment by tobiasmuecksch** [comment]
@jepiqueau All good. I completely understand that, and I'm thankful, that you tried to find a solution. As I said; I'd suggest to add a note about this on the readme, to prevent future duplicate issues.

**Comment by jepiqueau** [comment]
@tobiasmuecksch finally i got it see the code in [capacitor-sqlite-angular](https://github.com/jepiqueau/capacitor-sqlite-angular)🤪😅

**Comment by tobiasmuecksch** [comment]
@jepiqueau I'm confused. Does that mean, the problem needs to be fixed by changing files in the electron project?

**Comment by jepiqueau** [comment]
@tobiasmuecksch no  i change only the sqlite.service.ts and the package.json scripts to make them compatible mac and windows

**Comment by jepiqueau** [comment]
@tobiasmuecksch in web and electron i run the dbConnection.run with transaction false and i encapsulates the  await PromiseAll with BEGIN TRANSACTION ... COMMIT TRANSACTION or ROLLBACK TRANSACTION

**Comment by jepiqueau** [comment]
@tobiasmuecksch i also upgrade Electron to "electron": "^15.5.7" in Electron/package.json file

**Comment by tobiasmuecksch** [comment]
Okay, thank you for the information. I will try that too.

**Comment by mousepotato** [comment]
Sample code: https://github.com/jepiqueau/capacitor-sqlite-angular/blob/main/src/app/services/sqlite.service.ts#L103-L113

**Comment by caiorsantanna** [comment]
This should be in the documentation on the web version :)
