### ISSUE TITLE
Feat: Ionic/Angular app with TypeORM

### ISSUE THREAD

**Issue by Sampath-Lokuge** [capacitor-community/sqlite#259]
Hi,

Can we have a sample `Ionic/Angular` app with the `TypeORM` library? I think that will help a lot of devs who would like to use TypeORM with your plugin. Thanks!

https://typeorm.io/

**Comment by jepiqueau** [comment]
@Sampath-Lokuge You are asking far too much, you have to make your home work. There are developers working with TypeOrm and sqlite. There is a documentation available TypeORM-Usage.md and there is a vue typeorm example in https://github.com/jepiqueau and also a ionic angular app https://github.com/jepiqueau/ionic-sqlite

**Comment by Sampath-Lokuge** [comment]
I use Ionic/Angular only. It seems you have not documented [this ](https://github.com/jepiqueau/ionic-sqlite) TypeORM sample app no?

**Comment by tobiasmuecksch** [comment]
@Sampath-Lokuge I don't understand your problem. There is an example which will work in every framework here:

https://github.com/capacitor-community/sqlite/blob/master/docs/TypeORM-Usage.md

The documentation is not up-to-date because `createConnection()` is deprecated and you have to use `new DataSource()`. I've created a pull request, which should work with the latest version of typeorm.

You can find the pull request here: https://github.com/capacitor-community/sqlite/pull/262/commits/1d4c1e8edd7914cbe0a427e2288c59720a069d85

**Comment by jepiqueau** [comment]
@tobiasmuecksch @Sampath-Lokuge i knowall this guys i have less time to give to development those days but it will come. I like the way Tobias works asking and making PR's as he contributes to the improvment of the plugin. I am in the middle of the implementation of the delete command as requested   by @Sampath-Lokuge so i will see how and when to do the merge. You can have a look at vue-typeorm-app where there is a PR also to implement the new Datasource hope this will help and that you will have some patience

**Comment by jepiqueau** [comment]
@Sampath-Lokuge Did you make some progress on this. I still have to do the delete process for Electron platform before looking at this if it is still required.

**Comment by jepiqueau** [comment]
@Sampath-Lokuge I have been working on without success when entities have `OneToMany` and `ManyToOne` relation.
if someone can help here, he will be welcome.

**Comment by jepiqueau** [comment]
@Sampath-Lokuge I finally get there see app at [ionic-sqlite-typeorm-app](https://github.com/jepiqueau/ionic-sqlite-typeorm-app). It is the standard `category-author-post` example and i use migration . the migration file has been generated manually. Hope this will help you starting. I will close the issue
