### ISSUE TITLE
bug: electron db is not open although`.openDB()` runs without exception

### ISSUE THREAD

**Issue by tobiasmuecksch** [capacitor-community/sqlite#260]
**Describe the bug**
In the constructor of my `app.component.ts` I'm calling a method which creates tables if they do not exist and then inserts some data.

Sometimes it happens that, although I have called `await dbConnection.open()` and `dbConnection.isDBOpen()` is returning `true` I see the following error:

<img width="1112" alt="Bildschirmfoto 2022-04-19 um 18 40 19" src="https://user-images.githubusercontent.com/1294854/164053811-6407d3f4-294a-4ce6-83d7-8d3d99717f0c.png">

And even more confusing; sometimes `dbConnection.isDBOpen()` returns `false`, **ALTHOUGH** I call it AFTER `await dbConnection.open()`

<img width="1112" alt="Bildschirmfoto 2022-04-19 um 18 46 21" src="https://user-images.githubusercontent.com/1294854/164054579-4dfd3812-7afc-4abe-940c-b835766cf061.png">

This is how I open the database:

<img width="931" alt="Bildschirmfoto 2022-04-19 um 18 43 38" src="https://user-images.githubusercontent.com/1294854/164056860-7e56b492-68e7-44a0-9213-68b6bbf8831c.png">

**To Reproduce**
I have created a branch in my demo repo which reliably demonstrates this bug. These are the steps to reproduce the behavior:

1. `git clone --branch electron-dbOpen-bug git@github.com:tobiasmuecksch/capacitor-sqlite-angular.git`
2. `npm install`
3. `npm run electron:start`

Notice: You'll find the call of the init method in `src/app/home/home.page.ts`

**Desktop:**

- OS: macOS 12.3.1
- Platfrom: electron
- Version: 18.x

**Comment by jepiqueau** [comment]
@tobiasmuecksch i do not have the right to `git clone --branch electron-dbOpen-bug git@github.com:tobiasmuecksch/capacitor-sqlite-angular.git`

**Comment by tobiasmuecksch** [comment]
@jepiqueau That's strange, because this is a public repository. Can you clone it without the branch tag and then switch to the branch?

**Comment by jepiqueau** [comment]
@tobiasmuecksch i will have a look this evening now i am out travelling

**Comment by tobiasmuecksch** [comment]
For future reference: 

The first part of the problem was, that the `openDB()` method does **re-open a connection**, even if it is already open. That can result in **race-conditions**. Therefore the developer should manage the connections himself, and reuse open connections.

The second part of the problem was, that while `sqlite3` (the underlying sqlite package) is described to be a `non-blocking` database layer, **it has problems when transactions are started simultaneously.** So the solution is either to disable `transaction` for your `run` and `execute` calls or to implement your custom locking strategy (e.g. by creating a queue).
