### ISSUE TITLE
executeSet return capSQLiteChanges Changes.changes not equal to the statement in array

### ISSUE THREAD

**Issue by MonicaExplan** [capacitor-community/sqlite#265]
Hi,
I'm using executeSet to execute a set of "insert on conflict update" statement.
My statement are 57 butwhen I execute the executeSet statement:

- the first execution return Changes.changes 60
- the second one return Changes.changes 114
I expected Changes.changes return the number of statement I pass in.
So, what does Changes.changes mean in executeSet? 
The Changes.changes number what is referring to?

Thanks
Monica

**Comment by jepiqueau** [comment]
@MonicaExplan it is difficult to answer without having more details on the state of the database and the executeSet statement. The changes number is not tje number of statements executed but it is the number of changes in the database made by the set of statements.

**Comment by tobiasmuecksch** [comment]
@jepiqueau I'm not sure I understand your explanation. Let's say I  this is my Database:

**Database scheme**
user(userId, name, email, country)

**Already in the database**
user(1, Peter, peter@email.com, france)



Then I'm running this:
`REPLACE INTO user (userId, name, email, country) VALUES(1, 'Maria', `marina@email.com`, 'france');`

Will this return the count of changed column values (in this example 2), or will it return the number of changed rows (which would be 1 in this example).

**Comment by MonicaExplan** [comment]
@jepiqueau 

You have write:
"The changes number is not tje number of statements executed but it is the number of changes in the database made by the set of statements."

Briefly:
- there are already 3 records in table sites
- I prepare an array named "executionSet" with the statement below foreach of my sites (number 57)
`INSERT INTO sites (syncId, code, name, address, city, province, country, zip, email,telephone, lat, lng ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(syncId) DO UPDATE SET code=excluded.code,name=excluded.name,address=excluded.address,city=excluded.city,province=excluded.province,country=excluded.country,zip=excluded.zip,email=excluded.email,telephone=excluded.telephone,lat=excluded.lat,lng=excluded.lng;`
- i set transaction to false
- I execurte this statment 
executeSet(executionSet, transaction)
and I obtain 60 that is 3+57

So I suppose: 
- it execute the 3 insert, then conflict so execute 3 update on this record. 
- The other inserts 54 (57-3) work because the records don't exist.  
At the end:
- 3+ 3 +54 = 60, the executeSet() return Changes.changes 60 (but 60 are the SQL statement of the executeSet)
- After execution of executeSet() I have 57 records in my table (that' right)...I think that "_the number of changes in the database made by the set of statements" are the record changed succesfully, so 57 not 60
 
Thanks a lot
Monica

**Comment by jepiqueau** [comment]
@tobiasmuecksch a REPLACE will return changes.changes = 1

**Comment by jepiqueau** [comment]
@MonicaExplan I am looking at it this type of statement which was never test so i cannot anticipate the behavior of the plugin. I assume excluded.code, excluded.name ...  are some default values. Are these values the same for all your sites. I do not see the values given for the ?,?,...
Can you provide the detailed complete code of that executeSet

**Comment by MonicaExplan** [comment]
@jepiqueau 
I'm using this SQLite statement
https://www.sqlite.org/lang_UPSERT.html

**1. About "excluded"**
In the link above you can read this explanationa about excluded
"Column names in the expressions of a DO UPDATE refer to the original unchanged value of the column, before the attempted INSERT. To use the value that would have been inserted had the constraint not failed, add the special "excluded." table qualifier to the column name. "

To test in DB Browser is:
INSERT INTO sites (syncId, code, name, address, city, province, country, zip, email,telephone, lat, lng )
VALUES ("01FA1B4AB79B6D43C1257FD90056219C", "ANT012","PORTA DI ROMA","Contrada Mandria","ENNA","EN", "IT","20831","myname@domain.it","0935594117","37,5676737","14,2798519")
ON CONFLICT(syncId) DO UPDATE 
SET code=excluded.code
,name=excluded.name
,address=excluded.address
,city=excluded.city
,province=excluded.province
,country=excluded.country
,zip=excluded.zip
,email=excluded.email
,telephone=excluded.telephone
,lat=excluded.lat
,lng=excluded.lng

**2. About executeSet*
I'm using the code below to sync Sites data from a Rest Service. The Rest Service response is an Arrary of Object like this:
[
{"siteId":"01FA1B4AB79B6D43C1257FD90056219C","code":"ANT012","officeCode":"ANT012","name":"PORTA DI ROMA","address":"Via Alberto Lionello, 201, Località Bufalotta","city":"ROMA","province":"RM","country":"","zip":"","email":"prolocofossaltina@gmail.com","telephone":"0690233474","lat":"41,9716623","lng":"12,5401904","last_modified":"2021-09-08T10:05:13Z"}
,...
]

I get the response and then my code is very simple:

// a. upsert statement 
const statement = `INSERT INTO sites (syncId,code,name,address,city,province,country,zip,email,telephone,lat,lng) VALUES (?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(syncId) DO UPDATE SET code=excluded.code,name=excluded.name,address=excluded.address,city=excluded.city,province=excluded.province,country=excluded.country,zip=excluded.zip,email=excluded.email,telephone=excluded.telephone,lat=excluded.lat,lng=excluded.lng;`

// b. prepare array of [statement, values] using foreach on the response.data of a Rest Service returning a list of sites
const executionSet = []  
response.data.forEach( site => {
          const values = [
            site.siteId
            ,site.code
            ,site.name
            ,site.address
            ,site.city
            ,site.province
            ,site.country
            ,site.zip
            ,site.email
            ,site.telephone
            ,site.lat
            ,site.lng
          ]
    
          executionSet.push({
            statement,
            values,
          })
})
// c. execute the set of statement
mydb.executeSet(executionSet, false)

That's all, do you need something else to work on this issue?
Thanks a lot
Monica
P.S: I use this code to sync master data (very numerous) in my APP local DB. If you have others suggestions....it's a pleasure :-)

**Comment by jepiqueau** [comment]
@MonicaExplan 
I made the following example
i start with 6 users in my deb
```
id: 5, email: "Addington@example.com",name: "Addington", age: 22, sql_deleted: 0, last_modified: 1590388335
id: 6, email: "Bannister@example.com",name: "Bannister", age: 59, sql_deleted: 0, last_modified: 1590393015
id: 7, email: "Jackson@example.com",name: "Jackson", age: 18, sql_deleted: 0, last_modified: 1651648773
id: 8, email: "Bush@example.com",name: "Bush", age: 25, sql_deleted: 0, last_modified: 1651648773
id: 9, email: "Kennedy@example.com",name: "Kennedy", age: 45, sql_deleted: 0, last_modified: 1651648773
id: 10, email: "Jeep@example.com",name: "Jeep", age: 65, sql_deleted: 0, last_modified: 1651648773
```
the code is:
```
        try {
            const stuffSet: Array<capSQLiteSet>  = [
                { statement:`INSERT INTO users (name,email,age) VALUES (?,?,?)
                 ON CONFLICT (email) 
                 DO UPDATE SET email = "testconflict@example.com", name="TestConflict", last_modified=(strftime('%s', 'now'));`,
                  values:["Addington","Addington@example.com",22]
                },
                { statement:`INSERT INTO users (name,email,age) VALUES (?,?,?)
                 ON CONFLICT (email) 
                 DO UPDATE SET email = "testconflict1@example.com", name="TestConflict1", last_modified=(strftime('%s', 'now'));`,
                  values:["Jeep","Jeep@example.com",65]
                },
                { statement:`INSERT INTO users (name,email,age) VALUES (?,?,?)
                 ON CONFLICT (email) 
                 DO UPDATE SET email = "testconflict2@example.com", name="TestConflict2", last_modified=(strftime('%s', 'now'));`,
                  values:["Test1","Test1@example.com",45]
                },
                { statement:`INSERT INTO users (name,email,age) VALUES (?,?,?)
                 ON CONFLICT (email) 
                 DO UPDATE SET email = "testconflict3@example.com", name="TestConflict3", last_modified=(strftime('%s', 'now'));`,
                  values:["Test2","Test2@example.com",60]
                },
                { statement:`INSERT INTO users (name,email,age) VALUES (?,?,?)
                 ON CONFLICT (email) 
                 DO UPDATE SET email = "testconflict4@example.com", name="TestConflict4", last_modified=(strftime('%s', 'now'));`,
                  values:["Test3","Test3@example.com",15]
                },
            ];
            let res: any = await db.executeSet(stuffSet); 
            if(res.changes.changes != 5 || res.changes.lastId != 13) {
                const msg = 'changes !=5 or lastId != 13';
                console.log(`${msg}`)
            }

        } catch (err:any) {
            let msg: string = err.message ? err.message : err;
            console.log(`${msg}`)
        }

```
so the changes is 5:  2 update and 3 insert  and the lastId = 13 : 10 prior the executeSet + 3 new in executeSet 

the result in the database is
```
id: 5, email: "testconflict@example.com",name: "TestConflict", age: 22, sql_deleted: 0, last_modified: 1651651648
id: 6, email: "Bannister@example.com",name: "Bannister", age: 59, sql_deleted: 0, last_modified: 1590393015
id: 7, email: "Jackson@example.com",name: "Jackson", age: 18, sql_deleted: 0, last_modified: 1651648773
id: 8, email: "Bush@example.com",name: "Bush", age: 25, sql_deleted: 0, last_modified: 1651648773
id: 9, email: "Kennedy@example.com",name: "Kennedy", age: 45, sql_deleted: 0, last_modified: 1651648773
id: 10, email: "testconflict1@example.com",name: "TestConflict1", age: 65, sql_deleted: 0, last_modified: 1651651648
id: 11, email: "Test1@example.com",name: "Test1", age: 45, sql_deleted: 0, last_modified: 1651651648
id: 12, email: "Test2@example.com",name: "Test2", age: 60, sql_deleted: 0, last_modified: 1651651648
id: 13, email: "Test3@example.com",name: "Test3", age: 15, sql_deleted: 0, last_modified: 1651651648
```
i got the same result if transaction is false

So for me there is no issue

**Comment by jepiqueau** [comment]
@MonicaExplan Thanks for your explanation, i will make a new test

**Comment by MonicaExplan** [comment]
@jepiqueau 
I've tried your test and seems ok...maybe something wrong in my version or package.json?! 

### furthermore sqlite_sequence table increase seq value
I don't have experience if the table sqlite_sequence is managed by SQLite Manager or is about this capacitor sqlite plugin.
If so, the seq value increase even if NO insert are made.
If I run executeSet more then one time on the same resul set (no insert are made, only update!), the seq value in sqlite_sequence table increase even only update and 0 insert.

Thanks a lot
Monica

**Comment by jepiqueau** [comment]
@MonicaExplan 
i did the following test:
```
export const sitesData: any[] = [
    {"siteId":"01FA1B4AB79B6D43C1257FD90056219C","code":"ANT012","officeCode":"ANT012","name":"PORTA DI ROMA","address":"Via Alberto Lionello, 201, Località Bufalotta","city":"ROMA","province":"RM","country":"","zip":"","email":"prolocofossaltina@gmail.com","telephone":"0690233474","lat":"41,9716623","lng":"12,5401904","sql_deleted":0,"last_modified":1651201887},
    {"siteId":"01FA1B4AB79B6D43C1257FD90056220C","code":"ANT013","officeCode":"ANT013","name":"TEST1","address":"Via Test1 , 180","city":"Test1City1","province":"BK","country":"","zip":"","email":"protest1@gmail.com","telephone":"0690233475","lat":"40,9716623","lng":"11,5401904","sql_deleted":0,"last_modified":1651201888},
    {"siteId":"01FA1B4AB79B6D43C1257FD90056221C","code":"ANT014","officeCode":"ANT014","name":"TEST2","address":"Via Test2, 200","city":"Test1City2","province":"CD","country":"","zip":"","email":"protest2@gmail.com","telephone":"0690233476","lat":"39,9716623","lng":"13,5401904","sql_deleted":0,"last_modified":1651201889},
    {"siteId":"02FA1B4AB79B6D43C1257FD90056220C","code":"ANT015","officeCode":"ANT015","name":"TEST3","address":"Via Test3 , 120","city":"Test1City3","province":"TORINO","country":"","zip":"","email":"protest3@gmail.com","telephone":"0790233475","lat":"42,9716623","lng":"14,5401904","sql_deleted":0,"last_modified":1651202000},
    {"siteId":"02FA1B4AB79B6D43C1257FD90056221C","code":"ANT016","officeCode":"ANT016","name":"TEST4","address":"Via Test4, 210","city":"Test1City4","province":"AV","country":"","zip":"","email":"protest4@gmail.com","telephone":"0790233476","lat":"38,9716623","lng":"20,5401904","sql_deleted":0,"last_modified":1651202002},
    {"siteId":"03FA1B4AB79B6D43C1257FD90056220C","code":"ANT017","officeCode":"ANT017","name":"TEST5","address":"Via Test5 , 140","city":"Test1City5","province":"BW","country":"","zip":"","email":"protest5@gmail.com","telephone":"0690233585","lat":"37,9716623","lng":"19,5401904","sql_deleted":0,"last_modified":1651202004},
    {"siteId":"03FA1B4AB79B6D43C1257FD90056221C","code":"ANT018","officeCode":"ANT018","name":"TEST6","address":"Via Test6, 250","city":"Test1City6","province":"CT","country":"","zip":"","email":"protest6@gmail.com","telephone":"0690233586","lat":"36,9716623","lng":"18,5401904","sql_deleted":0,"last_modified":1651202006},
];

        try {
            // test Json object validity
            let res: any = await sqlite.isJsonValid(JSON.stringify(dataToImport265));
            if(!res.result) { 
                const msg = `Error: Json Object dataToImport265 not valid"\n`;
                setErrMsg((errMsg) => errMsg.concat(msg));
                return Promise.reject();
            }
            setLog((log) => log.concat(`> isJsonValid dataToImport265 successful\n`));

            // test import from Json Object
            res = await sqlite.importFromJson(JSON.stringify(dataToImport265)); 
            if(res.changes.changes === -1 ) {
                const msg = `Error: ImportFromJson dataToImport265 changes < 0"\n`;
                setErrMsg((errMsg) => errMsg.concat(msg));
                return Promise.reject();
            }
            setLog((log) => log.concat(`> importFromJson dataToImport265 successful\n`));


            db = await openConnection('db-issue265', false,
                                      'no-encryption', 1, false);
            setLog((log) => log.concat("> Open connection 'db-issue265' successful\n"));
            const twoSitesSet:Array<capSQLiteSet>  = [
                {   statement:`INSERT INTO sites (siteId,code,officeCode,name,address,city,province,country,zip,email,telephone,lat,lng) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)`,
                    values: [
                        ["01FA1B4AB79B6D43C1257FD90056219C","ANT012","ANT012","PORTA DI ROMA","Via Alberto Lionello, 201, Località Bufalotta","ROMA","RM","","","prolocofossaltina@gmail.com","0690233474","41,9716623","12,5401904"],
                        ["01FA1B4AB79B6D43C1257FD90056220C","ANT013","ANT013","TEST1","Via Test1 , 180","Test1City1","BK","","","protest1@gmail.com","0690233475","40,9716623","11,5401904"]
                    ]
                },
            ]
            res = await db.executeSet(twoSitesSet); 
            if(res.changes.changes != 2 || res.changes.lastId != 2) {
                const msg = `Error: twoSitesSet changes != 2 || lastId != 2"\n`;
                setErrMsg((errMsg) => errMsg.concat(msg));
                return Promise.reject();

            }

            const statement = `
            INSERT INTO sites (siteId,code,officeCode,name,address,city,province,country,zip,email,telephone,lat,lng) 
            VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)
            ON CONFLICT(siteId) DO UPDATE 
            SET code=excluded.code,officeCode=excluded.officeCode,name=excluded.name,address=excluded.address,city=excluded.city,province=excluded.province,country=excluded.country,zip=excluded.zip,email=excluded.email,telephone=excluded.telephone,lat=excluded.lat,lng=excluded.lng;
            `
            const fullSitesSet: capSQLiteSet[] = [];
            sitesData.forEach(site => {
                const values = [
                    site.siteId
                    ,site.code
                    ,site.officeCode
                    ,site.name
                    ,site.address
                    ,site.city
                    ,site.province
                    ,site.country
                    ,site.zip
                    ,site.email
                    ,site.telephone
                    ,site.lat
                    ,site.lng
                  ]
                  fullSitesSet.push({
                    statement,
                    values,
                  })                  
            });
            res = await db.executeSet(fullSitesSet); 

            console.log(`fullSiteSet res ${JSON.stringify(res)}`)
            let retQuery = await db.query("SELECT total_changes();", []);
            console.log(`>>> retQuery total_changes(): ${JSON.stringify(retQuery)}`)
            retQuery = await db.query("SELECT last_insert_rowid();", []);
            console.log(`>>> retQuery last_insert_rowid(): ${JSON.stringify(retQuery)}`)

            // Close Connection db-from-json
            res = (await sqlite.isConnection('db-issue265')).result;
            if(res) {
                await sqlite.closeConnection('db-issue265'); 
            } 

```

which is similar to what you do
the first executeSet with two sites returns 
``` changes.change = 2 & changes.lastId = 2 ``` 
the second execSet with seven sites including the two of the first executeSet returns
``` changes.changes = 7 & changes.lastId = 9 ``` 
if i look at the database
the id 3 & 4 does not exist.
so what i understand is that SQLite (not the plugin) is using the number of rows in the set ie 7  and the lastId is increase also by the number of rows in the set ( 2 + 7 = 9 ) but  2 rows are deleted this why the id 3 & 4 do not exist at the end
the sqlite_sequence is managed by SQLite not the plugin 
So if you use this a lot you are creating a lot of gaps in your database so you will need to run the VACUUM statement
