### ISSUE TITLE
Bug: Delete database is not working

### ISSUE THREAD

**Issue by Sampath-Lokuge** [capacitor-community/sqlite#272]
Hi,

Any reason why this is not working or there is another way to drop the database here? Thanks!

`Code:`

`CapacitorSQLite.deleteDatabase({ database: 'dataSQLite' });`

`Error:`

```
core.mjs:6495 ERROR Error: Uncaught (in promise): Error: deleteDatabase: No available connection for database dataSQLite
Error: deleteDatabase: No available connection for database dataSQLite
    at Object.cap.fromNative (home:414:32)
    at <anonymous>:1:18
    at resolvePromise (zone.js:1255:1)
    at zone.js:1162:1
    at rejected (tslib.es6.js:74:89)
    at ZoneDelegate.invoke (zone.js:400:1)
    at Object.onInvoke (core.mjs:25853:33)
    at ZoneDelegate.invoke (zone.js:399:1)
    at Zone.run (zone.js:160:1)
    at zone.js:1318:1
    at ZoneDelegate.invokeTask (zone.js:434:1)
    at Object.onInvokeTask (core.mjs:25840:33)
```

My use case here is I need to delete both the Cordova DB and its Capacitor one like so:

```
 async deleteDatabases(): Promise<void> {
    await this.sqliteConnection.deleteOldDatabases(); // this is working fine

    await CapacitorSQLite.deleteDatabase({ database: 'dataSQLite' }); //failed and gives above error
  }
```

**Comment by jepiqueau** [comment]
@Sampath-Lokuge as said by the error message you must create a connection first to the database and then delete it from the connection

**Comment by Sampath-Lokuge** [comment]
Sorry, I didn't get that? Can I have an example here?

My connection is this `this.sqliteConnection` and it doesn't have any `deleteDatabase` method. i.e. it has `deleteOldDatabases()` only.

**Comment by jepiqueau** [comment]
@Sampath-Lokuge it is the DBConnection which has a method delete

**Comment by Sampath-Lokuge** [comment]
Yes, it is for the `Delete a SQLite DB Connection`. i.e. not the database. Your thoughts?

**Comment by Sampath-Lokuge** [comment]
Hi @jepiqueau 

Will we have a solution here from you hence I'm completely blocked right now due to this issue? Please let me know. Thanks!

**Comment by jepiqueau** [comment]
@Sampath-Lokuge it is for deleting the database

**Comment by jepiqueau** [comment]
@there are plenty of angular starting apps

**Comment by Sampath-Lokuge** [comment]
It is working perfectly fine. Thanks a lot!

>  await this.sqliteDbConnection.delete();

**Comment by jepiqueau** [comment]
@Sampath-Lokuge 👍
