### ISSUE TITLE
Bug: Unable to delete data from a table

### ISSUE THREAD

**Issue by sattasundar** [capacitor-community/sqlite#273]
**Describe the bug**
I need to delete a row from the table by id. But getting error.

Code:
 ```
 async deleteMemberDataByMemKey(userId: number){
      const dbConnection = await this.sqliteDatabseService.openDatabase('user-db',false, 'full', 1);
      const statement = `DELETE FROM users WHERE userID = ${userId};`;
      const result = await dbConnection.execute(statement);
 }
```
Result:
`
changes:
   changes: 1
`
**Expected behavior**
Data need to be deleted.

- Version "@capacitor-community/sqlite": "^3.4.3"
- Framework Ionic-Angular

**Comment by jepiqueau** [comment]
@sattasundar if you got result = {changes:{changes:1}} means that it has been deleted. I do not understand why you need to ```
     const dbConnection = await this.sqliteDatabseService.openDatabase('user-db',false, 'full', 1);
```
may be you open several times a connection  to 'user-db' as i do not see a close of the database.
The syntax of your sql command is correct.

**Comment by jepiqueau** [comment]
@sattasundar a test has been added to Issue271.tsx of [capacitor-solid-sqlite](https://github.com/jepiqueau/capacitor-solid-sqlite) and it works fine.

**Comment by jepiqueau** [comment]
@sattasundar can you close the issue if it is working fine on your side

**Comment by sattasundar** [comment]
@jepiqueau yeah, its working for me now :-)
