### ISSUE TITLE
Errors When Installing SQLiteHook

### ISSUE THREAD

**Issue by rakibul111** [capacitor-community/sqlite#276]
Describe the bug
Error when installing sqlite hook with "@capacitor-community/sqlite": "^3.5.1-1" in React Ionic

To Reproduce

npm i --save-dev react-sqlite-hook@latest

Expected behavior
no errors

$ npm i --save-dev react-sqlite-hook@latest
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: nextjs-tailwind-capacitor@0.1.0
npm ERR! Found: @capacitor-community/sqlite@3.5.1-1
npm ERR! node_modules/@capacitor-community/sqlite
npm ERR!   @capacitor-community/sqlite@"^3.5.1-1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @capacitor-community/sqlite@"^3.0.0" from react-sqlite-hook@2.1.8
npm ERR! node_modules/react-sqlite-hook
npm ERR!   dev react-sqlite-hook@"2.1.8" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\User\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Local\npm-cache\_logs\2022-05-17T06_30_33_439Z-debug-0.log

**Comment by jepiqueau** [comment]
@rakibul111 fix by removing the peer-dependencies.

**Comment by rakibul-dit** [comment]
@jepiqueau I don't know how to remove peer-dependencies

**Comment by jepiqueau** [comment]
@rakibul111 remove the node_modules folder and the package-lock.json modified the package.json file to have the latest version of both @capacitor-community/sqlite and react-sqlite-hook and do npm install. This should work

**Comment by jepiqueau** [comment]
@rakibul111 this has been fixed with react-sqlite-hook@2.1.12
