### ISSUE TITLE
iOS does not throw an error if a table does not exist

### ISSUE THREAD

**Issue by robingenz** [capacitor-community/sqlite#277]
**Describe the bug**

Plugin version: `3.3.3-5`

When I run the following statement for a table that does not exist, iOS behaves differently than Android:

```ts
const statement = "INSERT OR REPLACE INTO \"Test\" VALUES(?, ?)";
const values = ["Key", "Value"];
const dbName = "mfapp.global";
const dbConnection = this.sqlite.createConnection(dbName, false, 'no-encryption', 1);
await dbConnection.open();
await dbConnection.run(statement, values, false);
```

As far as I know Android throws an error that the table does not exist.
On iOS I get no error and the following result: 

```ts
{
	"changes": {
		"changes": -1,
		"lastId": -1
	}
}
```

`returnCode` in https://github.com/capacitor-community/sqlite/blob/c7cc541568e6134e77c0c1c5fa03f7a79b1f9150/ios/Plugin/Utils/UtilsSQLCipher.swift#L438 has value `1`.

The issue has come to our attention because the implementation on Android and iOS behaved differently for our customers.

My workaround is to call `CREATE TABLE IF NOT EXISTS ...` for the respective table before each statement.

Generally, we create a table only when an error is thrown that it does not exist.

**To Reproduce**

1. Create a new database without tables
2. Run the above statements

**Expected behavior**

An error should be thrown on iOS if the table does not exist.

**Comment by jepiqueau** [comment]
@robingenz having returned changes.changes = -1 and change.lastId = -1 means that an error occurs i have to look why the error is not thrown

**Comment by jepiqueau** [comment]
@robingenz there is also a methos isTableExist

**Comment by robingenz** [comment]
Yes, but each request costs performance. I'd rather get an error that a table doesn't exist and then create it, like checking if the table exists before each statement. This would directly double my plugin calls.

**Comment by robingenz** [comment]
Either way, all platforms should behave consistently. If no platform throws an error, I'd still prefer that.

**Comment by jepiqueau** [comment]
@robingenz You must do this under a try ... catch in that way you will get the error in the catch

```
try {
    const statement = "INSERT OR REPLACE INTO \"Test\" VALUES(?, ?)";
    const values = ["Key", "Value"];
    const dbName = "mfapp.global";
    const dbConnection = this.sqlite.createConnection(dbName, false, 'no-encryption', 1);
    await dbConnection.open();
    await dbConnection.run(statement, values, false);
} catch (err:any) {
    let msg: string = err.message ? err.message : err;
    console.log(`catch message: ${msg}`)
}
```

then you will get the error message
- in iOS

```
[log] - catch message: Run: Failed in runSQL :  Error: prepareSQL prepare failed rc: 1 message: no such table: Test

```
- in Android

```
catch message: Run: no such table: Test: , while compiling: INSERT OR REPLACE INTO "Test" VALUES(?, ?)
```
- in Web

```
catch message: Run: RunSQL: RunSQL: run: no such table: Test
```

- in Electron the error is not returned so i will have a look for it

So for me except Electron everything works as expected. If you do not catch the error you will not see it.

**Comment by jepiqueau** [comment]
@robingenz you can have a look at [capacitor-solid-sqlite](https://github.com/jepiqueau/capacitor-solid-sqlite)

**Comment by jepiqueau** [comment]
@robingenz Where do you stand on this?

**Comment by robingenz** [comment]
@jepiqueau I am very busy at the moment and have not yet had time. I'll test it again but last time it didn't work on ios.
