### ISSUE TITLE
Bug: Error: CreateSyncTable: No last_modified column in tables

### ISSUE THREAD

**Issue by Sampath-Lokuge** [capacitor-community/sqlite#282]
Hi,

```
error.service.ts:21 Error: Uncaught (in promise): Error: CreateSyncTable: No last_modified column in tables
Error: CreateSyncTable: No last_modified column in tables
    at Object.cap.fromNative (VM3:414:32)
    at <anonymous>:1:18
    at resolvePromise (zone.js:1255:1)
    at resolvePromise (zone.js:1209:1)
    at zone.js:1162:1
    at asyncGeneratorStep (asyncToGenerator.js:11:1)
    at _throw (asyncToGenerator.js:29:1)
    at ZoneDelegate.invoke (zone.js:400:1)
    at Object.onInvoke (core.mjs:25826:1)
    at ZoneDelegate.invoke (zone.js:399:1)
    at Zone.run (zone.js:160:1)
    at zone.js:1318:1
```

But I have created Triggers or `last_modified` column for each and every table. Please see this:

![tri](https://user-images.githubusercontent.com/5206526/171420844-dde4f11d-ee05-47fb-9ec9-86938b7a1f11.png)

I use ` "@capacitor-community/sqlite": "3.5.1-2",` with native Ionic/Angular app. Thanks!

P.S.

`exportToJson` is also not working due to the above error. Any clue, please?

```
exportToJson Error: ExportToJson: ExportToJson SetLastExportDate: SetLastExportDate: No sync_table available
    at Object.cap.fromNative (VM3:411:32)
    at <anonymous>:1:18
```

I call this `this.sqliteDbConnection.createSyncTable()` after all the above tables have been created. But why this then? i.e. not like this use case here: https://github.com/capacitor-community/sqlite/issues/253

**Comment by jepiqueau** [comment]
@Sampath-Lokuge you must have a sql_deleted column on each of your table as well. The output message must be amended

**Comment by Sampath-Lokuge** [comment]
Yes, we would like a more meaningful/complete message here. Maybe with a link to the readme file for that section.

**Comment by jepiqueau** [comment]
@Sampath-Lokuge i think this has been fixed so i close the issue. Feel free to re-open it if it is not the case
