### ISSUE TITLE
[question/suggestion] why require old passphrase in `changeEncryptionSecret`?

### ISSUE THREAD

**Issue by chriswep** [capacitor-community/sqlite#283]
I wonder why it is necessary to pass the old passphrase when changing the stored secret? As far as i can see the underlying keychain interface (at least on iOS) does not request it. I see the following problem: If by any means (bug, crash, user issue; doesn't matter) we end up in a situation where we don't know the old passphrase anymore, the situation is unrecoverable, even beyond app re-install (since the keychain is not affected/reset) - the app is basically nuked for life for this user. Maybe i don't understand it correctly, but setting/changing the passphrase is not about getting access to the data but passing the passphrase to the underlying implementation in a secure way. In other words, there seems to be no security implication when setting this value (apart from not being able to read the db if it's wrong). But maybe i'm missing something here? Does `changePassphrase` also affect re-encrypting the data in some way? If not, i suggest removing the `oldPassphrase` requirement since that would enable the app to recover from a corrupted/wrong/forgotten value in the store (by just overwriting it with the correct value).

This is not about how to prevent the corruption/loosing of the value but about making the implementation robust against unforeseen situations. There should at least be a way to recover the situation by resetting the value on the users device.

**Comment by jepiqueau** [comment]
@chriswep it is required for security anyone hacking your device cannot change the passphrase without knowing the old one

**Comment by chriswep** [comment]
@jepiqueau does this method actually re-encrypt the data? If not, I don't see the security implications. Access to the data will just fail after setting a new/wrong passphrase with this method or?

**Comment by chriswep** [comment]
doesn't that mean that the old passphrase is already required to access the data / open the database? is there an added security by also adding it to this method? i feel it just prevents a legitimate use case (like overwriting the passphrase of a previous app-install).

**Comment by jepiqueau** [comment]
@chriswep yes the old passphrase is required to open the database prior to rekey the new passphrase

**Comment by jepiqueau** [comment]
@chriswep Sorry i do not understand your reasoning.

**Comment by jepiqueau** [comment]
@chriswep i am currently on a privat3 project which require all my time and attention feel free to make a PR resolving your case both in iOS and Android i will merge it

**Comment by chriswep** [comment]
@jepiqueau i created this PR: https://github.com/capacitor-community/sqlite/pull/289

after looking at the code i decided to resolve the issue by creating the method `clearEncryptionSecret`. That way the current API and behaviour is not changed and there should be no security concerns (since using the method can only remove access to data for an attacker). this resolves the issue by providing a way to reset a previously stored secret. 

a few thoughts about the handling of the database secret after working through the code:
- the methods `setEncryptionSecret` and `changeEncryptionSecret` both can have the side effect of re-encrypting all databases in the app package. i would suggest to separate this behaviour into different methods, one for managing the keychain and one for changing the database(s) (e.g. `reencryptDatabase(dbName, oldKey, newKey)`). Currently it is not clear from the method name or documentation what is happening.
- i suggest to scope the stored secrets to the database name so that different databases can have different passphrases. e.g. in the case of pre-encrypted databases this plugin can't be used (if there is more than one with different passphrases).
- In addition to the above i suggest to give the developer the option to manage the secrets themselves and just pass it when opening a database. that is what i actually initially expected of how it would work and for me it would be easier to understand and work with.
