### ISSUE TITLE
Help: Related to the latest Delete workflow

### ISSUE THREAD

**Issue by Sampath-Lokuge** [capacitor-community/sqlite#284]
Hi,

> On successful completion of your synchronization management process with the remote server database, you must

> Set a new synchronization date (as (new Date()).toISOString()) with the setSyncDate method.
Execute the deleteExportedRows method which physically deletes all table's rows having 1 as value for the sql_deleted column prior to the last_exported_date in your local database.

I have seen this related to the Delete workflow. But do we need to manually set the `setSyncDate`? We have not done that with the older version of this plugin hence it does by the Trigger. i.e. `last_modified`

> Execute the deleteExportedRows method which physically deletes all table's rows having 1 as value for the sql_deleted column prior to the last_exported_date in your local database.

I didn't get this. Can I have more details here?

I can see that you have removed `=` from the trigger. Is that an intended one or a typo issue?

```
CREATE TRIGGER YOUR_TABLE_NAME_trigger_last_modified
  AFTER UPDATE ON YOUR_TABLE_NAME
  FOR EACH ROW WHEN NEW.last_modified < OLD.last_modified
  BEGIN
      UPDATE YOUR_TABLE_NAME SET last_modified= (strftime('%s', 'now')) WHERE id=OLD.id;
  END;
```

Can we have an `Ionic/Angular` sample app for the Delete workflow use cases? i.e. I'm not a `SolidJS` dev and I hope most of this plugin users are also Ionic/Angular devs. Thanks!

**P.S.** It seems you have done it no? https://github.com/jepiqueau/angular-sqlite-synchronize-app Please put that link also on the doc.

**Comment by jepiqueau** [comment]
@Sampath-Lokuge no it is not a typo read the readme.md. there is an app shoping this https://github.com/jepiqueau/angular-sqlite-synchronization-app. It is working fine on iOS,
 Android and electron there is an issue with the web

**Comment by Sampath-Lokuge** [comment]
Do we need to manually set the `setSyncDate`? We have not done that with the older version of this plugin hence it does by the Trigger. i.e. `last_modified`

**Comment by jepiqueau** [comment]
@Sampath-Lokuge yes it is required as it check the last_modified against the stored sync_date which need to be updated after successful export to the remote server
