### ISSUE TITLE
How to connect to existing DB

### ISSUE THREAD

**Issue by rnmaaa** [capacitor-community/sqlite#295]
Hi,
i am using this plugin in my app. But i do not understand how to connect to my existing database to display information on the page.
I have my file test_db.db (sqlite database) in public/assets/databases. But the code creates connection to a new empty DB and not to the existing one. And i get the error that the table was not found in the database. What do i do wrong?
And another question is that when i console.log getDatabaseList() (just to check), i see 3 different databases including myDBSQLiteSQLite.db - where it comes from? And none of those is the DB that i have.
This is my code (it is ionic vue app):

  window.addEventListener('DOMContentLoaded', async () => {
    const sqlite = new SQLiteConnection(CapacitorSQLite);

    try {
      const ret = await sqlite.checkConnectionsConsistency();
      const isConn = (await sqlite.isConnection("test_db")).result;

      let db;   

      if (ret.result && isConn) {
        db = await sqlite.retrieveConnection("test_db");
      } else {
        db = await sqlite.createConnection("test_db");
      }
 
    let dblist = await sqlite.getDatabaseList();
    console.log(dblist)

      await db.open();  
      let res = await db.query("SELECT * FROM test_table");    
      sqlite.closeConnection("test_db");
 
    } catch (err) {
      console.log(`Error: ${err}`);
      throw new Error(`Error: ${err}`)
    }
  });

Thanks

**Comment by jepiqueau** [comment]
@rnmaaa you have to copy thedatabase from the asset folder to the internal database folder before to use it there is an example in https://github.com/jepiqueau/angular-sqlite-app-starter

**Comment by hhimanshu** [comment]
> @rnmaaa you have to copy thedatabase from the asset folder to the internal database folder before to use it there is an example in https://github.com/jepiqueau/angular-sqlite-app-starter

@jepiqueau , could you please share how to do that? I am using CapacitoryJS with ReactJS
1. When do I need to copy the `.db` file? before or after running `npx cap sync`?
2. Do I need to name my existing Db file using the naming convention? `SQLite` suffix and `.db` extension?

Is there a command I can use to copy to both Android and iOS? 

I looked in your repo you shared. I saw there was no `data` directory under `android`. Have I missed something?

**Comment by jepiqueau** [comment]
@hhimanshu In the index.ts or index.js file of your app do
```
import { CapacitorSQLite, SQLiteConnection, SQLiteDBConnection } from '@capacitor-community/sqlite';

const sqlite: SQLiteConnection = new SQLiteConnection(CapacitorSQLite);
await sqlite.copyFromAssets(false);
```
the false means do not overwrite. meaning that the first time all the db files or db's in zip files will be copied from the src/assets/databases folder to the right folder depending on your capacitor.config file and the Sqlite suffix will be added.

In Android the databases are stored in `data/data/YOUR_PACKAGE/databases` folder. you do not have the choice to modify this location.
look at  [copyfromassets](https://github.com/jepiqueau/angular-sqlite-app-starter/blob/master/src/app/test/copyfromassets/copyfromassets.page.ts) as an example.
hope this clarify

**Comment by hhimanshu** [comment]
This is useful @jepiqueau , thanks for the help. I will try out
