### ISSUE TITLE
Using read-only connection for querying data while a long running transaction is executed

### ISSUE THREAD

**Issue by SkoricIT** [capacitor-community/sqlite#296]
Thank you for your work on this.

We have a long-running SQL query that imports gigabytes of data and requires the use of the database connection with transaction enabled. Is there any way to read from the database while the queries are running so that the app stays usable?

**Comment by jepiqueau** [comment]
@SkoricIT when a  transaction is running the database is locked till the transaction is commited. Try do do a full export the first tume you open the app and then partial import to import only what has been modified. This will réduction the import time

**Comment by SkoricIT** [comment]
@jepiqueau We have to import many gigabytes the first time the app is opened and it takes hours. Meanwhile the app is unusable. SQLite does allow reading while a write is happening. Will this never be supported?

**Comment by jepiqueau** [comment]
@SkoricIT Importing many gigabytes of data will always be long. As the importFromJson is done in one connection and one transaction, no data will be available to query before the transaction is completed and the connection closed. I thing you should organized your app differently. 
- Create the schemas of the database when the application starts with or without a small number of data common to all the pages of your app as "full" mode.
- Import when a page starts the data required for this page in "partial" mode. This will avoid the user to have to wait too much.
Hope this will help.

**Comment by SkoricIT** [comment]
We do create the tables and we use thousands of 1MB sized sql files for the import. Queries still stall out and pages that require SQL stall for multiple seconds. The issue is not that the import takes a long time. Its that already available data is not queryable because the database connection is busy.

**Comment by jepiqueau** [comment]
@SkoricIT Ok, the code as of now does not allow multiple connections to the same database. It will be quite a job to do this. Cannot you split your database in several smaller databases?

**Comment by jepiqueau** [comment]
@SkoricIT Which platform and which framework are you using?  If this process happen only once why do not you create the database in the asset folder of your app and when the app is open the first time copy the database from the asset folder to the local sqlite folder. see https://github.com/jepiqueau/angular-sqlite-app-starter

**Comment by jepiqueau** [comment]
@SkoricIT and from there you can import "partial" when there is some modification in the remote database server

**Comment by SkoricIT** [comment]
@jepiqueau We are using ionic6 wit angular.

**Comment by jepiqueau** [comment]
@SkoricIT Understand your problem, well  unfortunately, i do not have more idea for the time being and i do not have enough free time in front of me to start going through all the code to implement multiple connections(one write,  multiple read) to the same database. In top of this i am in a middle of solving issue#285 which is also not an easy task. May be you could look yourself and make a PR

**Comment by SkoricIT** [comment]
@jepiqueau I fully understand. I can try to get a budget to support your work on one of the possible extensions that solve our problem if you are interested in something like that?

**Comment by jepiqueau** [comment]
@SkoricIT I do this on my free time as an open source developer. I am a retired guy, i had plenty of time free when i started this development but now i have less time as i am fully refurbishing an old house to leave in when completed. No one asks for this before, it would have been easier to implement at the beginning when i create the DBConnection. I will put it in the list of TODOS but do not expect it soon.

**Comment by jepiqueau** [comment]
@SkoricIT Well you can try this. Would you start by iOS or Android ? Do it for one and when done if you want to share it, i will do it for the other and Electron.

**Comment by SkoricIT** [comment]
@jepiqueau That sounds great, will come back to you on that when one platform is implemented!

**Comment by jepiqueau** [comment]
@SkoricIT 👍

**Comment by jepiqueau** [comment]
@SkoricIT may be you should look at the new functionality
- create a database to the cache by using an http fetch
- move the database from cache to database folder by using moveDatabasesAndAddSuffix("cache")

have a look to `downloadtocacheandmove` test at [angular-sqlite-app-starter](https://github.com/jepiqueau/angular-sqlite-app-starter)
this should solve your problem tell me if not

**Comment by SkoricIT** [comment]
We are downloading SQL statements in files and running them. I think that this would only help me if I copy the existing database, then update, then copy it back? This is not feasible with a 20GB SQLite file.

**Comment by jepiqueau** [comment]
@SkoricIT so i so not know what to do to help

**Comment by SkoricIT** [comment]
We can close this issue and i will open a pull request if we can get approval to implement the required changes! Thank you for your time and effort!

**Comment by jepiqueau** [comment]
@SkoricIT 👍

**Comment by jepiqueau** [comment]
@SkoricIT i have added for iOS and Android in 4.1.0-7 a feature to open a connection in read-only mode. So now a database can simultaneously be opened in `read&write` mode and `readonly mode`
Question if i create a method reading from https a database which may be zipped and open a `read&write` connection to load it and have a readonly connection to read it while it is loaded by using the WAL2 PRAGMA. Would this will help you? It is quite a work so before to start this i would like to give your comments

**Comment by SkoricIT** [comment]
> i have added for iOS and Android in 4.1.0-7 a feature to open a connection in read-only mode. So now a database can simultaneously be opened in read&write mode and readonly mode

This already seems like it is solving our problems at hand completely, will have to try it out! Thanks a lot!

> Question if i create a method reading from https a database which may be zipped and open a read&write connection to load it and have a readonly connection to read it while it is loaded by using the WAL2 PRAGMA. Would this will help you? It is quite a work so before to start this i would like to give your comments

I don't really understand the questions about downloading and executing completed files, as our usecase does not use that kind of process at all.

This is how we build the local database in JS pseudo code:
```javascript
const sqlite_db = create_sqlite_file();
const updates = http_get_update_info(current_revision)
for (const u of updates) { // dozens or hundreds of updates
    const zip_file = download_zip_file(u.revision)
    unzip_file(zip_file, '/data/temp'); // many thousand of .sql files
    for (const sql_file of get_sql_files('/data/temp')) {
        await sqlite_db.exec(sql_file);
        delete_file(sql_file);
    }
}
```
This runs the biggest set of files for an empty application (revision 0 -> current_revision)  but it also runs new updates every day or so (e.g. weather data, traffic data, ... ).

Not sure where in the process we could use the download of sqlite files by applying the proposed feature. What do you think?

**Comment by SkoricIT** [comment]
@jepiqueau That kind of infrastructural change has been proposed to management, but there is no indication if or when a change like that might be approved.

**Comment by jepiqueau** [comment]
@SkoricIT the full implementation for readonly is now available in release 4.1.0

**Comment by SkoricIT** [comment]
@jepiqueau Thank you very much, greatly appreciated!

**Comment by SkoricIT** [comment]
@jepiqueau Did I understand it correctly, that we can now open one write connection and 1..n read-only connections at the same time ?

**Comment by jepiqueau** [comment]
@SkoricIT no you can open one connection readwrite and one connection readonly
