### ISSUE TITLE
createSyncTable/getSyncDate with TypeORM

### ISSUE THREAD

**Issue by harikvpy** [capacitor-community/sqlite#297]
When *SyncTable() functions are used after TypeORM is initialized via TypeORM.createConnection() API, further TypeORM query methods fail with the message that the table doesn't exist.

Is there any restriction to using the *SyncTable() functions when TypeORM is used as the primary means of data manipulation? Or any special flags to configure to get these two to work together?

What am I doing wrong?

- Ionic 5.x App but running on Desktop
- capacitor-community/sqlite v3.5.1
- TypeORM v0.2.44 (I know it's a little dated, but everything works without the *SyncTable() methods)

**Comment by harikvpy** [comment]
I think I figured out the cause of this issue. I was closing the SQLiteDBConnection object after retrieving the syncDate and afterwards TypeORM calls fail. It seems TypeORM expects the initial connection to the DB to be open throughout the course of the program.

**Comment by jepiqueau** [comment]
@harikvpy i have not really an idea about this. I never test it , i am not really a typeOrm user. May be you could share your app ans i may have a look

**Comment by jepiqueau** [comment]
@harikvpy OK fine
