### ISSUE TITLE
Remove rows with sql_deleted = 1

### ISSUE THREAD

**Issue by MonicaExplan** [capacitor-community/sqlite#298]
Hi

perodically I would like to purge my Db, how can I Remove rows with sql_deleted = 1?

I have found deleteExportedRows(...) Remove rows with sql_deleted = 1 after an export, BUT I don't make export.
Can I use deleteExportedRows even if I have no export in my App?

Thanks a lot
Monica

**Comment by jepiqueau** [comment]
@MonicaExplan any news ? Or i will close the issue

**Comment by MonicaExplan** [comment]
@jepiqueau Hi

to tell the truth I was waiting for an answer because in the documentaizone I do not find the answer I need
Thank you

**Comment by jepiqueau** [comment]
@MonicaExplan you do not need to use sql_deleted and last_modified columns in your ta les if you do not synchronize your database with a remote server database. In that case the records will be deleted for any DELETE commands.npw you can use deleteExportRows to remove all the rows having a sql_deleted equal to 1

**Comment by MonicaExplan** [comment]
Thanks
Monica
