### ISSUE TITLE
After adding the plugin Android compilation fails

### ISSUE THREAD

**Issue by HarelM** [capacitor-community/sqlite#301]
**Describe the bug**
There seems to be a duplicate file between this plugin and probably another one (not sure which) that when I add this plugin I get a compilation error message.
In order to solve this error I add the following lines to gradle.build file in the app folder:
```
packagingOptions {
        exclude 'build-data.properties'
}
```

**To Reproduce**
1. `npm install @capacitor-community/sqlite`
2. `npx cap sync`
3. try and build in android studio

**Expected behavior**
I should be able to add this plugin without any compilation errors

**Screenshots**
N/A

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Android
- Browser [e.g. chrome, safari] N/A
- Version [e.g. 22] Any?

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jepiqueau** [comment]
@HarelM Is that still true with the latest release 3.7.0 ?

**Comment by HarelM** [comment]
I'll check and let you know.

**Comment by HarelM** [comment]
Yes, this is still relevant.

**Comment by jepiqueau** [comment]
@HarelM Can you try 4.0.1

**Comment by HarelM** [comment]
I'll try and let you know. Thanks for taking the time to look into this!

**Comment by HarelM** [comment]
@jepiqueau the issue still exists in 4.0.1.
You can try and use my project for testing if you would like:
https://github.com/IsraelHikingMap/Site/blob/da90897a8b2813e1851d623007f72036fae0e4fa/IsraelHiking.Web/package.json
basically run `npm i`, `npm run build:mobile`, `npx cap sync` and build in android studio.

**Comment by jepiqueau** [comment]
@HarelM i will try when i am back home

**Comment by jepiqueau** [comment]
@HarelM it seems that it may come from androidx.security:security-crypto where i use an alpha version but there is nothing i can do about.

**Comment by HarelM** [comment]
Ok, thanks for letting me know!
I have a work around that maybe worth mentioning in the docs then...?

**Comment by jepiqueau** [comment]
@HarelM can you make a PR for the doc?

**Comment by HarelM** [comment]
See #312

**Comment by jepiqueau** [comment]
@HarelM i now close this issue, i will wait for a stable release of `androidx.security:security-crypto` from the android team. The reason why i use the alpha was that someone was asking for keeping the minimum API to 21 which the stable release 1.0.0 was not doing. Now that capacitor 4 does not support API 21 this is a bit stupid but it is difficult to step back.
