### ISSUE TITLE
Compatibility with Capacitor v4

### ISSUE THREAD

**Issue by jeremyburton** [capacitor-community/sqlite#305]
Is there a plan to create a version of this plugin that is compatible with Capacitor v4? If so, is there any projected timeline for this?

**Comment by jepiqueau** [comment]
@jeremyburton thanks for asking there are few PRs to look at and merge prior to update to Capacitor 4. If you have time to do it and test it feel free to make a PR for this. For the time being i have no free time fforsoftware development and i do not know what are the main changes in Capacitor 4.

**Comment by jepiqueau** [comment]
@jeremyburton Thanks to the contribution of @rdlabo, there is a preliminary release 4.0.0-1 accessible with `npm install @capacitor-community/sqlite@next

**Comment by StevieWag** [comment]
@jeremyburton have you tested @capacitor-community/sqlite@next in your project and is it working as expected? we are also thinking about updating it

**Comment by jepiqueau** [comment]
@jeremyburton i did not test it yet, i hope some developers can do it and revert. It is generally not the way i work but i am busy on a private project and had no time to work on. Ones make a PR i approved it. Considering the doc of Capacitor 4 there are no big changes and i assume if you follow this doc for making recommended changes in your app it should work if not please revert to me i will have to dedicate some time on this.

**Comment by jeremyburton** [comment]
> @jeremyburton have you tested @capacitor-community/sqlite@next in your project and is it working as expected? we are also thinking about updating it

@StevieWag yes, and it is working as expected in my project.

**Comment by jepiqueau** [comment]
@StevieWag thank you for your feedback
