### ISSUE TITLE
sql-wasm.wasm not found on Angular PWA when hosting not on server root path

### ISSUE THREAD

**Issue by hschindler** [capacitor-community/sqlite#309]
My Anguar PWA ist hosted on https://server/sub-dir.

I had copied the file sql-wasm.wasm to assets. The PWA-App on Web Browser looking for it at url https://server/assets and not at the expected url https://server/sub-dir/assets.

How can I config this?

**Comment by jepiqueau** [comment]
@hschindler i assume that you have an index.html at `https://server` which is the root for your PWA-App and this is the reason why the the plugin is looking at  https://server/assets . There is no way to day to configure this. In case you have several PWA-Apps in your https://server you will have only one copy of the wasm file and not one per app so for me nothing wrong.

**Comment by hschindler** [comment]
Thanks for the fast response.
My PWA ist hosted on an IIS. All PWAs are on their own path and are own applications. There is no index.html on the root of the IIS.

**Comment by hschindler** [comment]
For now, I have solved it with a "rewrite rule" in IIS. A solution that makes it possible without a "rewrite rule" would be desirable.

**Comment by jepiqueau** [comment]
@hschindler This has been fixed in jeep-sqlite@1.5.7

**Comment by jepiqueau** [comment]
@hschindler in your app do
```
npm uninstall --save @capacitor-community/sqlite
npm install --save @capacitor-community/sqlite
npx cap sync
``` 
check the package.json file of the node_modules/jeep-sqlite it should be 1.5.7 
modify the jeep-sqlite call in the html file or in the .ts file by adding the property wasmPath
    ```
    <jeep-sqlite autoSave="true" wasmPath="/subdir/assets"></jeep-sqlite>
    ```
it should now work

**Comment by jepiqueau** [comment]
@hschindler Did you test it?

**Comment by EMTmcruz** [comment]
@jepiqueau. I tried and db open was successful but have "Error: queryAll: no such table" on my query. Localhost working with the same query and table name but my hosting no working

**Comment by jepiqueau** [comment]
@EMTmcruz i assume you work with @hschindler     the database does not work directly from the assets use copyFromAssets method and the open a connection to the database and do the query. You should look at the doc and app staters

**Comment by hschindler** [comment]
@jepiqueau with jeep-sqlite version 1.5.7 and the **wasmPath** attribute it works. Thanks for help.

**Comment by jepiqueau** [comment]
@hschindler you are welcome
