### ISSUE TITLE
 SQL Syntax error on Web platform

### ISSUE THREAD

**Issue by hschindler** [capacitor-community/sqlite#310]
**Describe the bug**
I get SQL syntax error on web platform with my create database schema. On Android it works.

error messsage: "Execute: ExecuteSQL: ExecuteSQL: Execute: near "DROP ": syntax error"

When I remove all DROPS then the error mesages says near "CREATE": syntax error"

Here a sample of my SQL command: 

`DROP TABLE IF EXISTS [SystemFlag];
CREATE TABLE IF NOT EXISTS [SystemFlag] ( 
        [Key] NVARCHAR(50) UNIQUE NOT NULL PRIMARY KEY, 
        [Value] NVARCHAR(255) NULL 
        );`

**To Reproduce**
-

**Expected behavior**
-

**Screenshots**
-

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser chrome

**Comment by jepiqueau** [comment]
@hschindler 
try
```
DROP TABLE IF EXISTS SystemFlag;
CREATE TABLE IF NOT EXISTS SystemFlag]( Key NVARCHAR(50) UNIQUE NOT NULL PRIMARY KEY, Value NVARCHAR(255) NULL );
```

**Comment by jepiqueau** [comment]
@hschindler 
i mean
```
CREATE TABLE IF NOT EXISTS SystemFlag ( Key NVARCHAR(50) UNIQUE NOT NULL PRIMARY KEY, Value NVARCHAR(255) NULL );
```

**Comment by hschindler** [comment]
I found a missing semicolon in my original 'create schema' that I didn't notice on Friday. It now works.
So sorry for wasting time.
