### ISSUE TITLE
Error: SetEncryptionSecret: keychain prefix must not be empty

### ISSUE THREAD

**Issue by zVynx** [capacitor-community/sqlite#311]
**Describe the bug**
When trying to set an EncryptionSecret, I get the error described above, this error I got so far only on IOS and there on the iPhone 12 Pro (IOS 15.5) and on the iPhone 13 Pro (IOS 15.5).

**To Reproduce**

1. Go to 'https://github.com/zVynx/capSqliteKeyChainBug'
2. Download/Clone the Source Code
3. go into the downloaded Folder
4. Run npm install
5. Run ionic build && ionic cap copy && ionic cap sync
6. Run ionic cap open ios
7. Run the App in an Emulator iPhone 12 Pro or iPhone 13 Pro with IOS 15.5
8. Open the the Console of the Emulator with Safari devtools

**Expected behavior**
EncryptionSecret should be set.

**Screenshots**
<img width="897" alt="Bildschirmfoto 2022-08-25 um 18 41 59" src="https://user-images.githubusercontent.com/54234147/186722515-195c825f-d3d3-4075-850a-400cbd91554f.png">

**Desktop (please complete the following information):**

- OS: [iOS]
- Browser -
- Version 15.5

**Smartphone (please complete the following information):**

- Device: iPhone 12 Pro, iPhone 13 pro (maybe more)
- OS: iOS 15.5
- Browser -
- Version -

**Comment by jepiqueau** [comment]
@zVynx Remove the `capacitor.config.json` file  and create a `capacitor.config.ts` file  containing:
```
import { CapacitorConfig } from '@capacitor/cli';

const config: CapacitorConfig = {
  appId: 'io.ionic.starter',
  appName: 'SqliteBug',
  webDir: 'www',
  bundledWebRuntime: false,
//  hideLogs: true,
  plugins: {
    CapacitorSQLite: {
      iosDatabaseLocation: 'Library/CapacitorDatabase',
      iosIsEncryption: true,
      iosKeychainPrefix: 'SqliteBug',
      iosBiometric: {
        biometricAuth: false,
        biometricTitle : "Biometric login for capacitor sqlite"
      },
      androidIsEncryption: true,
      androidBiometric: {
        biometricAuth : false,
        biometricTitle : "Biometric login for capacitor sqlite",
        biometricSubTitle : "Log in using your biometric"
      },
    }
  }
};

export default config;

```
this should work

**Comment by zVynx** [comment]
works now, thank you!
