### ISSUE TITLE
Create database from methon instead json

### ISSUE THREAD

**Issue by R1NEJ0** [capacitor-community/sqlite#314]
Hi everyone, 

I'm triying to use the dependencies but I'm not able to create a database with a method instead JSON file...

Could someone help me?

I'd like use something like :

sQLite.create({
      name: "myDatabase.db",
      location: "default",
      version: 1
    })

Thanks in advance.

**Comment by jepiqueau** [comment]
@R1NEJ0 Look at the documentation and at the application starters under `https://github.com/jepiqueau` . You will find your way. Thanks anyhow to use the plugin

**Comment by R1NEJ0** [comment]
I’m having a look in al test of your starter repositorie, I think I know how to do it.

thanks.

**Comment by jepiqueau** [comment]
@R1NEJ0 i assume you find your way so i close the issue

**Comment by R1NEJ0** [comment]
finally I'm moving the project to RN, with ionic I have bad perfomance.

Thanks!

**Comment by jepiqueau** [comment]
@R1NEJ0 what is RN for my knowledge

**Comment by jepiqueau** [comment]
@R1NEJ0 thanks for this, We have added a new functionality to transfer a database file from a remote server to the cache through a fetch request and when done and the to move the databases from cache  to the database folder. this process does not use the connection till its ended. May be those could have help you?

**Comment by R1NEJ0** [comment]
My problem is that first I have to catch data from a .txt and parse that data and insert into database.

I'm going to try perfomance with react native first. 

I will have ionic and these dependencies in mind.
