### ISSUE TITLE
Support for zip files with moveDatabaseAndAddSuffix()

### ISSUE THREAD

**Issue by LynearIngression** [capacitor-community/sqlite#316]
I'd like to download a database from the web into the Cache folder in zipped format, then move it and open it with sqlite.  It works as expected when the file is not compressed.

This appears to work, but once the database is opened, it has no tables.
await this.sqlite.moveDatabasesAndAddSuffix("cache",['custom.db.zip'])
CapacitorSQLite getTableList
{"values":[]}

This works as expected.
await this.sqlite.moveDatabasesAndAddSuffix("cache",['custom.db'])

It would be nice if zip files were supported, the way they are with copyFromAssets().  "custom.db.zip" opens as expected when using copyFromAssets().

I was able to download zipped files and unzip them with jsZip, and that works with smaller files, but crashes with big ones.

**Comment by jepiqueau** [comment]
@LynearIngression available in 4.2.0

**Comment by LynearIngression** [comment]
Hi, thank you for the update.

I am updating to Capacitor 4 and my project is broken right now while I update everything.

I will test it as soon as it is working again.
