### ISSUE TITLE
feat(): ionic storage module

### ISSUE THREAD

**Issue by mburger81** [capacitor-community/sqlite#318]
Is there a way to get work your capacitor sqlite plugin with `IonicStorage` Module, like we use with the cordova sqlite driver?

```
IonicStorageModule.forRoot({
      name: '_abc',
      storeName: 'ABC,
      driverOrder: [ CordovaSQLiteDriver._driver, Drivers.IndexedDB, Drivers.LocalStorage ]
    }),
```
we also used the old cordova sqlite with AKITA state management 
```
localForage.config({
  driver: [ CordovaSQLiteDriver._driver, localForage.INDEXEDDB, localForage.LOCALSTORAGE ],
  name: '_abc',
  version: 1.0,
  storeName: 'akita-storage',
});

```

is there a way to use it with your capacitor plugin? 

**If not could you implement this feature?**

**Comment by jepiqueau** [comment]
@mburger81 i already answer this in[capacitor-data-storage-sqlite](https://github.com/jepiqueau/capacitor-data-storage-sqlite/issues/54).
