### ISSUE TITLE
4.1.* broken on iOS - unexpected JSON returned

### ISSUE THREAD

**Issue by bkostjens** [capacitor-community/sqlite#319]
**Describe the bug**
When running query the returned JSON includes an unexpected ios_columns entry:

From the logs:
```TO JS {"values":[{"ios_columns":["total_count","objects"]},{"total_count":0,"objects":"[]"}]}```

**To Reproduce**
Do any query on iOS.

- Capacitor: 4
- sqlite plugin: 4.1.0-7
- Device: iPhone 14 Pro (simulator)
- OS: iOS 16

**Expected behavior**
A JSON of the results without the ios_columns entry:
```TO JS {"values":[{"total_count":0,"objects":"[]"}]}```

**Solution / Workaround?**
When commenting out line 899 to 902 from UtilsSQLCipher.swift the problem is gone and everything functions as normally.

```
  if columnNames.count <= columnCount {
      columnNames.append(String(cString: name))
      /* if columnNames.count == columnCount {
          columnData["ios_columns"] = columnNames
          result.append(columnData)
      } */
  }
```

**Comment by jepiqueau** [comment]
@bkostjens is that happen when your query returned zéro value

**Comment by bkostjens** [comment]
Yes, the queries are against a fresh and empty database.

**Comment by jepiqueau** [comment]
@bkostjens it is not an error this has been lengthly explained and solve in `Query returing multiple rows - Array` issue#195. i will test it with no returned values. Which framework are you using ? Are you calling the query through an `SQLiteDBConnection` or through the CapacitorSQLite plugin   ie
 ```
            this.sqlitePlugin = CapacitorSQLite;
            this.sqlite = new SQLiteConnection(this.sqlitePlugin);
```
this sqlite is an SQLiteConnection
this.sqlitePlugin is the Capacitor SQLite plugin

the remove of that `'ios_columns'` is done in the SQLiteDBConnection query method.
So for this you have to create a connection to your database by using the createConnection method which returns a SQLiteDBConnection

if you call directly the CapacitorSQLite query method  and then have no define any connection, you must remove yourself the first item in the returned array.
The normal way of using the plugin is by using the SQLite
Hope this clarify

**Comment by bkostjens** [comment]
Thanks for your explanation. Has this behavior changed since v 3.x of this plugin as nothing in our codebase related to db connection / querying has been changed. The problem started after upgrading to capacitor 4 / sqlite plugin v4.1.0.

We connect like this:

```
import { CapacitorSQLite, capSQLiteSet } from '@capacitor-community/sqlite';
const sqlite = CapacitorSQLite;

private async createConnection(): Promise<void> {
    const ret = await sqlite.checkConnectionsConsistency({ dbNames: [database] });

    if (!ret.result) {
      await sqlite.createConnection({ database: database });
    }
}
```

And query is executed like:

```
public async query(statement: string, values: queryValue[]): Promise<any> {
    try {
      const result = await sqlite.query({ database: database, statement: statement, values: values });
      return Promise.resolve(result.values);
    } catch (error) {
      console.error('db.ts - query - error: ' + error);
      return Promise.reject(error);
    }
 }
```

**Comment by bkostjens** [comment]
This behavior is only seen on iOS, not on Android. If I would discard the first result, then the app won't run correctly on Android anymore. On 3.x of the sqlite plugin it runs fine on both platforms with the provided code. Should I switch to using SQLiteDBConnection?

**Comment by jepiqueau** [comment]
@bkostjens you can test if the platform is android or ios and do it only for ios. For me it would be better if you can use the SQLiteDBConnection but i do not know what is the work behind this in modifying your app so it is up to you

**Comment by bkostjens** [comment]
Any pointer to docs regarding using SQLiteDBConnection?

**Comment by jepiqueau** [comment]
@bkostjens look at the Documentation in the docs folder and look at the app starters dépend ingénieur on the framework you use

**Comment by bkostjens** [comment]
Thanks. For now I went for platform detection. Might reconsider later down the line.
