### ISSUE TITLE
Join the capacitor community org?

### ISSUE THREAD

**Issue by mhartington** [capacitor-community/sqlite#32]
Hi there! My name is Mike and I'm from the Ionic team. We've recently started up the capacitor-community org on github to bring together capacitor plugin authors and provide a semi-official place to maintain plugins. 

I wanted to reach out and see if you'd be up for joining the org and having this sqlite plugin be part of that group.

https://github.com/capacitor-community

Let me know if you'd like to join and we can go from there! Cheers!

**Comment by jepiqueau** [comment]
@mhartington Hi Mike, i saw that the Ionic team launched recently the capacitor-community org on github and yes i will be pleased to have my plugins part of that group. I have 3 plugins which are possible candidates : capacitor-sqlite, capacitor-data-storage-sqlite and capacitor-video-player. Can you please explain me the process to follow to be part of that group. I was wondering if there is a technical review of the plugin made by someone of the Ionic team to make sure plugins conform to some of Ionic standards as i developed the plugins with my own understanding of the Ionic capacitor technology and may be i didn't grab everything from that technology. Waiting from your reaction as i found this initiative of great interest for the software community.

**Comment by mhartington** [comment]
@jepiqueau First step would be to join the capacitor slack 

https://getcapacitor.herokuapp.com

Once in there, ping me and we'll get you in a private contributors channel.
From there, we can get you added to the community org and discuss the plugins and transfer them over.

**Comment by mhartington** [comment]
I think we can close this now 😄
