### ISSUE TITLE
addUpgradeStatement doesn't create all versions when starting with an empty database

### ISSUE THREAD

**Issue by ChrisSmeets** [capacitor-community/sqlite#320]
**Describe the bug**
Using the new addUpgradeStatement(database, toVersion, statements) in version 4.1.0-6 doesn't create all versions when starting
with an empty database. It only executes the last added. 

**To Reproduce**
starting with an empty database and define multiple versions with their statements

``export const SqliteStatements1 = [
        `CREATE TABLE IF NOT EXISTS ledger (
            id INTEGER PRIMARY KEY NOT NULL,
            firstname TEXT
        );`
];``

``export const SqliteStatements2 = [
        `CREATE TABLE IF NOT EXISTS key_value (key TEXT PRIMARY KEY, value TEXT);`
];``

`this.sqlite.addUpgradeStatement('test', 1, SqliteStatements1);`
`this.sqlite.addUpgradeStatement('test', 2, SqliteStatements2);`

` this.sqlite.createConnection('test', false, 'no-encryption', 2);`

**Expected behavior**
All versions with their statements up to the version should be executed/created when starting with an empty database

**Smartphone (please complete the following information):**

Samsung S20 
Android 11

**Additional context**
In CapacitorSQLitePlugin.java:

`Dictionary<Integer, JSONObject> upgDict = implementation.addUpgradeStatement(upgrade);
 versionUpgrades.put(dbName, upgDict);`

does not merge the version statements, but overwrites for the same dbName
The latter is executed/created.

I have not tested in iOS, I cannot tell if there is the same problem ?

**Comment by jepiqueau** [comment]
@ChrisSmeets if you look at the example you will see that after creating the addUpgradeStatement for a version you must do a createConnection for that version, close the connectiob and later you define the second one and do again a createConnection with the next version and so on.
This is the way to do it hope this helpful

**Comment by ChrisSmeets** [comment]
That's odd. When I read the documentation it is explained:

The following scenarios may occur:

Opens a Version 0 database (empty database). Will execute version1Statements and version2Statements upgrade statements.
Opens a Version 1 database. Will execute version2Statements upgrade statements.
Opens a Version 2 database. Will not execute any upgrade statements (already on version 2).

This is not happening right now. And starting new connections for this feels a little strange.

**Comment by jepiqueau** [comment]
@dragermrb can you please answer that one

**Comment by dragermrb** [comment]
What @ChrisSmeets  comments is correct, let me take a look...

**Comment by dragermrb** [comment]
I have created PR #323  to fix it

**Comment by dragermrb** [comment]
I have created the PR https://github.com/jepiqueau/jeep-sqlite/pull/15 to fix the problem in jeepSqlite too

**Comment by ChrisSmeets** [comment]
thanks for the fast fix! I will test it soon. It's a new project I'm working on and I have just one version of the database now.
But I was curious about the new feature and gave it a try. I think it's a great improvement!
