### ISSUE TITLE
Questions regarding migrating from 3.3.3 to 4.0.1

### ISSUE THREAD

**Issue by scr2em** [capacitor-community/sqlite#322]
Hi, I'm struggling migrating from 3.3.3 to 4.0.1 

I have an application with an encrypted database (v.3.3.3)
```js
   if(some logic to make sure it's only called once ){
      await  this.sqlite.setEncryptionSecret({ passphrase: "RANDOM" });
   }
   this.sqlite.createConnection(dbName, true, "secret", 1);

```
which is working fine and the db is encrypted successfully 

here are my steps to migrate to (4.0.1)

1- I added in `plugins` in `capacitor.config.json`
```
 "CapacitorSQLite": {
          "iosDatabaseLocation": "Library/CapacitorDatabase",   
            "iosIsEncryption": true,
            "iosKeychainPrefix": "MY_APP_NAME"
        }
        
```
        
  2- I'm calling `isSecretStored` in my code
  
  ```js
      const isStored =(await this.sqlite.isSecretStored())?.result;
      
     if(!isStored ){
      await  this.sqlite.setEncryptionSecret("RANDOM");
   }
   
   this.sqlite.createConnection(dbName, true, "secret", 1, false); // added the fifth parameter 
  ```
  
  Here is what I understand about what is happening with these settings 
  
 1- the old database will be moved from `Documents` to `Library/CapacitorDatabase` automatically (which is correct and tested) 
 2- `iosIsEncryption` is used when our old database is encrypted 
 3- `isSecretStored` is used to migrate the old keychain value to the new one with the prefix `MY_APP_NAME` 
 
 
 I get an error `openOrCreateDatabase: Cannot open DB`

I think it's because the old secret key didn't migrate to the new key with the prefix, any advice ?

**Comment by jepiqueau** [comment]
@scr2em have you replace MY_APP_NAME by the name of your app as defined in your package.json.  otherwise it is difficult to understand not having the code. May be should have been better to migrate to 3.7.0 and when everything is done and checked to migrate to 4.1.0

**Comment by scr2em** [comment]
@jepiqueau Thank you for your fast reply, `MY_APP_NAME` is the same as `appName` in `capacitor.config.json` which is very different than `name` in `package.json`. is it required that it `iosKeychainPrefix` should be the same as `name` in `package.json` ?

**Comment by jepiqueau** [comment]
@scr2em no but it should be unique so that why i though that the app name what the right thing to take

**Comment by scr2em** [comment]
@jepiqueau 
ok so about these 
1- the old database will be moved from Documents to Library/CapacitorDatabase automatically (which is correct and tested)
2- iosIsEncryption is used when our old database is encrypted
3- isSecretStored is used to migrate the old keychain value to the new one with the prefix MY_APP_NAME

do I understand them correctly? 

also how can I test that the keychain value has been migrated to the new one with the prefix ?

**Comment by jepiqueau** [comment]
@scr2em  You understand correctly. there is no way to test the keychain value except in debugging your app by simulating a changeSecureSecret an put a breakpoint in line 28 of the class utilsSecret if it is going to line 29 means that the prefix is in and after this you stop the app.

**Comment by jepiqueau** [comment]
@scr2em any progress on this? can i close the issue

**Comment by scr2em** [comment]
@jepiqueau I'm still stuck on it. but sure you can close it 
also can you open Discussion on this repo ? 
https://docs.github.com/en/discussions/quickstart

**Comment by jepiqueau** [comment]
@scr2em i did open the Discussion on this repo as you suggested. i am not happy of closing the issue if you are still stuck on it. May be you could share your app?

**Comment by scr2em** [comment]
@jepiqueau I'm still debugging till I reach the root cause of this issue. if I need something I'll start a discussion.
also when I get some free time I'll help improving the current docs. 
Thanks

**Comment by jepiqueau** [comment]
@scr2em OK thanks keep me aware if you find something which can be useful for others.
