### ISSUE TITLE
Electron window not opening after installing dependency 

### ISSUE THREAD

**Issue by beligatclement** [capacitor-community/sqlite#327]
Electron window not opening on `npx cap open @capacitor-community/electron` after installing dependency `@capacitor-community/sqlite`. Linked issue on `@capacitor-community/electron` repo : [#212](https://github.com/capacitor-community/electron/issues/212).

**Steps to reproduce the behavior**:
Have a working `@capacitor-community/electron` project.

```
npm i @capacitor-community/sqlite
ng build
npx cap sync
npx cap add @capacitor-community/electron
cd electron
npm install --save sqlite3
npm install --save jszip
npm install --save-dev @types/sqlite3
cd ..
npx cap open @capacitor-community/electron
```
![image](https://user-images.githubusercontent.com/19620479/193561061-21bf59c3-992a-49af-b797-7e3e601ccd52.png)

**Expected behavior**
Electron window open with `@capacitor-community/sqlite` dependency.

**Desktop :**
- OS: Ubuntu 
- Version: 22.04.1 LTS

**Additional context**
I have also implemented [this solution](https://github.com/capacitor-community/sqlite/blob/master/docs/Ionic-Angular-Usage.md) that works well on Android/iOS but I have the above descripted behavior on electron... 
(This documentation should be updated to have a `sql_deleted` culumn in all tables) 

Dependencies :
```
"@capacitor-community/electron": "^4.1.2",
"@capacitor-community/sqlite": "^4.1.1",
"@capacitor/android": "^4.3.0",
"@capacitor/angular": "^2.0.3",
"@capacitor/core": "^4.3.0",
"@capacitor/ios": "^4.3.0",
```
Dev dependencies :
```
"@capacitor/cli": "^4.3.0",
```

**Comment by beligatclement** [comment]
I resolve my issue by adding into `capacitor.config.ts` a plugins property for CapacitorSQLite.
```
plugins: {
    CapacitorSQLite: {
      ...CapacitorSQLite,
      electronLinuxLocation: "/tmp/CapacitorDatabases"
    }
  }
```

Full file :
```
import { CapacitorConfig } from '@capacitor/cli';
import { CapacitorElectronConfig, ElectronConfig } from '@capacitor-community/electron';
import { CapacitorSQLite } from "@capacitor-community/sqlite";

const config: CapacitorConfig = {
  appId: 'com.my.app',
  appName: 'my-app'',
  webDir: 'dist/my-app',
  bundledWebRuntime: false
};

const configElectron: ElectronConfig = {
}

const configGlobal: CapacitorElectronConfig = {
  ...config,
  electron: configElectron,
  plugins: {
    CapacitorSQLite: {
      ...CapacitorSQLite,
      electronLinuxLocation: "/tmp/CapacitorDatabases"
    }
  }
};

export default configGlobal;
``` 

Maybe it should be include in the documentation ?

**Comment by jepiqueau** [comment]
@beligatclement it is in the doc 
Info_releases.md
Docs/API.md
