### ISSUE TITLE
CapacitorSQLite does not respond to method call "executeSet" using selector "executeSet:"

### ISSUE THREAD

**Issue by Karyfars** [capacitor-community/sqlite#33]
When i try to execute the executeSet command on iOS i receive the following error message (all other commands are fine):
```
To Native ->  CapacitorSQLite executeSet 132074728
Error: Plugin CapacitorSQLite does not respond to method call "executeSet" using selector "executeSet:".
Ensure plugin method exists, uses @objc in its declaration, and arguments match selector without callbacks in CAP_PLUGIN_METHOD.
```

I used the example code to reproduce the error on iOS 13.1 in the Simulator.
I'm running CapacitorSQLite Version 2.2.1-3

Code:
```
import { Plugins } from "@capacitor/core";
const { CapacitorSQLite } = Plugins;

const set: Array<any>  = [
	{ 
		statement:"INSERT INTO users (name,FirstName,email,age,MobileNumber) VALUES (?,?,?,?,?);",
	  	values: [
			"Blackberry","Peter","Blackberry@example.com",69,"4405060708"
		],
	},
	{ 
		statement:"INSERT INTO users (name,FirstName,email,age,MobileNumber) VALUES (?,?,?,?,?);",
	  	values: [
			"Jones","Helen","HelenJones@example.com",42,"4404030201"
		],
	},
	{ 
		statement:"INSERT INTO users (name,FirstName,email,age,MobileNumber) VALUES (?,?,?,?,?);",
	  	values: [
			"Davison","Bill","Davison@example.com",45,"4405162732"
		],
	},
	{ 
		statement:"INSERT INTO users (name,FirstName,email,age,MobileNumber) VALUES (?,?,?,?,?);",
	  	values: [
			"Brown","John","Brown@example.com",35,"4405243853"
		],
	},
	{ 
		statement:"UPDATE users SET age = ? , MobileNumber = ? WHERE id = ?;",
	  	values: [
			51,"4404030237",2
		],
	}
];
CapacitorSQLite.executeSet({ set: set });
```

**Comment by jepiqueau** [comment]
@Karyfars First thanks for using the plugin. have you try to run the app
```
https://github.com/jepiqueau/angular-sqlite-app-starter
```
you can use the tag 2.2.1-3 of the app, the latest version is under test as we are moving the capacitor-sqlite plugin to the @capacitor-community where it will be named sqlite

on your simulator with IOS 13.1, i test it with IOS 13.6 and i do not have any problem. tell me if it runs

In your example, i assume that the database was open and the table users created in an other part of your code

**Comment by Karyfars** [comment]
@jepiqueau Thanks for your answer. I updated xcode to the newest version and it solved the issue.

**Comment by jepiqueau** [comment]
@Karyfars  ok, i am happy that you solve it as i could not reproduce it. Enjoy
