### ISSUE TITLE
Documentation issue with `addUpgradeStatement`, especially for React

### ISSUE THREAD

**Issue by crowbait** [capacitor-community/sqlite#336]
**Describe the bug**
#320 doesn't seem to be resolved for React (on Android at least).
> Using the new addUpgradeStatement(database, toVersion, statements) in version 4.1.0-6 doesn't create all versions when starting
with an empty database. It only executes the last added.

Using [react-sqlite-hook](https://github.com/jepiqueau/react-sqlite-hook), on an empty (non-existent) db, I'm calling

```JS
await sqlite.addUpgradeStatement("shufflechat", {toVersion: 1, statements: [createGeneralTables1]});
await sqlite.addUpgradeStatement("shufflechat", {toVersion: 2, statements: [createGeneralTables2]});
let db = await sqlite.createConnection("shufflechat", false, "no-encryption", 2);
await db.open();
```
where
```JS
const createGeneralTables1: string = `
  CREATE TABLE IF NOT EXISTS chats (
    chatid varchar(255)
    (...)
  CREATE TABLE IF NOT EXISTS knownusers (
    (...)
(...)
const createGeneralTables2: string = `ALTER TABLE knownusers ADD COLUMN muted INTEGER NOT NULL DEFAULT 0`;
```
Note: I've omitted a hundred lines of schemas for reading convenience. They do work however, when I used them with ```db.execute```, everything was fine.

**To Reproduce**
Using [react-sqlite-hook](https://github.com/jepiqueau/react-sqlite-hook), start with an empty db, then add multiple upgrade statements and try to open with the highest version number.

**Expected behavior**
Upgrade statements should be called on by one, as outlined in the documentation.

**Screenshots**
```Error creating DB connection:  Error: Open: Error in creating the databaseError: onUpgrade executeStatementProcess failed java.lang.Exception: Error: executeStatementsProcess  failed java.lang.Exception: no such table: knownusers: ALTER TABLE (...)```

**Smartphone (please complete the following information):**

- Device: [Pixel 3a XL, Pixel 6a]
- OS: Android 13
- Browser: Android WebView
- Version: latest

**Additional context**
The react usage guide doesn't mention upgrades at all. It would be nice to update the documentation regarding that. I had to piece the usage together from the non-react documentation, the plugin's source and error messages.

**Comment by crowbait** [comment]
I made the error myself. The first upgrade statement should not have been an array of length 1 with multiple commands, but an array with the commands:
```JS
await sqlite.addUpgradeStatement("shufflechat", {toVersion: 1, statements: createGeneralTables1});
```
where
```JS
createGeneralTables1 = [`CREATE TABLE stuff (...);`, `ADD INDEX (...);`];
```

However, the [docs](https://github.com/capacitor-community/sqlite/blob/master/docs/API.md#capsqliteupgradeoptions) specifically state an array of length 1, so this still is a documentation issue.

Please consider updating the documentations for `addUpgradeStatement`, both the regular docs as well as the react usage guide. I think the react usage guide should reflect even creating tables with `addUpgradeStatement` because it's easier to maintain than just simply creating your table, like the docs suggest now.

I'm just leaving this open so you fantastic guy notice it. You may close this issue any time, as my original problem is solved.

**Comment by jepiqueau** [comment]
@crowbait I look back, but i think you were mixing `capSQLiteUpgradeOptions` and `capSQLiteVersionUpgrade`  and also the `addUpgradeStatement` method of the CapacitorSQLitePlugin and the `addUpgradeStatement` method of the SQLiteConnection. The react hook is using the SQLiteConnection. so the documentation is correct. So look back at the doc and tell me what do you need more if it is unclear
