### ISSUE TITLE
Using plugin on existing remote sqlite file

### ISSUE THREAD

**Issue by beyondsanity** [capacitor-community/sqlite#34]
**Is your feature request related to a problem? Please describe.**
I'm trying to work on a remote db file coming from our backend but i'm not sure if the library allows to work with external sources.

**Describe the solution you'd like**
I'd like a documented procedure to import external files as dbs on my app.

**Describe alternatives you've considered**
I've considered using .sql set of queries to recreate the db dynamically but this solution is not good for performance.

**Additional context**
-

**Comment by jepiqueau** [comment]
@beyondsanity 
Thanks for using the plugin. What is available from the library to transfer from the backend database server is the method `importFromJson` which take a stringify JSON Object where the format is described in `https://github.com/capacitor-community/sqlite/blob/master/ImportExportJson.md` This JSON Object must be created on the server side for good performance. I can be a **full** or **partial** loading 
if you wish to synchronize back to the backend, the library provides the method `exportToJson` again in **full** or **partial** mode. Here again, your app should manage the transfer of the JSON object back to the server and loaded.
look at the API doc `https://github.com/capacitor-community/sqlite/blob/communitySetUp/docs/APIdocumentation.md`

**Comment by jepiqueau** [comment]
@beyondsanity 
Having not received anything new from your side, i will close the issue
