### ISSUE TITLE
isConnection, retrieveConnections and other functions not implemented on Android

### ISSUE THREAD

**Issue by montagnamarco** [capacitor-community/sqlite#341]
**Describe the bug**
I get "Not implemented on Android" on retrieveConnections and isConnection

**Expected behavior**
I expect to have a result, true or false

**Comment by jepiqueau** [comment]
@montagnamarco have you solved it? If yes, can you close the issue

**Comment by jepiqueau** [comment]
@montagnamarco No answer from you so i close the issue. feel free to re-open it if requires
