### ISSUE TITLE
On mobile devices - WebStore is not open yet

### ISSUE THREAD

**Issue by Etchelon** [capacitor-community/sqlite#343]
**Describe the bug**
When I use my web app on my iPhone, with Safari, Edge or Chrome (doesn't matter), every time I **reload** the page (like F5) I get "WebStore is not open yet. You have to call "initWebStore()" first.".
If I close the tab and reopen it, it works fine.
On a tablet and PC/MacOS browsers it doesn't happen.
Sometimes it happens on PC browsers when hot module reloading kicks in.

**Expected behavior**
I expect to be able to reload the page without initWebStore "silently failing".

**Screenshots**
This is the code I execute:

<img width="505" alt="image" src="https://user-images.githubusercontent.com/4141889/200017460-7b690224-0ed3-4b73-b752-0530925ad97c.png">

At line 16, when I call this.sqlite.createConnection, I get the exception.

**Smartphone (please complete the following information):**

- Device: iPhone 12
- OS: iOS15/16 alike
- Browser: Safari, Edge, Chrome alike

**Additional context**
If you have any ideas (maybe from my code it's apparent that I'm doing something wrong) let me know.
If you need more info or a dedicate repo for the repro I'll provide it.

**Comment by Etchelon** [comment]
I just found out that if I add
`await delay(100); // wait for 100ms`
before calling
`await this.sqlite.initWebStore();`
the issue goes away.

Saying this hoping it will help understanding whether there's an issue somewhere in the plugin (I doubt it) or in my code (much more likely), not because I will settle for this workaround, of course. Why 100? How can I know it's going to work on all devices?

**Comment by jepiqueau** [comment]
@Etchelon which framework are you using i was force to do the same (delay function) on a vue app

**Comment by Etchelon** [comment]
@jepiqueau React.
I'm not strictly following your examples, in that I'm initializing the proper subclass of DbConnection depending on whether the app is running on native or web.
So the WebDbConnection does what you see in the screenshot: lazily imports the JeepSqlite stuff, awaits initialization and then creates the connection.

Btw I've read in other issues mentions to using `checkConnectionConsistency` in Web as well., I thought it was just a thing for running on native? May that have to do with this?

For completeness, here's how I use this method in my `AppsDbConnection` class:

<img width="515" alt="image" src="https://user-images.githubusercontent.com/4141889/200052344-854c95cf-8a84-4d91-80b9-814b500b36f5.png">

**Comment by jepiqueau** [comment]
@Etchelon the web initialization must be in the main.ts file which is the only file which is to rerun when you move from page to page  or reload a page. Put a console.log in all setup of pages and app and also on the onMount methods you will see how react work. The checkConnectionConsistency is required for livereload of page.
Follow the example it is the only i found to have it working but i am not à React specialist.

**Comment by Etchelon** [comment]
Unless mobile browsers behave in a different a misterious way, when you click on "reload" the whole page should be reloaded.
It means that my app
- loads the main.tsx file
- main.tsx loads App.tsx
- App.tsx awaits initialization of all the services. One of these initializers awaits loading of the JeepSqlite plugin, custom element definition and creates the connection.

I don't see why all that needs to happen before React starts rendering. Afaik, a custom element definition is not related to React's rendering process and can happen at any time during the page's lifetime.

Also, I want to be able to lazily load the SQLite code if needed, instead of doing it upfront, to make the app lighter with code splitting. Loading the plugin before rendering the React root would mean we can't do that, and it doesn't seem right. We have dynamic import now which makes this possible.

Ultimately, I think I'll try fiddling with `checkConnectionConsistency` and see what happens, but I have the gut feeling there may be some work that isn't properly awaited (or I'm not properly awaiting) going on inside this piece of code (or the plugin), which is worked around by adding that 100ms delay (something you had to do yourself in a Vue app!)

<img width="279" alt="image" src="https://user-images.githubusercontent.com/4141889/200127131-cde52920-b60e-48df-9968-03148c21c306.png">

**Comment by jepiqueau** [comment]
@Etchelon do it the way you want and if you find a better solution which is working please share it. It may interest other React developers. As i told you i am not à React specialist

**Comment by Etchelon** [comment]
Since it's not clear what the problem is and there's a working workaround, I'm going to close the issue for now.
I'll try a few more things and get back to you.

Regarding sharing my solution, I've pretty much explained what I'm doing compared to the [React example](https://github.com/capacitor-community/sqlite/blob/master/docs/Web-Usage.md#ionicreact-app) in the docs. What can I do to give it more visibility (provided my approach isn't faulty)? Create another example app to link in this repo?
