### ISSUE TITLE
ImportFromJson sync change no persist 

### ISSUE THREAD

**Issue by pedro21900** [capacitor-community/sqlite#345]
Good afternoon, I have a possible problem regarding importFromJson, the data arrives showing that there are 382 changes that came from the server, but when I check on the device, only one record was imported from each table, the rest of the data is lost, what is the solution what should I do ?

**Comment by jepiqueau** [comment]
@pedro21900 which framework ? which version are you using ? As i am away from computer till end of the month look at https://github.com/jepiqueau/angular-sqlite-app-starter or others app in different frameworks they all working fine and then compare with your code. 
Is the json object sent is a valid Json Sqlite object?

**Comment by pedro21900** [comment]
I'm using angular, and I need help I'm in a bit of urgency.

I'm using the
"@capacitor-community/sqlite": "^4.2.2",

I'm using the Partial Mode Two Steps concept

The table creation happens, plus the data when it arrives, only one record persists.

I used isJsonValid and it returns true.

If you can help me, I'm really stuck lol

**Comment by jepiqueau** [comment]
@pedro21900 can you share the piece of code where you use the import (two steps concept) and the json object for the schema definition and the data definition . Have you clone the angular-sqlite-app-starter and run the import export test. Did it work?

**Comment by pedro21900** [comment]
But I can't use "AUTOINCREMENT" when I use a "constraint" ,any tips?

**Comment by jepiqueau** [comment]
@pedro21900 have you tried


{
                    "column": "id",
                    "value": "INTEGER NOT NULL AUTOINCREMENT UNIQUE"
 },

**Comment by jepiqueau** [comment]
@pedro21900 if everything is fixed on your side can you close the issue thanks

**Comment by jepiqueau** [comment]
@pedro21900  No answer so i close the issue. Feel free to re-open it if required
