### ISSUE TITLE
documentation mistake for Ionic-Angular-Usage.md

### ISSUE THREAD

**Issue by aeinn** [capacitor-community/sqlite#347]
error section: https://github.com/capacitor-community/sqlite/blob/master/docs/Ionic-Angular-Usage.md#singleton-service-injection

the above linked section (singleton-service-injection) may have been incorrectly replaced with the definition of (singleton-service-definition)

new user may need to refer to the earlier version of Ionic-Angular-Usage.md for usage guide:

- https://github.com/capacitor-community/sqlite/blob/5551600ea6b1c7f789c6024ea350e6a0424f90d9/docs/Ionic-Angular-Usage.md

**Comment by jepiqueau** [comment]
@aeinn yes you right cut and paste mistake. Can you make a PR to modify it and add yourself in the readme.md contributor list. I will merge it from my phone device. I am away from my computer till end of the month. Thanks for this
