### ISSUE TITLE
No database in Android via Play Store only

### ISSUE THREAD

**Issue by rwilliamsBBM** [capacitor-community/sqlite#352]
I've built an app for iOS and Android using Ionic 6 and Capacitor 4.

It all works great in iOS (it's already available at the Apple app store) and in Android debugging using the emulator and an actual device. I've even built a signed release copy of the .apk and installed it on a device and it works.

When I build a signed bundle and upload to Google Play, the database doesn't initialize, like it's just not there.

This is all doing a clean install. If I run the debug version on my device, then install the google play version over that version, it works.

I feel like I'm missing something basic here.

**Comment by rwilliamsBBM** [comment]
For more follow up... 
I just built a version of the app, build 26, and created a signed .aab (bundle) and then a signed .apk

I uploaded the bundle to Google Play and pulled the .apk from the release bundle and installed it.

As expected, no database.

Installed the signed .apk directly to the device, it all works a treat.

Same code, I guess same .apk's? But one comes via the Google Play store, one I just build and install.

**Comment by jepiqueau** [comment]
@rwilliamsBBM  i do not have a glue on what is going on. In which android folder the database is stored?

**Comment by rwilliamsBBM** [comment]
In the versions that work on Android, debug it's in data/data/com.verticalbridge.sl/databases.

I've added an alert message at the catch here:

  private async getDataBaseConnection() : Promise<SQLiteDBConnection | null>
  {
    try{
      let dbConnection: SQLiteDBConnection;
      const connection = (await this.sqlite.checkConnectionsConsistency()).result;
      const openConnection = (await this.sqlite.isConnection(DB_NAME_KEY, false)).result;
     //alert("Connection: " + connection + ", " + "OpenConnection: " + openConnection);
      if(openConnection && connection){
        dbConnection = await this.sqlite.retrieveConnection(DB_NAME_KEY, false);
        //await dbConnection.open();
      }
      else{
        //alert('Creating...')
        dbConnection = await this.sqlite.createConnection(DB_NAME_KEY, false, "no-encryption", 1, false);
        //await dbConnection.open();
      }
      return dbConnection;
    }
    catch(ex)
    {
      alert("In CreateConnection: " + ex);
      console.error("In CreateConnection: " + ex);
      return null;
    }
  }

And I get "Error: CapacitorSQLitePlugin: Protocol message contained an invalid tag (zero)"
________________________________

**Comment by jepiqueau** [comment]
@rwilliamsBBM  can you show me DB_NAME_KEY.
Is the database loaded the first time you issue the app. 
If it is the case you should put the initial database in tje assets folder and if it does not exist in your database folder.copy it from the assets to your database folder and start to work from there.

**Comment by jepiqueau** [comment]
@rwilliamsBBM can you share your capacitor-config.ts

**Comment by rwilliamsBBM** [comment]
const DB_NAME_KEY = 'sir_db';

capacitor.config.ts:
import { CapacitorConfig } from '@capacitor/cli';

const config: CapacitorConfig = {
	'appId': 'io.ionic.starter',
	'appName': 'VerticalBridge',
	'webDir': 'www',
  plugins: {},
  server: {
	cleartext: true
  }
};

export default config;

Database does not appear to be there after initial app install, I can't really tell in Android Studio's Device Explorer in the release version.

I have tried putting a copy of the db in "assets".

**Comment by rwilliamsBBM** [comment]
I found mention of the "Invalid Tag" message here:
https://github.com/capacitor-community/sqlite/issues/196

Tried the solution at the end of the thread, and it seems to work now. I have a release version in review at Google Play Store, we'll see.

"Today I found out that this is caused by the automatic backups of app data via android. I could (partially) solve the problem by disabling backups in AndroidManifest with: android:allowBackup="false" and then after I uninstalled and reinstalled the new version, the problem was gone! Maybe this helps someone too."

I'm still researching the implications of this Android setting but maybe related to this:
https://android-developers.googleblog.com/2022/03/freeing-up-60-of-storage-for-apps.html

**Comment by rwilliamsBBM** [comment]
alright... now that I've a minute to read and to think... I realize this app and its first release did not even have a SQLite db in it. 

We added it in a later release to support new functionality.

I believe its the update functions of the google play app isn't creating the new database because it doesn't know that it needs to from previous installs? 

Just throwing spaghetti at the wall at this point... but it seems to fit.

**Comment by rwilliamsBBM** [comment]
Been trying to sort out how to add the database in my situation.

I was hoping copyFromAssets() would be what I needed, but I'm seeing now that no matter what operation I try with the plugin in an update version of my app, it throws the "Error: CapacitorSQLitePlugin: Protocol message contained an invalid tag (zero)" error.

**Comment by rwilliamsBBM** [comment]
Issue appears to be with Google Play and how it handles updates. 

Workaround in thread.

**Comment by jepiqueau** [comment]
@rwilliamsBBM what you could try is getting the database exported to json in the previous release copy that file into the assets folder of the new app release and import that json object into a newly created database. It is a bit trick but should work.
An other idea whould be to look if the backup handles by Google Play concerns all the folders of the app i was thinking about the files folder may be it is not backup
