### ISSUE TITLE
Module Not Found

### ISSUE THREAD

**Issue by vycoder** [capacitor-community/sqlite#361]
**Describe the bug**
I'm working on Vue project, I was using orm with it. Just updated to 4.x.x, I'm suddenly getting the following error when building for development.

```
Module not found: Can't resolve imported dependency "react-native-sqlite-storage"
Did you forget to install it? You can run: yarn add react-native-sqlite-storage
```

It's being installed fine on the emulator without any problems though, for now I'm ignoring the warning message, not sure if this is something of concern.

**Comment by jepiqueau** [comment]
@vycoder react-native-sqlite-plugin is not needed. It is an error in typeOrm  which initialize it automatically

**Comment by vycoder** [comment]
Hi @jepiqueau, thanks for the quick response. 
Does this mean I can safely ignore this warning error?

**Comment by jepiqueau** [comment]
@vycoder i have tried to add a script like shown in [ionic-typeorm-starter](https://github.com/coturiv/ionic-typeorm-starter/tree/master/scripts) and run it as a postinstall script in package.json.
i had to adapt the script for the latest typeORM release like this
```
#!/bin/bash
# file: patch.sh

replace() {
    # Explicitly specify file ending on Mac OSX.
    # @see https://myshittycode.com/2014/07/24/os-x-sed-extra-characters-at-the-end-of-l-command-error/
    if [[ "$OSTYPE" == "darwin"* ]]; then
      sed -i "" "s/$1/$2/g" "$3"
    else
      sed -i "s/$1/$2/g" "$3"
    fi
}

# ==========================
# Remove typeorm warnings:
# ==========================
#
# WARNING in ./node_modules/typeorm/browser/driver/react-native/ReactNativeDriver.js
# Module not found: Error: Can't resolve 'react-native-sqlite-storage' in '.\node
# _modules\typeorm\browser\driver\react-native'

replace 'const sqlite = this.options.driver || require("react-native-sqlite-storage");' '' 'node_modules/typeorm/browser/driver/react-native/ReactNativeDriver.js'
replace 'this.sqlite = sqlite;' '' 'node_modules/typeorm/browser/driver/react-native/ReactNativeDriver.js'
replace 'throw new DriverPackageNotInstalledError("React-Native", "react-native-sqlite-storage");' '' 'node_modules/typeorm/browser/driver/react-native/ReactNativeDriver.js'

```
check that in `node_modules/typeorm/browser/driver/react-native/ReactNativeDriver.js` the lines where not existing but i still get the error. May be it is a cache issue on my Mac.
May be try this on yours.

Anyhow you should not care about this warning, even if i do not like it to see it in the build process, as we never use that driver with @capacitor-community/sqlite. This is why everything works fine.

**Comment by vycoder** [comment]
Okay, thanks for all the help! Closing this issue now. Thanks again!
