### ISSUE TITLE
bug: [Windows] Drop Database error resource busy

### ISSUE THREAD

**Issue by tobiasmuecksch** [capacitor-community/sqlite#366]
I'm afraid I have to repoen issue #326 since the error reappeared in `v4.6.0`.

I'm investigating right now.

**Describe the bug**
When I try to drop a database on windows, the following error occurs:

![193466646-5269d063-cf07-486f-b62d-dc5e08f5cab8](https://user-images.githubusercontent.com/1294854/193610723-85c67577-56fb-4d06-801f-a9abac1385ea.png)

**To Reproduce**

```typescript

  /**
   * Drops a database
   * 
   * @param databasename 
   * @returns 
   */
  async dropDatabase(databasename: string): Promise<void> {
    console.log('DROPPING DATABASE');
    await this.ready('deleteDatabase');

    const dbConnection = await this.openDB(databasename);

    await dbConnection.close();
    await waitForTime(1000);

    await dbConnection.delete();

    delete this.connections[databasename];
  }
```

For this code, I used the following link as a guide:
https://github.com/jepiqueau/db-delete/blob/ae4c5b1d465cbb08d8ef3046dcdc828650b5e69d/src/app/database.service.ts#L36

**Desktop:**

- OS: Windows 10

**Versions:**

- **@capacitor-community/sqlite**: 4.6.0.
- **sqlite3**: 5.1.1
- **electron**: 20.3.0

**Comment by tobiasmuecksch** [comment]
Alright; I found a solution. I will create a pull request with a fix soon.

**Comment by jepiqueau** [comment]
@tobiasmuecksch 👌

**Comment by tobiasmuecksch** [comment]
On windows, the file lock behaves unpredictable. Often it claims a databsae file is locked / busy, although the file stream is already closed.
(Even though we already checked the status with the `waitForFilePathLock()` method previously.)

The only way I found to handle this reliably is to retry deletion until it works.

**Comment by jepiqueau** [comment]
@tobiasmuecksch Have you test 4.6.1-2 i have merged your PR. if it is OK can you close the issue. Thanks for your help

**Comment by tobiasmuecksch** [comment]
Sorry for the late reply, yes I will test it today.

**Comment by tobiasmuecksch** [comment]
@jepiqueau Yes, I have tested `4.6.1-2` and it works perfectly fine.

**Comment by jepiqueau** [comment]
@tobiasmuecksch 👍
