### ISSUE TITLE
Checking Password from Web App

### ISSUE THREAD

**Issue by KevinTurnbull** [capacitor-community/sqlite#370]
**Is your feature request related to a problem? Please describe.**
I want to be able to check whether a user has entered the correct password when trying to access the database. 

**Describe the solution you'd like**
Adding a function to CapacitorSQLitePlugin.java (and it's iOS equivalent) called checkEncryptionSecret(password) which loads the EncryptedSharedPreferences value (and it's iOS equivalent) and compares it against the provided password. If there is a match; return true - otherwise return false.

**Describe alternatives you've considered**
Currently the only way to do this is to check for an exception when calling changeEncryptionSecret(...) with the same old password as new password. This bares the totally unnecessary overhead of decrypting and reencrypting the database.

**Comment by jepiqueau** [comment]
@KevinTurnbull hi, i think you can write a function in your app framework to do this where you do a try ... catch around changeEncryptionSecret() where the try return true and the catch false which is what you are asking for.

**Comment by KevinTurnbull** [comment]
Yeah, I had mentioned this in my feature request. The problem is that this introduces big overhead when the user enters the correct overhead. For example in the case where the database is large; it will be decrypted and encrypted with the new (same as before) password without throwing an error. Yes; this does allow me to check the password but at a potential very large performance cost.

**Comment by jepiqueau** [comment]
@KevinTurnbull OK i will have a look

**Comment by KevinTurnbull** [comment]
Thanks! It's overall really good; I just need to be able to present the user with a password challenge when they want to perform secured actions and it's convenient to use the database unlock password as a challenge password.

**Comment by jepiqueau** [comment]
@KevinTurnbull this has been fixed in 4.6.1 method checkEncryptionSecret enjoy it

**Comment by KevinTurnbull** [comment]
That's great news! You're super quick and responsive. I'm excited to add a new feature to my product because you got this closed so quickly!
