### ISSUE TITLE
Class not found androidx/security/crypto/MasterKey

### ISSUE THREAD

**Issue by rmehul93** [capacitor-community/sqlite#376]
FATAL EXCEPTION: main
Process: com.example.wavesdk, PID: 17111
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/security/crypto/MasterKey$Builder;
at com.getcapacitor.community.database.sqlite.CapacitorSQLite.<init>(CapacitorSQLite.java:122)
at com.getcapacitor.community.database.sqlite.CapacitorSQLitePlugin.load(CapacitorSQLitePlugin.java:45)

**Comment by jepiqueau** [comment]
@rmehul93 which version of the plugin are you using? Which android api are you using. Is that an old app that you migrate or a new app

**Comment by rmehul93** [comment]
Plugin version: 4.6.0 
Android version: 4.6.2

Its fresh app, not migrated.

**Comment by jepiqueau** [comment]
@rmehul93 why Landroidx/security/crypto... it should be androidx/security/crypto...

**Comment by rmehul93** [comment]
We are getting that error

**Comment by jepiqueau** [comment]
@rmehul93 can you share your project on github i could not find the reason for this

**Comment by jepiqueau** [comment]
@rmehul93 Can you share 
- your package.json 
- the gradle file of the app
- the gradle file of the @capacitor-community/sqlite

**Comment by jepiqueau** [comment]
@rmehul93 As i do not get more info from you i will close the issue. feel free to reopen it if you provide the required info
