### ISSUE TITLE
Connection to 'database name' not available

### ISSUE THREAD

**Issue by petem24** [capacitor-community/sqlite#377]
**Describe the bug**
I am using Angular + Capacitor and when I try to connect to my database I am getting the error 'Connection to cache not available'. I have looked at the source code at it seems connection to the database is not in the dbDict but i'm not familiar with swift at all. My database is located in assets/database/cache.db and is copying over the 'Library/Caches' folder on the device just fine.

**To Reproduce**
```  
async initializePlugin() {
    try {
      switch (this._deviceInfo.platform) {
        case 'ios': {
          if (!(await this.isDatabase()).result) {
            await CapacitorSQLite.copyFromAssets({ overwrite: false });
          }

          await CapacitorSQLite.open({ database: 'cache' });
          break;
        }

        default: {
          break;
        }
      }
    } catch (error) {
      console.error(error);
      this._toast.error(error.message, 'Error');
    }
  }
```

Capacitor config
```
import { CapacitorConfig } from '@capacitor/cli';

const config: CapacitorConfig = {
  appId: 'com.my.app',
  appName: 'My App',
  webDir: '../dist/my-app',
  bundledWebRuntime: false,
  server: {
    url: 'http://192.168.1.137:4200',
    cleartext: true,
  },
  plugins: {
    CapacitorSQLite: {
      iosDatabaseLocation: 'Library/Caches',
    },
  },
};

export default config;
```

**Expected behavior**
Connection to the database to be successful

**Screenshots**
Assets Folder
<img width="250" alt="image" src="https://user-images.githubusercontent.com/25905414/218451844-f0946870-27a6-4719-ac10-765ee0254487.png">

Device cache folder
<img width="721" alt="image" src="https://user-images.githubusercontent.com/25905414/218451688-2bf4e7cd-0b0f-4c20-a43a-f15582952efd.png">

**Desktop (please complete the following information):**
- OS: MacOS 13.1 (22C65) (Macbook pro M1)

**Smartphone (please complete the following information):**
- Device: iPad Pro (12.9-inch) (6th generation)
- OS: iOS 16.2 (20C52)
- Browser: Capacitor 
- Version: "@capacitor/core": "^4.6.1" "@capacitor-community/sqlite": "^4.6.1"

**Comment by jepiqueau** [comment]
@petem24 before to use 
```ts
await CapacitorSQLite.open({ database: 'cache' });
```
you must create a connection this is why your dbDict is empty

Look at some of the example provided
Hope this will help you to start

**Comment by jepiqueau** [comment]
@petem24 I looked at it seems pretty old as even the web implementation was not existing
