### ISSUE TITLE
Crash Error while SDK initialization in iOS

### ISSUE THREAD

**Issue by neelpatel63moons** [capacitor-community/sqlite#379]
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[CapacitorSQLitePlugin getConfig]: unrecognized selector sent to instance 0x7fc5cd215530' in ios swift

**Comment by jepiqueau** [comment]
@neelpatel63moons thanks for reporting but you have to give some more infos plugin version package.json and the part of code where the error occurs

**Comment by jepiqueau** [comment]
@neelpatel63moons give also your capacitor.config.ts file

**Comment by neelpatel63moons** [comment]
capacitor-community/sqlite: 4.6.0

capacitor.config.ts file

import { CapacitorConfig } from '@capacitor/cli';
const config: CapacitorConfig = {
  appId: 'com.abc.dev',
  appName: 'xyz',
  webDir: 'www',
  bundledWebRuntime: false,
  plugins: {
    SplashScreen: {
      launchAutoHide: false
    }
  }
};
export default config;

**Comment by jepiqueau** [comment]
@neelpatel63moons look at the api.md doc you must have a config for the plugin CapacitorSqlite

**Comment by jepiqueau** [comment]
@neelpatel63moons Any feedback or i will close the issue

**Comment by jepiqueau** [comment]
@neelpatel63moons What do you mean by implement to iOS SDK? Can you share your app

**Comment by neelpatel63moons** [comment]
I am creating framework file of app in iOS and then I import that framework in iOS Parent App.

> @neelpatel63moons What do you mean by implement to iOS SDK? Can you share your app

**Comment by jepiqueau** [comment]
@neelpatel63moons can you share a simple repro app with the process you use.

**Comment by neelpatel63moons** [comment]
> @neelpatel63moons can you share a simple repro app with the process you use.

1.) I have my code in Ionic Angular Capacitor and in this I am using Capacitor-community/sqlite. 
2.) From this I am adding iOS platform. 
3.) From this iOS Platform I am copying public folder, config.xml, capacitor.config.json, info.plist files to iOS Native framework Project.
4.) Then I import mentioned 4 files to framework project and create build. In this build which we get will be .framework file.
5.) I am importing this .framework file to another iOS Native Project. Try to run that app in iOS Device there I am facing crash just because of capacitor-community/sqlite plugin. Without this plugin app is running fine.

**Comment by neelpatel63moons** [comment]
> > @neelpatel63moons can you share a simple repro app with the process you use.
> 
> 1.) I have my code in Ionic Angular Capacitor and in this I am using Capacitor-community/sqlite. 2.) From this I am adding iOS platform. 3.) From this iOS Platform I am copying public folder, config.xml, capacitor.config.json, info.plist files to iOS Native framework Project. 4.) Then I import mentioned 4 files to framework project and create build. In this build which we get will be .framework file. 5.) I am importing this .framework file to another iOS Native Project. Try to run that app in iOS Device there I am facing crash just because of capacitor-community/sqlite plugin. Without this plugin app is running fine.

@jepiqueau

**Comment by jepiqueau** [comment]
@neelpatel63moons Are you also using other capacitor plugins provided by the capacitor team and did they work following the same process?

**Comment by jepiqueau** [comment]
@neelpatel63moons any news?
