### ISSUE TITLE
ORM support

### ISSUE THREAD

**Issue by pritamsoni-hsr** [capacitor-community/sqlite#38]
Any plan for adding sqlite orm? something like `expo-sqlite-orm` maybe.

**Comment by jepiqueau** [comment]
@pritamsoni-hsr Thanks for looking at the plugin. i look at `expo-sqlite-orm` to understand the concept of ORM.  I have no plan yet but it is a quite interesting concept.

**Comment by dwieeb** [comment]
An ORM would require **a lot** of work, and they're hard to "finish" (users will report bugs and features no matter how much work goes into it).

If someone wanted to pursue it, I would recommend a separate package (`@capacitor-community/sqlite-orm`, for example). It could just be a JS library that uses `@capacitor-community/sqlite` as a driver.

**Comment by jepiqueau** [comment]
@dwieeb you right, it is a lot of work and i agree it should be a separate package to not add complexity and bugs to the `@capacitor-community/sqlite` package. Any idea on how to add a capacitor plugin in another capacitor plugin as i think the plugin interface of the called plugin should not go through the bridge so do we have to manage two interfaces for that plugin one going through the bridge for standard use and one call directly for being called by another plugin?

**Comment by pritamsoni-hsr** [comment]
@jepiqueau @dwieeb I don't think we need another capacitor plugin for this, having a serializer and de-serializer package would work. 
A rough approach to this could be, we design models and/or queries and orm translates them to sql queries, and the model class would take an extra database argument which is a capacitor/sqlite plugin.

**Comment by dwieeb** [comment]
Correct, `@capacitor-community/sqlite-orm` wouldn't need to be a Capacitor plugin, just a JS layer that builds SQL queries from models and uses the sqlite plugin to actually perform the query. Luckily, I think it may be possible to use an existing JS ORM and build the part that connects the ORM to the driver (e.g. ["dialects"](https://github.com/sequelize/sequelize/tree/master/src/dialects) for sequelize). Unfortunately, according to [this issue](https://github.com/sequelize/sequelize/issues/6986), I'm not sure it's possible with sequelize, so we may need to investigate alternative ORMs.

**Comment by chriswep** [comment]
i think using typeorm would make the most sense here. there are also similar plugins for cordova-sqlite and others that can be taken as a start.

Together with multiple database support (https://github.com/capacitor-community/sqlite/issues/1) this would make this plugin useful in many more use cases.

**Comment by accron-1** [comment]
I downvoted this suggestion as there is a real risk of it being a huge time sink and will distract @jepiqueau from the core functionality of the plugin.

Let's keep this plugin lean and focused, and avoid bloat.

Also, ORM in itself is [controversial](http://blogs.tedneward.com/post/the-vietnam-of-computer-science/), so I hope the idea will be rejected.

@jepiqueau: if you didn't know ORM before and what it does, please discard the request and don't look back.

**Comment by jepiqueau** [comment]
Thanks for your clear advise. I agree that it will be a big work to refactor the plug-in and I have not take any decision yet as for the time I know that the plug-in is working as it is and requires a good maintenance and cleaning. It is also requiring demonstrating apps in different frameworks which is my current plan I have already Ionic/Angular, Ionic/React, React and I will come soon with Ionic/Vue and Vue Hope this clarify.

**Comment by danielprrazevedo** [comment]
@accron-1 I agree that this should not be the responsibility of @jepiqueau, as he is responsible for the plugin only, drivers for orm can be for other members of the community, including me, of course. However, I do not believe that rejecting the request is the best. I believe we can move it to other discussions or maybe bring it to the typeorm itself, because the typeorm drivers are included in their repository
but definitely, that shouldn't be @jepiqueau responsibility

**Comment by accron-1** [comment]
@danielprrazevedo If adding ORM support didn't require any additional work from @jepiqueau there wouldn't be a request here, you'd simply use his existing code/plugin as-is. So clearly this request does expect him to do some work in some shape or form.

The core function of this plugin is to provide cross platform access to Sqlite. It doesn't say anything about ORM, nor would I expect it to. ORM tries to solve problems which are unrelated to the purpose of this plugin (and it solves them poorly, many would argue, or at the expense of other metrics, e.g. performance, simplicity, etc...).

This plugin is very appreciated by many users, and much needed. A stable and bug free plugin will require continuous maintenance and updates by @jepiqueau, as the platforms (Android/iOS/Electron) and the different frameworks (Ionic Angular/React/Vue) evolve. We don't need code that introduce complexity, bloat, or worse, bugs. Adding ORM increases the surface area and potentially means more code that needs to be adequately maintained.

So let's not distract him with completely unrelated features, so that we have an awesome plugin that works great not only today, but also next year, and beyond.

Given the above, I hope the request is rejected.

**Comment by pritamsoni-hsr** [comment]
@accron-1  I agree, we can add typeorm with some effort, this issue was more of a question to @jepiqueau and I agree it'll bring more complexity and bugs, add bloatware.

**Comment by jepiqueau** [comment]
@pritamsoni-hsr,  @dwieeb ,  @noerw , @danielprrazevedo,  i am currently working on a refactor of the `@capacitor-community/sqlite` plugin in view of exposing it through a connection to the database, multiple database connection, ...  
this should easy the way to create a driver to `typeorm`.
An alpha version for Android  is now available including some of the basic sqlite methods ` https://github.com/capacitor-community/sqlite/tree/refactor`. could be installed with `npm i --save @capacitor-community/sqlite@refactor` So if one of the community member wants to write the driver to `typeorm` and/ or to `spatialite` he will be welcome. I am concentrating myself on the refactor.

**Comment by chriswep** [comment]
@jepiqueau i can have a look into the typeorm driver as soon as https://github.com/capacitor-community/sqlite/issues/1 is finalised

**Comment by jepiqueau** [comment]
@chriswep This will be very nice if you can do it. You can even start quickly as the Android refactor is ready, only missing the json import/export. The iOS refactor will be there soon again without the json import/export so the interfaces  `ISQLiteConnection` and `ISQLiteDBConnection` will not really change now . I will only add a `getExistingConnection(database:string)` in `ISQLiteConnection` to retrieve an existing connection which will allow to use  a db connection created in one page of the app and using it in another page.

**Comment by chriswep** [comment]
i'm not getting to this the next days anyway. maybe you have some basic documentation ready at some point? that would help getting started quickly.

**Comment by jepiqueau** [comment]
@chriswep Ok fine, the documentation is there already
[API_Documentation](https://github.com/capacitor-community/sqlite/blob/refactor/docs/API.md)

[API_Connection_Wrapper_Documentation](https://github.com/capacitor-community/sqlite/blob/refactor/docs/APIConnection.md)

[API_DB_Connection_Wrapper_Documentation](https://github.com/capacitor-community/sqlite/blob/refactor/docs/APIDBConnection.md)

**Comment by jepiqueau** [comment]
@chriswep sorry i close it by mistake

**Comment by jepiqueau** [comment]
Now that the refactor release is launched, it would be easy for one to develop the `typeorm driver`  when required. I will not develop it myself so i close that issue

**Comment by chriswep** [comment]
i just created a PR for the driver on the TypeORM repo: https://github.com/typeorm/typeorm/pull/7695

@jepiqueau you might want to mention it somewhere in the docs/README when it's released.

**Comment by jepiqueau** [comment]
@chriswep For sure i will do, thanks for your contribution in making the sqlite plugin stronger and for providing the `typeorm`  driver. Tell me when it is released i will mention it in the README. Would be nice if you could have also a link to an or several examples. The best will be that you create a PR with a TypeORM-Usage.md in the docs which i can refer to in the README Documentation/API chapter. What do you think about it?

**Comment by jepiqueau** [comment]
@chriswep I saw the PR  for the driver on the TypeORM repo has been merged.  Will you write a TypeORM-Usage.md so i can refer to it in the REAGME.md of the sqlite plugin?

**Comment by chriswep** [comment]
done @jepiqueau

**Comment by jepiqueau** [comment]
@chriswep I am currently travelling for the next 3 weeks with not really a viable Internet connection and I have also few issues that I want to solve. This PR will be merge to be part of the release 3. If I found a Internet connection I will merge it to be part of release 3.0.0-rc.2
