### ISSUE TITLE
CapacitorSQLPlugin: Protocol message contained in invalid tag (zero) #363

### ISSUE THREAD

**Issue by mannysangra** [capacitor-community/sqlite#382]
Hi,

This problem occurs when I run the app on a physical device (Android 12).

Searching in the web I found someone with the same problem.

**Note: I solved this by setting the property " android:allowBackup="false"" in AndroidManifest.xml** 

**To Reproduce**
here is the configuration file of capacitor: 

`export const config: CapacitorConfig = {
  appId: 'test.sqlite'
  appName: 'sqlite',
  webDir: 'www',
  bundledWebRuntime: true,
  plugins: {
    CapacitorSQLite: {
      androidIsEncryption: true,
    },
  },
};
`
**Additional context**
So if in the configurations capacitor androidIsEncryption has true value, 
when the application is built the AndroidManifest is generated with the property "android:allowBackup="true" by default,
this configuration cause the error reported, to work around I had to set the android:allowBackup="false" property.

**Comment by jepiqueau** [comment]
@mannysangra look at the Android Quirks in the last release of the plugin. You will see what you need to do. If this does not solve the issue tell me

**Comment by mannysangra** [comment]
Yes resolved
