### ISSUE TITLE
isDatabase - Connection to Database "Database-Name" is not Available

### ISSUE THREAD

**Issue by michaelbutler1998** [capacitor-community/sqlite#383]
**Describe the bug**
After updating to the latest version of the plugin (I've been using an outdated version for which this error did not occur), upon calling "isDatabase" on a database name, I receive the error "Connection to database "database-name" not available. 

I have noted this issue raised here: https://github.com/capacitor-community/sqlite/issues/377 but believe it is different as I'm not trying to open a connection, and the API docs on isDatabase state that it should work without a database connection: https://github.com/capacitor-community/sqlite/blob/master/docs/API.md#isdatabase

**To Reproduce**
1. Create a new SQLiteConnection(CapacitorSqlite) connection
2. 2. Call await CapacitorSQLite.isDatabase({ database: "database-name" }) 

**Expected behavior**
Receive error: ERROR MESSAGE: {"message":"isDatabase: Connection to database-name not available","errorMessage":"isDatabase: Connection to database-name not available"}

**Screenshots**
![image](https://user-images.githubusercontent.com/15836316/221930301-30e27861-4f27-4a1a-a02d-ac5b08635445.png)

![image](https://user-images.githubusercontent.com/15836316/221930330-019551ae-2b43-47ca-857a-5d77b829fd14.png)

**Smartphone (please complete the following information):**

- Device: Simulator - iPhone 14

**Additional context**
I'm developing in Ionic/Vue

**Comment by jepiqueau** [comment]
@michaelbutler1998 may be you should look at the doc there is know à readonly boolean to provide

**Comment by michaelbutler1998** [comment]
Apologies @jepiqueau, I thought this was an optional parameter. This has resolved my issue

**Comment by jepiqueau** [comment]
@michaelbutler1998 it is optional if you use the ISQLiteConnection wrapper not if you use directly the CapacitorSqlite plugin. Have a good app development
