### ISSUE TITLE
CapacitorSQLite.execute on Android does not support comments

### ISSUE THREAD

**Issue by patdx** [capacitor-community/sqlite#386]
**Describe the bug**

If CapacitorSQLite.execute is used on Android with a sql script that contains `--` comments, the comments lines can be squashed (as in, newlines `\n` removed) with statement lines and comment out the statement lines.

I discovered this by trying to use the execute command to run a migration script generated by Prisma Migrate.

**To Reproduce**

Run a script like the following in an Android app:

```js
const script = `-- RedefineTables
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_comment" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "text" TEXT NOT NULL,
    "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO "new_comment" ("id", "text") SELECT "id", "text" FROM "comment";
DROP TABLE "comment";
ALTER TABLE "new_comment" RENAME TO "comment";
PRAGMA foreign_key_check;
PRAGMA foreign_keys=ON;`;

CapacitorSQLite.execute({
  database: 'my_db',
  statements: script,
});
```

You will get an error saying that  `-- RedefineTables PRAGMA foreign_keys=OFF;` is not a valid statement, because  the newline was removed and `PRAGMA foreign_keys=OFF` is now part of the comment.

**Expected behavior**

Should be able to use sql scripts with comments on Android without needing to remove the comments by hand.

**Desktop (please complete the following information):**

- OS: Fedora 37
- Browser Chrome
- Version 110

**Smartphone (please complete the following information):**

- Device: Samsung Galaxy A03s
- OS: Android 13
- Browser Android System Webview
- Version 110

**Additional context**

I prepared a PR with one possible strategy of just stripping any line that starts with "--". See #387

**Comment by jepiqueau** [comment]
@patdx this has been amended in 4.6.3-3

**Comment by patdx** [comment]
Thank you, I updated to the latest Capacitor SQLite plugin version, and tested again in the Android app where I originally discovered this bug. It seemed to work without errors now :pray:
