### ISSUE TITLE
sqlite 4.6.2 has depdenies, that require android compileSdkVersion 33

### ISSUE THREAD

**Issue by mueggi** [capacitor-community/sqlite#391]
**Describe the bug**
sqlite 4.6.1 works fine. sqlite 4.6.2 has android dependencies that are compiled against android sdk version 33. Therefore, during a gradle build, errors show up, that the app needs to be compiled against sdk 33. Capacitor 4 supports only sdk 32. 

        1.  Dependency 'androidx.room:room-runtime:2.5.0' requires libraries and applications that
        depend on it to compile against version 33 or later of the
        Android APIs.
        
        :app is currently compiled against android-32.
        
        Recommended action: Update this project to use a newer compileSdkVersion
        of at least 33, for example 33.
        
        Note that updating a library or application's compileSdkVersion (which
        allows newer APIs to be used) can be done separately from updating
        targetSdkVersion (which opts the app in to new runtime behavior) and
        minSdkVersion (which determines which devices the app can be installed
        on).
        
        2.  Dependency 'androidx.sqlite:sqlite-framework:2.3.0' requires libraries and applications that
        depend on it to compile against version 33 or later of the
        Android APIs.
        
        :app is currently compiled against android-32.
        
        Recommended action: Update this project to use a newer compileSdkVersion
        of at least 33, for example 33.
        
        Note that updating a library or application's compileSdkVersion (which
        allows newer APIs to be used) can be done separately from updating
        targetSdkVersion (which opts the app in to new runtime behavior) and
        minSdkVersion (which determines which devices the app can be installed
        on).
        
        3.  Dependency 'androidx.sqlite:sqlite:2.3.0' requires libraries and applications that
        depend on it to compile against version 33 or later of the
        Android APIs.
        
        :app is currently compiled against android-32.
        
        Recommended action: Update this project to use a newer compileSdkVersion
        of at least 33, for example 33.
        
        Note that updating a library or application's compileSdkVersion (which
        allows newer APIs to be used) can be done separately from updating
        targetSdkVersion (which opts the app in to new runtime behavior) and
        minSdkVersion (which determines which devices the app can be installed
        on).
        
        4.  Dependency 'androidx.security:security-crypto:1.1.0-alpha05' requires libraries and applications that
        depend on it to compile against version 33 or later of the
        Android APIs.
        
        :app is currently compiled against android-32.
        
        Recommended action: Update this project to use a newer compileSdkVersion
        of at least 33, for example 33.
        
        Note that updating a library or application's compileSdkVersion (which
        allows newer APIs to be used) can be done separately from updating
        targetSdkVersion (which opts the app in to new runtime behavior) and
        minSdkVersion (which determines which devices the app can be installed
        on).

**To Reproduce**

1. Create a capacitor app with the supported compileSdkVersion 32 and include sqlite 4.6.2.
2. npx cap run android --> the errors show up

**Expected behavior**
sqlite should be compiled against sdk 32, as long as 33 is not officially supported by capacitor. 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

- Device: Pixel 7
- OS: Android 13
- Version 32/33

**Comment by jepiqueau** [comment]
@mueggi Thanks for your remark, either you keep running with 4.6.1 which works with API 32 or the latest release which requires API 33. The update to `androidx.security:security-crypto:1.1.0-alpha05` was required to fix some issues. @capacitor/core doesn't seems to suffer from this. May be you should ask the ionic team to move Capacitor 4 to API 33.
