### ISSUE TITLE
Remove logs in build

### ISSUE THREAD

**Issue by muuvmuuv** [capacitor-community/sqlite#392]
**Is your feature request related to a problem? Please describe.**

Yes, we really would like to avoid any logs printed to the users' console to not leak any information about tools or configs we use. Could you remove or at least bring console logs behind a debug flag?

> https://github.com/capacitor-community/sqlite/blob/master/src/web.ts#L145

**Describe the solution you'd like**

One of:

- Remove all console.logs
- Add `debug` option that prints verbose information about
  - sql run
  - options passed
  - etc. (if wanted)

**Describe alternatives you've considered**

None

**Additional context**

None

**Comment by jepiqueau** [comment]
@muuvmuuv did you add hideLogs:true in the capacitor.config.ts

**Comment by muuvmuuv** [comment]
I use `loggingBehavior` but left it default for development. But yours is in the web.js so will always be printed, even in production, isn't it?

**Comment by jepiqueau** [comment]
@muuvmuuv which log messages are you refferring to in web.js

**Comment by muuvmuuv** [comment]
I linked the file and line above

**Comment by jepiqueau** [comment]
@muuvmuuv OK i will remove it

**Comment by jepiqueau** [comment]
@muuvmuuv This has been fixed  in 4.6.3-4.
