### ISSUE TITLE
`drizzle-orm` maybe future?)

### ISSUE THREAD

**Issue by reslear** [capacitor-community/sqlite#395]
hi @jepiqueau there seems to be a normal orm for the frontend based on zod:
https://github.com/drizzle-team/drizzle-orm/blob/main/drizzle-orm/src/sqlite-core/README.md

What do you think about it?)

**Comment by jepiqueau** [comment]
hi @reslear , One has to write a driver to @capacitor-community/sqlite for `drizzle-orm` as one did it for `typeOrm`. May be you could do it and add a PR to `drizzle-orm`

**Comment by jepiqueau** [comment]
@reslear any progress on this ? if you do not give feedback, i will close the issue
