### ISSUE TITLE
Data import where the ID is a UUID and sql_deleted = 1

### ISSUE THREAD

**Issue by maxsoftware** [capacitor-community/sqlite#399]
Import from JSON fails on Android when sql_deleted = 1 and ID is a UUID. The affected line in ImportFromJson.java is 551 onwards - DELETE FROM command.

Changing ImportFromJson.java DELETE FROM fixes the issue.
```Object key = tColNames.get(0);
StringBuilder sbQuery = new StringBuilder("DELETE FROM ")
        .append(tableName)
        .append(" WHERE ")
        .append(tColNames.get(0))
        .append(" = ");
    if (key instanceof Integer) sbQuery.append(row.get(0)).append(";");
    if (key instanceof String) sbQuery.append("'").append(row.get(0)).append("';");
    stmt = sbQuery.toString();
```

This is an identical issue to #75 but the fix in that doesn't fix sql_deleted = 1 on import.

**Comment by maxsoftware** [comment]
Any news on a fix?

**Comment by jepiqueau** [comment]
@maxsoftware not yet i am travelling i will look at it when i am back
