### ISSUE TITLE
Better permission request on Android

### ISSUE THREAD

**Issue by paulantoine2** [capacitor-community/sqlite#40]
**Is your feature request related to a problem? Please describe.**

The immediate permission request on load must not be mandatory, it's really aggressive.

**Describe the solution you'd like**

I would like to be able to request Storage permission myself when needed

**Describe alternatives you've considered**

For ANDROID

I've replaced the `pluginRequestPermissions()` in the plugin `load()` function by `isPermissionGranted = false;`  then used `CapacitorSQLite.requestPermissions()` when needed in my Javascript which work but doesn't exist on the Typescript declaration and does not allow to wait for the result nor provide a listener.

**Comment by jepiqueau** [comment]
@paulantoine2 Sorry, i did not want to be agressive, it is just that sqlite requires the storage permission. i will have a look later.
which frameworks and platforms are you using

**Comment by paulantoine2** [comment]
Thanks for the quick answer @jepiqueau !
I mean it's aggressive for users to see the popup straight when you open the app (on Android). Usually apps have an onboarding process with pretty screens gently asking to give permissions in that case.
I'm using React Ionic for Android/Ios

**Comment by paulantoine2** [comment]
This is what worked for me if you are interested : #41

**Comment by jepiqueau** [comment]
@paulantoine2 i have accepted the pull request, i trust that you test it and it works. I add you as a contributor in the readme file. Thanks for this, do not hesitate if you find other issues. I close this one

**Comment by paulantoine2** [comment]
Not sure if it's a good idea to merge it like that, it might be a breaking change for apps already using it !

**Comment by jepiqueau** [comment]
@paulantoine2 Developers can still use the old version of the plugin if they wish on their applications or they will have to update, it is how software development goes. i judge that your pull request was acceptable and bring more softness by asking the permissions when the app needs them and not at the beginning of the app which you and some others, i assume, did not like. voilà ... i think i will do the same in my others plugins

**Comment by jepiqueau** [comment]
@paulantoine2 Any idea why it `doesn't exist on the Typescript declaration and does not allow to wait for the result nor provide a listener` Where did you find an example of this implementation so i can have a look
