### ISSUE TITLE
I want to add a small nice thing to documentation for IntelliJ-Ultimate users

### ISSUE THREAD

**Issue by folsze** [capacitor-community/sqlite#400]
My chat with ChatGPT (useless things left out):

ME:
in intellij for recognizing database schemas is it possible to hardcode a schema if the real db cannot be recognized? Do you know what I mean?

GPT-4:
I apologize for the confusion in my previous response. I made an error in my instructions, as [...].

In this case, you can still create an SQLite data source in IntelliJ to help it recognize the schema and provide better code assistance when working with SQL files and code blocks in your project. However, the process is slightly different:

Go to View > Tool Windows > Database to open the Database tool window.
Click the + button and select Data Source > SQLite.
Instead of selecting the schema.sql file in the "File" field, create an empty SQLite database file. You can do this by clicking the "Create" button next to the "File" field and providing a name for the new SQLite database file (e.g., my_database.sqlite). This file will be created in your project directory.
Click "OK" to save the data source.
Now, you should have an SQLite data source in your Database tool window. To create the schema in the new SQLite database file, follow these steps:

[IN THE DATABASE SIDEBAR TAB] Right-click on the SQLite data source you just created in the Database tool window.
Select "Open SQL Console" to open a new SQL console connected to your SQLite data source.
Copy and paste the SQL schema you prepared earlier into the SQL console.
Run the SQL script by clicking the "Execute" button or pressing Ctrl+Enter (Cmd+Enter on macOS).
This will create the schema in your SQLite database file, and IntelliJ should now recognize it and provide better code assistance when working with SQL files and code blocks in your project.

Regarding my previous instructions, I apologize for any confusion I may have caused. I appreciate your patience and understanding as we work to find the correct solution for your needs.

Links:
(note: you have to be in the database tool window and click [QL])
https://www.jetbrains.com/help/idea/working-with-database-consoles.html#create_console

if it is possible to even use SQL-wasm.wasm for this then apologize, then I would not include this into the docs.

Otherwise I think this can help you spot bugs a lot easier in IntelliJ. Previously I had 500 errors in my db-service.ts files, now I have zero and see right away if I make a mistake

Of course I would emphasize that you need to always keep your fake .sqlite database file schema up to date to get the correct IntelliJ-Errors

**Comment by folsze** [comment]
possibly this could prevent things like:
https://github.com/capacitor-community/sqlite/discussions/384#discussioncomment-5196908

**Comment by jepiqueau** [comment]
@folsze Cool, make a PR and i wiil merge it

**Comment by folsze** [comment]
@jepiqueau  https://github.com/capacitor-community/sqlite/pull/405

**Comment by jepiqueau** [comment]
@folsze this has been merged thanks for your contribution
