### ISSUE TITLE
can't launch my app using capacitor-community/sqlite plugin

### ISSUE THREAD

**Issue by Ly-sg** [capacitor-community/sqlite#404]
**Describe the bug**
Hello, new to the ionic ecosystem here.
I'm just trying to run a simple ionic app with the "capacitor-community/sqlite" on an andoird emulator (tryied android 32 and 33)

**To Reproduce**
1. Create a blank ionic 7 app with this command : ionic start myApp blank --type=angular --capacitor
2. npm install --save @capacitor-community/sqlite
3. Edit MainActivity.java :
`package io.ionic.starter;
import android.os.Bundle;

import com.getcapacitor.BridgeActivity;
import com.getcapacitor.Plugin;
import com.getcapacitor.community.database.sqlite.CapacitorSQLite;

import java.util.ArrayList;

public class MainActivity extends BridgeActivity {
  @Override
  public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    // Initializes the Bridge
    this.init(savedInstanceState, new ArrayList<Class<? extends Plugin>>() {{
      // Additional plugins you've installed go here
      // Ex: add(TotallyAwesomePlugin.class);
      add(CapacitorSQLite.class);
    }});
  }
}`

5. Added a service to load a database (i followed this tutorial [https://devdactic.com/sqlite-ionic-app-with-capacitor](url) and **i don't think the issue is here, the project doesn't start at all**)

**Expected behavior**
Launch the ionic app on my android emulator (i already maunched it successfully on emulator 32)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

- Device: Adnroid emualtor
- Version 32 and 33
**Additional context**
The ionic 7 blank app comes with this gradle variables config : 
`ext {
    minSdkVersion = 22
    compileSdkVersion = 32
    targetSdkVersion = 32
    androidxActivityVersion = '1.4.0'
    androidxAppCompatVersion = '1.4.2'
    androidxCoordinatorLayoutVersion = '1.2.0'
    androidxCoreVersion = '1.8.0'
    androidxFragmentVersion = '1.4.1'
    coreSplashScreenVersion = '1.0.0-rc01'
    androidxWebkitVersion = '1.4.0'
    junitVersion = '4.13.2'
    androidxJunitVersion = '1.1.3'
    androidxEspressoCoreVersion = '3.4.0'
    cordovaAndroidVersion = '10.1.1'
}`

**and when i try to start the app using this config it recommends me to upgrade to android 33 because some dependancies require at least android 33 to run, it also tells me to upgrade gradle plugin so i changed the dependencies in the build.gradle** file : 
`dependencies {
        classpath 'com.android.tools.build:gradle:7.2.1' // this one to 7.2.2`

**Here is the full stacktrace i have when running the app with the blank ionic app setup (meaning: android target ver 32 and gradle plugin 7.2.1)** 
`[capacitor]         FAILURE: Build failed with an exception.
[capacitor]         
[capacitor]         * What went wrong:
[capacitor]         Execution failed for task ':app:checkDebugAarMetadata'.
[capacitor]         > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
[capacitor]         > 4 issues were found when checking AAR metadata:
[capacitor]         
[capacitor]         1.  Dependency 'androidx.room:room-runtime:2.5.0' requires libraries and applications that
[capacitor]         depend on it to compile against version 33 or later of the
[capacitor]         Android APIs.
[capacitor]         
[capacitor]         :app is currently compiled against android-32.
[capacitor]         
[capacitor]         Also, the maximum recommended compile SDK version for Android Gradle
[capacitor]         plugin 7.2.1 is 32.
[capacitor]         
[capacitor]         Recommended action: Update this project's version of the Android Gradle
[capacitor]         plugin to one that supports 33, then update this project to use
[capacitor]         compileSdkVerion of at least 33.
[capacitor]         
[capacitor]         Note that updating a library or application's compileSdkVersion (which
[capacitor]         allows newer APIs to be used) can be done separately from updating
[capacitor]         targetSdkVersion (which opts the app in to new runtime behavior) and
[capacitor]         minSdkVersion (which determines which devices the app can be installed
[capacitor]         on).
[capacitor]         
[capacitor]         2.  Dependency 'androidx.sqlite:sqlite-framework:2.3.0' requires libraries and applications that
[capacitor]         depend on it to compile against version 33 or later of the
[capacitor]         Android APIs.
[capacitor]         
[capacitor]         :app is currently compiled against android-32.
[capacitor]         
[capacitor]         Also, the maximum recommended compile SDK version for Android Gradle
[capacitor]         plugin 7.2.1 is 32.
[capacitor]         
[capacitor]         Recommended action: Update this project's version of the Android Gradle
[capacitor]         plugin to one that supports 33, then update this project to use
[capacitor]         compileSdkVerion of at least 33.
[capacitor]         
[capacitor]         Note that updating a library or application's compileSdkVersion (which
[capacitor]         allows newer APIs to be used) can be done separately from updating
[capacitor]         targetSdkVersion (which opts the app in to new runtime behavior) and
[capacitor]         minSdkVersion (which determines which devices the app can be installed
[capacitor]         on).
[capacitor]         
[capacitor]         3.  Dependency 'androidx.sqlite:sqlite:2.3.0' requires libraries and applications that
[capacitor]         depend on it to compile against version 33 or later of the
[capacitor]         Android APIs.
[capacitor]         
[capacitor]         :app is currently compiled against android-32.
[capacitor]         
[capacitor]         Also, the maximum recommended compile SDK version for Android Gradle
[capacitor]         plugin 7.2.1 is 32.
[capacitor]         
[capacitor]         Recommended action: Update this project's version of the Android Gradle
[capacitor]         plugin to one that supports 33, then update this project to use
[capacitor]         compileSdkVerion of at least 33.
[capacitor]         
[capacitor]         Note that updating a library or application's compileSdkVersion (which
[capacitor]         allows newer APIs to be used) can be done separately from updating
[capacitor]         targetSdkVersion (which opts the app in to new runtime behavior) and
[capacitor]         minSdkVersion (which determines which devices the app can be installed
[capacitor]         on).
[capacitor]         
[capacitor]         4.  Dependency 'androidx.security:security-crypto:1.1.0-alpha05' requires libraries and applications that
[capacitor]         depend on it to compile against version 33 or later of the
[capacitor]         Android APIs.
[capacitor]         
[capacitor]         :app is currently compiled against android-32.
[capacitor]         
[capacitor]         Also, the maximum recommended compile SDK version for Android Gradle
[capacitor]         plugin 7.2.1 is 32.
[capacitor]         
[capacitor]         Recommended action: Update this project's version of the Android Gradle
[capacitor]         plugin to one that supports 33, then update this project to use
[capacitor]         compileSdkVerion of at least 33.
[capacitor]         
[capacitor]         Note that updating a library or application's compileSdkVersion (which
[capacitor]         allows newer APIs to be used) can be done separately from updating
[capacitor]         targetSdkVersion (which opts the app in to new runtime behavior) and
[capacitor]         minSdkVersion (which determines which devices the app can be installed
[capacitor]         on).`

My goal here is to be able to launch the app and learn Ionic, it doesn't matter which android API i use (be it 32 or 33...etc)
Is there some config i can modify to have compatible dependancies ?

**Comment by folsze** [comment]
simply google this error:

```
Dependency 'androidx.room:room-runtime:2.5.0' requires libraries and applications that [capacitor]         depend on it to compile against version 33 or later of the [capacitor]         Android APIs. [capacitor]          [capacitor]         :app is currently compiled against android-32. [capacitor]          [capacitor]         Also, the maximum recommended compile SDK version for Android Gradle [capacitor]         plugin 7.2.1 is 32. [capacitor]          [capacitor]         Recommended action: Update this project's version of the Android Gradle [capacitor]         plugin to one that supports 33, then update this project to use [capacitor]         compileSdkVerion of at least 33. 
```

You will find good solutions on stackoverflow. Have you tried it? It's in your build.gradle file as far as I rememeber (one of the two main build.gradle files, not sure which one.

Also I recommend going through this libraries Angular Starter Application. It helps a lot
https://github.com/capacitor-community/sqlite#ionicangular

I made an even simpler version of it with only employees and without all the encryption/decryption stuff, you can check it out if you want but keep in mind it's not the official so there might be errors cannot guarantee:
https://github.com/folsze/ionic-angular-sqlite-starter-minified/settings

I don't think this is an issue with the library and this should be closed. I think you just need some more native experience, maybe post questions in the Q&A of this repo instead

**Comment by folsze** [comment]
have you managed to get the angular starter application working? Did it work there?

**Comment by Ly-sg** [comment]
Hello sorry for the late reply, i actually tried many things to make it work and i managed to get my blank app to work with minor changes : 

- I changed     compileSdkVersion = 32    targetSdkVersion = 32 in "variables.gradle" file to  33
- changed "classpath 'com.android.tools.build:gradle:7.2.1'" in the "build.gradle" file to "classpath 'com.android.tools.build:gradle:7.2.2'"
- i deleted the code in the MainActivity.java file that registers the Capacitor plugin and basically left it in it's initial state 

Most of the tutorials/blogs i found were outdated and apparently that android part of the code wasn't needed anymore, now the app works, i managed to implement some basic crud features.

I know my way around angular but i don't have any experience with ionic yet, do  you guys use the capacitor/sqlit plugin as is or is there a more convenient way to manage persistence, i don't know if it's easy to interface with typeOrm or knexJs ? (using a local database like sqlite)

i'll try and dive into the docs to see how i can use the plugin properly.

**Comment by jepiqueau** [comment]
@Ly-sg this is the reason why i propose some demo app on https://github.com/jepiqueau that i try to keep inline with the current status of the plugin
