### ISSUE TITLE
Blob type is not converted to a usable type in javascript

### ISSUE THREAD

**Issue by ngarel** [capacitor-community/sqlite#410]
I have a TEXT column with the following text: 
"Fabio Stergulc, Università di Udine, Bugwood.org"
When running a SELECT query the library thinks it is a Blob type (probably because of the non english characters) and calls 
`c.getBlob(index)` in Database.java
This returns a byte array which is then sent back to javascript as 
`[B@f16786c` 
not really useful

Current work around is to convert the blob to a string:
`String str = new String(c.getBlob(index), "UTF-8");`

Note: This does not happen in iOS

**Comment by jepiqueau** [comment]
@ngarel can you please provide the database schema , the data and the select command. i test the text you gave "Fabio Stergulc, Università di Udine, Bugwood.org" and when i do a select *  i get the right value for the text not going through a Blob type

**Comment by jepiqueau** [comment]
@ngarel test i did is in Android

**Comment by ngarel** [comment]
Try this:
[dataSQLite.db.zip](https://github.com/capacitor-community/sqlite/files/11437440/dataSQLite.db.zip)
SELECT * FROM media

**Comment by jepiqueau** [comment]
@ngarel How this db has been created?  this is pretty strange.

if i create a new database myDataSQLite.db in DBBrowser and create the table media with 
```
CREATE TABLE media (ID SMALLINT, pest SMALLINT, image_number TINYINT, file_name VARCHAR(38), caption TEXT)
```
and filled the data by cut and paste your data  it works fine

**Comment by ngarel** [comment]
The problem is that I have many rows and some of them are seen as String other as Blobs even thought the column is set to TEXT so i can't manually recreate them unless I used some kind of script.

If you look at the definition of getType(), it says the data may be converted to other types. Couldn't find the doc for it though.
![image](https://github.com/capacitor-community/sqlite/assets/815480/d9b93980-f765-4ee8-a789-f5bad6c66b17)


I believe the file was made with this tool:
https://pypi.org/project/mysql-to-sqlite3/

I have changed the tool to https://github.com/dumblob/mysql2sqlite and it seems to be working fine now.

So not sure what happened but it is ok for me now.

However if I had and wanted a blob type, the returned value didn't seem to be useful so not sure what you want to do here.

I leave it up to you.

Thanks for helping

**Comment by jepiqueau** [comment]
@ngarel if i do what you suggest the blob will be **always** converted to a string which i do not think it will be the case for standard usage of a blob. this is why i was more looking at the reason for this happening. if it is working for you know i will suggest to close the issue for the time-being

**Comment by ngarel** [comment]
I didn't mean to convert a blob to string but to return an array of bytes in js (I just don't think it's happening right now).
I'm closing this for now.

**Comment by jepiqueau** [comment]
@ngarel look ar release 5.0.3-1 it is now returning an array of byte. Give me your feedback
