### ISSUE TITLE
Property `addListener` does not exist on type `CapacitorSQLitePlugin`

### ISSUE THREAD

**Issue by vycoder** [capacitor-community/sqlite#411]
**Describe the bug**
I'm trying to use the `sqliteImportProgressEvent` on a vue capacitor app (no using the vue-sqlite-hook) with typescript but it's throwing an error:
```bash
Property `addListener` does not exist on type `CapacitorSQLitePlugin`
```
I'm not sure if I'm doing it wrong, but I was just following how it was being implemented in `vue-sqlite-hook`:
```javascript
sqlitePlugin.addListener('sqliteImportProgressEvent',
                (e: any) => {
                    if(typeof onProgress.onProgressImport !== 'undefined')
                        onProgress.onProgressImport(e.progress);
                });
```
Here's my failing code snippet:
```typescript
import { CapacitorSQLite, capJsonProgressListener } from '@capacitor-community/sqlite'

// ....
    CapacitorSQLite.addListener('sqliteImportProgressEvent', (event: capJsonProgressListener) => {
      console.log(`Setting up offline databases. ${event.progress}`)
    })

```

I'm using the current latest version: `@capacitor-community/sqlite: 4.6.3`

**Comment by jepiqueau** [comment]
@vycoder the hook has been developed to make your life easy. So please use it. i will close this.

**Comment by vycoder** [comment]
@jepiqueau I'm using Quasar and things are a bit different, it's much easier in my case to not use the hook.

I tried looking into the implementation of the hook, to check where the listener is being attached as far as I can tell, I'm doing it correctly. But it appears like the `addListener` is not defined in `CapacitorSQLite`, I tried matching the same plugin version as what's `vue-sqlite-hook` is using, but I'm still getting the same errors. Am I doing something wrong? Or am I not getting the proper plugin definitions?

**Comment by jepiqueau** [comment]
@vycoder Can you share a simple app reproducing the issue as i do not know how to set a Quasar project

**Comment by vycoder** [comment]
@jepiqueau I think it's not Quasar being the project itself, but more of the plugin does not expose any `addListener` in the types? I'm just plainly using the plugin and calling `CapacitorSQLite.addListener`, typescript errors out saying `addListener` is not defined in `CapacitorSQLite`.

This snippet fails on compile-time, the IDE itself complains that there's no `addListener` function.

```typescript
CapacitorSQLite.addListener('sqliteImportProgressEvent', (event: capJsonProgressListener) => {
      console.log(`Setting up offline databases. ${event.progress}`)
    })
```
Does it have something to do with typescript? I'm using Typescript 4.9.4, if that helps.

**Comment by jepiqueau** [comment]
@vycoder as i said send le your app otherwise i cannot help you and i will close the issue.

**Comment by vycoder** [comment]
Okay, I'll try to create a basic project that uses, will update here as soon as I can.

**Comment by jepiqueau** [comment]
@vycoder Any progress ?

**Comment by vycoder** [comment]
@jepiqueau apologies for the late response. I'm having trouble replicating the issue on a fresh project. VSCode still flags it with the same error though, but it builds without no error though, my other project just fails. 

Will be closing this issue for now and will just reopen it if ever I've found an issue. Thanks!
