### ISSUE TITLE
Could not install the plugin 

### ISSUE THREAD

**Issue by devaliy** [capacitor-community/sqlite#417]
I'm having issues installing the plugin it seems to be having dependency conflict with Capacitor 5.0

How can I sail through this

**Comment by jepiqueau** [comment]
@devaliy with capacitor 5 you must use @capacitor-community/sqlite@next which is a bêta version till i publish the release 5

**Comment by vgrunner4v** [comment]
@jepiqueau any ETA for version 5 release? :)

**Comment by jepiqueau** [comment]
@vgrunner4v use @capacitor-community/sqlite@next
