### ISSUE TITLE
isConnection() return false even if connection exists

### ISSUE THREAD

**Issue by vgrunner4v** [capacitor-community/sqlite#418]
**Describe the bug**
isConnection() return false even if connection exists

**To Reproduce**
when connection exisits, call isConnection() and it return false

Checked on Android.

code: 
```
let isConn = await sqlite.isConnection("db", false);
  console.log("isConn: " + JSON.stringify(isConn));
  let db;
  if (!isConn.result) {
    db = await sqlite.createConnection("db", false, "no-encryption", 1);
  } else {
    db = await sqlite.retrieveConnection("db", false);
  }
```

results in log:

```
File: https://localhost/static/js/main.58ae0723.js - Line 2 - Msg: isConn: {"result":false}
To native (Capacitor plugin): callbackId: 31604378, pluginId: CapacitorSQLite, methodName: createConnection
callback: 31604378, pluginId: CapacitorSQLite, methodName: createConnection, methodData: {"database":"db","encrypted":false,"mode":"no-encryption","version":1,"readonly":false}
*** ERROR CreateConnection: Connection db already exists
Sending plugin error: {"save":false,"callbackId":"31604378","pluginId":"CapacitorSQLite","methodName":"createConnection","success":false,"error":{"message":"CreateConnection: Connection db already exists"}}
File: https://localhost/ - Line 771 - Msg: Uncaught (in promise) Error: CreateConnection: Connection db already exists
```

edit: its happening after refresh the page, maybe the hook reset its values and thats why isConnection is false even though its actually open?

**Comment by jepiqueau** [comment]
@vgrunner4v  you must do a checkConnectionConsistency first. Look at the example apps

**Comment by vgrunner4v** [comment]
@jepiqueau ah, i see. its working, thanks!

another question, what is the best practice? should i do db.open() only once at startup and keep this open, or should i do db.open() and db.close() for each operation? also, can i have multiple db.open() connections or its single connection too?

**Comment by jepiqueau** [comment]
@vgrunner4v you can have multiple db open. You do not need to open and close the db each time you make an operation it is time consuming but you can do it if you whish. Look at the demo apps for multiple db's open

**Comment by vgrunner4v** [comment]
@jepiqueau thanks! i'll stick to single connection. 

and last question (i hope), is there an option to track "live" changes on a table? for example, in Dexie (for indexeddb) they have hook of "useLiveQuery" that track changes and reload it for UI live updates.

**Comment by jepiqueau** [comment]
@vgrunner4v No, i do not see the need for it. If an insert update transaction is completed the database is updated. Otherwise i do not understand the question

**Comment by vgrunner4v** [comment]
@jepiqueau its just for UI components for auto reload instead changing the states myself, small example, you have a counter that update here and there and you want to show it in multiple pages, so the live query will do it automatically without the need of re-set the states.

but if its not possible, i'll find a workaround. :) very appreciate your help!

**Comment by jepiqueau** [comment]
@vgrunner4v this should be possible with observable instead of promise

**Comment by jepiqueau** [comment]
@vgrunner4v if you do something with observable may be you can share it

**Comment by vgrunner4v** [comment]
@jepiqueau I do something similar to the "existingConn" in App.js, added this:

App.js
```
export let txUpdateTrigger;
--------
const [updateTrigger, setUpdateTrigger] = useState(0);
txUpdateTrigger = {updateTrigger: updateTrigger, setUpdateTrigger: setUpdateTrigger};
```

Componenet
```
  const [pageNum, setPageNum] = useState(1);
  const [pageSize] = useState(10);
  const [txCount, setTxCount] = useState(0);
  const [transactions, setTransactions] = useState([]);

  useEffect(() => {
    countLocalTransactions().then(c => {
      setTxCount(c);
    });
  }, [txUpdateTrigger.updateTrigger]);

  useEffect(() => {
    getPageLocalTransactions(pageNum, pageSize).then(res => {
      setTransactions(res);
    });
  }, [pageNum, pageSize, txUpdateTrigger.updateTrigger]);
```

and when i update a value in DB or inserting new row, i just increase the trigger counter and then it calls the "count" and "get" and update the values. i don't know if its best practice, but its working. basically i'm backend engineer with no much knowledge on frontend 😜

**Comment by francoisduchemin** [comment]
@vgrunner4v @jepiqueau Could you please indicate at which example app I should look to find an example of using `checkConnectionConsistency`, or explain how I can use this method?

I looked at https://github.com/jepiqueau/angular-sqlite-app-starter/blob/master/src/app/services/database.service.ts and there is no mention of `checkConnectionConsistency`.

Thanks in advance!
