### ISSUE TITLE
Unable to insert value containing double dash ```--```

### ISSUE THREAD

**Issue by ariane10** [capacitor-community/sqlite#419]
**Describe the bug**
I'm trying to insert a value in a database like:

```SQL
INSER INTO table(reference_id, reference_value) VALUES ('id1','value1'),('id2','value2'),('id2----','value2');
```
but the function UtilsSQLite in class UtilsSQLite (node_modules/@capacitor-community/sqlite/android/src/main/java/com/getcapacitor/community/database/sqlite/SQLite/UtilsSQLite.java) detects the '--' as comment and cuts the line there. This results in a incoherent statement and returns syntax error.

**To Reproduce**

```SQL
INSER INTO table(reference_id, reference_value) VALUES ('id1','value1'),('id2','value2'),('id2----','value2');
```

**Expected behavior**

I would like to be able to insert a double dash ('--') as a value in my database as well as support comments. 

**Additional context**
Capacitor-community/sqlite@5.0.0-beta.2

**Comment by jepiqueau** [comment]
@ariane10 can you share the table schema

**Comment by jepiqueau** [comment]
@ariane10 you should another character as this pne is reserved for comment

**Comment by jepiqueau** [comment]
@ariane10 I will close that issue as i will not support '--' inside a table field name
