### ISSUE TITLE
jeep-sqlite element missing after manual page reload

### ISSUE THREAD

**Issue by Blanner** [capacitor-community/sqlite#420]
**Describe the bug**
When reloading a page via F5 or the browser reload button, in a capacitor angular application running in a web browser, the jeep-sqlite element is not present anymore after the reload and an error gets thrown. The SQLite database subsequently does not work anymore.

**To Reproduce**

1. Serve your angular application
2. Open your app in a web browser
3. Go to a page that uses the SQLite DB, for example to display a chart.
4. Click on the reload button in the browser or press F5
5. Notice the "jeep-sqlite element not present in the DOM" error in the browser console (see screenshot below)
6. The chart using the SQLite DB does not show any data anymore since the SQLite integration does not work without the jeep-sqlite DOM-element.

**Expected behavior**
The page should reload, the jeep-sqlite element should be added again and the SQLite DB should work like normal

**Screenshots**
![image](https://github.com/capacitor-community/sqlite/assets/21127280/6772071b-0dca-4846-b7ca-25f0c89c9820)

**Desktop:**

- OS: Windows 10
- Browser Chrome
- Version 113

**Additional context**
I am not sure whether this is expected or I am doing something wrong. Any hints would be greatly appreciated.

**Comment by jepiqueau** [comment]
@Blanner which version of jeep-sqlite are you using?

**Comment by Blanner** [comment]
I am thinking it might be a problem of one of my components accessing the sqlite db before the jeepsqlite element was added again. Is there a best practice on how I can wait inside a component until everything is initialized correctly?

**Comment by jepiqueau** [comment]
@Blanner you must have 
``` 
Await customElements.whenDefined('jeep-sqlite ');
``` 
Prior to the checkConnectionsConsistency()
Like this it should work

**Comment by Blanner** [comment]
You mean inside the component? 
I currently don't have a call to checkConnectionConsistency in the component prior to starting the first sql queries. 
I didn't find a reference on where to use it in the documentation.
Can you point me to where I can read up about it?

**Comment by jepiqueau** [comment]
@Blanner look at the app example depending on your framework

**Comment by Blanner** [comment]
I have been using your angular sqlite app starter project (https://github.com/jepiqueau/angular-sqlite-app-starter/tree/c9d86435acf2e5b21f3a19998d8040b0fb509abf) and basically mirrored the sqlite setup with repositories, a database service & an sqlite service.

However using the database service like shown there resulted in the above described error and I could not find a usage of  checkConnectionConsistency there. Are you refering to a different sample app?

**Comment by Blanner** [comment]
The executeQuery function looks like below in the sample app:
`  
async executeQuery<T>(callback: SQLiteDBConnectionCallback<T>, databaseName: string = environment.databaseName): Promise<T> {
    try {
      let isConnection = await this.sqlite.isConnection(databaseName);

      if (isConnection.result) {
        let db = await this.sqlite.retrieveConnection(databaseName);
        return await callback(db);
      }
      else {
        const db = await this.sqlite.createConnection(databaseName, false, "no-encryption", 1);
        await db.open();
        let cb = await callback(db);
        await this.sqlite.closeConnection(databaseName);
        return cb;
      }
    } catch (error) {
      throw Error(`DatabaseServiceError: ${error}`);
    }
  }
}`

When the page is reloaded manually by the browser, the isConnection.result is true when the page is loaded again but the `callback(db)` call throws the error that no db connection is available.

I've modified this like below to try to incorporate your feedback and get around this error. I mainly disabled the connection retrieving altogether and always create & close a new connection. I also added some code that waits for the jeep-sqlite element to be present and for the datastore to be open:

`
  async executeQuery<T>(callback: SQLiteDBConnectionCallback<T>, databaseName: string = environment.databaseName): Promise<T> {

    await customElements.whenDefined('jeep-sqlite');
    const jeepSqliteEl = document.querySelector('jeep-sqlite');
    if(jeepSqliteEl != null) {
      console.log(`>>DbService: isStoreOpen ${await jeepSqliteEl.isStoreOpen()}`);
    }

    try {
      let isConnection = await this.sqlite.isConnection(databaseName);
      console.log('executing query, isConnection: ' + isConnection.result);

      if(isConnection.result) {
        console.log('closing previous Connection');
        await this.sqlite.closeConnection(databaseName);
      } 

      console.log('creating connection');
      const db = await this.sqlite.createConnection(databaseName, false, "no-encryption", this.dbVersion);
      await db.open();

      let consistency: capSQLiteResult = await  this.sqlite.checkConnectionsConsistency();
      console.log('>>> Connection consistency: ' + consistency.result);
      let dbOpen: capSQLiteResult = await db.isDBOpen();
      console.log('>>> DB open: ' + dbOpen.result);
      let cb = await callback(db);

      console.log('closing Connection');
      await this.sqlite.closeConnection(databaseName);
      return cb;
      //}
    } catch (error) {
      throw Error(`DatabaseServiceError: ${error}`);
    }
  }`

With this, I'm not getting the above described error anymore but when I have multiple components accessing the DB more or less at once (some using the same, some using different repositories), then the Database is sometimes not opened for some of these accesses after the call to `db.open()`.
This is the current state that I'm at. If you have feedback for how I can improve this code or even resolve my new error, it would be greatly appreciated.

**Comment by jepiqueau** [comment]
@Blanner can you share your app

**Comment by jepiqueau** [comment]
@Blanner look at openDatabase in  sqlite.service.ts of ionic-angular-sqlite-starter

**Comment by Blanner** [comment]
The app itself yes, but to try this yourself you would need a personal data-download from Spotify which includes sensitive data, so I can't share that data with you and obtaining it yourself would take 2-5 days (if you already have a spotify account)

**Comment by Blanner** [comment]
Can you explain why a call to db.open might not actually open a database or why a createConnection might not be able to create a connection? Maybe this helps me to solve the problem myself.

Is there some sort of limit on how many connections to a database can be used simultaneously?

**Comment by jepiqueau** [comment]
@Blanner ir is only due to the live reload  which requires to have the check connections consistency to make sure that the connections are aligned between the SQLiteConnection wrapper and the plugin. I was thinking to share the app or a repro app on github

**Comment by jepiqueau** [comment]
@Blanner Did you make any progress? Is that solve by adding the checkConnectionsConsistency?

**Comment by jepiqueau** [comment]
@Blanner look at lines 41-42 of sqlite.service.ts of ionic-angular-sqlite-starter app

**Comment by jepiqueau** [comment]
@Blanner as you do not follow-up .i close the issue. Feel free to re-opens it if needed
