### ISSUE TITLE
WEB: Database gets reset to initial state on refresh (capv5, ionicv7)

### ISSUE THREAD

**Issue by folsze** [capacitor-community/sqlite#425]
**Describe the bug**
I am pretty sure this does not happen with capacitor version 4, with the older version of this plugin. I tested it in my real app and it all worked back in capv4 with this plugin. I am also pretty sure this only happens in the web version of this plugin.

On web after refreshing the data somehow gets reset to the state when the data was initially inserted (any updates made after the initial data was inserted are not kept). But not for the ionic-7-cap5-starter repo. Just for my code somehow. I created a minimal reproducible example with the ionic-5-capv5 repository. Here is the repo:
https://github.com/folsze/cap-v5-breaks-after-reload

**To Reproduce**
1. 
![image](https://github.com/capacitor-community/sqlite/assets/81622754/c36a31b9-81a5-423f-905d-f70e2bf5a0ed)
2.
![image](https://github.com/capacitor-community/sqlite/assets/81622754/d80da482-7830-4175-b358-3ddc0acedca3)
3.
![image](https://github.com/capacitor-community/sqlite/assets/81622754/12812e53-6f16-4354-81b0-da84f05a9296)
4.
go back into the page, see the changes now appear:
![image](https://github.com/capacitor-community/sqlite/assets/81622754/afb3cd46-b024-40a4-937a-2f5a58231460)
5. refresh the page
6. see changes disappear:
![image](https://github.com/capacitor-community/sqlite/assets/81622754/72df267e-867a-4089-a127-e9108a486bad)

The insertion happens in the DepartmentEmployeesService, see createInitialData there

**Expected behavior**
data receives the update & keeps after reload

Browser: Chrome Windows 11

**Comment by jepiqueau** [comment]
@folsze seems the  autosave property of jeep-sqlite is not set to true meaning that the database which resides in memory is not save to the store meaning that when you do a refresh the database is read from the store which has not been updated. So you must call the saveToStore method after the insert or set the autosave property to true.  I did not look in detail to your code as i do not have any idea on what you try to achieve.

**Comment by folsze** [comment]
Thank you. Adding this:
`jeepEl.autoSave = true;`

Here, in main.ts:
`if(platform === "web") {
  // Web platform
  // required for toast component in Browser
  pwaElements(window);

  // required for jeep-sqlite Stencil component
  // to use a SQLite database in Browser
  jeepSqlite(window);

  window.addEventListener('DOMContentLoaded', async () => {
    const jeepEl = document.createElement("jeep-sqlite");
    document.body.appendChild(jeepEl);
    jeepEl.autoSave = true;
  });
}`

did fix it. Interesting that this was not necessary before I updated the plugin version to v5 (required with capacitor v5)
