### ISSUE TITLE
Unable to read blob column in ionic/capacitor project with @capacitor-community/sqlite plugin in Android phone

### ISSUE THREAD

**Issue by veeru-d** [capacitor-community/sqlite#426]
**Describe the bug**
Have a simple table with a blob column, where a png image is store. While querying for the column, this plugin returns "[B@e44e523" instead of "iVBORw0..." (or something like that)

**To Reproduce**
clone this [sample](https://github.com/veeru-d/capcacitor-sqlite-v1/tree/main) project

(ionic project with capacitor and capacitor-community/sqlite plugin, with testdbSQLite.db test db

**Expected behavior**
should return `ivBORw0K...` (or something like that from the png image) for `img` blob column

**Screenshots**
returns `[B@aee96b4'` instead

**Desktop (please complete the following information):**
```
$ ionic info
[WARN] Error loading @ionic/angular package.json: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package' is not defined by "exports" in ...\capcacitor-sqlite-v1\node_modules\@ionic\angular\package.json
[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package'

       Require stack:
       - ...\AppData\Roaming\npm\node_modules\@ionic\cli\lib\project\index.js
       - ...\AppData\Roaming\npm\node_modules\@ionic\cli\lib\index.js
       - ...\AppData\Roaming\npm\node_modules\@ionic\cli\index.js
       - ...\AppData\Roaming\npm\node_modules\@ionic\cli\bin\ionic

Ionic:

   Ionic CLI                     : 6.19.0 (...\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : not installed
   @angular-devkit/build-angular : 16.0.4
   @angular-devkit/schematics    : 16.0.4
   @angular/cli                  : 16.0.4
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.0.4
   @capacitor/android : 5.0.4
   @capacitor/core    : 5.0.4
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v16.14.0 (...\nodejs\16\node.exe)
   npm    : 8.3.1
   OS     : Windows 10
```

**Smartphone (please complete the following information):**
Any Android 12 phone should be able to reproduce this issue.

I tested with OnePlus Nord N200 5G Android phone running OxygenOS with Android version 12)

**Additional context**
sample project to reproduce this issue is [here](https://github.com/veeru-d/capcacitor-sqlite-v1/tree/main).

**Comment by veeru-d** [comment]
I created the pre-seeded db by some other means. Not using this plugin.
You can view the db and "teach" table and the png image stored in "img" column in any db browser.
I used "DB Browser for SQLite" app.

**Comment by veeru-d** [comment]
stackoverflow [issue](https://stackoverflow.com/questions/76408481/how-to-query-a-blob-column-in-capacitor-community-sqlite-in-android-platform)

**Comment by jepiqueau** [comment]
@veeru-d the only way to store image in the plugin is to convert them to base64 string

**Comment by jepiqueau** [comment]
@veeru-d i am looking at it i already figure out how to do it on ios for reading from your fatabase and it works. The problem i still have is how to write a Uint8Array as bytes[] in the database. What means are you using to create the database you gave

**Comment by jepiqueau** [comment]
@veeru-d in what you suggest you convert it as Base64 to display the image in HTML and you have to assume that you know the image type 
ie ```
img.src = 'data:image/png;base64,' + imageData;
```

**Comment by jepiqueau** [comment]
@veeru-d i would have preferred to transfer a UInt8Array as this would have work for any type of data not only images. this works in iOS but not in Android as Java do not have unsigned Int array. i also did not find the way to save the image as Blob in the database in both platforms so i published the minimum i can do quickly for you .

**Comment by veeru-d** [comment]
@jepiqueau thank you, it works as expected now.

**Comment by jepiqueau** [comment]
@veeru-d this will be modified in the next release and will returned a byte array so it can be used not only for image.

**Comment by jepiqueau** [comment]
@veeru-d Can you test release 5.0.3-1 and give me your feedback

**Comment by veeru-d** [comment]
Extremely sorry, I missed this email chain altogether.
I’ll try this release later today and let you know.

**Comment by veeru-d** [comment]
Hi
5.0.3-1 is not working. It looks as if the fix isn’t present.

After 5.0.3-1, i reverted to 5.0.2 and it’s working.

Thanks

**Comment by veeru-d** [comment]
I created the db files using node.js script that reads png files and store
them as blob (binary and not base64) in sqlite db.

(Apparently, base64 format increases the size by 33% compared to raw
binary).

The script uses typeorm and @journeyapps/sqlcipher (and the db is password
protected)

**Comment by jepiqueau** [comment]
@veeru-d 5.0.3-1 is working fine but the image are not returned as Base64 images but as byte array look at the doc SQLiteBlob.md to see how you have to modify your code to retrieve the image

**Comment by veeru-d** [comment]
Ok, let me check.
