### ISSUE TITLE
i  have created plgugin  project  for  ios  but  in  main App  module  not  found

### ISSUE THREAD

**Issue by vikashsingh009** [capacitor-community/sqlite#43]
**Describe the bug**
i  have create plugin  project and  then  use  plugins and  link  plugin  using  npx  cap  link:bss  after  that  in  main  projects  install  dependency  using npp i  plugin  project  file  location

**To Reproduce**

1. Go to '"MobileApp  Project in  vscode '
2. install  npm i  plugin  file  path  ,theb  npx cap  sync after  that  npx  cap add  ios
3. then  npx  cap  open  ios  
in Xcode  Below Developement  Pods  inside Pods Project  could  not found  module  SQlCipher  but  as  module  builded  in  Pods  Project  ealier  and  also  show  in  pods 

![image](https://user-images.githubusercontent.com/7962189/94293993-c129ef80-ff7c-11ea-81b6-15485e8d79eb.png)

![image](https://user-images.githubusercontent.com/7962189/94294065-e1f24500-ff7c-11ea-9b00-a7117ee6ea08.png)
![image](https://user-images.githubusercontent.com/7962189/94294096-f0d8f780-ff7c-11ea-934c-892a60056b99.png)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jepiqueau** [comment]
@vikashsingh009 in your app folder 
``` 
cd ios
pod install
cd ..
npx cap update
npm run build
npx cap copy
npx cap open ios
```

in Xcode, clean the project and build the project

**Comment by jepiqueau** [comment]
@vikashsingh009 any news

**Comment by vikashsingh009** [comment]
Hello @jepiqueau   thanks  for  you  reply,i  have  tried with  created  new Plugin  but  whenever link  with  Application  to call  plugin  still  i  am  getting  SqlChipher No Module found  in  development,i  have  triyed  so  many  times  above  steps  but unfortunately its  not  worked  please  find  some  of  the  check

![Screenshot_3](https://user-images.githubusercontent.com/7962189/94699058-8bf41780-0357-11eb-83b0-6a3d1b79ce85.png)
![Screenshot_2](https://user-images.githubusercontent.com/7962189/94699064-8dbddb00-0357-11eb-9740-40cf835ad502.png)

**Comment by jepiqueau** [comment]
@vikashsingh009 Well looking at the views, it seems that you have created a new plugin which is using SQLCipher
In the `CapacitorPluginBackgroundSqliteSync.podspec` file you must add `s.dependency 'SQLCipher'`  and redo the `pod install` hope this will help

**Comment by vikashsingh009** [comment]
@jepiqueau , thanks  for  above  dependency  issues  solution  ,  now  i  able  to  buid  and  trigger  plugin  app

**Comment by jepiqueau** [comment]
@vikashsingh009 ok fine i close the issue
