### ISSUE TITLE
Previous iOS DB cannot be opened with Capacitor 5

### ISSUE THREAD

**Issue by mobilemarines** [capacitor-community/sqlite#430]
**Describe the bug**
When an iOS DB was created with the Capacitor 4 SQLite plugin without having set a iosKeychainPrefix it cannot be used on an updated App version anymore with this Capacitor 5 plugin.

**To Reproduce**

1. "Erase All Content and Settings..." in the iPhone Simulator
2. Install a Capacitor 4 iOS App creating a DB with this plugin on Capacitor 4 with encryption enabled but no iosKeychainPrefix set
3. Now update the installed app with a Capacitor 5 version and try to open the DB
4. If you don't set iosKeychainPrefix you get the error: "SetEncryptionSecret: keychain prefix must not be empty"
5. So set it. Then you get the error "Open: Failed in openOrCreateDatabase Cannot open the DB".

If you install and open the old Capacitor 4 app again you still can open the db. But no chance with the Capacitor 5 app.

**Expected behavior**
iOS DBs created with a previous major version of this plugin must be openable with Capacitor 5+.

**Desktop (please complete the following information):**

- OS: iOS 16.2

**Smartphone (please complete the following information):**
- Device: iPhone 14 Simulator

**Comment by mobilemarines** [comment]
To workaround this I have to delete (SQLiteDBConnection.delete()) and re-initialize the db with the prefix.
Instead of loosing app data it would be better to make UtilsSecret.checkEncryptionSecret less strict and allow an unset prefix like in the previous major release.

**Comment by jepiqueau** [comment]
@mobilemarines this will allow you to reopen the database correctly

**Comment by mobilemarines** [comment]
Thanks @jepiqueau, but what if I did not safe the passphrase because it was not needed yet? :)

**Comment by jepiqueau** [comment]
@mobilemarines i do not really understand.
To encrypt a database you need to set a passphrase from à suite long time already. So nothing change in moving to Capacitor 5. If as you said you did not set it means that you are always using the secret defined in the GlobalSQLite.swift file so look at the value and set this one following the  procedure setEncryptionSecret

**Comment by mobilemarines** [comment]
Sorry for the misunderstanding, @jepiqueau , the database initialization process we use is as follows:
1. check if a passphrase is already set with isSecretStored()
2. if not, generate a random password and set it with setEncryptionSecret(). So this is done once. This secret was not needed to be saved in another place yet because it was never asked again with the next app startup where step 2 is not needed anymore.
3. if isConnection() then retrieveConnection() else checkConnectionsConsistency() + createConnection() 
4. open()

So we set a secret and cannot use the default one from GlobalSQLite.swift but also did not safe our own secret because it was not needed (and would be insecure with no encrypted SharedPreferences available on Android via Capacitor yet).
Now, with Capacitor 5, we cannot restore the saved secret from the keychain because it's not allowed to use no prefix anymore which seems to be the only way to retrieve it because there is only setEncryptionSecret() and no getEncryptionSecret().

I hope this makes it clear.
A solution/workaround for this scenario would be nice.

**Comment by mobilemarines** [comment]
It has been quite a debugging odyssey and much trial and error but now I found a workaround to migrate a DB that should have been encrypted with the Capacitor 4 plugin but wasn't because the `iosKeychainPrefix` was missing and then trying to open that DB with the Capacitor 5 plugin having an `iosKeychainPrefix` set.

So the now working startup procedure is as follows:
> this.sqlitePlugin = CapacitorSQLite;
this.sqlite = new SQLiteConnection(this.sqlitePlugin);
const isSecretStored = !!(await this.sqlite.isSecretStored()).result;
if (!isSecretStored) {
  await this.sqlite.setEncryptionSecret("secret");
}
try {
  // this.dbConnection = await this.sqlite.createConnection(dbName, true, "secret", 1); // Not working
  // this.dbConnection = await this.sqlite.createConnection(dbName, false, "no-encryption", 1); // Not working
  const isDbUnencrypted = !!(await CapacitorSQLite.isDBExists({ database: dbName })).result; // needs open connection -> not available/possible on first run
} catch (error) {}
if (isUnencrypted) {
  // Encrypt unencrypted DB
  await this.sqlite.closeConnection(dbName); // Close concurring secret connection to setup encryption
  this.dbConnection = await this.sqlite.createConnection(dbName, true, "encryption", 1);
  await this.dbConnection.open(); // This encrypts the db
  await this.sqlite.closeConnection(dbName, false);
}
if ((await this.sqliteService.isConnection(dbName)).result) {
  this.dbConnection = await this.sqliteService.retrieveConnection(dbName);
} else {
  const openedConnections = (await this.sqliteService.checkConnectionsConsistency()).result;
  if (openedConnections) {
    console.info("Open database connections cleaned up.");
  }
  this.dbConnection = await this.sqliteService.createConnection(dbName, true, "secret", 1)
}
try {
  await this.dbConnection.open();
} catch (error) {
  // Fails on first attempt so try the whole procedure once more, then the unencrypted DB gets encrypted and the DB connection can be opened
}

But it has an issue I could not fix yet:
- The `CapacitorSQLite.isDBExists` command fails because there is no connection yet. No matter if I try to open an unencrypted  or encrypted connection (they fail, too). So I cannot check if the DB is encrypted or not and we have a chicken-and-egg-problem. But on the 2nd attempt the connection is available and thus I can check if the DB is not encrypted yet, which is the case, then I can encrypt it and it can be opened.

Is the startup procedure wrong then or is it a bug?
It is so hard to understand how to implement a DB startup that can handle migration.
These tests https://github.com/jepiqueau/angular-sqlite-app-starter/blob/master/src/app/test/testencryption/testencryption.page.ts were the only examples that helped me make encryption work at all but I'd really appreciate help or examples to make a robust DB startup that can handle all migration scenarios, including `getMigratableDbList` of old unencrypted Capacitor DBs.

So the most important open question is:
- How can be checked if a DB is encrypted or not in this scenario?

**Comment by jepiqueau** [comment]
@mobilemarines i do not know where is the problem. For me all these commands work fine and are usedin ionic7-angular-sqlite-app. I am bisy rewriting the electron part of the plugin which take all my free time. So i have no time to go in the detail of what your are doing

**Comment by mobilemarines** [comment]
No worries, @jepiqueau.
Thanks again and hopefully this thread can help someone else.
