### ISSUE TITLE
Can't save blob image in iOS

### ISSUE THREAD

**Issue by rattata2023** [capacitor-community/sqlite#431]
I have tested checked blob with 5.0.3-1  with android it is working fine but with iOS I am getting this error 
"errorMessage":"Query: Failed in selectSQL : Error: bindValues bind failed The operation couldn’t be completed. (CapacitorCommunitySqlite.UtilsSQLCipherError error 26.)
after some debug found that 
 if let value = value.unsafelyUnwrapped as? [UInt8] {
            let data: Data = Data(value)
            sqlite3_bind_blob(handle, Int32(idx), data.bytes,
                              Int32(data.bytes.count), SQLITETRANSIENT)
        }
code is not going under these lines for Blob images in iOS I have used same code that you told in SQLiteBlob.md file 
could you fix that as I am not that good in iOS can do it in android.

thanks

**Comment by jepiqueau** [comment]
@rattata2023 look at angular-sqlite-app-starter i added a testblobs page

**Comment by rattata2023** [comment]
@jepiqueau thanks working
