### ISSUE TITLE
An ability to load sqlite extensions

### ISSUE THREAD

**Issue by Azarattum** [capacitor-community/sqlite#433]
**Is your feature request related to a problem? Please describe.**
I need to load an external extension from a file into my SQLite database. Just using:
```ts
await db.execute(`
  SELECT load_extension('./path');
`);
```
Throws `{"errorMessage":"Execute: Failed in executeSQL: Error: execute failed rc: 1 message: not authorized","message":"Execute: Failed in executeSQL: Error: execute failed rc: 1 message: not authorized"}` on iOS (haven't tested on other platforms).

**Describe the solution you'd like**
I think you need to [`enable_load_extension`](https://www.sqlite.org/c3ref/enable_load_extension.html) in native code. It would be nice to have a wrapper function like:
```ts
await db.loadExtension("./path");
```
or at least a way to set `enable_load_extension`:
```ts
await db.enableLoadExtension(true);
await db.execute(`SELECT load_extension('./path')`);
await db.enableLoadExtension(false);
```

**Describe alternatives you've considered**
There is none as far as I know. Let me know if there are any workarounds with the current implementation.

**Additional context**
More context for `non authorised` error [here](https://github.com/TryGhost/node-sqlite3/issues/1123).

**Comment by jepiqueau** [comment]
@Azarattum can you give me an example of extension so i can use it for testing.

**Comment by Azarattum** [comment]
@jepiqueau I want to load [cr-sqlite](https://github.com/vlcn-io/cr-sqlite) extension which is a CRDT implementation for SQLite.

**Comment by jepiqueau** [comment]
@Azarattum  for which platform (s)

**Comment by Azarattum** [comment]
@jepiqueau I've mentioned before that I've tested on iOS. If you are asking about the extension, I think `darwin-aarch64` should work there.

**Comment by zbrongyaozb** [comment]
I also need it.
This is an example of loading an extension in Node.js
https://github.com/zbrongyaozb/node-sqlite-loadExtension.
The platform requires Electron, Android, and IOS. If the web can support it, it's best, but it's not mandatory

**Comment by jepiqueau** [comment]
@Azarattum , @zbrongyaozb Can you give me the path of the .so file  for ios you want to use on the [cr-sqlite](https://github.com/vlcn-io/cr-sqlite) i could not find it.

**Comment by jepiqueau** [comment]
@Azarattum @zbrongyaozb  i spent 2 full days on this without success  Xcode does not allows to create dynamic link libraries (.dylib) which are the ones used by sqlite3_load_extension. .dylib created for MacOs cannot also be read by SQLite iOS. the iOS static libraries created with Xcode cannot be read by sqlite3_load_extension.
So i will not pursue on this. 
SQLite extensions and user functions are then not planned.

**Comment by tantaman** [comment]
And here's an update with the extension statically linked to SQLite -- https://github.com/vlcn-io/cr-sqlite/pull/284

**Comment by tantaman** [comment]
I've done more digging on SQLite extensions w/ iOS

1. They need to be statically linked
2. You can compile the extension as its own static object file and link against it in xcode
3. Doing (2) allows users to use any sqlite build they like
4. Doing (2) requires users to invoke `sqlite3_auto_extension(sqlite3_extname_init);` at the start of their application
5. To support all the various targets, you need to cross compile the extension for each ios and macos and simulator target

I've done all this in my latest update here: https://github.com/vlcn-io/cr-sqlite/pull/284#issuecomment-1645798902

Next step is to publish an xcode template and/or an xcframework for the extension.

**Comment by tantaman** [comment]
The above approach should work for any sqlite extension and may require minimal to no changes to capacitor itself.

**Comment by tantaman** [comment]
I think I'll need to write a blog post because getting sqlite extensions working on iOS was a horrible pain but we have an xcode template project that works:

https://github.com/tantaman/xcode-starter

It calls a custom init function here:

https://github.com/tantaman/xcode-starter/blob/main/xcode-starter/xcode_starterApp.swift#L13

Which is defined here:

https://github.com/tantaman/xcode-starter/blob/main/xcode-starter/crsqlite-init.c

The SQLite extension you want to include needs to be compiled for each iOS target you're targeting & all simulator targets. Example of doing this for cr-sqlite:
https://github.com/vlcn-io/cr-sqlite/blob/a288be040cdf1d96fe9db15a90ed16d3f200b215/core/all-ios.sh

anyway @jepiqueau, hopefully that helps for getting a start on sqlite extensions in capacitor.

**Comment by AntiGuide** [comment]
The feature would be great in a project of mine. I want to use Spellfix1 which is a SQLite plugin. @jepiqueau Sounds like @tantaman 's work would help a lot if you are still interested in the feature.
