### ISSUE TITLE
CapacitorSQLitePlugin: the master key android-keystore://_androidx_security_master_key_ exists but is unusable

### ISSUE THREAD

**Issue by skrilax91** [capacitor-community/sqlite#437]
**Describe the bug**
The application crash and an error is displayed when the method createConnection is called internally

**Expected behavior**
The application should connect to the database

**Screenshots**
![image](https://github.com/capacitor-community/sqlite/assets/6585219/1a125e2f-aeb6-414b-a51c-ad13fbc20f99)

**Desktop (please complete the following information):**

- OS: Android
- Version 11

**Smartphone (please complete the following information):**

- Device: Rockchip RK3366 L Shape tablet
- OS: Android 11
- Browser chrome
- Version 

**Additional context**
The application is constructed with Nuxt 3, it work on samsung tablet on android 8 and on samsung SM-T515 - Android (11)

**Comment by jepiqueau** [comment]
@skrilax91 Is it happening in a new application or an old application that you are migrating?  I do not know Nuxt 3. it seems that it is device dependent. Are you using database encryption ? can you share your package.json file. Can you go in android studio with your device connected and go to device file explorer and go to data/data/YOUR_APPLICATION/shared_prefs and delete the file sqlite_encrypted_shared_prefs.xml and restart your app.

**Comment by skrilax91** [comment]
This is happening on an old application migrated to vue3 with nuxt3, I'm not using database encryption. i can't find my application file inside the file explorer.

this is my package.json :
`
{
    "name": "delyss",
    "version": "3.8.1",
    "private": true,
    "scripts": {
        "build": "nuxt build",
        "ionic:build": "npm run generate && npx cap sync",
        "ionic:serve": "npm run dev",
        "dev": "nuxt dev",
        "generate": "nuxt generate",
        "preview": "nuxt preview",
        "postinstall": "nuxt prepare"
    },
    "devDependencies": {
        "@bootstrap-vue-next/nuxt": "^0.0.5",
        "@capacitor/cli": "4.6.1",
        "@nuxtjs/i18n": "^8.0.0-beta.7",
        "@nuxtjs/ionic": "^0.8.1",
        "@types/node": "^18.11.18",
        "@vue/cli-service": "5.0.8",
        "autoprefixer": "^10.4.13",
        "bootstrap": "^5.2.3",
        "bootstrap-vue-next": "^0.8.0",
        "nuxt": "^3.6.1",
        "postcss": "^8.4.21",
        "prisma": "^4.9.0",
        "ts-node": "^10.9.1",
        "typescript": "^4.9.4",
        "vue-svg-loader": "^0.16.0",
        "vue-template-compiler": "^2.7.14"
    },
    "dependencies": {
        "@capacitor-community/sqlite": "^4.8.0",
        "@capacitor/android": "4.6.1",
        "@capacitor/app": "4.1.1",
        "@capacitor/core": "4.6.1",
        "@capacitor/device": "^4.1.0",
        "@capacitor/filesystem": "^4.1.4",
        "@capacitor/haptics": "4.1.0",
        "@capacitor/keyboard": "4.1.0",
        "@capacitor/splash-screen": "^4.2.0",
        "@capacitor/status-bar": "^4.1.1",
        "@hugotomazi/capacitor-navigation-bar": "^2.0.0",
        "@nuxt/test-utils": "^3.1.1",
        "@nuxt/types": "^2.15.8",
        "@nuxtjs/svg": "^0.4.0",
        "@pinia/nuxt": "^0.4.6",
        "@vue/compat": "^3.2.45",
        "@vueuse/motion": "^2.0.0-beta.27",
        "bootstrap-vue-3": "^0.5.1",
        "capacitor-blob-writer": "^1.1.9",
        "pinia": "^2.0.28",
        "qrcode.vue": "^3.3.3",
        "sass": "^1.57.1",
        "sass-loader": "^13.2.0",
        "vite-svg-loader": "^4.0.0",
        "vitest": "^0.32.0",
        "vue-i18n": "^9.3.0-beta.14-77e850b",
        "vue-router": "^4.1.6",
        "vue-sqlite-hook": "^3.0.3",
        "vue3-popper": "^1.5.0"
    },
    "overrides": {
        "vue": "latest"
    }
}
`

**Comment by jepiqueau** [comment]
@skrilax91 if you do not use database encryption it is normal that you did not find the file. So it is really specific to that device so i cannot really help you. You said that the same app migration works on other devices.

**Comment by jepiqueau** [comment]
@skrilax91 which version of Android is running on that device and which version of Android on other devices where rhe app works?

**Comment by skrilax91** [comment]
That device run Android 11, the same tablet type work on android 8.1. I tested on 2 samsung tablets, one on 8.1 that work and one on 11 that also work.
One more information, i use the plugin jepiqueau/vue-sqlite-hook for Vue implementation of sqlite.

**Comment by jepiqueau** [comment]
@skrilax91 I do not know if this problem still exist. May be you can try updating to
 `implementation "androidx.security:security-crypto:1.1.0-alpha06" ` in the build.gradle file of the capacitor-community/sqlite module. Otherwise it is too much related to the device. may be you can upgrade the device to android 12 or 13 and see if it is working. 
i will close the issue as there is nothing i can do to help
