### ISSUE TITLE
Connection already exists - race condition

### ISSUE THREAD

**Issue by biesbjerg** [capacitor-community/sqlite#438]
**Describe the bug**
I think I'm running into a race condition bug when trying to retrieve/create the same connection multiple times simultaneously.

**To Reproduce**

main.ts
```ts
import { SqliteStorageService } from "./services";

SqliteStorageService.getConnection();
SqliteStorageService.getConnection();
SqliteStorageService.getConnection();
SqliteStorageService.getConnection();
```

services.ts
```ts
import { CapacitorSQLite, SQLiteConnection } from "@capacitor-community/sqlite";

const DATABASE_NAME = "MwData";
const sqlite = new SQLiteConnection(CapacitorSQLite);

export async function getConnection() {
  // When HMR we need to make sure connections
  // are consistent between native layer and JS.
  // See https://github.com/capacitor-community/sqlite/issues/106
  const { result: isConsistent } = await sqlite.checkConnectionsConsistency();

  const { result: isConnected } = await sqlite.isConnection(DATABASE_NAME, false);
  if (isConsistent && isConnected) {
    return sqlite.retrieveConnection(DATABASE_NAME, false);
  }

  const connection = await sqlite.createConnection(DATABASE_NAME, false, "no-encryption", 1, false);
  await connection.open();

  return connection;
}
```

Console:
![image](https://github.com/capacitor-community/sqlite/assets/230182/8b925325-b7fe-4cc2-935f-4e5b7177baab)

As seen in screenshot, the last three `getConnection` calls throw errors, because at the time of checking if connection existed, it didn't, then all 4 calls will go ahead and create a connection, in which only one will succeed. 

**Expected behavior**
I expected to be able to get a connection of all calls. 

Do we need a new method, something like `retrieveOrCreateConnection(DATABASE_NAME)` to make it an atomic operation?

**Smartphone (please complete the following information):**

- Device: iPhone 14 Pro
- OS: 16.5
- Browser: Safari

**Additional context**
Above code reproduces the error, but in my app I'm not in control of when the calls happen, since I'm using Vue/Pinia with https://github.com/iendeavor/pinia-plugin-persistedstate-2 to persist stores, and they're automatically hydrated simultaneously at startup - one call per store.

**Comment by jepiqueau** [comment]
@biesbjerg The @capacitor-community/sqlite accepts only two simultaneously connections to a database one in READ/WRITE mode and one in READONLY mode.

**Comment by khromov** [comment]
Really appreciate this issue, I was having a tough time with Vite HMR losing the connection betewen HMR reloads but `checkConnectionsConsistency()` solved it for me.

Here is my code that attempts to initialize a connection.

```ts
let sqlite: SQLiteConnection | undefined = undefined;
let db: SQLiteDBConnection | undefined = undefined;

export async function maybeInitialize(): Promise<any> {
	if(!sqlite) {
		sqlite = new SQLiteConnection(CapacitorSQLite) 
	}

	try {
		await sqlite.checkConnectionsConsistency();
	} catch (e) {
		console.log('❌ Could not check connections consistency', e);
	}

	if(db && await db?.isDBOpen()) {
		console.log('⚠️ SQLite already initialized');
		return; 
	}

	// Try to retreive existing connection
	try {
		console.log('⚡ Trying to retrieve connection');
		db = await sqlite?.retrieveConnection('db', false);
		console.log('⚡ Retrieved connection', db);
	} catch (e) {
		console.log('Could not retrieve connection', e);
	}

	// If no connection exists, create a new one
	if(!db) {
		try {
			console.log('🚀 Initializing SQLite'); 
			db = await sqlite?.createConnection( 
				'db',
				false,
				'no-encryption',
				1,
				false
			); 

			try {
				await db?.open();
	
				console.log('🚀 SQLite initialized');
			} catch (e) {
				console.log('Could not connect to db', e);
			} 
		} catch (e) {
			console.log('Could not open db', e);
		}
	}
}
```
