### ISSUE TITLE
SQLITE not saved run browser

### ISSUE THREAD

**Issue by yuan8** [capacitor-community/sqlite#440]
**Describe the bug**
implemented with quasar capacitor user vue. i try implement same like ionic/ vue. 
on mobile device (.apk Capasitor) is well but on browser version every query after insert on database when i refresh my browser all is gone (back to zero).

**Expected behavior**
sory im newbe i think its only missing step on example used for browser. 
btw on example is only for build schema.  missing step to insert update delete.

**Screenshots**
![Screenshot 2023-07-11 at 08 20 30](https://github.com/capacitor-community/sqlite/assets/9335377/43dac57d-dc4d-4450-af79-86bb46485667)

After Refresh 

![Screenshot 2023-07-11 at 08 20 44](https://github.com/capacitor-community/sqlite/assets/9335377/6d506aa4-df39-40ca-bf2c-1cc9b78b64aa)

**Desktop (please complete the following information):**

- OS: Mac OS Venture
- Browser Chrome
- 114.0.5735.198 (Official Build) (arm64)

**Additional context**
that my code 
```

      async loadDB() {
          const db_name = "ehdw_" + this.user.nik;
         const platform = Capacitor.getPlatform();
       try {
          if (this.db) {
            this.db.close();
        }

        
        
        if (platform === "web") {
          customElements.define("jeep-sqlite", JeepSqlite);
          const jeepSqliteEl = document.createElement("jeep-sqlite");
          document.body.appendChild(jeepSqliteEl);
          await customElements.whenDefined("jeep-sqlite");
          await this.sqlite.initWebStore();
        }

        const ret = await this.sqlite.checkConnectionsConsistency();
        const isConn = (await this.sqlite.isConnection("ehdw_db_2", false))
          .result;
        if (ret.result && isConn) {
          this.db = await this.sqlite.retrieveConnection("ehdw_db_2", false);
        } else {
          this.db = await this.sqlite.createConnection(
            "ehdw_db_2",
            false,
            "no-encryption",
            2,
            false
          );
        }
        await this.db.open();
        const query = [
          `
        CREATE TABLE IF NOT EXISTS mapping_dusun (
          self_id INTEGER PRIMARY KEY NOT NULL,
          key_refrences TEXT,
          last_method TEXT,
          self_updated_at TEXT,
          last_check_exist TEXT,

          id INTEGER,
          trans_id TEXT NOT NULL,
          name TEXT NOT NULL,
          people INTEGER NOT NULL,
          kpm_id INTEGER,
          desa_id INTEGER,
          user_created INTEGER,
          user_created_model,
          created_at TEXT,
          updated_at TEXT,
          server_message TEXT

        );
        `,
          `
        CREATE TABLE IF NOT EXISTS sink_table (
          uuid TEXT PRIMARY KEY NOT NULL,
          method TEXT NOT NULL,
          context TEXT NOT NULL,
          data TEXT,
          queue_updated TEXT
        );

        `,
        ];
        var i_migrate = 0;

        while (i_migrate < query.length) {
          await this.db.execute(query[i_migrate]);
          i_migrate++;
        }
      } catch (e) {
        console.error(e);
      }
    },


```

transaction code 

```
 var query = `
          insert into mapping_dusun
          (id,trans_id,name,people,desa_id,kpm_id,user_created,user_created_model,created_at,updated_at,key_refrences,last_method) VALUES
          (NULL,'${trans_id}','${data.name}',${data.people},'${this.auth.user.desa_id}',${this.auth.user.id},${this.auth.user.id},'App\Models\UserKPM','${now}','${now}','${sink_id}','create');
          `;
          await this.db.query(query);
```

**Comment by jepiqueau** [comment]
@yuan8 when using in a browser you have to use the saveToStore from time to time  it is automatically save to store when you close the connection. You might also use the autosave property of the jeep-sqlite component meaning that everything will be save for each transaction this can be time consuming when your database size is large.

**Comment by yuan8** [comment]
ok. that solved. thank @jepiqueau

**Comment by Sadi-1992** [comment]
Has anyone else had the experience that saveToStore increases the memory used with each call, even if there were no changes to the DB? It seems to me that it does not overwrite the localForage, but simply adds the DB again and again.
