### ISSUE TITLE
Error: `"CapacitorSQLite.createConnection()"` is not implemented on android

### ISSUE THREAD

**Issue by AQUASINE** [capacitor-community/sqlite#441]
Hello!
I have integrated the sqlite plugin into my Vue application. I have set it up similarly to the vue-sqlite-app example project, and it works without issue on the web version. I am also able to build to Android without any errors. However, upon running the Android app, attempting to call createConnection() results in the following error:
`Error: "CapacitorSQLite.createConnection()" is not implemented on android`

This also occurs for any other plugin method defined in the CapacitorSQLitePlugin.java file (e.g. checkConnectionsConsistency()), but does not occur for other methods such as isConnection(). So, it seems this is an issue with something within the Android project structure, but I am unsure what exactly might be causing it. I have been digging through closed issues to see if anything similar has been reported, but I have not been able to find anything that has helped. In the case that it is related to dependency versions, here is a selection of my `package.json` dependencies block:

```
    "@capacitor-community/sqlite": "^5.0.5-2",
    "@capacitor/android": "^5.0.0",
    "@capacitor/app": "^5.0.0",
    "@capacitor/core": "^5.0.0",
    "@capacitor/ios": "^5.0.0",
    "@jeepq/capacitor": "^0.0.4-1",
    "jeep-sqlite": "^2.3.7",
    "sql.js": "^1.8.0",
```

I can provide any other information that might be helpful. Thanks!

**Comment by jepiqueau** [comment]
@AQUASINE Can you provide your code through github. i do not know why you are using @jeepq/capacitor

**Comment by AQUASINE** [comment]
Didn't even occur to me that I wasn't using @jeepq/capacitor for anything, not sure why it was even there. Removing that from package.json resolved the issue. Thank you!
