### ISSUE TITLE
Add support of math functions

### ISSUE THREAD

**Issue by quolpr** [capacitor-community/sqlite#446]
We recently discovered that at least iOS version (not sure about android) misses math functions https://www.sqlite.org/lang_mathfunc.html . We tried to use `SQRT` function, but SQLite returns "no such function: SQRT".

The example query is: `SELECT SQRT(4)`

**Comment by jepiqueau** [comment]
@quolpr can you try to add -DSQLITE_ENABLE_MATH_FUNCTIONS in the OTHER_CFLAGS for the file SQLCipher.debug and SQLCipher.release in the Pods/SQLCipher/Support Files rebuild and tell me if it works

**Comment by jepiqueau** [comment]
@quolpr it is not supported by android.sqlite so i will close it as not planned
