### ISSUE TITLE
Typeorm migratoins from CLI always fail due to jeep-sqlite check

### ISSUE THREAD

**Issue by LucEnden** [capacitor-community/sqlite#450]
**Describe the bug**
Running typeorm migrations from the CLI always quits prematurely with the following error.

EDIT: only tested in Angular

```
$ npx typeorm-ts-node-esm migration:run -d src/app/data-source.ts
```

```
Error during migration run:
Error: The jeep-sqlite element is not present in the DOM! Please check the @capacitor-community/sqlite documentation for instructions regarding the web platform.
    at CapacitorSQLiteWeb.ensureJeepSqliteIsAvailable (<path-to-project>\node_modules\@capacitor-community\sqlite\dist\esm\web.js:374:19)
    at CapacitorSQLiteWeb.createConnection (<path-to-project>\node_modules\@capacitor-community\sqlite\dist\esm\web.js:71:14)
    at <path-to-project>\node_modules\@capacitor\core\build\runtime.js:95:35
    at async SQLiteConnection.createConnection (<path-to-project>\node_modules\@capacitor-community\sqlite\dist\esm\definitions.js:128:13)
    at async CapacitorDriver.createDatabaseConnection (<path-to-project>\node_modules\typeorm\src\driver\capacitor\CapacitorDriver.ts:73:28)
    at async CapacitorDriver.connect (<path-to-project>\node_modules\typeorm\src\driver\capacitor\CapacitorDriver.ts:36:9)
    at async DataSource.initialize (<path-to-project>\node_modules\src\data-source\DataSource.ts:249:9)
    at async Object.handler (<path-to-project>\node_modules\src\commands\MigrationRunCommand.ts:52:13)
```

After diving into the source it seems that the jeep-sqlite check always happens and thus this error will always be thrown if the migrations are ran from the command line. Ive tried initializing the `DataSource` programmatically in a web environment, following the [web usage documentation](https://github.com/capacitor-community/sqlite/blob/master/docs/Web-Usage.md) and then the error does not appear. However, I was expecting to be able to perform migrations from the CLI regardless of the platform I'm targeting. 

Note: I am neither a typeorm expert nor an Ionic/Capacitor expert (this is my first time building a native PWA). If I am missing something please let me know.

**To Reproduce**

1. Start an empty ionic project using ```$ ionic start test blank --capacitor --type=angular``` (there should be 2 prompts, one to pick modules and sign in using ionic account. Pick modules and dont sign in)
2. Copy/paste the [capacitor.config.ts from the README](https://github.com/capacitor-community/sqlite/tree/master)
3. Update ts-node (required for typeorm) ```$ npm install ts-node@latest```
4. Install packages: ```$ npm install --save @capacitor-community/sqlite typeorm```
5. Set project type in `package.json` to module:
```
...
    "type": "module",
...
```
6. Create a file in src/app called `data-source.ts` and copy the code bellow into it (specified in additional context.
8. Run the migrations:create command; ```$ npx typeorm-ts-node-esm migration:create src/app/migrations/initial-migration```
9. Run the migrations:run command; ```$ npx typeorm-ts-node-esm migration:run -d src/app/data-source.ts```
10. The error should be displayed.

**Expected behavior**
The jeep-sqlite check should not happen when running the migrations from the CLI, as jeep-sqlite is platform depended and CLI migrations are not.

**Screenshots**
N/A

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Firefox
- Version: 115.0.3 (64-bit)

**Smartphone (please complete the following information):**

- Device: N/A
- OS: N/A
- Browser N/A
- Version N/A

**Additional context**

*The data source setup ( src/app/data-source.ts ):*
```typescript
import { isDevMode } from "@angular/core";
import { CapacitorSQLite, SQLiteConnection } from '@capacitor-community/sqlite';
import { DataSource, DataSourceOptions } from "typeorm";

// Create a SQLite Connection Wrapper
const sqliteConnection = new SQLiteConnection(CapacitorSQLite);

// Create the TypeORM connection
// For more information see https://typeorm.io/data-source#creating-a-new-datasource
const options: DataSourceOptions = {
    name: 'securityDbConnection',
    type: 'capacitor',
    driver: sqliteConnection,
    database: 'security',
    mode: 'encryption',
    entities: [
        './dtos/**/*.ts' // DTO stands for 'data transfor object' and is essentially the same as a database entity
    ],
    migrations: [
        './migrations/**/*.ts'
    ],
    subscribers: [],
    logging: isDevMode() ? [ 'query', 'schema', 'error' ] : [ 'error', 'schema' ],
    synchronize: false,
    migrationsRun: false,
}

// Expose the DataSource as default export, which is required to run migrations from the CLI
const dbSource = new DataSource(options);
export default dbSource;
```

*The expected result of the package.json after following the reproduction steps:*
```json
{
    "name": "test",
    "version": "0.0.1",
    "author": "Ionic Framework",
    "homepage": "https://ionicframework.com/",
    "scripts": {
        "ng": "ng",
        "start": "ng serve",
        "build": "ng build",
        "watch": "ng build --watch --configuration development",
        "test": "ng test",
        "lint": "ng lint"
    },
    "private": true,
    "type": "module",
    "dependencies": {
        "@angular/animations": "^16.0.0",
        "@angular/common": "^16.0.0",
        "@angular/compiler": "^16.0.0",
        "@angular/core": "^16.0.0",
        "@angular/forms": "^16.0.0",
        "@angular/platform-browser": "^16.0.0",
        "@angular/platform-browser-dynamic": "^16.0.0",
        "@angular/router": "^16.0.0",
        "@capacitor-community/sqlite": "^5.0.6",
        "@capacitor/app": "5.0.6",
        "@capacitor/core": "5.2.2",
        "@capacitor/haptics": "5.0.6",
        "@capacitor/keyboard": "5.0.6",
        "@capacitor/status-bar": "5.0.6",
        "@ionic/angular": "^7.0.0",
        "ionicons": "^7.0.0",
        "rxjs": "~7.8.0",
        "tslib": "^2.3.0",
        "typeorm": "^0.3.17",
        "zone.js": "~0.13.0"
    },
    "devDependencies": {
        "@angular-devkit/build-angular": "^16.0.0",
        "@angular-eslint/builder": "^16.0.0",
        "@angular-eslint/eslint-plugin": "^16.0.0",
        "@angular-eslint/eslint-plugin-template": "^16.0.0",
        "@angular-eslint/schematics": "^16.0.0",
        "@angular-eslint/template-parser": "^16.0.0",
        "@angular/cli": "^16.0.0",
        "@angular/compiler": "^16.0.0",
        "@angular/compiler-cli": "^16.0.0",
        "@angular/language-service": "^16.0.0",
        "@capacitor/cli": "5.2.2",
        "@ionic/angular-toolkit": "^9.0.0",
        "@types/jasmine": "~4.3.0",
        "@types/node": "^12.11.1",
        "@typescript-eslint/eslint-plugin": "5.3.0",
        "@typescript-eslint/parser": "5.3.0",
        "eslint": "^7.26.0",
        "eslint-plugin-import": "2.22.1",
        "eslint-plugin-jsdoc": "30.7.6",
        "eslint-plugin-prefer-arrow": "1.2.2",
        "jasmine-core": "~4.6.0",
        "jasmine-spec-reporter": "~5.0.0",
        "karma": "~6.4.0",
        "karma-chrome-launcher": "~3.2.0",
        "karma-coverage": "~2.2.0",
        "karma-coverage-istanbul-reporter": "~3.0.2",
        "karma-jasmine": "~5.1.0",
        "karma-jasmine-html-reporter": "~2.0.0",
        "ts-node": "^10.9.1",
        "typescript": "~5.0.2"
    },
    "description": "An Ionic project"
}
```

**Comment by jepiqueau** [comment]
@LucEnden thanks for reporting this. There is nothing we can do about this except to rewrite the web plugin without using jeep-sqlite web component. This method was used to reduce the size of the plugin when used with iOS or Android. At that time the driver for typeORM was not existing. In the example of typeorm applications i gave i run the migrations inside the application not with the typeorm cli. Sorry it is not planned to integrate the jeep-sqlite inside the web part of the plugin

**Comment by LucEnden** [comment]
Thanks for clarifying. I've indeed opted for the same strategy of running the migrations on startup. Perhaps ik create a pull request in the future and fix it myself. For now the on boot migration approach seems appropriate in my use case.

**Comment by jepiqueau** [comment]
@LucEnden i develop a specific [capacitor-typeorm-cli ](https://www.npmjs.com/package/capacitor-typeorm-cli). If you could test it and revert to me
