### ISSUE TITLE
SQL92 compatibility issue

### ISSUE THREAD

**Issue by vorujack** [capacitor-community/sqlite#451]
**Describe the bug**
As described in [this link](https://github.com/capacitor-community/sqlite/blob/8593070116da2bbe8eb4ffc34c2685671553d1c6/docs/ElectronBetterSQLite3.md?plain=1#L22-L23), double quotes can be used for statements. However, the code mentioned in [this link](https://github.com/capacitor-community/sqlite/blob/8593070116da2bbe8eb4ffc34c2685671553d1c6/electron/src/electron-utils/utilsSQLite.ts#L1056-L1058) replaces all double quotes with single quotes.

**Expected behavior**
When we call this query, it should return incorrect data:

`SELECT * FROM table1 WHERE "field1"='value';`

**Desktop (please complete the following information):**
- OS: [e.g. MacOSX 13.4.1]
- Browser: [e.g. Chrome]
- Version: [e.g. 5.0.6]

@jepiqueau

**Comment by vorujack** [comment]
@jepiqueau

**Comment by michaelwolz** [comment]
I encountered the exact same error today too. This is actually causing trouble in conjunction with TypeORM. When using the `synchronize: true` option in the TypeORM DataSource it will try to get existing tables from the schema table (`sqlite_master`). See: https://github.com/typeorm/typeorm/blob/ff6e8751d98dfe9999ee21906cca7d20b1c6b15d/src/driver/sqlite-abstract/AbstractSqliteQueryRunner.ts#L1321-L1323

However, this will lead to an empty result set even though the query itself seems to be perfectly fine. When removing the linked line by @vorujack in the `utilsSQLite.ts` (`sql.replaceAll('"', "'");`) everything works out fine.  Though, I am not quite sure about any side-effects this might cause with other queries which I don't have in mind 🫤.

Is anybody aware of why the replacement is done in the first place :thinking:? In my opinion this will always lead to converting an identifier into a string laterals which is probably not desired.

**Comment by jepiqueau** [comment]
@michaelwolz @vorujack the replace command was done to make better_sqlite3 working as it dies not accept values with "" on a sql statement  the error is that it must not replace the "" for names of field i will have to revisit that. To have it working quickly do not use "" around your field names as they are not required.

**Comment by michaelwolz** [comment]
@jepiqueau thanks for the quick answer :) Ok, I understand. So you mean it does not accept `"` for string laterals but for identifiers, right? As far as I remember correctly this was a quirk of sqlite in general that it accepted `"` for strings and for identifiers which causes confusion.

Hm, yes I'd totally do this if I could but since the queries are built by typeORM which always surrounds identifiers with (most often unnecessary) double quotes this is currently hard to achieve. I'll also think about a solution here.

**Comment by vorujack** [comment]
> @michaelwolz @vorujack the replace command was done to make better_sqlite3 working as it dies not accept values with "" on a sql statement the error is that it must not replace the "" for names of field i will have to revisit that. To have it working quickly do not use "" around your field names as they are not required.

Thats right. But when we using typeORM it added "" around field names. 
I apply a patch on installed package and remove mentioned three lines and it works. But no idea about side effects.

**Comment by jepiqueau** [comment]
@michaelwolz @vorujack @Guiqft  this has been fix in 5.0.7 a new parameter isSQL92 has been added to the methods execute, executeSet, run and query. 
- setting it to true will assume that your statement is SQL92 compliant so the statement is used as is. 
- setting it to false will go to the converter process (time consuming)

i encourage all of you for new app to use SQL92 compliant statements.

**Comment by vorujack** [comment]
@jepiqueau Thanks a lot
