### ISSUE TITLE
jeep-sqlite element is not present in the DOM!

### ISSUE THREAD

**Issue by jahanviadaptit** [capacitor-community/sqlite#453]
The jeep-sqlite element is not present in the DOM! Please check the @capacitor-community/sqlite documentation for instructions regarding the web platform.
Error: The jeep-sqlite element is not present in the DOM! Please check the @capacitor-community/sqlite documentation for instructions regarding the web platform.

getting this error while testing ionic with angular project on web. not able to insert/update data in database

**Comment by jepiqueau** [comment]
@jahanviadaptit can you share your code. Have you had a look to the links for ionic/angular apps provided in the readme

**Comment by jahanviadaptit** [comment]
this has started working after completely following to this
