### ISSUE TITLE
cleanStatement affects the query behavior

### ISSUE THREAD

**Issue by Guiqft** [capacitor-community/sqlite#455]
**Describe the bug**
Trying to use the recent version of the plugin that uses `better-sqlite3-multiple-ciphers` gives me a unexpected behavior on `UtilsSQLite.queryAll` function. 

Before the `cleanStatement` call, my query is:
```sql
SELECT * FROM "sqlite_master" WHERE "type" = 'table' AND "name" = 'migrations'
```
but the function replaces `"` with `'`, resulting on:
```sql
SELECT * FROM 'sqlite_master' WHERE 'type' = 'table' AND 'name' = 'migrations'
```
This results on an unexpect behavior, since the "cleaned" query returns nothing on my db, while the first returns the correct record of the table `migrations`. 

**Expected behavior**
I expect that the `cleanStatement` function doesn't affect the result of the query. 

**Additional context**
- `sqlite_version()`: `3.41.0`

**Comment by Guiqft** [comment]
Duplicated of #451. Sorry for that.

**Comment by jepiqueau** [comment]
@Guiqft i will come soon with a fix i am in final testing
