### ISSUE TITLE
ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'query')

### ISSUE THREAD

**Issue by Rose-Miller-web-dev** [capacitor-community/sqlite#458]
**Describe the bug**
Hi. I'm trying to use capacitor-community/sqlite in my ionic app and applying CRUD operations. I have implemented all the methods and the service but keep getting this error. I found the line of code that causes this in tab2 addUser method              -I've marked it with a comment-

**To Reproduce**

**Expected behavior**

**Screenshots**

the component :
import { CommonModule } from '@angular/common';
import { Component, effect } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { IonicModule } from '@ionic/angular';
import { StorageService, User } from '../storage.service';

@Component({
  selector: 'app-tab2',
  templateUrl: 'tab2.page.html',
  styleUrls: ['tab2.page.scss'],
})

export class Tab2Page {
  
  newUserName = ''
  users = this.storage.getUsers()

  constructor(private storage: StorageService) {
    // effect(() => {
    //   console.log('USERS CHANGED', this.users)
    // })
  }

  async createUser() {
    console.log(this.newUserName ,' added')
    await this.storage.addUser(this.newUserName)
    console.log(this.newUserName ,' added2')
    this.newUserName = ''
  }

  updateUser(user: User) {
    const active = user.active ? 1 : 0
    this.storage.updateUserById(user.id.toString(), active)
    console.log("updated")
  }

  deleteUser(user: User) {
    this.storage.deleteUserById(user.id.toString())
  }
}

the HTML code:
<style>

</style>

<ion-header>
  <ion-toolbar>
    <ion-title>
      Tab Two
    </ion-title>
  </ion-toolbar>
</ion-header>

<ion-content>

  <ion-row>
    <ion-col size="9">
      <ion-item>
        <ion-input
        label="Name" labelPlacement="stacked" placeholder="Rose Miller" [(ngModel)]="newUserName"
        >
        </ion-input>
      </ion-item>
    </ion-col>

    <ion-col size="3">
      <ion-button
      (click)="createUser()" expand="block" fill="outline">
        <ion-icon name="add" slot="icon-only"></ion-icon>
      </ion-button>
    </ion-col>
  </ion-row>

  <ion-item *ngFor="let user of users">
    <ion-checkbox
    aria-label="Label"
    slot="start"
    [(ngModel)]="user.active" 
    (ionChange)="updateUser(user)" >
    </ion-checkbox>

    <ion-label>
      {{ user }}
    </ion-label>

    <ion-button slot="end" (click)="deleteUser(user)" fill="clear" color="danger">
      <ion-icon name="trash" slot="icon-only"></ion-icon>
    </ion-button>
  </ion-item> 

</ion-content>

<router-outlet></router-outlet>

my storage.service.ts:

import { Injectable, signal, WritableSignal } from '@angular/core';
import { CapacitorSQLite, SQLiteConnection, SQLiteDBConnection } from '@capacitor-community/sqlite';

const DB_USERS = 'myuserdb'

export interface User {
  id: number
  name: string
  active: number
}

@Injectable({
  providedIn: 'root'
})

export class StorageService {
  private sqlite: SQLiteConnection = new SQLiteConnection(CapacitorSQLite)
  private db!: SQLiteDBConnection
  private users: WritableSignal<User[]> = signal<User[]>([])
  constructor() { 

  }

  async initializePlugin() {
    this.db = await this.sqlite.createConnection(
      DB_USERS,
      false,
      'no-encryption',
      1,
      false
    )

    await this.db.open()

    const schema = `CREATE TABLE IF NOT EXISTS users(
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      name TEXT NOT NULL,
      active INTEGER DEFAULT 1
    );`

    await this.db.execute(schema)
    this.loadUsers()
    return true
  }

  getUsers() {
    return this.users
  }

  async loadUsers() {
    const result = await this.db.query('SELECT * FROM users;')
    this.users.set(result.values || [])
  }

  async addUser(name: string) {
    console.log(' added')
    const query = `INSERT INTO users (name) VALUES ('${name}')`;
    const result = await this.db.query(query)  //THIS LINE DOES NOT WORK
    console.log(' added')
    this.loadUsers()
    
    return result
  }

  async updateUserById(id: string, active: number) {
    const query = `UPDATE users SET active=${active} WHERE id=${id}`
    const result = await this.db.query(query)

    this.loadUsers()
    return result
  }

  async deleteUserById(id: string) {
    const query = `DELETE FROM users WHERE id=${id}`
    const result = await this.db.query(query)

    this.loadUsers()
    return result
  }
}

app.component.ts:
import { Component } from '@angular/core'
import { SplashScreen } from '@capacitor/splash-screen'
import { IonicModule, Platform } from '@ionic/angular'

import { Network, ConnectionStatus } from '@capacitor/network'
import { StatusBar, Style } from '@capacitor/status-bar'
import { StorageService } from './storage.service'
import { FormsModule } from '@angular/forms'
import { CommonModule } from '@angular/common'

@Component({
  selector: 'app-root',
  templateUrl: 'app.component.html',
  // standalone: true,
  // imports: [IonicModule, FormsModule, CommonModule]
})

export class AppComponent {

  constructor(private storage: StorageService) {
    this.initApp()
  }

  async initApp() {
    await this.storage.initializePlugin()
    SplashScreen.hide()
  }
 
}

and package.json:
{
  "name": "polyonic",
  "productName": "Polyonic App",
  "description": "An Ionic project",
  "version": "3.0.6",
  "author": {
    "name": "Your Name",
    "email": "email@your-email.com",
    "url": "http://yourwebsite.com"
  },
  "repository": "https://github.com/paulsutherland/polyonic",
  "copyright": "© 2018, Your Name",
  "private": true,
  "main": "electron.js",
  "scripts": {
    "build:electron": "ng build --base-href ./",
    "build:electron:dev": "npm run build:electron -- -c dev",
    "build:electron:prod": "npm run build:electron -- -c production",
    "electron:dev": "export NODE_ENV=development || set NODE_ENV=development && npm-run-all -p ng:serve electron:serve",
    "electron:dev:debug": "npm-run-all -p ng:serve electron:serve:debug",
    "electron:dev:debug-live": "npm-run-all -p ng:serve electron:serve:debug-live",
    "electron:serve": "wait-on http-get://localhost:4200/ && run-electron . --serve",
    "electron:serve:debug": "wait-on http-get://localhost:4200/ && run-electron --inspect-brk=9229 . --serve",
    "electron:serve:debug-live": "wait-on http-get://localhost:4200/ && nodemon --watch electron.js --exec run-electron --inspect-brk=9229 . --serve",
    "electron:local": "npm run build:electron:prod && run-electron .",
    "electron:linux": "npm run build:electron:prod && npx electron-builder build --linux",
    "electron:windows": "npm run build:electron:prod && npx electron-builder build --windows",
    "electron:mac": "npm run build:electron:prod && npx electron-builder build --mac",
    "ionic": "npm run ng:serve:web",
    "emulate:ios-dev": "ionic cordova emulate ios --l",
    "run:ios-dev": "ionic cordova run ios --l --device",
    "emulate:ios": "ionic cordova emulate ios",
    "run:ios": "ionic cordova run ios --device",
    "release:ios": "ionic cordova build ios --configuration production --release",
    "emulate:android-dev": "ionic cordova emulate android --l",
    "run:android-dev": "ionic cordova run android --device --l",
    "emulate:android": "ionic cordova emulate android",
    "run:android": "ionic cordova run android --device",
    "release:android": "ionic cordova build android --configuration production --release ",
    "ng": "ng",
    "ng:serve": "ng serve",
    "ng:serve:web": "ng serve -o",
    "test": "ng test",
    "e2e": "ng e2e",
    "xcode": "open -a Xcode platforms/ios/",
    "postinstall": "patch-package"
  },
  "dependencies": {
    "@angular-devkit/architect": "^0.1602.0",
    "@angular-devkit/core": "^16.2.0",
    "@angular-devkit/schematics": "^16.2.0",
    "@angular/common": "16.2.0",
    "@angular/core": "16.2.0",
    "@angular/forms": "16.2.0",
    "@angular/platform-browser": "16.2.0",
    "@angular/platform-browser-dynamic": "16.2.0",
    "@angular/router": "16.2.0",
    "@capacitor-community/sqlite": "^5.0.7-2",
    "@capacitor/android": "^5.2.3",
    "@capacitor/cli": "^5.2.3",
    "@capacitor/core": "^5.2.3",
    "@capacitor/device": "^5.0.6",
    "@capacitor/ios": "^5.2.3",
    "@capacitor/keyboard": "^5.0.6",
    "@capacitor/network": "^5.0.6",
    "@capacitor/splash-screen": "^5.0.6",
    "@capacitor/status-bar": "^5.0.6",
    "@ionic/angular": "^7.2.3",
    "@ionic/storage": "^4.0.0",
    "@ionic/storage-angular": "^4.0.0",
    "@types/ws": "^8.5.4",
    "cordova": "^12.0.0",
    "cordova-plugin-ionic-webview": "^5.0.0",
    "core-js": "3.25.4",
    "localforage-cordovasqlitedriver": "^1.8.0",
    "ngx-electron": "^2.2.0",
    "patch-package": "^8.0.0",
    "polyonic-secure-pouch": "1.0.7",
    "run-electron": "1.0.0",
    "rxjs": "7.5.0",
    "zone.js": "~0.13.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^16.2.0",
    "@angular/cli": "^16.2.0",
    "@angular/compiler": "16.2.0",
    "@angular/compiler-cli": "16.2.0",
    "@angular/language-service": "16.2.0",
    "@ionic/angular-toolkit": "^10.0.0",
    "@types/jasmine": "3.6.7",
    "@types/jasminewd2": "2.0.8",
    "@types/node": "14.14.35",
    "codelyzer": "6.0.1",
    "electron": "^25.5.0",
    "electron-builder": "22.10.5",
    "husky": "5.1.3",
    "jasmine-core": "3.7.1",
    "jasmine-spec-reporter": "6.0.0",
    "karma": "6.4.2",
    "karma-chrome-launcher": "3.1.0",
    "karma-coverage-istanbul-reporter": "3.0.3",
    "karma-jasmine": "4.0.1",
    "karma-jasmine-html-reporter": "1.5.4",
    "nodemon": "^2.0.7",
    "npm-run-all": "4.1.5",
    "ts-node": "9.1.1",
    "typescript": "^5.1.6",
    "wait-on": "5.3.0"
  },
  "cordova": {
    "plugins": {
      "cordova-plugin-statusbar": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-webview": {},
      "cordova-plugin-ionic-keyboard": {},
      "cordova-plugin-androidx-adapter": {}
    },
    "platforms": []
  }
}

**Desktop (please complete the following information):**

- OS: linux
- Browser: Chrome

**Additional context**
I'll be thankful if someone helps me with this

**Comment by jepiqueau** [comment]
@Rose-Miller-web-dev thanks for using the plugin the method to write on the database are exexute, executeSet and run. The method query is used olny for reading to the database. Look at the code example and application provided
