### ISSUE TITLE
Error during app initialization: Error: The jeep-sqlite element is not present in the DOM! Please check the @capacitor-community/sqlite documentation for instructions regarding the web platform.

### ISSUE THREAD

**Issue by Rose-Miller-web-dev** [capacitor-community/sqlite#459]
**Describe the bug**
Hi, I'm trying to setup Capactor sqlite on my Angular ionic electron app but there is an error while the app is working on web:
Error during app initialization: Error: The jeep-sqlite element is not present in the DOM! Please check the @capacitor-community/sqlite documentation for instructions regarding the web platform.
The error stays still even after adding jeep-sqlite tag to my app.component.html and I have no idea what else to do!

app.component.html:

<jeep-sqlite *ngIf="isWeb" />

<ion-app>
  <app-dbtest></app-dbtest>
  <jeep-sqlite *ngIf="isWeb" />
</ion-app>

app.component.ts:

export class AppComponent {

  newUserName = ''
  users = this.storage.getUsers()
  public JeepSqliteElement: any
  public isWeb: boolean = false;
  private initPlugin: boolean;

  constructor(private storage: StorageService, private platform: Platform) {
    //customElements.define("jeep-sqlite", this.JeepSqliteElement)
    this.initApp()
    // this.loadProducts()
    
  }

  async initApp() {
     
    this.platform.ready().then(async () => {
      this.storage.initializePlugin().then(async (ret) => {
        this.initPlugin = ret;
        if( this.storage.platform === "web") {
          this.isWeb = true;
          await customElements.whenDefined('jeep-sqlite');
          const jeepSqliteEl = document.querySelector('jeep-sqlite');
          if(jeepSqliteEl != null) {
            await this.storage.initWebStore();
            console.log(`>>>> isStoreOpen ${await jeepSqliteEl.isStoreOpen()}`);
          } else {
            console.log('>>>> jeepSqliteEl is null');
          }
        }

        console.log(`>>>> in App  this.initPlugin ${this.initPlugin}`);
      });
    });
  
    await this.storage.initializePlugin()
    SplashScreen.hide()
  }

  loadProducts() {
    this.users = this.storage.getUsers()
  }

  async createUser() {
    console.log(this.newUserName ,' added')
    await this.storage.addUser(this.newUserName)
    console.log(this.newUserName ,' added2')
    this.newUserName = ''
    console.log(this.users, '#users')
  }

  updateUser(user: User) {
    const active = user.active ? 1 : 0
    this.storage.updateUserById(user.id.toString(), active)
    console.log("updated")
    console.log(this.users, '#users')
  }

  deleteUser(user: User) {
    this.storage.deleteUserById(user.id.toString())
  }
 
}

app.module.ts:

@NgModule({
    declarations: [
        AppComponent,
        DbtestComponent,
    ],

    imports: [
        BrowserModule,
        IonicModule.forRoot(), 
        AppRoutingModule,
        HttpClientModule,
        FormsModule,
    ],

    providers: [
        StorageService,
        {
          provide: RouteReuseStrategy,
          useClass: IonicRouteStrategy,
        }
    ],

    bootstrap: [
        AppComponent,
    ],
    
    schemas: [CUSTOM_ELEMENTS_SCHEMA],
})

debtest.component.html:
<ion-content>

  <ion-row>
    <ion-col size="9">
      <ion-item>
        <ion-input
        label="Name" labelPlacement="stacked" placeholder="Rose Miller" [(ngModel)]="newUserName"
        >
        </ion-input>
      </ion-item>
    </ion-col>

    <ion-col size="3">
      <ion-button
      (click)="createUser()" expand="block" fill="outline">
        <ion-icon name="add" slot="icon-only"></ion-icon>
      </ion-button>
    </ion-col>
  </ion-row>

  <ion-item *ngFor="let user of users()">
    <ion-checkbox
    aria-label="Label"
    slot="start"
    [(ngModel)]="user.active" 
    (ionChange)="updateUser(user)" >
    </ion-checkbox>

    <ion-label>
      {{ user }}
    </ion-label>

    <ion-button slot="end" (click)="deleteUser(user)" fill="clear" color="danger">
      <ion-icon name="trash" slot="icon-only"></ion-icon>
    </ion-button>
  </ion-item> 

</ion-content>

dbtest.component.ts:
export class DbtestComponent  implements OnInit {

  ngOnInit() {}

  newUserName = ''
  users = this.storage.getUsers()

  constructor(private storage: StorageService) {
    // effect(() => {
    //   console.log('USERS CHANGED', this.users)
    // })

    this.loadProducts()
  }

  loadProducts() {
    this.users = this.storage.getUsers()
  }

  async createUser() {
    console.log(this.newUserName ,' added')
    await this.storage.addUser(this.newUserName)
    console.log(this.newUserName ,' added2')
    this.newUserName = ''
    console.log(this.users, '#users')
  }

  updateUser(user: User) {
    const active = user.active ? 1 : 0
    this.storage.updateUserById(user.id.toString(), active)
    console.log("updated")
    console.log(this.users, '#users')
  }

  deleteUser(user: User) {
    this.storage.deleteUserById(user.id.toString())
  }
}

and last but not least package.json:
{
  "name": "polyonic",
  "productName": "Polyonic App",
  "description": "An Ionic project",
  "version": "3.0.6",
  "author": {
    "name": "Your Name",
    "email": "email@your-email.com",
    "url": "http://yourwebsite.com"
  },
  "repository": "https://github.com/paulsutherland/polyonic",
  "copyright": "© 2018, Your Name",
  "private": true,
  "main": "electron.js",
  "scripts": {
    "build:electron": "ng build --base-href ./",
    "build:electron:dev": "npm run build:electron -- -c dev",
    "build:electron:prod": "npm run build:electron -- -c production",
    "electron:dev": "export NODE_ENV=development || set NODE_ENV=development && npm-run-all -p ng:serve electron:serve",
    "electron:dev:debug": "npm-run-all -p ng:serve electron:serve:debug",
    "electron:dev:debug-live": "npm-run-all -p ng:serve electron:serve:debug-live",
    "electron:serve": "wait-on http-get://localhost:4200/ && run-electron . --serve",
    "electron:serve:debug": "wait-on http-get://localhost:4200/ && run-electron --inspect-brk=9229 . --serve",
    "electron:serve:debug-live": "wait-on http-get://localhost:4200/ && nodemon --watch electron.js --exec run-electron --inspect-brk=9229 . --serve",
    "electron:local": "npm run build:electron:prod && run-electron .",
    "electron:linux": "npm run build:electron:prod && npx electron-builder build --linux",
    "electron:windows": "npm run build:electron:prod && npx electron-builder build --windows",
    "electron:mac": "npm run build:electron:prod && npx electron-builder build --mac",
    "ionic": "npm run ng:serve:web",
    "emulate:ios-dev": "ionic cordova emulate ios --l",
    "run:ios-dev": "ionic cordova run ios --l --device",
    "emulate:ios": "ionic cordova emulate ios",
    "run:ios": "ionic cordova run ios --device",
    "release:ios": "ionic cordova build ios --configuration production --release",
    "emulate:android-dev": "ionic cordova emulate android --l",
    "run:android-dev": "ionic cordova run android --device --l",
    "emulate:android": "ionic cordova emulate android",
    "run:android": "ionic cordova run android --device",
    "release:android": "ionic cordova build android --configuration production --release ",
    "ng": "ng",
    "ng:serve": "ng serve",
    "ng:serve:web": "ng serve -o",
    "test": "ng test",
    "e2e": "ng e2e",
    "xcode": "open -a Xcode platforms/ios/",
    "postinstall": "patch-package",
    "start": "npm run copysqlwasm && ng serve",
    "build": "npm run copysqlwasm && ng build",
    "lint": "ng lint",
    "copysqlwasm": "copyfiles -u 3 node_modules/sql.js/dist/sql-wasm.wasm src/assets"
  },
  "dependencies": {
    "@angular-devkit/architect": "^0.1602.0",
    "@angular-devkit/core": "^16.2.0",
    "@angular-devkit/schematics": "^16.2.0",
    "@angular/common": "16.2.0",
    "@angular/core": "16.2.0",
    "@angular/forms": "16.2.0",
    "@angular/platform-browser": "16.2.0",
    "@angular/platform-browser-dynamic": "16.2.0",
    "@angular/router": "16.2.0",
    "@capacitor-community/sqlite": "^5.0.7-2",
    "@capacitor/android": "^5.2.3",
    "@capacitor/cli": "^5.2.3",
    "@capacitor/core": "^5.2.3",
    "@capacitor/device": "^5.0.6",
    "@capacitor/ios": "^5.2.3",
    "@capacitor/keyboard": "^5.0.6",
    "@capacitor/network": "^5.0.6",
    "@capacitor/splash-screen": "^5.0.6",
    "@capacitor/status-bar": "^5.0.6",
    "@ionic/angular": "^7.2.3",
    "@ionic/storage": "^4.0.0",
    "@ionic/storage-angular": "^4.0.0",
    "@types/ws": "^8.5.4",
    "cordova": "^12.0.0",
    "cordova-plugin-ionic-webview": "^5.0.0",
    "core-js": "3.25.4",
    "jeep-sqlite": "^2.5.0",
    "localforage-cordovasqlitedriver": "^1.8.0",
    "ngx-electron": "^2.2.0",
    "patch-package": "^8.0.0",
    "polyonic-secure-pouch": "1.0.7",
    "run-electron": "1.0.0",
    "rxjs": "7.5.0",
    "sql.js": "^1.8.0",
    "zone.js": "~0.13.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^16.2.0",
    "@angular/cli": "^16.2.0",
    "@angular/compiler": "16.2.0",
    "@angular/compiler-cli": "16.2.0",
    "@angular/language-service": "16.2.0",
    "@ionic/angular-toolkit": "^10.0.0",
    "@types/jasmine": "3.6.7",
    "@types/jasminewd2": "2.0.8",
    "@types/node": "14.14.35",
    "codelyzer": "6.0.1",
    "copyfiles": "^2.4.1",
    "electron": "^25.5.0",
    "electron-builder": "22.10.5",
    "husky": "5.1.3",
    "jasmine-core": "3.7.1",
    "jasmine-spec-reporter": "6.0.0",
    "karma": "6.4.2",
    "karma-chrome-launcher": "3.1.0",
    "karma-coverage-istanbul-reporter": "3.0.3",
    "karma-jasmine": "4.0.1",
    "karma-jasmine-html-reporter": "1.5.4",
    "nodemon": "^2.0.7",
    "npm-run-all": "4.1.5",
    "ts-node": "9.1.1",
    "typescript": "^5.1.6",
    "wait-on": "5.3.0"
  },
  "cordova": {
    "plugins": {
      "cordova-plugin-statusbar": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-webview": {},
      "cordova-plugin-ionic-keyboard": {},
      "cordova-plugin-androidx-adapter": {}
    },
    "platforms": []
  }
}

I'll be really thankful if someone helps me with this

**Comment by jepiqueau** [comment]
@Rose-Miller-web-dev Thanks for using the plugin Can you share your project on Github so i will have a look

**Comment by Rose-Miller-web-dev** [comment]
> @Rose-Miller-web-dev Thanks for using the plugin Can you share your project on Github so i will have a look

sure! Here's the repo
https://github.com/Rose-Miller-web-dev/polyonic

**Comment by jepiqueau** [comment]
Do you want to run it with Electron?

**Comment by jepiqueau** [comment]
you should look at the application links for Ionic/ angular app in the readme of the @capacitor-community/sqlite i do not recognize any thing in the code you sent jeep-sqlite is a component wh is to be used in Web platform. in Electron platform  the @capacitor-community/sqlite has a plugin for ELECTRON, iOS and Android

**Comment by Rose-Miller-web-dev** [comment]
> Do you want to run it with Electron?

right now I wanna use it in web

**Comment by Rose-Miller-web-dev** [comment]
> you should look at the application links for Ionic/ angular app in the readme of the @capacitor-community/sqlite i do not recognize any thing in the code you sent jeep-sqlite is a component wh is to be used in Web platform. in Electron platform the @capacitor-community/sqlite has a plugin for ELECTRON, iOS and Android

it's actually a directive
I asked chat gpt to provide a solution and got this:
Create a Directive: We'll create a directive to handle the custom element within Angular's component system.
Append Custom Element to the DOM: Within the directive, we'll append the custom element to the DOM.
Initialize the SQLite Connection: We can also handle the SQLite initialization within the directive.
Use the Directive in a Component: Finally, we'll use this directive within an Angular component.

**Comment by jepiqueau** [comment]
@Rose-Miller-web-dev did you look at the doc Web-usage.md provided

**Comment by jepiqueau** [comment]
@Rose-Miller-web-dev see app example [testIssue459](https://github.com/jepiqueau/testIssue459) hope this will help you to start

**Comment by Rose-Miller-web-dev** [comment]
Luckily I found a solution
after adding this piece of code to my app.component.ts ngOnInit, the error was removed!
try {
    const platform = Capacitor.getPlatform();

    // WEB SPECIFIC FUNCTIONALITY
    if (platform === "web") {
      sqlite = new SQLiteConnection(CapacitorSQLite)
      // Create the 'jeep-sqlite' Stencil component
      customElements.define("jeep-sqlite", JeepSqlite)
      const jeepSqliteEl = document.createElement("jeep-sqlite")
      document.body.appendChild(jeepSqliteEl)
      await customElements.whenDefined("jeep-sqlite")
      //console.log(`after customElements.whenDefined`)
      // console.log(sqlite , '#sqlite')
      // Initialize the Web store
      await sqlite.initWebStore()
      //console.log(`after initWebStore22`)
    }
    
    } catch (e) {
      console.log(e);
    }
