### ISSUE TITLE
Data is committed only after db of type SQLiteDBConnection is closed

### ISSUE THREAD

**Issue by Rose-Miller-web-dev** [capacitor-community/sqlite#461]
Hi
I'm trying to add a simple CRUD in my Angular ionic app.
There is a service that initializes the db and opens it

The problem is that the data is not committed to the db if I do not close it and if I close it, it cannot be opened again!
I have no idea of what to do
I also tried closing the db in ngOnDestroy of the component but it works only after I navigate from the curreent component and if I refresh the page after adding the user, does not work

the service code:
export class StorageService implements OnInit{

  ngOnInit(): void {
      this.nice.ngOnInit()
  }

  private nice: NiceComponent
  private sqlite: SQLiteConnection = new SQLiteConnection(CapacitorSQLite)
  private db!: SQLiteDBConnection
  private user: any
  
  constructor() { 
    
   }

  async initializePlugin() {
    this.db = await this.sqlite.createConnection(
      "db_vite",
      false,
      "no-encryption",
      1,
      false
    )

    await this.db.open()

    const schema = `CREATE TABLE IF NOT EXISTS users (
      id INTEGER PRIMARY KEY NOT NULL,
      name TEXT NOT NULL
      );`

    await this.db.execute(schema)
    //await this.sqlite.closeConnection("db_vite", false)
    return true
  }

  async loadUsers() {
    console.log("loading users")

    try {
      const respSelect = await this.db.query(`SELECT * FROM users`);
      const userArray = Array.from(respSelect.values);
      this.user = userArray.map(user => ({
        id: user.id,
        name: user.name,
      }));

      console.log("loaded successfully!");
    } catch (error) {
      console.error("Error loading users:", error);
    }
  }

  async addUser(name: string) {

    try {
      console.log("Adding user:", name);
      const id = Math.floor(Math.random() * 1000000);
      await this.db.query(`INSERT INTO users (id, name) VALUES (?, ?)`, [id, name]);
      await this.loadUsers();
      console.log("User added successfully!");
    } catch (error) {
      console.error("Error adding user:", error);
    }

    await this.sqlite.closeConnection("db_vite", false) //PROBLEMATIC LINE
  }
}

Here's the component code:
export class NiceComponent  implements OnInit {

  async ngOnInit() {
    await this.loadProducts()
  }

  newUserName = ''
  users: any
  isWeb: any

  constructor(private storage: StorageService) { }

  async loadProducts() {
    await this.storage.loadUsers()
    this.users = await this.storage.getUsers()
    console.log("nice users: ", this.users)
  }

  async createUser(name: string) {
    await this.storage.addUser(name.toString())
    this.newUserName = ''
    await this.loadProducts()
    console.log(this.users, '#users')
  }
  
  and this is my app.component.ts:
  export class AppComponent implements OnInit{

  ngOnInit(): void {
    this.initApp()
  }

  constructor(private platform: Platform, private storage: StorageService) { }

  async initApp() {
    var sqlite:any
  try {
    const platform = Capacitor.getPlatform();

    // WEB SPECIFIC FUNCTIONALITY
    if (platform === "web") {
      sqlite = new SQLiteConnection(CapacitorSQLite)
      // Create the 'jeep-sqlite' Stencil component
      customElements.define("jeep-sqlite", JeepSqlite)
      const jeepSqliteEl = document.createElement("jeep-sqlite")
      document.body.appendChild(jeepSqliteEl)
      await customElements.whenDefined("jeep-sqlite")
      //console.log(`after customElements.whenDefined`)
      // console.log(sqlite , '#sqlite')
      // Initialize the Web store
      await sqlite.initWebStore()
      //console.log(`after initWebStore22`)
    }
    
    } catch (e) {
      console.log(e);
    }
    
    try {

      sqlite = new SQLiteConnection(CapacitorSQLite)
      var db = await sqlite.createConnection(
          "db_vite",
          false,
          "no-encryption",
          1,
          false
      );
      console.log("Database connection successful!")
  } catch (error) {
      console.error("Error creating database connection:", error)
  }
    
    await this.storage.initializePlugin()
    await this.storage.loadUsers()
    SplashScreen.hide()
  }
  
  and this is the link to the repo:
  https://github.com/Rose-Miller-web-dev/polyonic

I'll be thankful if you help me with this!

**Comment by jepiqueau** [comment]
@Rose-Miller-web-dev  yes that is true but you can use the saveToStore method in between the openConnection and the closeConnection. Keep in mind that when your database grow-up this will be time consuming so my advice is not to do it after each crud operation.
