### ISSUE TITLE
How to import and export encrypted database - Capacitor Sqlite Plugin?

### ISSUE THREAD

**Issue by sadamameer** [capacitor-community/sqlite#463]
Hello developers,

I am using the capacitor sqlite plugin with vue.js and developing the native mobile apps.  The issue I am facing is, after encrypting the database the exportToJson function does not provide the valid json that could be imported later. This is generating some expData object having base64 encoded string. 

My question is how could I import this base64 encoded string by using importFromJson method? Currently its showing invalid json all the time.

Please help as soon as possible.

Thanks and keep the good work up.

**Comment by sadamameer** [comment]
Is it not possible to import data when expData contains a base64 string? Is there an alternative solution? Could we potentially utilize an encrypted database for simultaneous import and export?
@patdx  @cosentino  @oscarfonts  @gion-andri

**Comment by jepiqueau** [comment]
@sadamameer Can you share your code or a simple repro of your code in github so i see what is wrong to help fixing as i have a code which works well.

**Comment by sadamameer** [comment]
@jepiqueau  Thanks for the response. I am sharing the code snippets that I am using to export and import the encrypted database. 

`EXPORT TO JSON METHOD`

```
var db: SQLiteDBConnection;

db = await this.$sqlite.createConnection("databse_name");

await db.open();

await db.exportToJson("full")
.then((data) => {
  // data is the a json string with the format like this:
  // {
  //   expData : base64 string
  // }
});
```

`IMPORT FROM JSON METHOD`

```
`backup is the exported json string with the format :`

// {
//   expData : base64 string
// }


const jsonstring = JSON.stringify(backup);
await CapacitorSQLite.isJsonValid({ jsonstring });
await CapacitorSQLite.deleteDatabase({ database : "databse_name" });
await CapacitorSQLite.importFromJson({ jsonstring });
```

> The encrypted database is working perfectly fine.
> The exporting part is also perfect.
> Getting error in importing function "Must provide a valid json object"

Please help me out in this situation. Your quick support will be appreciated.

Thanks!

**Comment by jepiqueau** [comment]
@sadamameer if i look at this 
```
db = await this.$sqlite.createConnection("databse_name");
```
means to your database is not encrypted meaning that the export full must not be encrypted meaning that there is no expData 

the correct code should be something like
``` 
        
        let jsonObj: any = await db.exportToJson('full');
        console.log(`returned JSONObject: ${JSON.stringify(jsonObj.export)};
        const isValid = (await CapacitorSQLite.isJsonValid({ jsonstring: JSON.stringify(jsonObj.export) })).result;
        if (isValid) {
            await CapacitorSQLite.deleteDatabase({ database : "databse_name" });
            await CapacitorSQLite.importFromJson({ jsonstring: JSON.stringify(jsonObj.export)});
       }

```

**Comment by sadamameer** [comment]
@jepiqueau 

I appreciate your assistance. The previous problem has been resolved, but I've encountered a new and puzzling error.

When I generate a debug build, the database and SQLite plugin function correctly. However, when I create a release build, I consistently encounter an error message that states: "Capacitor SQLite Plugin is not implemented on Android."

I kindly request your help in resolving this issue. Your assistance would be greatly appreciated.

**Comment by jepiqueau** [comment]
@sadamameer can you describe the procedure used to create the release build

**Comment by sadamameer** [comment]
> @jepiqueau I adhere to a straightforward process where I enable resource minification and shrinking, followed by generating the release build or signed APK. If I omit the resource minification and shrinking, the release build functions correctly, but the code remains readable if someone were to decompile the APK. Consequently, I employ ProGuard to perform code minification, shrinking, and obfuscation. While this procedure works seamlessly for most Capacitor plugins, such as camera and geolocation, it encounters issues with the Capacitor SQLite plugin.

**Comment by jepiqueau** [comment]
@sadamameer did you look at docs/AndroidMinify.md which has been added with the last release of the plugin

**Comment by sadamameer** [comment]
Yes, I already did the same, and added these 2 statements in the Proguard Rules.

> -keep class net.sqlcipher.** { *; }
> -keepclassmembers class net.sqlcipher.** { *; }

but still, its showing the same error.

**Comment by jepiqueau** [comment]
@sadamameer @muuvmuuv Marvin, can you help on this as you went through all the process

**Comment by muuvmuuv** [comment]
What is the log output? Guess its some func that gets mangeled

**Comment by jepiqueau** [comment]
@sadamameer any progress on this as i do not have any feedback i close the issue
