### ISSUE TITLE
How to apply setEncryptionKey in capacitor-community/sqlite?

### ISSUE THREAD

**Issue by Rose-Miller-web-dev** [capacitor-community/sqlite#465]
Hi, sorry to ask here but I have set up a database in capacitor sqlite and now I wanna set an encryption key using
async setEncryptionSecret(passphrase: string): Promise<void> {
    if(!this.native) {
        return Promise.reject(new Error(`Not implemented for ${Capacitor.getPlatform()} platform`))
    }

    if(this.sqlite != null) {
        try {
            return Promise.resolve(await this.sqlite.setEncryptionSecret(passphrase))
        } catch (err) {
            return Promise.reject(new Error(err))
        }
    } else {
        return Promise.reject(new Error(`no connection open`))
    }

  }

and this is the Angular service I have:
export class StorageService implements OnInit{

  ngOnInit(): void {
  }

  private sqlite: SQLiteConnection = new SQLiteConnection(CapacitorSQLite)
  private db!: SQLiteDBConnection
  private user: any
  platform: any
  native: any
  isService: any
  sqlitePlugin: any
  
  constructor() { }

  async initializePlugin() {

    this.db = await this.sqlite.createConnection(
      "db_vite",
      false,
      "no-encryption",
      1,
      false
    )

    await this.db.open()

    const schema = `CREATE TABLE IF NOT EXISTS users (
      id INTEGER PRIMARY KEY NOT NULL,
      name TEXT NOT NULL
      );`

    await this.db.execute(schema)

    return new Promise (resolve => {
      this.platform = Capacitor.getPlatform()
      if(this.platform === 'ios' || this.platform === 'android') 
        this.native = true
      this.sqlitePlugin = CapacitorSQLite
      this.sqlite = new SQLiteConnection(this.sqlitePlugin)
      this.isService = true
      resolve(true)
    })

  }

  async loadUsers() {
    
    try {
      const respSelect = await this.db.query(`SELECT * FROM users`)
      const userArray = Array.from(respSelect.values)
      this.user = userArray.map(user => ({
        id: user.id,
        name: user.name,
      }));

    } catch (error) {
      console.error("Error loading users:", error);
    }
  }

  async addUser(name: string) {

    try {
      console.log("Adding user:", name);
      const id = Math.floor(Math.random() * 1000000);
      await this.db.query(`INSERT INTO users (id, name) VALUES (?, ?)`, [id, name]);
      //console.log("User added successfully!");
    } catch (error) {
      console.error("Error adding user:", error);
    }

    await this.loadUsers();
  }

  async updateUserById(user: any, name: string) {
   
    try {
      console.log("Updating user:", name);
      const id = Math.floor(Math.random() * 1000000);
      await this.db.query(`UPDATE users SET name=? WHERE id=?;`, [name, user.id]);
      //console.log("User updated successfully!");
    } catch (error) {
      console.error("Error updating user:", error);
    }

    await this.loadUsers();
  }

  async deleteUserById(id: string) {
    const query = `DELETE FROM users WHERE id=${id}`
    const result = await this.db.query(query)

    await this.loadUsers()
    //console.log("deleted successfully")
    return result
  }

  async getUsers() {
    await this.loadUsers()
    return await this.user
  }

  async closeDB() {
    await this.sqlite.closeConnection("db_vite", false)
  }

  async setEncryptionSecret(passphrase: string): Promise<void> {
    if(!this.native) {
        return Promise.reject(new Error(`Not implemented for ${Capacitor.getPlatform()} platform`))
    }

    if(this.sqlite != null) {
        try {
            return Promise.resolve(await this.sqlite.setEncryptionSecret(passphrase))
        } catch (err) {
            return Promise.reject(new Error(err))
        }
    } else {
        return Promise.reject(new Error(`no connection open`))
    }

  }
}

and this is the component I applied db in:
export class NiceComponent  implements OnInit {
  
  async ngOnInit() {
    await this.loadDb()
  }

  async ngOnDestroy() {
    window.location.reload()
    await this.loadDb()
  }

  async ngAfterViewInit() {
    this.router.navigate(['/nice'])
    await this.loadDb()
  }
  
  public isEdit: boolean = false
  newUserName = ''
  users: any
  private currentUser: any
  
  constructor(private storage: StorageService, private router: Router,) { }

  async loadProducts() {
    await this.storage.loadUsers()
    this.users = await this.storage.getUsers()
  }

  async createUser(name: string) {

    if (this.isEdit) {
      await this.storage.updateUserById(this.currentUser, this.newUserName)
      this.isEdit = false
      this.currentUser = null
    } else {
      await this.storage.addUser(name.toString())
    }

    this.newUserName = ''
    await this.loadProducts()
    await this.storage.closeDB()
    this.router.navigate(['/nice'])
    await this.initWebApp()
  }

  async updateUser(user: User) {
    this.newUserName = user.name
    this.isEdit = true
    this.currentUser = user
  }

  async deleteUser(user: User) {
    await this.storage.deleteUserById(user.id.toString())
    await this.loadProducts()
    await this.storage.closeDB()
    await this.initWebApp()
    this.router.navigate(['/nice'])
    
  }

  async initWebApp() {
    var sqlite:any
    try {
      const platform = Capacitor.getPlatform();

      if (platform === "web") {
        sqlite = new SQLiteConnection(CapacitorSQLite)
        customElements.get('jeep-sqlite') || customElements.define("jeep-sqlite", JeepSqlite)
        const jeepSqliteEl = document.createElement("jeep-sqlite")
        document.body.appendChild(jeepSqliteEl)
        await customElements.whenDefined("jeep-sqlite")
        await sqlite.initWebStore()
      }
      
      } catch (e) {
        console.log(e);
      }
    
    try {

      sqlite = new SQLiteConnection(CapacitorSQLite)
      var db = await sqlite.createConnection(
          "db_vite",
          false,
          "no-encryption",
          1,
          false
      );
      //console.log("Database connection successful!")
  } catch (error) {
      console.error("Error creating database connection:", error)
  }
    
    await this.storage.initializePlugin()
    await this.storage.loadUsers()
    SplashScreen.hide()
  }

  async loadDb() {
    await this.initWebApp()
    await this.storage.initializePlugin()
    await this.storage.loadUsers()
    await this.loadProducts()
  }

may someone help me with this?? When and where should I apply the setEncryption??
and in case you needed the repo, here's the link:
https://github.com/Rose-Miller-web-dev/polyonic

**Comment by jepiqueau** [comment]
@Rose-Miller-web-dev you can also have a look at [test-encryption](https://github.com/jepiqueau/test-encryption)

**Comment by jepiqueau** [comment]
@Rose-Miller-web-dev No news from you so i assume it is solved
