### ISSUE TITLE
Move database throws an exception sometimes

### ISSUE THREAD

**Issue by HarelM** [capacitor-community/sqlite#468]
**Describe the bug**
When using `moveDatabasesAndAddSuffix` the plugin throws an exception with message:
`CapacitorSQLitePlugin: null`

**To Reproduce**
I'm not sure, I've got this report from one or two of my users.
When uninstalling the app and installing it again the problem does not repeat, but this seems to happen sometimes for some users.

**Expected behavior**
There should be a meaningful error message, but there isn't one...

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

- Device: Samsung SM-G998B
- OS: Android 13
- Browser Chrome for android
- Version IDK
- 
**Additional context**
I looked at the code and I couldn't find a path that returns an error message or exception of null, so I'm not sure where to look for this issue...
Any help would be appreciated...

**Comment by jepiqueau** [comment]
@HarelM look in your code at the time you call moveDatabaseAndAddSuffix the CapacitorSQLitePlugin is not defined. Which framework are you using? Can you show the initialization of jeep-sqlite ?

**Comment by HarelM** [comment]
These are the relevant lines:
https://github.com/IsraelHikingMap/Site/blob/main/IsraelHiking.Web/src/application/services/database.service.ts#L199L232
This happens when the app starts basically, I'm using capacitor.

**Comment by HarelM** [comment]
I'm not initializing `jeep-sqlite` explicitly in my code, so I'm not sure how to answer that...

**Comment by jepiqueau** [comment]
@HarelM is it a native app or browser app ? Which framework are you using?

**Comment by HarelM** [comment]
Oh, sorry, Android.

**Comment by jepiqueau** [comment]
@HarelM so you do not need to initialize jeep-sqlite which framework angular,react vue

**Comment by jepiqueau** [comment]
@HarelM i saw that your database url is the "cache" 
```
await this.sqlite.moveDatabasesAndAddSuffix("cache", [dbFileName]);
```
this function was written to move an existing cordova database to move it to the right folder to be used with the capacitor plugin. 
how did you load the database to the cache?

**Comment by jepiqueau** [comment]
@HarelM in 
```
    public async moveDownloadedDatabaseFile(dbFileName: string) {
        await this.closeDatabase(dbFileName.replace(".db", ""));
        this.loggingService.info(`[Database] Starting moving file ${dbFileName}`);
        await this.sqlite.moveDatabasesAndAddSuffix("cache", [dbFileName]);
        this.loggingService.info(`[Database] Finished moving file ${dbFileName}`);
    }
```
can you print this.sqlite it may be null  this is why you get `CapacitorSQLitePlugin: null`

**Comment by jepiqueau** [comment]
@HarelM how do you call moveDownloadedDatabaseFile ? it seems your app is quite complex so it is difficult for me to find a reason for it can you try to define breakpoint in moveDownloadedDatabaseFile at `await this.closeDatabase(dbFileName.replace(".db", "")); ` move once and see what is the value of this.sqlite before ` await this.sqlite.moveDatabasesAndAddSuffix("cache", [dbFileName]);` and put some breakpoints inside the `moveDatabasesAndAddSuffix`

**Comment by HarelM** [comment]
I can't debug this as this doesn't happen all the time, all I can do is add logs and wait for the next user report... :-/

**Comment by jepiqueau** [comment]
@HarelM in which part of your code do you call moveDownloadedDatabaseFile ?

**Comment by HarelM** [comment]
When the app starts, in angular init method, after device ready event.

**Comment by jepiqueau** [comment]
@HarelM i am reviewing the issues, is this one still happen or not?

**Comment by HarelM** [comment]
Yes, Just got a report from a user yesterday, Any logging I can add to better understand the root cause?

**Comment by jepiqueau** [comment]
@HarelM can i see the app starts code and the package.json

**Comment by HarelM** [comment]
Sure:
Here is the main method:
https://github.com/IsraelHikingMap/Site/blob/16c39060d72f360ea9a4f9ab5b112e4c9525b2fc/IsraelHiking.Web/src/application/services/application-initialize.service.ts#L51

Called from here:
https://github.com/IsraelHikingMap/Site/blob/16c39060d72f360ea9a4f9ab5b112e4c9525b2fc/IsraelHiking.Web/src/application/application.module.ts#L195

**Comment by pct-cclausen** [comment]
We also have an Android-App which right at startup tries to use sqlite via this plugin and then fails with this error.

I think there is something that on some devices, of which I have access to none, somehow causes sqlite initialization to fail such that calls to anything yield this error.

**Comment by jepiqueau** [comment]
@pct-cclausen @HarelM  can you tell me on which devices and which android API are they running?
