### ISSUE TITLE
Bug: Cannot build plugin, typescript operator used in javascript file

### ISSUE THREAD

**Issue by bkostjens** [capacitor-community/sqlite#472]
**Describe the bug**
When trying to build v5.2.3, the build fails with error:

Failed to compile with 1 error                                                                                         
 error  in ./node_modules/@capacitor-community/sqlite/dist/esm/definitions.js

Module parse failed: Unexpected token (912:16)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders

     async reorderRows(res) {
         const retRes = res;
         if (res?.values && typeof res.values[0] === 'object') {
             if (Object.keys(res.values[0]).includes('ios_columns')) {
                 const columnList = res.values[0]['ios_columns'];

 @ ./node_modules/@capacitor-community/sqlite/dist/esm/index.js 7:0-30 7:0-30

**To Reproduce**

Simply try to build it (rpm run build) will give this error.

**To Fix**
replace the optional chaining operator (this is a typescript feature) in @capacitor-community/sqlite/dist/esm/definitions.js:

    if (res?.values && typeof res.values[0] === 'object') {

with pure javascript: 

    if (res && res.values && typeof res.values[0] === 'object') {

**Comment by bkostjens** [comment]
Actually I see that optional chaining is perfectly fine in javascript. The problem is caused by webpack.

**Comment by bkostjens** [comment]
Closing this, as it is more of a webpack problem.

**Comment by Sampath-Lokuge** [comment]
You have not closed this yet.

**Comment by aaronksaunders** [comment]
@bkostjens how did you resolve this with webpack?

**Comment by atrujillofalcon** [comment]
Same problem here, please reopen o tell us how fix the webpack bug.
