### ISSUE TITLE
Typeorm transaction doesn't rollback if a query fails

### ISSUE THREAD

**Issue by Ly-sg** [capacitor-community/sqlite#473]
**Describe the bug**
i have three tables Food <---FoodXStore---> Store (many to many relationship between Food & Store)
There's have a unique constiraint on (foodId,soreId) in the FoodXStore join table

I want to run a simple transaction that inserts a Food and two identical joins to the FoodXStore join table, the transaction runs and creates the Food entity and the first join, but doesn't rollback when it fails to create the 2nd join, which leaves me with a data integrity problem

**To Reproduce**
Here's the code that executes the transaction, i pass objects containing the necessary input data which is are "food" and the "foodXStore" object , i basically followed the doc's 3rd example : https://orkhan.gitbook.io/typeorm/docs/transactions (also tried other syntaxes, it doesn't work)

`await appDatasource.manager.transaction(async (transactionEntityManager) => {
      const foodRes = await transactionEntityManager.save(Food, transactionEntityManager.create(Food, food));
      const fxs = foodXStore.map(fxs => transactionEntityManager.create(
        FoodXStore, 
        {
          ...fxs,
          foodId: foodRes.id,
        }));        
      await transactionEntityManager.save(fxs);
    });`

**Expected behavior**
I expected the transaction to fail and rollback without inserting any entity, but in this case it still inserts the entities until it fails

The entity food and the first join are inserted, the 2nd join isn't, it shouldn't insert anything and just rollback the transaction but it says that no transaction is active

**Desktop (please complete the following information):**

- OS: Linux
- Browser Chrome

**Additional context**
Running an app with angular and the capacitor-typeorm-sqlite with angular 16 setup, CRUD operations and transactions work fine, but if the transaction has a conflict it doesn't rollback
here are some relevant dependencies :
    "@capacitor-community/sqlite": "^4.6.3",
    "@capacitor/android": "4.8.0",
    "@capacitor/app": "4.1.1",
    "@capacitor/core": "4.8.0",
    "@capacitor/haptics": "4.1.0",
    "@capacitor/keyboard": "4.1.1",
    "@capacitor/splash-screen": "^4.2.0",
    "@capacitor/status-bar": "^4.1.1",
    "jeep-sqlite": "^2.3.3",
    "tslib": "^2.3.0",
    "typeorm": "^0.3.17",

**AppDatasource code :** 
-------------------
`const sqliteService = new SQLiteService();
const sqliteConnection = sqliteService.getSqliteConnection();

export default new DataSource({
    name: 'appConnection',
    type: 'capacitor',
    driver: sqliteConnection,
    database: 'fasterfood',
    mode: 'no-encryption',
    entities: [Store, Food, FoodXStore],
    migrations: [initFood1685296531290, initAppData1687097727412],
    subscribers: [],
    logging: ['query', 'error', 'schema'],
    synchronize: false,
    migrationsRun: false,
});`
-------------------

**Log Stack**
--------------
query: BEGIN TRANSACTION

query: INSERT INTO "food"("id", ...

query: SELECT "Food"."id" AS ...

query: INSERT INTO "food_x_store"...

query: SELECT "FoodXStore"."id" AS...

query: INSERT INTO "food_x_store"...

query failed: INSERT INTO "food_x_store"("id", "foodId", "storeId"...

query: ROLLBACK

query failed: ROLLBACK

error: Error: Query failed: SelectSQL: queryAll: cannot rollback - no transaction is active

ERROR Error: Uncaught (in promise): QueryFailedError: Run: RunSQL: run: UNIQUE constraint failed: food_x_store.foodId, food_x_store.storeIdQueryFailedError: Run: RunSQL: run: UNIQUE constraint failed: food_x_store.foodId, food_x_store.storeId
------------------

**My guess :** There's no transaction active because the inserts above are commited in some way, or the entities aren't inserted with the same EntityManager ? (even if i followed the example and i use the same one)

**What i tried : **
I tried starting a fresh TypeOrm sandbox project to see if it's the library's problem, but it works just fine with the same transaction code and same tables so i don't think it's Typeorm's problem (i used the same version of typeorm)

**Comment by jepiqueau** [comment]
@Ly-sg I am not a specialist of TypeOrm but it manages directly the transactions and do not use the ones of the plugin so i wonder why you have query: BEGIN TRANSACTION. Are you using the TypeOrm transaction process?

**Comment by Ly-sg** [comment]
> @Ly-sg I am not a specialist of TypeOrm but it manages directly the transactions and do not use the ones of the plugin so i wonder why you have query: BEGIN TRANSACTION. Are you using the TypeOrm transaction process?

Its the code example for writing a transactionin TypeOrm, i use it since i want the whole transaction to fail if a query inside hetransaction fails. 
`await appDatasource.manager.transaction(async (transactionEntityManager)` starts a transaction and provides a transactionEntityManager to use for that.
query: BEGIN TRANSACTION means that typeOrm starts a transaction
"Are you using the TypeOrm transaction process?" -> I'm not sure what you mean, since i'm using the transaction method i guess yes ?

**Comment by Ly-sg** [comment]
Hey, i found this post which has some similarities with my prblem, which is mainly the "no transaction is active" error message https://github.com/capacitor-community/sqlite/issues/414

**So after reading this i realized that the rollback features works well when i run the app/debug on android**, so the problem might be the sqlite plugin "jeep-sqlite".
first thing i did was to upgrade it to 2.5.2 (i was on 2.3.8) but that doesn't fix the problem.
i also tried to set the plugin's autosave attribute to false with `jeepEl.autoSave = true;` it doesn't commit any transaction now, i guess the rollback works on failure but i have no item inserted even when there is no failure.
@jepiqueau it seems the problem isn't really typeOrm but something to do with the plugin, any idea on how to solve the problem with these new informations ?

**Comment by jepiqueau** [comment]
@Ly-sg i you set the autosave to false which is good you have somewhere in the code at the end of the typeOrm transaction to save the database yourself with the saveToStore method

**Comment by Ly-sg** [comment]
> @Ly-sg i you set the autosave to false which is good you have somewhere in the code at the end of the typeOrm transaction to save the database yourself with the saveToStore method

I turned off autosave and added this block of code to use the saveToStore method : 
`      if (this.sqliteService.getPlatform() === 'web') {
        const ret = await this.sqliteService.getSqliteConnection().saveToStore("fasterfood");
      }`
Now it works if i call the method after each query so i need to refactor the code, but this means taht the autosave feature can't be used if we use transactions ?
I guess the problem is that the autosave feature "commits" each query even if it's wrapped in a transaction and thus making it impossible to rollback if that query or a subsequent one fails ?

Thank you for your help

**Comment by jepiqueau** [comment]
@Ly-sg sorry autosave must not be used with typeOrm

**Comment by jepiqueau** [comment]
@Ly-sg i assume it is fixed so i close the issue

**Comment by Ly-sg** [comment]
> @Ly-sg i assume it is fixed so i close the issue

Yes thanks
