### ISSUE TITLE
Updating to capacitor electron 5.0.1 breaks db connection

### ISSUE THREAD

**Issue by CosminCraciun** [capacitor-community/sqlite#474]
Updating to latest capacitor community electron (5.0.1) breaks db initialization.
When running in dev mode I just see the app dieing without any context. When creating an installer and running it from the terminal I get: `[4172:0929/141145.426:ERROR:crashpad_client_win.cc(844)] not connected`

Had the same issue with typeorm and without.

- OS: Windows
- Browser: Electron v26
- Version: 5.2.3

Could you update the examples to use the latest capacitor electron?
I suspect they are doing something differently on version 26 of electron that might break the IPC between the renderer and the electron browser. I might be way off tho.

**Comment by jepiqueau** [comment]
@CosminCraciun i was just testing it and discuter that it does not work so for the time being stay with @capacitor-community/electron@4.1.2.

**Comment by jepiqueau** [comment]
@CosminCraciun it works well with this in the electron package.json
```
  "dependencies": {
    "@capacitor-community/electron": "^5.0.1",
    "@capacitor-community/sqlite": "^5.2.5",
    "better-sqlite3-multiple-ciphers": "^8.4.0",
    "chokidar": "~3.5.3",
    "crypto": "^1.0.1",
    "crypto-js": "^4.1.1",
    "electron-is-dev": "~2.0.0",
    "electron-json-storage": "^4.6.0",
    "electron-serve": "~1.1.0",
    "electron-unhandled": "~4.0.1",
    "electron-updater": "~5.0.1",
    "electron-window-state": "~5.0.3",
    "jszip": "^3.10.1",
    "node-fetch": "2.6.7"
  },
  "devDependencies": {
    "@electron/rebuild": "^3.3.0",
    "@types/better-sqlite3": "^7.6.4",
    "@types/crypto-js": "^4.1.1",
    "@types/electron-json-storage": "^4.5.0",
    "electron": "^25.8.4",
    "electron-builder": "^24.6.4",
    "typescript": "^5.0.2"
  },
```
seems to indicate that it is not the upgrade of @capacitor-community/electron to 5.0.1 it seems to come from the upgrade to electron 26

**Comment by jepiqueau** [comment]
@CosminCraciun As soon as i update to Electron 26.x.x i got called ipcMain.handle: CapacitorSQLite-open

**Comment by jepiqueau** [comment]
@CosminCraciun as i mentioned it is coming from better_sqlite3 so we have to wait for a fix from them sorry for that

**Comment by jepiqueau** [comment]
@CosminCraciun Can you try with `better-sqlite3-multiple-ciphers@9.1.1` and `electron@27.1.3` and tell me if it works

**Comment by CosminCraciun** [comment]
Yeah, it works fine. Thanks

**Comment by jepiqueau** [comment]
OK thanks so i will upgrade the documentation. So i close the issue
