### ISSUE TITLE
Ionic 7 / Capacitor 5 / Angular 16 / Error: CapacitorSQLitePlugin: null

### ISSUE THREAD

**Issue by Hirumago** [capacitor-community/sqlite#475]
Hello everyone,

I'm trying to use "@capacitor-community/sqlite" but I got an error on my android phone but not my android emulator.

My phone screenshot: 
![image](https://github.com/capacitor-community/sqlite/assets/21058915/725bdefb-dd2e-4925-ae9d-cd5b81619900)

Code: 
![image](https://github.com/capacitor-community/sqlite/assets/21058915/48816efb-a7ae-45c2-acbd-3528dd011b87)

Infos:
My phone is on Android 12
My emulator is on Android 13

ionic info:
![image](https://github.com/capacitor-community/sqlite/assets/21058915/48e7c9c9-48c3-4910-a2d8-3b644c74e3fb)

MainActivity.java (it's empty because Capacitor auto add plugins now since cap v4):
![image](https://github.com/capacitor-community/sqlite/assets/21058915/0a395804-1333-4698-b74a-c885c8cc7934)

Thank you for your time and help !

**Comment by jepiqueau** [comment]
@Hirumago Thanks for using the plugin you may look at [Ionic7Angular-SQLite-CRUD-App](https://jepiqueau.github.io/2023/08/26/Ionic7Angular-SQLite-CRUD-App.html) and/or at the documentation provided. Download the tutorial and tell me if you get the same error. i need to see more code especially the one where you define this.sqlite

**Comment by Hirumago** [comment]
Thanks @jepiqueau et sorry for the delay. I try this link and it's working. 
However, I tried to implement in my project with the same basics but it's not working. Maybe because I use workspace. I have to try ASAP. I'll keep you inform.

**Comment by Hirumago** [comment]
Hello, I just tried to use workspace but it was not working. There is my testing repo : [](https://github.com/Hirumago/test-community-sqlite/tree/main). 
I think I'm missing something about working with workspace but i don't really know what.

**Comment by jepiqueau** [comment]
@Hirumago can you explain what is workspace and what is the value to use it

**Comment by Hirumago** [comment]
We want to use workspace to do multi-app project. Use our library on multiples projects and technologies.

**Comment by Hirumago** [comment]
By the way, when i relaunch my app base on your tutorial, I have this message : "initializeAppError: Error: Query failed: SelectSQL: queryAll: no such table: users".

**Comment by jepiqueau** [comment]
@Hirumago on which platform this happen Android, iOS, Electron, Web? What do you mean by re-launch ? Can you comment quickly ?

**Comment by jepiqueau** [comment]
@Hirumago Did you create your workspace with this
```
ng new angular-multi-projects --createApplication=false
```

**Comment by Hirumago** [comment]
> @Hirumago on which platform this happen Android, iOS, Electron, Web? What do you mean by re-launch ? Can you comment quickly ?

That was on Android and Web.
Re-launch = I stopped my local server and I started again

**Comment by Hirumago** [comment]
> @Hirumago Did you create your workspace with this
> 
> ```
> ng new angular-multi-projects --createApplication=false
> ```

Yes, I followed :

https://github.com/ionic-team/ionic-cli/wiki/Angular-Monorepo
https://ionicframework.com/docs/cli/configuration?_gl=1*1p4obac*_ga*MzMxODIxNTYxLjE2OTI3NzI0Mjg.*_ga_REH9TJF6KF*MTY5NzAwNjQ4MC40MC4xLjE2OTcwMDY0ODguMC4wLjA.#multi-app-projects

**Comment by jepiqueau** [comment]
@Hirumago well you did not really follow it you do not have a Web folder and how do you create the app to have it in the apps folder as 
```
ng generate application --prefix=app --routing --style=css main-app
``` 
will generate the main-app under the root folder

**Comment by jepiqueau** [comment]
@Hirumago i git clone your app an run it without any issue in an emulator API 32  and on a physical device API 33

**Comment by jepiqueau** [comment]
@Hirumago can you give me after the git clone what are the set of commands that you do till the error so i can replicate exactly the same process flow.

**Comment by Hirumago** [comment]
> @Hirumago well you did not really follow it you do not have a Web folder and how do you create the app to have it in the apps folder as
> 
> ```
> ng generate application --prefix=app --routing --style=css main-app
> ```
> 
> will generate the main-app under the root folder

If I do that I'm missing depencies, including Capacitor so I have to manually add everything that Ionic is doing for me.
So what I've done was to skip a segment of the first docs to begin the other one. Here, when I did "ionic init --multi-app", I switched to the other one.

![image](https://github.com/capacitor-community/sqlite/assets/21058915/5f40b3f4-d374-4e32-9504-a650633e471a)
![image](https://github.com/capacitor-community/sqlite/assets/21058915/34d60589-7f65-4791-9e7d-65c120bc3b7e)

**Comment by jepiqueau** [comment]
@Hirumago  thanks for this but can you also answer my last comment as in fact i git clone your multi-app project and after having install everything and the go in the main-app folder and did the following commands
```
npm run build
npx  cap sync
npx cap copy
npx cap open android
```
and it works fine on both emulator and physical device

**Comment by G4mingEdition** [comment]
I got the same error "CapacitorSQLitePlugin: null" on android in an "Ionic/React" project

**Comment by jepiqueau** [comment]
@Hirumago Where do you stand on this? Wich version of Android Studio are you using?

**Comment by Hirumago** [comment]
> @Hirumago Where do you stand on this? Wich version of Android Studio are you using?

Android Studio Giraffe | 2022.3.1 Patch 1

![image](https://github.com/capacitor-community/sqlite/assets/21058915/945fcc17-97be-4287-93f3-d549706ae432)

Actually, I tried to clone my project and it works even after restarting it.
I guess, the problem was when I first start to implement the tutorial and server crashed but not showing it... I really don't get why the first one was not working. Or android folder was corrupted.

**Comment by jepiqueau** [comment]
@Hirumago it may be due to the Android cache so can you close the issue if it works
