### ISSUE TITLE
Cannot find module 'sqlite3'

### ISSUE THREAD

**Issue by narianangel** [capacitor-community/sqlite#477]
I followed all the steps in the documentation, but when I try to run a electron app i got a error message with "Cannot find module 'sqlite3'"

**Version**
"sqlite3": "^5.0.8", "electron": "25.8.4"

**Node.js Version**
Node.js v16.13.2

**Comment by narianangel** [comment]
I had a wrong electron / capacitor versions.

**Comment by MattSynaptic** [comment]
> I had a wrong electron / capacitor versions.

I just got this as well. What do you mean you had the wrong versions. How did you fix it?
