### ISSUE TITLE
Capacitor SQLite Plugin when the application is not running (terminated)

### ISSUE THREAD

**Issue by sadamameer** [capacitor-community/sqlite#480]
_**Is it feasible to add records to a database through the Capacitor SQLite Plugin when the application has been terminated? I'm utilizing the Capacitor Local Notifications Plugin, and my objective is to insert a record into the local database when the application responds to a local notification. It's important to note that, during this process, the application will not be running and will not be stored in RAM.**_

> **await db.query("INSERT INTO notifications (title,message,type,target_id,status,received_at) VALUES ('"+notification.title+"','"+notification.body+"','"+notification.extra.type+"',"+notification.extra.target_id+",'unread',"+received_at+")");**

_**Here's the code snippet I'm currently using to insert a record. It works perfectly when the application is active and listens to a local notification. However, when the application is closed, the record doesn't get inserted. Can you please provide guidance on how to address this issue?**_

**Thanks!**

**Comment by jepiqueau** [comment]
@sadamameer this is not possible with the way the plugin has been set up as the database are not sharable with other applications and i do not see à way to implement this. By the way db.query is made for SELECT and not for INSERT.
I keep this request in mind but it is not planned.
