### ISSUE TITLE
Android: Move databases folder to `/files/databases` 

### ISSUE THREAD

**Issue by erik-cc** [capacitor-community/sqlite#481]
**Is your feature request related to a problem? Please describe.**
Similiar problem like #77 - I am downloading a database from a server (using @capacitor/filesystem) and it get's stored in `/files` because the @capacitor/filesystem plugin can't interact with the root directory. Then I want to open this database.

**Describe the solution you'd like**
In #208 you mention to move the databases to the `/files/databases` folder. Is this possible or is there no way to change the android database location like `iosDatabaseLocation`?

Thank you!

**Comment by jepiqueau** [comment]
@erik-cc what is about security of having your databases stored on the files folder of the application

**Comment by erik-cc** [comment]
I am building an application that will be used on just one device by a small group of people. Also the device will only run this application. So in my case, I don't have to worry about the security of the database.

**Comment by jepiqueau** [comment]
@erik-cc what did you close it? Doyou want the database to be stored on files or do you want the ability after having downloading to files be move to the databases folder. The second one will be quite easy to do the first one will require to go through all the code to allow a custom database location like i dis for ios

**Comment by erik-cc** [comment]
I closed it by accident. Sorry!
The second approach would be fine. Am I missing something - how can I move the dowloaded file to the databases folder?

**Comment by jepiqueau** [comment]
@erik-cc if you use the files/databases folder just to transfer the database why do not you copy it to the cache and move it to the right location like this
```
    let response = await fetch("https://raw.githack.com/jepiqueau/angular-sqlite-app-starter/26ca67486713fc9b6ea4a37a889f0fd189c18926/src/assets/databases/dbForCopy.db");
    this.log += "  > fetched 'dbForCopy' from github\n";
    let dbBlob = await response.blob();
    let base64Db = await this.getBlobAsBase64(dbBlob);
    this.log += "  > converted 'dbForCopy' to base64\n";
    await Filesystem.writeFile({ data: base64Db, path: "dbForCopyCache.db", directory: Directory.Cache });
    this.log += "  > saved 'dbForCopyCache.db' in cache folder\n";
    await this._sqlite.moveDatabasesAndAddSuffix("cache");
    this.log += "  > moved 'dbForCopyCache' to databases folder\n";
    let db = await this._sqlite.createConnection("dbForCopyCache", false, "no-encryption", 1);
```
so you fetch it from your server convert the response blob to base64 use the Filesystem to write it to cache and then move the database  and add suffix from cache it will give you what you want 

```
  private getBlobAsBase64(blob: Blob): Promise<string> {
    return new Promise((resolve, _) => {
      let reader = new FileReader();
      reader.onload = (event: any) => {
        resolve(event.target.result);
      };
      reader.readAsDataURL(blob);
    });
  }
```

**Comment by jepiqueau** [comment]
@erik-cc if you. do this it works too
```
    await Filesystem.writeFile({ data: base64Db, path: "databases/dbForCopyCache.db", directory: Directory.Data });
    this.log += "  > saved 'dbForCopyCache.db' in cache folder\n";
    await this._sqlite.moveDatabasesAndAddSuffix("files/databases");
```

**Comment by erik-cc** [comment]
Oh! I didn't know about the `moveDatabasesAndAddSuffix` method. This solves the problem.
Thank you very much for you help!

**Comment by binaryking979** [comment]
Hello, 
I also had the same problem and followed your solution but it did not work. Could you please tell me again?

**Comment by binaryking979** [comment]
@jepiqueau

**Comment by binaryking979** [comment]
@jepiqueau 
Hello,
I also had the same problem and followed your solution but it did not work. Could you please tell me again?

**Comment by binaryking979** [comment]
@erik-cc 
Hello,I also had the same problem and followed your solution but it did not work. Did it run well?

**Comment by jepiqueau** [comment]
@binaryking979 look at [ionic-react-test-issues](https://github.com/jepiqueau/ionic-react-test-issues/tree/main/src/pages/FromHttpPage) this is an example

**Comment by erik-cc** [comment]
First I download the database using @capacitor/filesystem. Then I use `moveDatabasesAndAddSuffix` to move it, like this:

```js
const file = await Filesystem.downloadFile({
    url: `url-to-db`,
    path: '/data.db',
    directory: Directory.Cache,
    progress: false,
})

if (file.path) {
    await CapacitorSQLite.moveDatabasesAndAddSuffix({
        folderPath: 'cache',
        dbNameList: ['data.db'],
    })
}
```

**Comment by binaryking979** [comment]
Thank you for your help.

**Comment by jepiqueau** [comment]
@binaryking979 i am glad that you ffind the solution.
