### ISSUE TITLE
Double create connection

### ISSUE THREAD

**Issue by gassssty** [capacitor-community/sqlite#486]
Hi guys! 

I have implemented the SQL Lite of you guys in my **Ionic** App (v. 1.0.3) with Capacitor 3. The plugin version is this one:
"@capacitor-community/sqlite": "^3.4.1-1",

When I create the connection of the database, it executes the function two times:
![image](https://github.com/capacitor-community/sqlite/assets/83598997/e10630f6-70e1-47de-8549-2981959aed71)

Can you help me, please?
Thanks.

**Comment by jepiqueau** [comment]
@gassssty Upgrade your code to Capacitor 5 and the latest release of @capacitor-community/sqlite. release 3 of Capacitor is not supported anymore
