### ISSUE TITLE
execute method in sqliteconnection does not work when sending a delete query in ios alone but works in android. (ionic angular app )

### ISSUE THREAD

**Issue by rengadevigg** [capacitor-community/sqlite#488]
I have ionic angular application for ios and android. Recently i updated the capacitor 3 to 5. after updated capacitor 5 i update capacitor-community/sqlite-5 .40.2 version i think it does not get work properly in ios. But it works fine in android. Issue is I could not execute which means execute method the delete query and it returns changes: 0 in ios but in android it returns changes: 1. Any idea?

**Comment by jepiqueau** [comment]
@rengadevigg Sorry to come late i was busy on another plugin. You have to be more specific. Are you database standalone or coming from a remote server with the use of importFromJson and exportToJson methods and having the fields sql_deleted and last_modified?

**Comment by jepiqueau** [comment]
@rengadevigg Any news?

**Comment by rengadevigg** [comment]
It worked after adding ; at the end of the query.

**Comment by jepiqueau** [comment]
@rengadevigg yes it is mandatory as the execute statement in iOS SQLite can take several statements which is not the case for Android SQLite where the user'statements is split in individual stztement before to be executed by Androis SQLite. So i close the issue
