### ISSUE TITLE
fetch Column info bypass  chacking sqlite3_step(handle) when select Query in  ios

### ISSUE THREAD

**Issue by vikashsingh009** [capacitor-community/sqlite#49]
**Describe the bug**
i  am  trying  to  query sqlite  db  table  for  that  i  have useed UtillSqlite  Query Function ,but  when  i  am calling and  passing select  query  for  table ,its  not  checking while sqlite3_step(handle) == SQLITE_ROW 

**To Reproduce**

1. create a select  statement query  eg;  select *  from Users
2 Call  the SQlite Query function which  will  call  fetchColumnInfo
3. while loop sqlite3_step(handle) == SQLITE_ROW  failed but  passed  if  statement  like "Pragma user_version"

**Expected behavior**
should  return  column  name 

here is  error  point
       https://github.com/capacitor-community/sqlite/blob/master/ios/Plugin/Utils/UtilsSQLite.swift#L178

**Comment by jepiqueau** [comment]
@vikashsingh009 Can you be more specific what do you mean by `failed but passed if statement like "Pragma user_version" ` You mean its failed when you do `select * from Users`

**Comment by vikashsingh009** [comment]
Yes ,it failed for that select user query
