### ISSUE TITLE
Export / backup db binary file on Android device?

### ISSUE THREAD

**Issue by asika32764** [capacitor-community/sqlite#491]
I want to backup db binary files regularly for testing use, it's for internal use with no security concerns.

Currently we have `exportToJson()` method, and there has a way to export binary from localStorage if in Web environment, see https://github.com/jepiqueau/jeep-sqlite/issues/3

But It seems impossible to read the files from Android app's `databases/` folder, even we have the `getUrl()` method.

So is there has any way to save db binary to device documents folder if i was missed?

**Comment by asika32764** [comment]
I found that I can read DB raw data by:

```ts
const url = await db.getUrl();
  
  const file = await Filesystem.readFile({
    path: url.url!,
    encoding: Encoding.UTF8
  });

  const time = dateFormat('yyyy-MM-dd-HH-mm-ss');

  const r = await Filesystem.writeFile({
    path: `db/backup-${time}.db`,
    data: file.data,
    directory: Directory.Documents,
    recursive: true,
    encoding: Encoding.UTF8
  });
```

But after write to Documents and trying to read it by DB explorer, this file will corrupted and shows

> Error encountered when performing Introspect schema main: [SQLITE_CORRUPT] The database disk image is malformed 

I'm not sure how to handle this issue.

**Comment by asika32764** [comment]
I still cannot solve the corrupted files issue above, but finally I can read the db file if I use copy method.

This is my solution:

```ts
const url = await db.getUrl();

  const time = dateFormat('yyyy-MM-dd-HH-mm-ss');

  const r = await Filesystem.copy({
    from: url.url!,
    to: `db/backup-${time}.db`,
    toDirectory: Directory.Documents
  });
```

**Comment by jepiqueau** [comment]
@asika32764 thanks for this for me using copy is the best as it is a deep copy. May be it is due to the Encoding.ASCII may be it would have work with Encoding.UTF8. In my tutorials, can i use your suggestion if ones wants also to backup their database

**Comment by jepiqueau** [comment]
@asika32764 which is the application DB explorer that you are using in iOS and Android to read the database

**Comment by jepiqueau** [comment]
@asika32764 No news from you so i close it

**Comment by asika32764** [comment]
I'm using webstorm / phpstorm database reader.

I tried to compare 2 files but it seems they are same, I think maybe due to some difference in the file metadata.
