### ISSUE TITLE
Request: Add examples for angular and sqlite without Ionic.

### ISSUE THREAD

**Issue by DannyBoyNg** [capacitor-community/sqlite#499]
Could you add examples for angular and sqlite, but without using Ionic. Most of your examples use Ionic and I would like to see examples without Ionic.
I would like to see an example specifically for web. I can get the mobile and sqlite working without Ionic but web is a huge pain to figure out.

**Comment by jepiqueau** [comment]
@DannyBoyNg which framework

**Comment by DannyBoyNg** [comment]
Angular

**Comment by jepiqueau** [comment]
@DannyBoyNg i do not know what is the issue
- You create your angular project
- You install capacitor
- ng add @capacitor/angular
- ng build --prod
- npm i @capacitor/ios @capacitor/android
- npx cap add ios
- npx cap add android
- npm i @capacitor-community/sqlite
- édit your capacitor.config.ts file as per my tutorial  site for ionic angular 
- follow the same setup that on the tutorial
- add the services
- Develop your own code

When all is done
- npx cap sync
- ng build --prod
- npx cap copy

For Web 
- ng serve

For iOS
-npx cap open iox

For Android
-npx cap open android

That is it

**Comment by DannyBoyNg** [comment]
I followed your instructions and the code works fine for android and ios but for web I always get runtime errors.

![2024-01-15 160400](https://github.com/capacitor-community/sqlite/assets/1233297/21be67b3-50fb-4b8c-9786-384c2a6dcece)

The above error I fixed by copying the files in "SqliteTest\node_modules\jeep-sqlite\dist\esm" to "SqliteTest\.angular\cache\17.0.10\vite\deps". After fixing this error I get a different error:


![2024-01-15 161219](https://github.com/capacitor-community/sqlite/assets/1233297/aacd9897-4c35-4d1b-bfb7-7dbd3ebd416e)

![2024-01-15 161316](https://github.com/capacitor-community/sqlite/assets/1233297/d4cc11c6-95d3-4f2d-a9e0-16985102380b)

I can't figure out how to fix these errors. Could you help. I tried it in Chrome and Firefox but I get the same result.

**Comment by jepiqueau** [comment]
@DannyBoyNg Can you share your app on github

**Comment by jepiqueau** [comment]
@DannyBoyNg see example [test-angular-sqlite-app](https://github.com/jepiqueau/test-angular-sqlite-app) hope this will be helpful

**Comment by DannyBoyNg** [comment]
Thank you for the examples @jepiqueau. I'll look into it soon.
