### ISSUE TITLE
Support API level 34 on Android

### ISSUE THREAD

**Issue by ygarg465** [capacitor-community/sqlite#501]
**Is your feature request related to a problem? Please describe.**
I am not able to use this library for devices having API level 34 it throws an error.

**Describe the solution you'd like**
Add support for API level 34 that is TIRAMISU and above

**Comment by ygarg465** [comment]
> @ygarg465 nice comment but capacitor5 do not support API34

Ohh that's why, but the app runs just fine on API 34??

**Comment by jepiqueau** [comment]
@ygarg465 i have issue a first release npm i --save @capacitor-community/sqlite@capv6 i tested it in Android, Electron and Web and it works fine. I could not tested it in iOS as it requires Xcode15+ which is not available for my MacBook Pro too old. so you can use it for Android API34
