### ISSUE TITLE
Support for dynamic database path

### ISSUE THREAD

**Issue by ygarg465** [capacitor-community/sqlite#502]
**Is your feature request related to a problem? Please describe.**
Is there any way to specify path to database in the code instead of capacitor.config.ts file because I want separate folder for separate database.

**Describe the solution you'd like**
A way to dynamically create database with specifying location for the file

**Describe alternatives you've considered**
I haven't found any alternative for the same.

**Comment by jepiqueau** [comment]
@ygarg465 you can create multiple databases but they are all at the same location
