### ISSUE TITLE
The run method returns the wrong type

### ISSUE THREAD

**Issue by playaz87** [capacitor-community/sqlite#506]
`run()` returns the type:

```
interface capSQLiteChanges {
  changes?: Changes;
}

interface Changes {
  changes?: number;
  lastId?: number;
  values?: any[];
}
```

However the actual returned data is of type `Changes`

**Comment by jepiqueau** [comment]
@playaz87 on which platform?

**Comment by jepiqueau** [comment]
@playaz87 After checking all platform i do not see it is the case

**Comment by playaz87** [comment]
@jepiqueau 

I appologise. I checked again and it seems to be correct. I'm sure it wasn't working yesterday as I have to override the return type. I must have been tired... again I appologise for wasting your time.
