### ISSUE TITLE
out of memory since 1.9.0

### ISSUE THREAD

**Issue by JuanLongines** [capacitor-community/sqlite#509]
I have tracked the issue in the sql.js repository because since version 1.9.0 I have had this problem, they just recently closed it but I continue with the problem.

https://github.com/sql-js/sql.js/issues/561#issuecomment-1849080965

Latest version :
https://github.com/sql-js/sql.js/issues/561#issuecomment-1905270851

@jepiqueau in the last commit I saw that you did a rollback to version 1.8.0 there is no way to use the last one?

**Comment by jepiqueau** [comment]
@JuanLongines you said they fix the issue but you continue to have the issue so for the time being i stick to the 1.8.0 release. If you can share on github your app where you have still the issue using 1.9.0 i may have a look

**Comment by JuanLongines** [comment]
> @JuanLongines you said they fix the issue but you continue to have the issue so for the time being i stick to the 1.8.0 release. If you can share on github your app where you have still the issue using 1.9.0 i may have a look

I'm using the repository example, no additional code just updating **sql.js** version **1.10.2**
https://github.com/jepiqueau/blog-tutorials-apps/tree/main/SQLite/Part-1/ionic7-angular-sqlite-app

**Comment by jepiqueau** [comment]
@JuanLongines Did it works with sql.js version 1.10.2

**Comment by folsze** [comment]
Is it possible that this did not fix it? 

I am still experiencing this error, even after updating to 5.5.2

I will update here if I was wrong, but if this happens to you too then maybe like this message.

**Comment by JuanLongines** [comment]
yes I continue getting the same error, update to the latest versions:

![image](https://github.com/capacitor-community/sqlite/assets/51804152/17163f28-7707-4a01-8de0-fa5867a28789)

and the error: 

![image](https://github.com/capacitor-community/sqlite/assets/51804152/37cd14ab-1e7f-4ea6-b124-eaf57b45df46)

**Comment by folsze** [comment]
I was missing this step! Thanks a lot, especially for mentioning this again, that I have to copy the `sql-wasm.wasm` file.

**Comment by jepiqueau** [comment]
@folsze you always have to copy the wasm file especially when the version of sql.js change that why it is better to have it in your scripts  the build script should be amended to make the copy prior to build see example on my tutorial site
