### ISSUE TITLE
Update 5.6.0

### ISSUE THREAD

**Issue by MonicaSvs** [capacitor-community/sqlite#516]
I'm working on a project ionic 7, capacitor 5 and angular 15. I've updated sqllite to the latest version (5.6.0), but when I synchronize on Android it gives me several errors. 
An extract of the errors:

**./node_modules/sql.js/dist/sql-wasm.js:790:18-35 - Warning: Module not found: Error: Can't resolve 'crypto' in 'C:\Users\m.ria\Repository\EasyOBL-Trasporti\node_modules\sql.js\dist'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
        - install 'crypto-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "crypto": false }

./node_modules/@capacitor-community/sqlite/dist/esm/web-typeorm-utils/utilsSQLite.js:16:14-27 - Error: Module not found: Error: Can't resolve 'os' in 'C:\Users\m.ria\Repository\EasyOBL-Trasporti\node_modules\@capacitor-community\sqlite\dist\esm\web-typeorm-utils'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "os": require.resolve("os-browserify/browser") }'
        - install 'os-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "os": false }

./node_modules/@capacitor-community/sqlite/dist/esm/web-typeorm-utils/utilsSQLite.js:17:14-27 - Error: Module not found: Error: Can't resolve 'fs' in 'C:\Users\m.ria\Repository\EasyOBL-Trasporti\node_modules\@capacitor-community\sqlite\dist\esm\web-typeorm-utils'

./node_modules/@capacitor-community/sqlite/dist/esm/web-typeorm-utils/utilsSQLite.js:18:16-31 - Error: Module not found: Error: Can't resolve 'path' in 'C:\Users\m.ria\Repository\EasyOBL-Trasporti\node_modules\@capacitor-community\sqlite\dist\esm\web-typeorm-utils'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
        - install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "path": false }

./node_modules/sql.js/dist/sql-wasm.js:548:15-28 - Error: Module not found: Error: Can't resolve 'fs' in 'C:\Users\m.ria\Repository\EasyOBL-Trasporti\node_modules\sql.js\dist'

./node_modules/sql.js/dist/sql-wasm.js:549:13-28 - Error: Module not found: Error: Can't resolve 'path' in 'C:\Users\m.ria\Repository\EasyOBL-Trasporti\node_modules\sql.js\dist'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
        - install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "path": false }

[ERROR] An error occurred while running subprocess ng.

        ng.cmd run app:build exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.**

In the meantime I reverted to the previous version.

Someone can help me?

**Comment by mirulshahqube** [comment]
> I'm working on a project ionic 7, capacitor 5 and angular 15. I've updated sqllite to the latest version (5.6.0), but when I synchronize on Android it gives me several errors. An extract of the errors:
> 
> **./node_modules/sql.js/dist/sql-wasm.js:790:18-35 - Warning: Module not found: Error: Can't resolve 'crypto' in 'C:\Users\m.ria\Repository\EasyOBL-Trasporti\node_modules\sql.js\dist'
> 
> BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default. This is no longer the case. Verify if you need this module and configure a polyfill for it.
> 
> If you want to include a polyfill, you need to: - add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }' - install 'crypto-browserify' If you don't want to include a polyfill, you can use an empty module like this: resolve.fallback: { "crypto": false }
> 
> ./node_modules/@capacitor-community/sqlite/dist/esm/web-typeorm-utils/utilsSQLite.js:16:14-27 - Error: Module not found: Error: Can't resolve 'os' in 'C:\Users\m.ria\Repository\EasyOBL-Trasporti\node_modules@capacitor-community\sqlite\dist\esm\web-typeorm-utils'
> 
> BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default. This is no longer the case. Verify if you need this module and configure a polyfill for it.
> 
> If you want to include a polyfill, you need to: - add a fallback 'resolve.fallback: { "os": require.resolve("os-browserify/browser") }' - install 'os-browserify' If you don't want to include a polyfill, you can use an empty module like this: resolve.fallback: { "os": false }
> 
> ./node_modules/@capacitor-community/sqlite/dist/esm/web-typeorm-utils/utilsSQLite.js:17:14-27 - Error: Module not found: Error: Can't resolve 'fs' in 'C:\Users\m.ria\Repository\EasyOBL-Trasporti\node_modules@capacitor-community\sqlite\dist\esm\web-typeorm-utils'
> 
> ./node_modules/@capacitor-community/sqlite/dist/esm/web-typeorm-utils/utilsSQLite.js:18:16-31 - Error: Module not found: Error: Can't resolve 'path' in 'C:\Users\m.ria\Repository\EasyOBL-Trasporti\node_modules@capacitor-community\sqlite\dist\esm\web-typeorm-utils'
> 
> BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default. This is no longer the case. Verify if you need this module and configure a polyfill for it.
> 
> If you want to include a polyfill, you need to: - add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }' - install 'path-browserify' If you don't want to include a polyfill, you can use an empty module like this: resolve.fallback: { "path": false }
> 
> ./node_modules/sql.js/dist/sql-wasm.js:548:15-28 - Error: Module not found: Error: Can't resolve 'fs' in 'C:\Users\m.ria\Repository\EasyOBL-Trasporti\node_modules\sql.js\dist'
> 
> ./node_modules/sql.js/dist/sql-wasm.js:549:13-28 - Error: Module not found: Error: Can't resolve 'path' in 'C:\Users\m.ria\Repository\EasyOBL-Trasporti\node_modules\sql.js\dist'
> 
> BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default. This is no longer the case. Verify if you need this module and configure a polyfill for it.
> 
> If you want to include a polyfill, you need to: - add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }' - install 'path-browserify' If you don't want to include a polyfill, you can use an empty module like this: resolve.fallback: { "path": false }
> 
> [ERROR] An error occurred while running subprocess ng.
> 
> ```
>     ng.cmd run app:build exited with exit code 1.
> 
>     Re-running this command with the --verbose flag may provide more information.**
> ```
> 
> In the meantime I reverted to the previous version.
> 
> Someone can help me?

hi im facing the same problem. may i know which version that you reverted to. Im thinking that i want to use the previous version first while they address this issue

**Comment by MonicaSvs** [comment]
I reverted to 5.5.2

**Comment by jepiqueau** [comment]
@MonicaSvs Thanks for reporting, i saw the issue, for Angular you have to stick to 5.5.2 till i solve the issue. I made some changes for TypeOrm users which works fine with React and Svelte but cause that issue for Angular.  I start yesterday on it but did not find a solution yet. I will keep you updated

**Comment by jepiqueau** [comment]
@MonicaSvs @mirulshahqube this must be fixed in v5.6.1-1 Can you test an revert back Thanks for your patience.

**Comment by MonicaSvs** [comment]
@jepiqueau Great work! Everything works correctly!
Thanks!

**Comment by jepiqueau** [comment]
@MonicaSvs thanks for your feedback, i close the issue then
