### ISSUE TITLE
Electron Platform SQL92 false generates invalid SQL query

### ISSUE THREAD

**Issue by ygarg465** [capacitor-community/sqlite#518]
**Describe the bug**
Calling the query method of the library on the electron platform generates an invalid SQL query when having the isSQL92 parameter equal to false.

The generated query has the table name and 'WHERE' clause having no space between them.

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser Electron
- Version 25.8.4

**Additional context**
[whereSQL92 method in UtilsSQL92Compatibility  class](https://github.com/capacitor-community/sqlite/blob/10a88ddbaf1b3d5680e2913971871c83e59a133a/electron/src/electron-utils/UtilsSQL92Compatibility.ts#L55C2-L66C4)

I think this is also causing [this](https://github.com/capacitor-community/sqlite/blob/523bacce721c0d05fe38f026a5f8b35ef8dc790e/src/definitions.ts#L2169C2-L2200C4) problem where we are passing different cased isSQL92 property to the method.

@jepiqueau can you take a look at this.

Thanks

**Comment by ygarg465** [comment]
@jepiqueau this was the sql query which failed with isSQL92 = true
```sql
SELECT version FROM _electric_migrations
        WHERE version != '0'
        ORDER BY version DESC
        LIMIT 1
````

**Comment by jepiqueau** [comment]
@ygarg465 this must be fixed in v5.6.1-1

**Comment by ygarg465** [comment]
And why do we pass different properties to the same query method
```typescript
 async query(
    statement: string,
    values?: any[],
    isSQL92 = true,
  ): Promise<DBSQLiteValues> {
    let res: any;
    try {
      if (values && values.length > 0) {
        res = await this.sqlite.query({
          database: this.dbName,
          statement: statement,
          values: values,
          readonly: this.readonly,
          isSql92: true,
        });
      } else {
        res = await this.sqlite.query({
          database: this.dbName,
          statement: statement,
          values: [],
          readonly: this.readonly,
          isSQL92: isSQL92,
        });
      }

      // reorder rows for ios
      res = await this.reorderRows(res);
      return Promise.resolve(res);
    } catch (err) {
      return Promise.reject(err);
    }
  }
```

**Comment by ygarg465** [comment]
@jepiqueau Looks good 👍

**Comment by jepiqueau** [comment]
@ygarg465 thanks for the feedback
