### ISSUE TITLE
SQL query is converted to be compatible with SQL92 regardless of argument value of isSQL92 in query method when values argument is an empty array

### ISSUE THREAD

**Issue by ygarg465** [capacitor-community/sqlite#519]
**Describe the bug**
query method of the library is converting the SQL query to be compatible with SQL92 whether or not isSQL92 parameter is true or false.
This occurs when the query method has values as an empty array. 

**Desktop (please complete the following information):**

- OS: Windoes
- Browser Electron
- Version 25.8.4

**Additional context**

@jepiqueau I think the problem occurs due to this [code](https://github.com/capacitor-community/sqlite/blob/523bacce721c0d05fe38f026a5f8b35ef8dc790e/src/definitions.ts#L2169C2-L2200C4)
```typescript
 async query(
    statement: string,
    values?: any[],
    isSQL92 = true,
  ): Promise<DBSQLiteValues> {
    let res: any;
    try {
      if (values && values.length > 0) {
        res = await this.sqlite.query({
          database: this.dbName,
          statement: statement,
          values: values,
          readonly: this.readonly,
          isSql92: true, // we check for this value further down in the code
        });
      } else {
        res = await this.sqlite.query({
          database: this.dbName,
          statement: statement,
          values: [],
          readonly: this.readonly,
          isSQL92: isSQL92, // but this is invalid I think
        });
      }

      // reorder rows for ios
      res = await this.reorderRows(res);
      return Promise.resolve(res);
    } catch (err) {
      return Promise.reject(err);
    }
  }
```

**Comment by jepiqueau** [comment]
@ygarg465 i do not understand why you said is wrong. 
 - When there is some values, we do not need to check so isSQL92 = true  which is correct.
 - When there is no values, depending on the value of isSQL92 entered by the developer, the query will use the statement as is if isSQL92 is true or will modify the statement to make it SQL92 compatible which is correct

**Comment by ygarg465** [comment]
@jepiqueau The problem is the object being passed to the `the.sqlite.query` method, read the comment in the code block.

The `isSql92` and `isSQL92` are two different properties.

**Comment by jepiqueau** [comment]
@ygarg465 okn thanks it is isSql92 which is wrong so i will fix this in the next release

**Comment by jepiqueau** [comment]
@ygarg465 v5.6.1 has been released. After test on your side can you close the issue

**Comment by ygarg465** [comment]
@jepiqueau Yes this works perfectly fine and Thanks for releasing it this fast :)
