### ISSUE TITLE
Encryption question

### ISSUE THREAD

**Issue by jtheiss** [capacitor-community/sqlite#52]
Hi, 

as soon as i enable the encryption every single request works, but takes ~500ms on my real android device. 
(without encryption it is ~30ms).
After a look at your plugin this may be due to connection open & close with every request. 

The question is:
Is 500ms a normal/expected value because it seems very high to me? (Samsung A50, so the phone is not that old)

Thanks & have a good day!

**Comment by jepiqueau** [comment]
@jtheiss thanks for using the plugin, Are you comparing the same request with and without encryption. the `connection open and close` is done the same way for with and without encryption and it give access security to the database for each request. I have notice that the android plugin is slower compare to the iOS plugin. In android i use the `net.sqlcipher.database.SQLiteDatabase`, `net.sqlcipher.database.SQLiteOpenHelper` and `net.sqlcipher.database.SQLiteStatement` where with iOS i worked directly with the sqlite3 api. How have you done the the time test as i might have a look at this. For the time being i am developing the sqlcipher encryption for the Electron plugin which requires all my attention.

**Comment by jtheiss** [comment]
@jepiqueau Thank you for your response!

At first i noticed this with the app i am currently working on. 
To be sure there is no other influcence i created a plain ionic/angular app with the cli, added the sqlite plugin and the following simple code for testing:

```
import { Injectable } from '@angular/core';
import { Plugins } from '@capacitor/core';
const { CapacitorSQLite } = Plugins;

@Injectable()
export class DatabaseService {

    constructor() {
        this.createTable();
    }

    async createTable() {
        await CapacitorSQLite.requestPermissions();
        await CapacitorSQLite.open({ database: 'testing.db', encrypted: true, mode: 'secret' });
        await CapacitorSQLite.run({ statement: 'CREATE TABLE IF NOT EXISTS test (id INTEGER PRIMARY KEY, name TEXT, timestamp INTEGER);' });
    }

    public async test() {
        console.log('starting test');
        let startTime = 0;

        for (let i = 1; i <= 10; i++) {
            startTime = Date.now();
            await CapacitorSQLite.executeSet({
                set: [{
                    statement: `REPLACE INTO test (name, timestamp) VALUES (?, ?)`,
                    values: [i, Date.now()]
                }]
            });
            console.log(Date.now() - startTime);
        }

        const statements = [];
        for (let i = 1; i <= 10; i++) {
            statements.push({
                statement: `REPLACE INTO test (name, timestamp) VALUES (?, ?)`,
                values: [i, Date.now()]
            });
        }
        startTime = Date.now();
        await CapacitorSQLite.executeSet({ set: statements });
        console.log(Date.now() - startTime);

        startTime = Date.now();
        await CapacitorSQLite.query({ statement: `SELECT * FROM test`, values: [] });
        console.log(Date.now() - startTime);
    }
}
```

No matter if i execute 1 statement in the executeSet or all 10 together in one set it shows >500 ms with encryption.
It does not happen on the executeSet only, also the query takes the same amount of time.

Even the open & run  commands show this behaviour when i check the timestamps in adblog.

When i switch to no encryption by changing the open command { database: 'testing.db', encrypted: false, mode: null }
every command takes only 30 to 40ms.

So the commands are the same and very simple. 
For me it looks like there is something expensive like key derivation performed with every request but thats only a vague guess.
It is absolutely clear that it takes longer when encryption is enabled but x10 is quiet much.

**Comment by jepiqueau** [comment]
@jtheiss I have published a first alpha release of the refactor `npm i @capacitor-community/sqlite@refactor` and provide an Ionic/angular app to demonstrate the use `https://github.com/jepiqueau/angular-sqlite-app-refactor`.I have remove the open/close for each sqlite query, that should normally give a better response time. the interface of the plugin has changed allowing for connection to multiple databases and simpler interfacing like `db.open(), db.close()` If you could have a look and comment

**Comment by jtheiss** [comment]
@jepiqueau Thank you for your effort!

I quickly did the needed changes to my testapp and it seems to work good on android now.
There is no noticeable difference between unencrypted & encrypted anymore for this simple case.


One thing i noticed:
When i query a table wich does not exist (yes, this is my fault - meant only as feedback ;-) 
the app crashes and gets closed immediately.

` FATAL EXCEPTION: CapacitorPlugins
 Caused by: net.sqlcipher.database.SQLiteException: no such table: nonexistingtable: , while compiling: SELECT * FROM nonexistingtable;
        at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
        at net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:89)`

I would expect something like `message: "Query command failed"` as it was before.

**Comment by jepiqueau** [comment]
@jtheis Do you mean that you have tested with the plugin refactor? You have to understand that it is not finalize yet but it good that you test it and report issues. that will help to debug and get a better and stable release when publish.
Thanks for your help.

**Comment by jepiqueau** [comment]
@jtheiss I didn't succeed to crash the app when inserting in a non existing table. Did you test the `result.changes.changes === -1` before continuing the rest of the code ?

```
    ...
    // Test on wrong table ; the table test does not exist
    const sql = "INSERT INTO test (name) VALUES (?)";
    const vals  = ["test wrong table "];
    result = await db.run(sql, vals);
    console.log('$$$ wrong table ret.changes.changes in db' + result.changes.changes)
    if (ret.changes.changes === -1 ) {
      return false;
    }
    ...

```

**Comment by jtheiss** [comment]
@jepiqueauy Yes, i did test the plugin refactor, sorry if that was unclear. 
It is absolutely clear to me that this is an early not finished version and i will not really use it until a published version arrives.
I just tested it with my "sandbox" app only to provide you some hopefully useful feedback.

The crashing-problem does appear on a real android device with a simple query (SELECT * FROM nonexistingtable;) and it immediately crashes on native side (SQLiteCompiledSql.java:89) with the adb entry i previously provided. No javascript callback arrived at all to work with.

It is perfectly reproducable here. So let me know if you need any more information.

**Comment by jepiqueau** [comment]
@jtheiss thanks for the clarification, your feedback are important to me, so thanks for taking the time.
Can you share the code, on github, where the crash happen. What do you mean by `with the adb entry i previously provided` ? So please give me more info

**Comment by jepiqueau** [comment]
@jtheiss What is the Android device are you doing the test and what is the Android (API level) on this device

**Comment by jepiqueau** [comment]
@jtheiss i test it on my physical device which is quite old Samsung Note3 running lollipop and the app failed. It cannot open the database.
```
E/Capacitor: Serious error executing plugin
    java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:99)
        at com.getcapacitor.Bridge$1.run(Bridge.java:526)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:145)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: net.sqlcipher.database.SQLiteException: error code 14: Could not open database

```

**Comment by jepiqueau** [comment]
@jtheiss i finally got it working on my samsung and it work without crashing when i ask to insert in a wrong table without changing the code. the problem above come from the `deleteDatabase` i still have to figure out this

**Comment by jtheiss** [comment]
@jepiqueau I tested on Samsung A50 (Android 10), but have several testing devices if you want me to test some specific android version. Just let me know.

As i said the crash does not happen on INSERT or REPLACE. Just on SELECT.

**Comment by jtheiss** [comment]
@jepiqueau ADB log means the following lines taken from the native log of the phone:

```FATAL EXCEPTION: CapacitorPlugins Caused by: net.sqlcipher.database.SQLiteException: no such table: nonexistingtable: , while compiling: SELECT * FROM nonexistingtable; at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method) at net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:89)```

So its clear what exact statement caused the problem in which file at which line.

**Comment by jepiqueau** [comment]
@jtheiss i just published a new release i changed the select the try was not at the right position. Can you test and tell me if it is working now

**Comment by jepiqueau** [comment]
@jtheiss the new release is `2.9.0-alpha.3`

**Comment by jtheiss** [comment]
@jepiqueau confirmed working with 2.9.0-alpha.3

**Comment by jepiqueau** [comment]
@jtheiss Thanks for the confirmation 👍

**Comment by jepiqueau** [comment]
@jtheiss the refactor is now on release 2.9.0-beta.1 and got all the features available for the 3 platforms. I think you can start planning to use it
