### ISSUE TITLE
"CapacitorSQLite" plugin is not implemented on ios

### ISSUE THREAD

**Issue by itsalb3rt** [capacitor-community/sqlite#530]
**Describe the bug**

I received `"CapacitorSQLite" plugin is not implemented on ios` in the console after running the iOS emulator, using Quasar v2

- I have a plugin installed on my `package.json` 
- I have the capacitor configuration
```
{
  "appId": "org.myapp.app",
  "appName": "mutus",
  "bundledWebRuntime": false,
  "npmClient": "yarn",
  "webDir": "www",
  "server": {
    "androidScheme": "https",
    "url": "http://10.0.0.6:9500"
  },
  "plugins": {
    "CapacitorSQLite": {
      "iosDatabaseLocation": "Library/MyDatabase",
      "iosIsEncryption": false,
      "iosKeychainPrefix": "my-app",
      "iosBiometric": {
        "biometricAuth": false,
        "biometricTitle": "Biometric login for myapp sqlite"
      },
      "androidIsEncryption": true,
      "androidBiometric": {
        "biometricAuth": false,
        "biometricTitle": "Biometric login for myapp sqlite",
        "biometricSubTitle": "Log in using your biometric"
      }
    }
  }
}
```
- I run the `npx cap sync` and `npx cap sync ios`

Only one thing won't happened in my `Podfile` the plugin is not in the list and when I add this manually, the `npx cap sync` removed that from the list, this is my `Podfile`

```
require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '13.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCommunityAppleSignIn', :path => '../../node_modules/@capacitor-community/apple-sign-in'
  pod 'CapacitorApp', :path => '../../node_modules/@capacitor/app'
  pod 'CapacitorFilesystem', :path => '../../node_modules/@capacitor/filesystem'
  pod 'CodetrixStudioCapacitorGoogleAuth', :path => '../../node_modules/@codetrix-studio/capacitor-google-auth'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end

post_install do |installer|
  assertDeploymentTarget(installer)
end

```

**Comment by jepiqueau** [comment]
@itsalb3rt Did you look at the tutorial at https://github.com/jepiqueau/jepiqueau.github.io/blob/main/_posts/2023-11-28-Quasar-SQLite-CRUD-App.md clone it and run it. is it working. If yes look at the différences with your code.

**Comment by itsalb3rt** [comment]
Yes, I follow this step by step but not working on my project

**Comment by itsalb3rt** [comment]
ohhh Sh**tt I see the problem, I have a `src-capacitor` dir, and I install the `@capacitor-community/sqlite` package outside this lol, sorry. thanks!

**Comment by jepiqueau** [comment]
@itsalb3rt 👍

**Comment by nimishdesai1989** [comment]
I am getting the same error 
 [log] - initializeAppError: Error: "CapacitorSQLite" plugin is not implemented on ios
⚡️  [error] - ERROR {"code":"UNIMPLEMENTED"}
⚡️  [log] - {"code":"UNIMPLEMENTED"}

i checked all installations but still get this issue only on iOS. Any idea on how to solve this ?
