### ISSUE TITLE
Multi Row Statement does not escape characters

### ISSUE THREAD

**Issue by lasher23** [capacitor-community/sqlite#535]
**Describe the bug**
Using a multi row statement via the executeSet Plugin Method does not escape special characters 

**To Reproduce**
1. use executeSet method
2. pass a two dimensional array as paramter to trigger multi row statement
3. pass as one parameter of the value a string with a special charachter, like '

**Expected behavior**
If a special character is used it should be appropriatly escaped

**Desktop (please complete the following information):**

- OS: Android --> unknown if the same error persists on IOS
- Browser chrome 
- Version 5.7.0

**Comment by jepiqueau** [comment]
@lasher23 please give a full example

**Comment by lasher23** [comment]
Yeah Sure i also created a [pull request](https://github.com/capacitor-community/sqlite/pull/537)

`
execute("create table abc (name varchar(20))")
executeSet([{statement: "insert into abc(name) values (?)", values: ["a'b"]}])
`

**Comment by jepiqueau** [comment]
@lasher23 fix in v5.7.3-2 thanks for your contribution

**Comment by lasher23** [comment]
@jepiqueau thank you for merging
