### ISSUE TITLE
Multiple Row Statement Values case insensitive

### ISSUE THREAD

**Issue by lasher23** [capacitor-community/sqlite#536]
**Describe the bug**
The Multiple Row Statement only matches if "VALUES" is written in caps. The SQL is also valid if it is written in lowercase.

**To Reproduce**
1. use executeSet method
2. pass a two dimensional array as paramter to trigger multi row statement
3. pass SQL statement with values written in lower case.

**Expected behavior**
Behaves exactly the same as if it would be written in upper case

**Desktop (please complete the following information):**
- OS: Android --> unknown if the same error exists on IOS
- Browser chrome
- Version 5.7.0

**Comment by jepiqueau** [comment]
@lasher23 please give a full example of your statement

**Comment by jepiqueau** [comment]
@lasher23 fix in v5.7.3-2

**Comment by lasher23** [comment]
@jepiqueau thank you for fixing this
