### ISSUE TITLE
Multirow statements inserts wrong semicolon

### ISSUE THREAD

**Issue by lasher23** [capacitor-community/sqlite#538]
**Describe the bug**
After the replaced values in the multirow statement it always inserts a semicolon. [Code](https://github.com/capacitor-community/sqlite/blob/master/android/src/main/java/com/getcapacitor/community/database/sqlite/SQLite/Database.java#L523)

This only works if the insert has the values at the end of the statement. 
`Insert into values (?,?,?)` changes into `Insert into table values ('','','');`
If we for example use the SQLite Upsert/On Conflict the values are not at the end of the statement.
`INSERT INTO users (name, email) VALUES (?, ?)   ON CONFLICT(email) DO UPDATE SET name = excluded.name` changes into 
`INSERT INTO users (name, email) VALUES ('', '');  ON CONFLICT(email) DO UPDATE SET name = excluded.name`

This transforms is an invalid statement

**To Reproduce**

1. Execute the statements from above

**Expected behavior**
No semicolon is inserted at all.

**Desktop (please complete the following information):**

- OS: Android --> unknown if the same error exists on IOS
- Browser chrome
- Version 5.7.0

**Comment by jepiqueau** [comment]
@lasher23 fix in v5.7.3-2 thanks for your contribution

**Comment by lasher23** [comment]
@jepiqueau thank you for merging
