### ISSUE TITLE
Is there a way to open an existing database?

### ISSUE THREAD

**Issue by eduard1993-sudo** [capacitor-community/sqlite#54]
Hello,
Is there a way to open an existing .db file on android and ios?
I'm using this plugin for the first time and I want to open an existing .db file ( called "mydatabase.db) which in pre-populated.
1. where i should put the .db file?
2. how the code will look for opening and querying and existing db?
Many thanks!

**Comment by jepiqueau** [comment]
@eduard1993-sudo Hi, thanks for looking at the plugin. i never test but i do not see any reason why not.
According to the API doc 
```
The plugin add a suffix "SQLite" and an extension ".db" to the database name given as options in the open method ie (fooDBSQLite.db)

Android
data/data/YOUR_PACKAGE/databases
IOS
in the Document folder of YOUR_APPLICATION

```
so your database should be rename as `mydatabaseSQLite.db` and when you open the database the command should be  something 
```
await this.sqlite.open({database: mydatabase,
                                            encrypted: false,
                                            mode: "no-encrytion",
                                            version: 1}));
``` 
Have a look at the different app starters (Ionic/Angular, Ionic/React, Ionic/Vue, React or Vue) depending on the framework you are using. Keep me aware

**Comment by eduard1993-sudo** [comment]
Hey jepiqueau, thank you so much for your message and support.
I will try this solution, i didn't name the .db file with "SQLite.db" at the end and the parameter for .open method without the suffix.
But until tomorrow, i do have one more question:
Where is the path data/data/MY_APP/databases ? i can't find it. should i create it?

I uploaded a pic with the tree in my android project dummy app. (i suppose that i have to add the .db file in android studio, after "ionic build" and "npx cap copy" and run android. right?

Many thanks again for your help, I really cannot switch to capacitor if i don't make it work with this plugin to open a local db file. All the best!

![tree android project](https://user-images.githubusercontent.com/74826125/99884610-51607a00-2c38-11eb-9dfe-5791aec3238b.PNG)

**Comment by jepiqueau** [comment]
@eduard1993-sudo In Android Studio, open the `Device File Explorer` Select your device emulator or your physical device 

![image](https://user-images.githubusercontent.com/16580653/99897167-8819ad00-2c97-11eb-8de2-821e8b84741d.png)

Look for the package define in your manifest file

```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="io.ionic.starter">

    <application

```

![image](https://user-images.githubusercontent.com/16580653/99897240-31f93980-2c98-11eb-8f45-108bec8c9ac8.png)

then create a `databases` folder in the package ie `io.ionic.starter` 
Click on `databases` and upload your database file
that is it

**Comment by jepiqueau** [comment]
@eduard1993-sudo   Is that solved your issue? if yes can you please close the issue

**Comment by eduard1993-sudo** [comment]
Sure! all the best!!
