### ISSUE TITLE
Create CapacitorJS v6 package compatibility

### ISSUE THREAD

**Issue by bluepuma77** [capacitor-community/sqlite#541]
**Describe the bug**
CapacitorJS v6.0 was just released ([Github](https://github.com/ionic-team/capacitor/releases/tag/6.0.0), [Blog](https://ionic.io/blog/announcing-capacitor-6-0)). Now `npm` is throwing error on update, need to use `--force` or `--legacy-peer-deps` to make it work.

**To Reproduce**
Update all npm libraries to latest with `ncu -u`, then run `npm i`.

**Expected behavior**
Should work without "force".

**Additional context**
Big question for me is how to make CapacitorJS v5 continue smoothly, so those users don't get an update error.

**Comment by bluepuma77** [comment]
According to ChatGPT multiple major versions can be enabled:
```
  "peerDependencies": {
    "@capacitor/core": "^5.0.0 || ^6.0.0"
  },
```

**Comment by jepiqueau** [comment]
@bluepuma77 capacitor 6 is not supported yet

**Comment by rosostolato** [comment]
@jepiqueau, any chance we can expect support for capacitor 6 in the next few days?

**Comment by jepiqueau** [comment]
@rosostolato not really Capacitor 6 requires for iOS Xcode 15 which runs only on Sonatra which is not supported on my MacBook Pro. So i cannot build the ios part otherwise it would have been released already.

**Comment by lajith111** [comment]
@jepiqueau time being  is it possible to update only for Android ?

**Comment by rosostolato** [comment]
@jepiqueau got it, I had just tested on Android.

But actually, xcode 15 requires Ventura 13.5 to run: https://developer.apple.com/documentation/xcode-release-notes/xcode-15-release-notes

Doesn't your Mac support it? And if not, can't you run it on a vm?

**Comment by jepiqueau** [comment]
@rosostolato thanks for your proposalbut my Mac is from 2016so it does not even support Ventura.  I will what solutions i have but it will take a bit of time free which is not the case those week as i got some personal issues. I will keep you aware of the progress

**Comment by bluepuma77** [comment]
@jepiqueau Did you contact Ionic developer relations, if they could sponsor you a new MacBook, as you are an important community maintainer? Their "Director of Developer Relations" is on LinkedIn 😄

**Comment by jepiqueau** [comment]
@bluepuma77 can give me his références name and email please

**Comment by bluepuma77** [comment]
Sorry, only got links:
https://www.linkedin.com/in/mhartington/
https://twitter.com/mhartington
https://mastodon.social/@mhartington
https://github.com/mhartington

Or you could try other channels:
https://forum.ionicframework.com/
https://discord.com/invite/UPYYRhtyzp

**Comment by Meerkap** [comment]
Same here, waiting for support v6

**Comment by jepiqueau** [comment]
@bluepuma77 i sent an email to Mike, we will see. May be some of you can also sponsor me for part of it

**Comment by rosostolato** [comment]
Dude, you should try a VM. If you have Linux or even windows, you can try [docker-osx](https://github.com/sickcodes/Docker-OSX)

**Comment by rosostolato** [comment]
@jepiqueau have you tried docker-osx running on wsl? I know it's not that fast like an actual Mac but not too slow that you can't use to compile stuff.

**Comment by RubioN** [comment]
Waiting for support v6 too here 🙏

**Comment by rosostolato** [comment]
@jepiqueau if you tell me the steps I can compile it for you. We can't just let this package get stale because of that.

**Comment by jepiqueau** [comment]
@rosostolato i have publish an alpha version for Capacitor6 that you can install with `npm i --save @capacitor-community/sqlite@capv6 in your app, i will check it to day for Android, Electron and Web by migrating my testing apps to Capacitor6. If you can do it for one of your app (migrating to Capacitor6) and build it and report to me the result it would be great

**Comment by lajith111** [comment]
@jepiqueau  I have checked in my app in browser as well as android emulator(14) its working fine..Thanks

**Comment by jepiqueau** [comment]
@bluepuma77 @rosostolato @lajith111 @RubioN @Meerkap I tested the `@capacitor-community/sqlite@capv6 ` on Android, Electron, Web it works fine.

**Comment by jepiqueau** [comment]
@lajith111 thanks for the feedback on Android and Web

**Comment by RubioN** [comment]
Thank you very much @jepiqueau !
I'll keep an eye on developments for iOS

**Comment by eideard-hm** [comment]
Same here, waiting for support v6
![image](https://github.com/capacitor-community/sqlite/assets/82130680/36605b4b-257e-4bbd-b865-800c1995bf7d)

**Comment by rosostolato** [comment]
@eideard-hm you can try out the new version by installing `@capacitor-community/sqlite@capv6`

**Comment by jepiqueau** [comment]
@rosostolato did you try building the ios plugin in an app ? What was the result?

**Comment by rosostolato** [comment]
@jepiqueau not yet, I will try tonight or tomorrow, I will let you know.

**Comment by rosostolato** [comment]
@jepiqueau I just tested it on my capacitor v6 app and everything looks good. Both iOS and Android are just working. Thank you for that!

**Comment by jepiqueau** [comment]
@rosostolato thanks for your feedback. Happy of this

**Comment by xsorifc28** [comment]
When V6?

**Comment by RubioN** [comment]
@jepiqueau do you have some news please ? 🙏

**Comment by jepiqueau** [comment]
@RubioN as mentioned above you can use @capacitor-community/sqlite@capv6 it has been tested by myself for Web, Electron and Android and by @rosostolato  for iOS and it works fine.

**Comment by Sampath-Lokuge** [comment]
@jepiqueau I think you can use the `macincloud` service until you have a new Mac: https://checkout.macincloud.com/
I have used it and very fast service too.

**Comment by Sampath-Lokuge** [comment]
@jepiqueau when will you release the production-ready version of this?

**Comment by jepiqueau** [comment]
@Sampath-Lokuge i will issue a full Capacitor V6 version of this plugin and it will be the last one.

**Comment by rosostolato** [comment]
Thank you all the effort you put on this amazing plug-in. I hope this project never dies 🙏

**Comment by Sampath-Lokuge** [comment]
Thanks, @jepiqueau That will give us at least a small joy hence we cannot update our apps to Cap 6 until we have official support from this plugin. i.e. we cannot use the alpha version with production-ready apps. Good luck!

**Comment by robingenz** [comment]
@jepiqueau Let me know if you need any support with the release.

**Comment by jormaj** [comment]
@jepiqueau Thank you for all your work! 
Is there anything we can do to help you in your situation?
If money is an issue I would be happy to contribute something through a crowdfunding f.ex.

**Comment by jepiqueau** [comment]
@robingenz @rosostolato  thanks, i will need someone to validate the iOS part when issues like @rosostolato did for the alpha release.
@jormaj it is not a question of money, No one can get me back to my sixties... More seriously, several members of my family are impacted by serious healthy problems which requires my full attention and time. 
I will try to issue the v6 in the course of the week and after your validation it will be the last release from me.
Hope some of you will take the challenge to keep the plugin alive. Talk to Mike Hartington in chargé from Ionic of the capacitor-community.

Thanks to all of you for your understanding and support

**Comment by jormaj** [comment]
@jepiqueau I understand. 
I think it's amazing that you're still developing, I hope I will be the same when I reach your age!
Even though money is not the issue, I saw that you had Github sponsor setup so I've sponsored you as a token of appreciation.
All the best!

**Comment by sertal70** [comment]
@jepiqueau I have a MacBook M3 Pro looking forward to be stressed 😃 so I can validate the iOS part of the plugin, I have some experience in Capacitor Plugins development because I 've written a couple of them for company internal purposes. I just need instructions on what to do, hope  this can help.

**Comment by jepiqueau** [comment]
@bluepuma77 @rosostolato @lajith111 @RubioN @Meerkap Can some of you test the beta release tag --capv6.  Waiting for your feedback before releasing 6.0.0

**Comment by sertal70** [comment]
@jepiqueau I'll check the iOS part this evening (CEST) and put my feedback here. Is there any test suite I can use for that?

**Comment by CarlosPoventud** [comment]
I downloaded the cap6 version and am not seeing any issues so far on web, iOS or Android! Thanks for all the hard work @jepiqueau !

**Comment by jepiqueau** [comment]
@sertal70  you can clone [ionic-react-test-issues](https://github.com/jepiqueau/ionic-react-test-issues), the main branch is for version 6 in the Home page select the menu and you will find a list of tests. They must all run to completion

**Comment by jepiqueau** [comment]
@CarlosPoventud thanks for the feedback, can you also clone [ionic-react-test-issues](https://github.com/jepiqueau/ionic-react-test-issues) and test it on iOS. i run the tests on Web, Android and Electron, they all complete successfully

**Comment by CarlosPoventud** [comment]
@jepiqueau  Running from the emulator it all seems to work! Attaching several pictures from an iPhone 15 simulator:

![image](https://github.com/capacitor-community/sqlite/assets/97455004/9c3bc4cd-38f9-4c2f-86da-e3d70dbf55a5)
![image](https://github.com/capacitor-community/sqlite/assets/97455004/030c7e63-75ba-4a99-9498-c26a9ceb3548)
![image](https://github.com/capacitor-community/sqlite/assets/97455004/a21a4e3d-16af-46af-9ba7-8af3274a92ea)
![image](https://github.com/capacitor-community/sqlite/assets/97455004/e7de4c93-7462-4ee7-a30e-8152127bf2ca)

**Comment by jepiqueau** [comment]
@CarlosPoventud thanks for the feedback waiting more feedbacks from others and i will then publish the release 6.0.0

**Comment by sertal70** [comment]
@jepiqueau I've tested the plugin on a physical iPhone XR v17.3.1, a physical iPhone 7 Plus v15.8.2 and a simulator iPhone 15 v.17.5 All the tests completed without any visible errors, except the "MultipleRows test" which does not complete with the following log:
```
To Native ->  CapacitorSQLite executeSet 40086323
ERROR MESSAGE:  {"message":"ExecuteSet: Failed in execSet :  Error: prepareSQL finalize failed rc: 19 message: UNIQUE constraint failed: contacts.email","errorMessage":"ExecuteSet: Failed in execSet :  Error: prepareSQL finalize failed rc: 19 message: UNIQUE constraint failed: contacts.email"}
⚡️  [error] - {"message":"ExecuteSet: Failed in execSet :  Error: prepareSQL finalize failed rc: 19 message: UNIQUE constraint failed: contacts.email","errorMessage":"ExecuteSet: Failed in execSet :  Error: prepareSQL finalize failed rc: 19 message: UNIQUE constraint failed: contacts.email"}
```
It is weird because this test starts to fail only after I run "Get from HTTP test". If I do a clean install and avoid to run that test, it completes ok.

**Comment by jepiqueau** [comment]
@sertal70 thanks for the feedback. That strange behaviour as the two tests are completely separate i will have a look

**Comment by jepiqueau** [comment]
@sertal70 have you clean all databases on the device before starting the tests?

**Comment by jepiqueau** [comment]
Release 6.0.0 has been published. Thanks all for your contribution

**Comment by jepiqueau** [comment]
@sertal70 you are welcome

**Comment by lajith111** [comment]
> @bluepuma77 @rosostolato @lajith111 @RubioN @Meerkap Can some of you test the beta release tag --capv6. Waiting for your feedback before releasing 6.0.0

Checked in web  and real android device working perfectly fine. Thanks
