### ISSUE TITLE
Migration not working on iOS

### ISSUE THREAD

**Issue by tradingproject19** [capacitor-community/sqlite#546]
**Describe the bug**
First of all thank you so much for this awesome plugin. We have an issue with iOS. We were using cordova sqlite plugin and were using the default location, when I migrated to capacitor sqlite, it seems to work on Android and creates a copy of our database file, 
but when I run the app in iOS it does not seems to work.

I am passing the "default" to getMigratableDbList method but it does not pick the database. I checked on iOS simulator folder and our database exists in "/Library/LocalDatabase/ourdb.db

Is the "default" supposed to pick from LocalDatabase folder or am I missing something?

**To Reproduce**

**Expected behavior**
Should create a copy on iOS

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

- Device: iPhone15
- OS: 17.0

**Additional context**

**Comment by tradingproject19** [comment]
I have changed the path to Library/LocalDatabase for iOS and it seems to be working fine now. Default path uses Documents folder inside app on iOS.

```
public async migrateFromCordova() {
  try {
    let path = Capacitor.getPlatform() === 'ios' ? 'Library/LocalDatabase' : 'default';
    let dbSchema = await this.sqliteService.getMigratableDbList(path);
    await this.sqliteService.addSQLiteSuffix(path, dbSchema.values);
    await this.sqliteService.deleteOldDatabases(path);
    return true;
  }
  catch (ex) {
    console.log(ex, 'Unable to migrate to capacitor! migrateFromCordova');
    return true;
  }
}
```

**Comment by jepiqueau** [comment]
@tradingproject19 Yes this is what is written in the doc MigratingCordovaDatabases.md. so i assume that i can close the issue

**Comment by tradingproject19** [comment]
It's working on simulator but not on physical device. :(

I will go to my office tomorrow and troubleshoot it. I think path on device may be different than path on simulator.

Thank you for your help.
