### ISSUE TITLE
CapacitorSQLite.requestPermissions() never ending on Android

### ISSUE THREAD

**Issue by MattOnyx** [capacitor-community/sqlite#55]
**Describe the bug**
`await CapacitorSQLite.requestPermissions()` does not resume execution after storage permissions are granted on Android;

**To Reproduce**

1. Add `await CapacitorSQLite.requestPermissions()` in your app initialization.
2. Run app on physical device

**Expected behavior**
The app should halt the execution on `requestPermissions()` and display a permission dialog, and resume the execution after the permissions have been granted.

Here is an extract of the Angular code I used:
```
if (info.platform === "android") {
      try {
        const sqlite = CapacitorSQLite as any;
        console.log('REQUESTING PERMS');
        await sqlite.requestPermissions();
        console.log('GOT PERMS');
      } catch (e) {
        const alert = await this.alertCtrl.create({
          header: "No DB access",
          message: "This app can't work without Database access.",
          buttons: ["OK"],
        });
        await alert.present();
      }
    }
```
I do get "REQUESTING PERMS", but never "GOT PERMS", after allowing storage, or if it was already allowed.

**Smartphone:**

- Device: OnePlus 7 Pro
- OS: Android
- Version: 10

**Additional context**
I'm using Angular, so I created a new issue despite the very similar case on #48 
Also, unlike this issue, I don't have any other call to the database in my code.
I'm using version 2.4.2-9 of capacitor-community/sqlite.

**Comment by jepiqueau** [comment]
@MattOnyx Thanks for using the plugin, a listener `androidPermissionsRequest` has been added to solve the issue#48

```
    initializePlugin(): Promise<boolean> {
        return new Promise (resolve => {
            this.platform = Capacitor.platform;
            console.log("*** platform " + this.platform)
            this.sqlite = CapacitorSQLite;
            if(this.platform === "android") {
                this.handlerPermissions = this.sqlite .addListener(
                    'androidPermissionsRequest', async (data:any) => { 
                    if (data.permissionGranted === 1) {
                        this.handlerPermissions.remove();
                        resolve(true);
                    } else {
                        console.log("Permission not granted");
                        this.handlerPermissions.remove();
                        this.sqlite = null;
                        resolve(false);
                    }      
                });
                try {
                   this.sqlite .requestPermissions();
                } catch (e) {
                    console.log("Error requesting permissions " + JSON.stringify(e));
                    resolve(false);
                }
            } else {
                resolve(true);
            }
        });
    }

```
look at`https://github.com/jepiqueau/angular-sqlite-app-starter` Hope this clarify

**Comment by MattOnyx** [comment]
My bad, I was indeed missing the androidPermissionsRequest part, thanks for your help!

**Comment by jepiqueau** [comment]
@MattOnyx No problems, you are welcome.

**Comment by accron-1** [comment]
@jepiqueau Just to confirm: is `.addListener('androidPermissionsRequest'...)` the new way of requesting the permissions, in **all** JS frameworks, as opposed to the old way of simply doing an `await CapacitorSQLite.requestPermissions()` (which of course worked when I reported the issue #48 after your fix)?

**Comment by jepiqueau** [comment]
@accron-1 Yes this is the way to do it now, see above. It was working well before but some users where complaining that the requestPermissions was not ending properly. With this way, at least there is no doubt.
