### ISSUE TITLE
Update Capacitor dependencies to version >6

### ISSUE THREAD

**Issue by eideard-hm** [capacitor-community/sqlite#554]
**Describe the bug**

**To Reproduce**

**Expected behavior**
Updating the dependencies throws the image error in the @capacitor-community/sqlite package.

**Screenshots**
![image](https://github.com/capacitor-community/sqlite/assets/82130680/769bb677-493c-4053-aa7b-a519d4960696)

**Comment by RubioN** [comment]
Same here. Will an update to run on Capacitor 6 be available soon?

**Comment by jepiqueau** [comment]
@eideard-hm @RubioN  see response in issue#541
