### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'lastId')

### ISSUE THREAD

**Issue by tradingproject19** [capacitor-community/sqlite#558]
**Describe the bug**
Thank you for this plugin.

I am getting TypeError: Cannot read properties of undefined (reading 'lastId') error when I try to insert data which has ?. It works perfectly fine in iOS and Android but query breaks when there's ? in data.

**To Reproduce**

1. Use electron
2. `insert into tbl_document( taskID, id, name, fileType, projectName, location, type, url, projectId, lotId,                           date, builderId, typeCode, isImage, erpType, erpCCID, isTaskDocument, vendorId, operatingUnitCode, localFilePath, bucketId, modelId, elevationId, productId, prodListId, productCategoryCode, productSubCategoryCode, wRNo, itemNo)  values  ('0123','9F14C512-AFF9-4D28-935D-C660B5DA7C57','1716373921.jpeg','.jpg','ASDF Solutions','','Task','https://my-server/GetFile.aspx?PublicToken=kXgBagqzHAOG8ABzopcwc3RzqnDfp1cwVpVIGd2zmxbvb3gbmIS70o9hY7wj1lx6ZyFpA1OeUt28X/bhs/MUvROfDKLQ6+/Umqvt5I40ECg=','00010266','0095×00010266','2024-05-22','116','TASK','1','1','147','1','','HOM','','','','','','','','','','')`
3. `public async executeQueries(queries: string[], params?: any[][]): Promise<capSQLiteChanges> {
    try {
      const txn: capSQLiteSet[] = [];
      for (let i = 0; i < queries.length; i++) {
        if (!this.helper.isNullorEmpty(queries[i]))
          txn.push({
            statement: queries[i],
            values: (params && params != null && params.length > 0) ? (params[i] ?? []) : []
          });
      }
      if (!this.helper.isArrayNullorEmpty(txn))
        return await this.dbConnection.executeSet(txn);
      else
        throw new Error("Provide non-empty queries!");
    }
    catch (ex) {
      console.log(ex, 'Error executing queries! executeQueries', queries, params);
      throw new Error("Error executing queries! executeQueries");
    }
  }`
4. `await this.executeQueries(["delete from tbl_document where id IN ('9F14C512-AFF9-4D28-935D-C660B5DA7C57')", "insert into tbl_document( taskID, id, name, fileType, projectName, location, type, url, projectId, lotId,                           date, builderId, typeCode, isImage, erpType, erpCCID, isTaskDocument, vendorId, operatingUnitCode, localFilePath, bucketId, modelId, elevationId, productId, prodListId, productCategoryCode, productSubCategoryCode, wRNo, itemNo)  values  ('0123','9F14C512-AFF9-4D28-935D-C660B5DA7C57','1716373921.jpeg','.jpg','ASDF Solutions','','Task','https://my-server/GetFile.aspx?PublicToken=kXgBagqzHAOG8ABzopcwc2FLjztSE6JNmn7cqnn4HsCw6en7nWRVppdjTmw/UFkQO1gDvAoBATVWPVEKd3kSFoIZf1ebGeDoFFyNwbmx37o=','00010266','0095×00010266','2024-05-22','116','TASK','1','1','147','1','','HOM','','','','','','','','','','') "])`

**Expected behavior**
Query should work with ? in data.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Electron
- Version [e.g. 25.8.4]

**Additional context**

**Comment by tradingproject19** [comment]
When I remove ? from my data it works fine on electron,

**Comment by tradingproject19** [comment]
I found the issue but not the solution:

In my query I have '?' so code in prepareRun method checks for the occurence of '?s' in the query and creates an array of null values.

I dont see the purpose of creating an array of null values if no values were passed. do we need else condition here?

`if (mValues.length > 0) {
                mVal = this.replaceUndefinedByNull(mValues);
            }
            else {
                const findVals = sqlStmt.match(/\?/gi);
                const nbValues = findVals ? findVals.length : 0;
                for (let i = 0; i < nbValues; i++) {
                    mVal.push(null);
                }
            }`

@jepiqueau waiting for your input

can we check for delete update and insert in else condition before creating an array?

**Comment by tradingproject19** [comment]
it will work for select statements like 

select ? , ? , ? ,? from table where col1 = ? and col2 = ? and so on 

but not for CRUD operations.

**Comment by tradingproject19** [comment]
I have changed the else part based on stmtType and it seems to be working. Let me know if it's the right way:

`if (mValues.length > 0) {
        mVal = this.replaceUndefinedByNull(mValues);
      } else {
        switch (stmtType) {
          case 'SELECT': {
            const findVals = sqlStmt.match(/\?/gi);
            const nbValues = findVals ? findVals.length : 0;
            for (let i = 0; i < nbValues; i++) {
              mVal.push(null);
            }
            break;
          }
          case 'UPDATE':
          case 'DELETE':
          case 'INSERT':
            mVal = [];
            break;
          default:
            throw new Error(`Error: ${stmtType} not implemented`);
        }
      }`

**Comment by tradingproject19** [comment]
@jepiqueau  could you please review this PR?

**Comment by jepiqueau** [comment]
@tradingproject19 will be fixed in next release

**Comment by tradingproject19** [comment]
Thank you so much @jepiqueau  We are using Capacitor v5 could you please also include that fix for sqlite@5?

**Comment by jepiqueau** [comment]
It wull be done for v5 first and later for v6

**Comment by jepiqueau** [comment]
@tradingproject19 has been fixed in v5.7.3

**Comment by tradingproject19** [comment]
Thank you so much..
