### ISSUE TITLE
Insert statement not accepting null values by parameter on iOS

### ISSUE THREAD

**Issue by marcsances** [capacitor-community/sqlite#56]
**Describe the bug**
When passing a ``null`` value as a parameter on a INSERT statement, on Android the insert is performed with NULL values as expected. On iOS I get an error "Not a SQL type".

**To Reproduce**
Attempt to perform an INSERT like this (assume ``this._sqlite`` is an open database with a table named Table and a column. The column is of type TEXT and nullable):

```typescript
const statement = 'INSERT INTO Table(column) VALUES (?);';
const values = [null];
await this._sqlite.run({statement, values});
```

**Expected behavior**
An insert is performed and the value inserted is NULL, in any platform.

**Actual behavior**
On Android and Electron the INSERT succeeds. On iOS the insert fails with a "Not a SQL type" error ( [see the line generating the error](https://github.com/capacitor-community/sqlite/blob/73f723af69b685085cb1c1ef7601dbb5d0c5e653/ios/Plugin/Plugin.swift#L269) ).

**Smartphone (please complete the following information):**

- Device: iPhone 7
- OS: iOS 13.4
- Package versions:

```
capacitor/core: 2.4.2
capacitor/android: 2.4.2
capacitor/ios: 2.4.2
capacitor-community/sqlite: 2.4.2-8
```

**Additional context**
I've worked around the problem by doing a check if the value is null, then instead of using ``?`` I straight append NULL to the query, like this. It is an acceptable workaround while this issue is fixed:

```typescript
const statement = 'INSERT INTO Table(column) VALUES (' + (param === null ? '?' : 'NULL') + ');';
// to ensure query safety we still use the parameter array for the non null values
const values = (param === null ? [] : [param]);
await this._sqlite.run({statement, values});
```

**Comment by jepiqueau** [comment]
@marcsances Thank for using the plugin and for reporting the issue. I will take into account of this in the next release as you didn't use the latest release to make your pull request.

**Comment by jepiqueau** [comment]
@marcsances This is fixed in release 2.4.3-1 of the plugin. i will reject the pull request
the test will be
``` 
const statement = 'INSERT INTO Table(column) VALUES (?);';
const values = [];
await this._sqlite.run({statement, values});
```
Thanks again to use the plugin, close the issue when tested

**Comment by marcsances** [comment]
Thank you for the quick reply on the matter. While the previous fix did work for some reason, now that I've checked out the plugin straight from master I'm having the same problem despite the NSNull check. It could be my environment. I've tried debugging, and it does have type NSNull, but the ``value is NSNull`` doesn't pass for some reason and falls to the ``else`` block.

I'm gonna further this tomorrow and reply back.

**Comment by jepiqueau** [comment]
@marcsances   
my test is 
```ts
            const testcmd = `
            BEGIN TRANSACTION;
            CREATE TABLE IF NOT EXISTS test (
            id INTEGER PRIMARY KEY NOT NULL,
            name TEXT
            );
            INSERT INTO test (name) VALUES ("test 1");
            INSERT INTO test (name) VALUES ("test 2");
            COMMIT TRANSACTION;
            `;
            result = await this._SQLiteService.execute(testcmd);
            const retEx4 = result.changes.changes === 2 ? true : false;
           // add one test with statement and values              
            testcmd = "INSERT INTO test (name) VALUES (?)";
            let vals: Array<any>  = ["test 3 added insert "];
            result = await this._SQLiteService.run(testcmd,vals);
            const retRun5 = result.changes.changes === 1 &&
                            result.changes.lastId === 3 ? true : false;
            // add one test with statement and values [null]             
            testcmd = "INSERT INTO test (name) VALUES (?)";
            vals = [null];
            result = await this._SQLiteService.run(testcmd,vals);
            const retRun6 = result.changes.changes === 1 &&
                            result.changes.lastId === 4 ? true : false;
            // add one test with statement and values []             
            testcmd = "INSERT INTO test (name) VALUES (?)";
            vals = [];
            result = await this._SQLiteService.run(testcmd,vals);
            const retRun6 = result.changes.changes === 1 &&
                            result.changes.lastId === 5 ? true : false;
           if (retEx4 && retRun5 && retRun6 && retRun7) {
                console.log("Test successful");
          } else {
                console.log("Test failed");
         }
```
and the test was successful
after `npm i --save @capacitor-community/sqlite@latest` did you make a `npx cap sync` before the `npm run build`

**Comment by marcsances** [comment]
Yeah now it's working, seems like our build scripts were messing with me and keeping the old plugin version. Thank you for the effort!

**Comment by digaus** [comment]
@jepiqueau 

this won't work for `"INSERT INTO test (name, name1) VALUES (?,?)";` where `vals = [null, 'test2']`

Could you fix it for such cases aswell?

Also why is `run` check different from the `query `check?

Run: https://github.com/capacitor-community/sqlite/blob/master/ios/Plugin/Plugin.swift#L245

Query: https://github.com/capacitor-community/sqlite/blob/master/ios/Plugin/Plugin.swift#L314

**Comment by ksymmonds** [comment]
@digaus This looks like you're not sanitising/validating your inputs. This is potentially dangerous.

**Comment by digaus** [comment]
> @digaus This looks like you're not sanitising/validating your inputs. This is potentially dangerous.

Why? I sync data from cloud and some values are null and I need to insert them into the local DB so I can access everything offline. Nothing to do with input values.

**Comment by jepiqueau** [comment]
@digaus, which version of the plugin are you using. i test it with the `refactor` release and it works fine and it works also fine with release `2.4.3-1`

**Comment by jepiqueau** [comment]
@digaus Have you checked that it works fine with `2.4.3-1` the fix has been made in that version
