### ISSUE TITLE
Multi Row Statement does not suppress control characters ($)

### ISSUE THREAD

**Issue by l1ndch** [capacitor-community/sqlite#562]
**Describe the bug**
When executing a multi row statement via the executeSet Plugin with a replacement string containing $1 or other $-prefixed sequences, the _replaceFirst_ method will interpret them as references to capture groups and, since there might not be such a capture group, there will be an IndexOutOfBoundsExecption, as _replaceAll()_ will not suppress the special meaning of control characters like "\" and "$". Using Matcher.quoteReplacement will make them behave as they were literal characters and not control characters.

**To Reproduce**

1. use executeSet method
2. pass a two dimensional array as paramter to trigger multi row statement
3. pass string containing '$1' as replacement string

**Expected behavior**
If a dollar sign is used in the replacement string, it should not cause an issue

**Reference to issue**
- Capacitor Bug: https://github.com/ionic-team/capacitor/issues/7309
- https://www.w3resource.com/java-tutorial/string/string_replaceall.php

**Desktop (please complete the following information):**

- OS: Android --> unknown if the same error persists on IOS
- Browser chrome
- Version 5.7.0

**Additional context**
> Backslashes (\) and dollar signs ($) in the replacement string may cause the results to be different than if it were being treated as a literal replacement string; see Matcher.replaceAll. Use Matcher.quoteReplacement(java.lang.String) to suppress the special meaning of these characters, if desired.

**Comment by jepiqueau** [comment]
@l1ndch can you give a supporting example i can use to test the issue in other OS

**Comment by l1ndch** [comment]
Sure, just call the method replacePlaceholders() with a statement like: `insert into table (id, someColumn, body) VALUES (?,?,?)`.

In the sqlBuilder pass some data, the id should contain values containing special characters.
Example: `('72b8$2z18:gp51bp$2h18','someData','{"someKey":"someValue"}')` (note that $2 will be considered a control character when using [replaceFirst()](https://www.w3resource.com/java-tutorial/string/string_replaceall.php)).

Calling Matcher.quoteReplacement() first, these control characters will be escaped "\$" and the sqlBuilder string will look like this: `('72b8\$2z18:gp51bp\$2h18','someData','{"someKey":"someValue"}')`

**Comment by jepiqueau** [comment]
@l1ndch thanks i will have a look then on other OS

**Comment by jepiqueau** [comment]
@l1ndch has been fixed in v5.7.3
