### ISSUE TITLE
SQLite compatibility with Capacitor 6.0.0

### ISSUE THREAD

**Issue by EduGese** [capacitor-community/sqlite#564]
## Description

I'm currently using Capacitor 6.0.0, the latest stable version, in my Ionic/Angular 7 application. When attempting to install the @capacitor-community/sqlite plugin, I encountered a dependency conflict due to the plugin's peer dependency on @capacitor/core requiring a version starting with "^5.0.0".

While I understand that the core functionality of SQLite might still work with Capacitor 6.0.0, I couldn't find an official version of the @capacitor-community/sqlite plugin that explicitly states compatibility with Capacitor 6.0.0.

## Steps to Reproduce:

1. Create a new Ionic/Angular 7 application using the latest CLI.
2. Attempt to install @capacitor-community/sqlite: npm install @capacitor-community/sqlite

##Expected Behavior:

The @capacitor-community/sqlite plugin should install successfully without any dependency conflicts and work seamlessly with Capacitor 6.0.0.

## Actual Behavior:

An error message is displayed indicating a dependency conflict between @capacitor-community/sqlite and @capacitor/core.

## Additional Context:

I have checked the release notes for @capacitor-community/sqlite but couldn't find any explicit mention of compatibility with Capacitor 6.0.0.
I have searched for community-maintained versions of the plugin with updated peer dependencies, but I'm hesitant to use them due to potential lack of official support.
Downgrading @capacitor/core to an older version is not an ideal solution as it would mean missing out on newer features and bug fixes.

## Request:

I would appreciate it if you could provide an update on the compatibility status of @capacitor-community/sqlite with Capacitor 6.0.0. If there's no official version yet, could you please share any plans or timelines for releasing a compatible version?

Thank you for your time and consideration.

**Comment by srapport** [comment]
@EduGese, You might checkout existing issue: #541 

This comment: https://github.com/capacitor-community/sqlite/issues/541#issuecomment-2095379119

`pnpm add @capacitor-community/sqlite@capv6`

**Comment by EduGese** [comment]
@srapport ups, I didn't see that one, thank you so much!
