### ISSUE TITLE
For-in loop requires 'Archive?' to conform to 'Sequence'; did you mean to unwrap optional?

### ISSUE THREAD

**Issue by ebarolo** [capacitor-community/sqlite#565]
**Describe the bug**
For-in loop requires 'Archive?' to conform to 'Sequence'; did you mean to unwrap optional?
line 432 
UtilsFile.swift

**To Reproduce**
Update the app from 6.0.0 alpha  to version 6.0.0 and when I try to build the application it fails giving the error

**SPEC**

 OS: iOS 
 Version [17.5]
 Capacitor core: 6.1.0
 Capacitor iOS: 6.1.0
 Pwa-elements: 3.3.0
 Ionic-angular: 8.2.2

<img width="929" alt="Screenshot 2024-06-13 alle 14 56 20" src="https://github.com/capacitor-community/sqlite/assets/24942103/09cce7b9-cb63-489b-ae7e-7f753257e1a9">

**Comment by maxsoftware** [comment]
I'm having the same issue. Beta 1, Beta 2 and version 6.0.0 all have the above erorr. Alpha 1 works fine.

**Comment by robingenz** [comment]
I will take a look at it on the weekend.

**Comment by jepiqueau** [comment]
@maxsoftware @ebarolo  can you explain the contexte in which that's happened get a zip archive from http or get the zip archive from the assets folder

**Comment by maxsoftware** [comment]
> @maxsoftware @ebarolo can you explain the contexte in which that's happened get a zip archive from http or get the zip archive from the assets folder

I’m not using zip archives in my app

**Comment by jepiqueau** [comment]
@maxsoftware @robingenz @ebarolo this must be fixed in v6.0.1 waiting for your feedback

**Comment by ebarolo** [comment]
me to I’m not using zip archives in my app, I have just update the plugin from 6 alpha to 6.0.0 and when I try to rebuild the app I was that error

**Comment by ebarolo** [comment]
> @maxsoftware @robingenz @ebarolo this must be fixed in v6.0.1 waiting for your feedback

It's work fine 👍

**Comment by jepiqueau** [comment]
@ebarolo  thanks for your feedback so i close the issue
