### ISSUE TITLE
Can I always keep the await db?open() ?

### ISSUE THREAD

**Issue by akshar-bk** [capacitor-community/sqlite#577]
Hi I am using capacitor sqlite plugin for my ionic react app.
I am saving the data in sqlite db.
Everytime I am inserting/updating the data, I am always doing db?.open() and after executing query I am using db?.close()
But I am facing issue in this 
For eg : 
There are two function A and function B, both open and close the connection.
Let say function A has open the db and it is computing something, mean while function B has open and close the connection.
Now when function A tries to db?.query() it says db not open
Note: overall I have a single instance of db in my application.
@jepiqueau Can you suggest some solutions? Can I keep db?.open() when I am initializing DB and never close it, will this works?

**Comment by jepiqueau** [comment]
@akshar-bk createConnection return à db pointer to a database but do not open the database for this you have to use db.open(). Meanwhile closeConnection close rhe database and then close the connection. 
So you may create a connection when your app initialize and close the connection when the app is unmounted. You may decide to open and close the database or not each time you make a query. In that case you must before making a query to test of the db is open and if not open it . You can also decide to db.open() just after the createConnection and keep it open till you close the connection
