### ISSUE TITLE
Permission Request mostly unnecessary / unnecessary for Android > Api Level 19?

### ISSUE THREAD

**Issue by elianterelle** [capacitor-community/sqlite#60]
I looked a little bit into why you need to request permissions for sqlite to work.
For me it seems like in most situations, it isn't necessary at all, because the permission requested by the Plugin are `READ_EXTERNAL_STORAGE` and `WRITE_EXTERNAL_STORAGE`. I guess these are only required when the user offloads the App's data to an SD Card for example?
Also, according to https://developer.android.com/reference/android/Manifest.permission#WRITE_EXTERNAL_STORAGE, those permissions are not needed for writing in app-specific directories on Android Versions above API Level 19(Android 4.4). Capacitor currently supports Android 4.0 or above, which they say targets 90% of all Android Users.
So i guess it would make sense to either make the permission request optional, or check the Users Api Level and request / not request the permissions based on that.

**Comment by jepiqueau** [comment]
@elianterelle thank you for your comment, i will have a look

**Comment by JayHong705** [comment]
Our team also wondered why it requires permission for external storage. Is it possible to use internal storage instead of external storage? In the perspective of UX, it is very awkward for users to see an external storage permission on Android.
Our team always appreciates your effort for managing this plugin. Thank you and happy new year :)

**Comment by no-dap** [comment]
Is this is progress? I also want to stop asking for 'photo' permissions to use a local database.  
I can do some work for it if you want.

**Comment by jepiqueau** [comment]
@no-dap @JayHong705 @elianterelle I have not yet started to look at it as i am concentrating on my two others plugins that i left away to develop the refactor and also trying to understand the effort to move to capacitor3. Is it something urgent ?

**Comment by no-dap** [comment]
Yes. I currently add this plugin to my application, and the permission we're asking shown as photo permission on Android.  
My customers barely grant it because of its name.

**Comment by jepiqueau** [comment]
@no-dap Ok i will do it are you using the 2.4.5-1 or the refactor ?

**Comment by jepiqueau** [comment]
@no-dap @elianterelle @JayHong705  this is fix in 2.4.5-2

**Comment by maartenmensink** [comment]
Thanks for creating a pre-release. Any idea when this will 2.4.5 will be released?

**Comment by jepiqueau** [comment]
@maartenmensink This is done

**Comment by JayHong705** [comment]
You released our users from embarrassment! Appreciate it so much!

**Comment by jepiqueau** [comment]
@JayHong705 Thanks, you are welcome
