### ISSUE TITLE
REFACTOR - Electron 'encryption test' crashes example app on Windows 10

### ISSUE THREAD

**Issue by gabrielberlanda** [capacitor-community/sqlite#62]
**Describe the bug**

Running tests that use encrypted sqlite with electron on windows crashes the example app.

![image](https://user-images.githubusercontent.com/11332820/104598175-0588ea80-5655-11eb-8234-b5bd28be06fd.png)

**To Reproduce**

1. Clone [react-sqlite-app-starter](https://github.com/jepiqueau/react-sqlite-app-starter/tree/refactor)
2. Checkout in the refactor branch
3. Do all the [Installation steps](https://github.com/jepiqueau/react-sqlite-app-starter/tree/refactor)
4. Run `npx cap open @capacitor-community/electron`
5. Change to the tests tab
6. Click on SQLITE TWO DBS TESTS or SQLITE ENCRYPTION TEST

**Expected behavior**
Execute encryption tests successfully as informed on [Supported methods section](https://github.com/capacitor-community/sqlite/tree/refactor#supported-methods)

**Screenshots**
![image](https://user-images.githubusercontent.com/11332820/104598691-a37cb500-5655-11eb-9c12-f4b899150e41.png)

**Desktop (please complete the following information):**

- OS: Windows 10 Pro version 19041
- Electron 11.0.1
- Plugin version 2.9.0

**Comment by jepiqueau** [comment]
@gabrielberlanda I will have a look but i do not have a development platform on Windows so it may take some time

**Comment by jepiqueau** [comment]
see REFACTOR - All tests failed running electron packaged on Windows 10 #63
