### ISSUE TITLE
REFACTOR - All tests failed running electron packaged on Windows 10

### ISSUE THREAD

**Issue by gabrielberlanda** [capacitor-community/sqlite#63]
**Describe the bug**
Running [react-sqlite-app-starter](https://github.com/jepiqueau/react-sqlite-app-starter/tree/refactor#electron) or [angular-sqlite-app-refactor](https://github.com/jepiqueau/angular-sqlite-app-refactor) packaged for windows fails all tests

**To Reproduce**

1. Clone [react-sqlite-app-starter](https://github.com/jepiqueau/react-sqlite-app-starter/tree/refactor#electron)
2. Checkout in the refactor branch
3. Do all the [Installation steps](https://github.com/jepiqueau/react-sqlite-app-starter/tree/refactor)
4. `cd electron`
5. run `npm run electron:pack` or `npm run electron:build-windows`
6. Run the packaged program on dist folder
7. Try to run any app test

**Expected behavior** 
Run all tests successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/11332820/104600758-2f8fdc00-5658-11eb-8f30-690cf404e8c4.png)

**Desktop (please complete the following information):**

- OS: Windows 10 Pro version 19041
- Electron 11.0.1
- Plugin version 2.9.0

**Comment by rubentlc** [comment]
I have exactly the same problem with the android app...

**Comment by jepiqueau** [comment]
@gabrielberlanda 
this is the process
1. git clone --branch refactor https://github.com/jepiqueau/react-sqlite-app-starter.git
2. cd react-sqlite-app-starter
3. npm install
4. cd electron
5. npm install
6. cd ..
7. npm run build
8. npx cap sync 
9. npx cap sync @capcitor-community/electron
10. npm run build
11. npx cap copy
12. npx cap copy @capacitor-community/electron
13. npx cap open @capacitor-community/electron

this should work
i do not know why you did `run npm run electron:pack or npm run electron:build-windows` this is not in the doc

**Comment by jepiqueau** [comment]
@rubentlc you have to be more specific are you testing on a real device or on a simulator, are you using Android studio on windows or macOs? I can understand that electron could have an issue on windows but the android plugin is not sensitive to windows.

**Comment by jepiqueau** [comment]
@gabrielberlanda, @rubentlc thanks for using the refactor release i will do all i can do to help you

**Comment by gabrielberlanda** [comment]
@jepiqueau the electron:pack and the electron:build-windows are the commands to pack the application for distribution, to generate the .exe file.

Running with the npx cap open @capacitor-community/electron is for local test, running locally I found errors with encryption mentioned at #62.

**Comment by jepiqueau** [comment]
@gabrielberlanda ok, i learned something, thanks i have something strange on my side i got a black screen and moving down to the elements in the dev tools where i got all the elements a blue rectangle appears on the black screen and if i click on i got the real player icon and when i click on i see the tab one and the tab button and sometime when clicking on tab2 and on the three test buttons it works and sometimes it failed like you mentioned `Devtools was disconnected from the page Once ....`  This is not happening on MacOs

**Comment by jepiqueau** [comment]
@gabrielberlanda it seems that there are some issues with @journeyapps/sqlcipher so i will have a deeper look

**Comment by gabrielberlanda** [comment]
@jepiqueau Thanks a lot.

Unfortunately I don't have experience with capacitor plugins and Sqlite, but I can help testing this issue

**Comment by rubentlc** [comment]
hi @jepiqueau,

I'm testing in a real android device and I'm using android studio on a macOs.

The problem that I found is that the function "createConnection" returns always null.

**Comment by jepiqueau** [comment]
@rubentic Are you testing an app starter  `react-sqlite-app-starter` or `angular-sqlite-app-refactor ` or in one of your app?

**Comment by rubentlc** [comment]
@jepiqueau  I'm using in my own react app. Basically I have installed the modules "@capacitor-community/sqlite": "^2.9.0" and  "react-sqlite-hook": "^1.0.0-beta.4" as dependencies (not as dev-dependencies, I don't know if it does difference) and copied all the content of yout Tab2 page, all the components and the utils folder.

**Comment by jepiqueau** [comment]
@rubentlc  Ok Did you modify the MainActivity.java file with the following
```ts
...
import com.getcapacitor.community.database.sqlite.CapacitorSQLite;
...
public class MainActivity extends BridgeActivity {
  @Override
  public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    // Initializes the Bridge
    this.init(savedInstanceState, new ArrayList<Class<? extends Plugin>>() {{
      // Additional plugins you've installed go here
      // Ex: add(TotallyAwesomePlugin.class);
      add(CapacitorSQLite.class);
    }});
  }
}
```
you must do this otherwise the plugin is unknown try and come back to me

**Comment by jepiqueau** [comment]
@gabrielberlanda There was an error with the get App path in case of an executable, so this will be fixed and allow to run non-encrypted tests but the main problem is that @journeyapps/node-sqlcipher does not work or i could not make it working on windows, it works fine on mac you can visit `https://github.com/journeyapps/node-sqlcipher/issues`and the author did not give a way to solve this. i spent all my day trying to figure out a way to use it but without success Sorry, i will keep an eye to see if there are some progress on their side  and i will add a note that `encryption is not working under windows`

**Comment by gabrielberlanda** [comment]
@jepiqueau Thanks a lot!!

The encryption is not a big problem in my usecase, if it's working on packaged mode for me it's a big deal! 

Out of curiosity, Would you know if have someone already working on the driver for the typeorm framework?

**Comment by jepiqueau** [comment]
@gabrielberlanda typeorm see issue#38 and @chriswep he has proposed to do it.
if you give me still a bit of time, i found something so i will look to find how to solve it otherwise i will publish a new release with the warning on Windows if it is ok for you

**Comment by jepiqueau** [comment]
@gabrielberlanda this is fix in 2.9.1 in fact when the app is running under Windows no encryption is done as i cannot figure out to do that with  @journeyapps/sqlcipher. It may come sometimes but to day i prefer spending my time on other bugs and on migrating my plugins to capacitor3.0. You can close the issue when you have tested on your side

**Comment by jepiqueau** [comment]
@rubentlc as i did not hear from you i am assuming that your app works fine on android

**Comment by gabrielberlanda** [comment]
@jepiqueau It's working, thanks a lot!

**Comment by rubentlc** [comment]
@jepiqueau it's working ok now! thanks!
