### ISSUE TITLE
 create the  UNIQUE indexes

### ISSUE THREAD

**Issue by deepakjsr7979** [capacitor-community/sqlite#64]
Thanks for valuable addition to capacitor community..

I 
want to add a index
 "indexes": [
	 	 { "name": "EmpIDIndex", "column": "CREATE UNIQUE INDEX EmpIDIndex ON FingerTemplateM (EmployeeId ASC, FingerIndex ASC)"}
	  ] 
can you place the what i am doing Wong ; or can suggest me how to create indexes in table using .json file
thanks ..
Import and export the json file 
**UNIQUE INDEX**

**Comment by jepiqueau** [comment]
@deepakjsr7979 This is explained in the doc `https://github.com/capacitor-community/sqlite/blob/master/docs/ImportExportJson.md`
```
const dataToImport: jsonSQLite = {
  database: 'db-from-json',
  version: 1,
  encrypted: false,
  mode: 'full',
  tables: [
    {
      name: 'users',
      schema: [
        { column: 'id', value: 'INTEGER PRIMARY KEY NOT NULL' },
        { column: 'email', value: 'TEXT UNIQUE NOT NULL' },
        { column: 'name', value: 'TEXT' },
        { column: 'age', value: 'INTEGER' },
        { column: 'last_modified', value: 'INTEGER' },
      ],
      indexes: [
        { name: 'index_user_on_name', column: 'name' },
        { name: 'index_user_on_last_modified', column: 'last_modified' },
      ],
      values: [
        [1, 'Whiteley.com', 'Whiteley', 30, 1582536810],
        [2, 'Jones.com', 'Jones', 44, 1582812800],
        [3, 'Simpson@example.com', 'Simpson', 69, 1583570630],
        [4, 'Brown@example.com', 'Brown', 15, 1590383895],
      ],
    },
  ],
};
```
I take the point on index UNIQUE and with combining columns. this is not implemented so it has to be done. Are you using the `REFACTOR`?

**Comment by deepakjsr7979** [comment]
> @deepakjsr7979 This is explained in the doc `https://github.com/capacitor-community/sqlite/blob/master/docs/ImportExportJson.md`
> 
> ```
> const dataToImport: jsonSQLite = {
>   database: 'db-from-json',
>   version: 1,
>   encrypted: false,
>   mode: 'full',
>   tables: [
>     {
>       name: 'users',
>       schema: [
>         { column: 'id', value: 'INTEGER PRIMARY KEY NOT NULL' },
>         { column: 'email', value: 'TEXT UNIQUE NOT NULL' },
>         { column: 'name', value: 'TEXT' },
>         { column: 'age', value: 'INTEGER' },
>         { column: 'last_modified', value: 'INTEGER' },
>       ],
>       indexes: [
>         { name: 'index_user_on_name', column: 'name' },
>         { name: 'index_user_on_last_modified', column: 'last_modified' },
>       ],
>       values: [
>         [1, 'Whiteley.com', 'Whiteley', 30, 1582536810],
>         [2, 'Jones.com', 'Jones', 44, 1582812800],
>         [3, 'Simpson@example.com', 'Simpson', 69, 1583570630],
>         [4, 'Brown@example.com', 'Brown', 15, 1590383895],
>       ],
>     },
>   ],
> };
> ```
> 
> I take the point on index UNIQUE and with combining columns. this is not implemented so it has to be done. Are you using the `REFACTOR`?

Thanks for your reply. 👍  
No i m not using  REFACTOR yet.

**Comment by jepiqueau** [comment]
@deepakjsr7979 This has been fixed in the refactor 2.9.2

**Comment by deepakjsr7979** [comment]
> refactor 2.9.2

i am using "@capacitor-community/sqlite": "^2.4.5",
how i can get the latest one i run the cmd like
`npm i @capacitor-community/sqlite @latest -- save`
but nothing got changed.
please suggest 👍

**Comment by jepiqueau** [comment]
@deepakjsr7979 to install the refactor you must do `npm i -- save @capacitor-community/sqlite@refactor` but before to do that as the interface as change visit the documentations for the refactor
- https://github.com/capacitor-community/sqlite/blob/refactor/docs/APIConnection.md
- https://github.com/capacitor-community/sqlite/blob/refactor/docs/APIDBConnection.md
- https://github.com/capacitor-community/sqlite/blob/refactor/docs/API.md
- https://github.com/capacitor-community/sqlite/blob/refactor/docs/Ionic-Angular-Usage.md
- https://github.com/capacitor-community/sqlite/blob/refactor/docs/Ionic-React-Usage.md
- https://github.com/capacitor-community/sqlite/blob/refactor/docs/Ionic-Vue-Usage.md

and also to the apps starter
- https://github.com/jepiqueau/angular-sqlite-app-refactor
- https://github.com/jepiqueau/react-sqlite-app-starter/tree/refactor
- https://github.com/jepiqueau/vue-sqlite-app-starter/tree/refactor

All these would help you to make an easy transition
Good luck

**Comment by jepiqueau** [comment]
@deepakjsr7979 Any news ?

**Comment by deepakjsr7979** [comment]
> @deepakjsr7979 Any news ?

Haf of the reference  link  are not working ,
However if i update the existing plugin did i have to change my code big way?

**Comment by jepiqueau** [comment]
@deepakjsr7979 All the links where working when i gave them to you, but now the don't as i move the refactor branch of the plugin to branch 2.9.x since i have published the beta using the capacitor3 in the master. so they are now
- https://github.com/capacitor-community/sqlite/blob/2.9.x/docs/APIConnection.md
- https://github.com/capacitor-community/sqlite/blob/2.9.x/docs/APIDBConnection.md
- https://github.com/capacitor-community/sqlite/blob/2.9.x/docs/ImportExportJson.md
- https://github.com/capacitor-community/sqlite/blob/2.9.x/docs/Ionic-Angular-Usage.md
and so on... replace refactor by 2.9.x in the previous link

```
{
  ...
  ...
  tables: [
    {
      name: 'FingerTemplateM',
      schema: [
        ....
        ....
      ],
      indexes: [
        {
          name: 'EmpIDIndex',
          value: 'EmployeeId ASC, FingerIndex ASC',
          mode: 'UNIQUE',
        },
      ],
    }
  ]
}
```
Yes you have to change your code, the 2.4.x release is not going to be maintained, so the 2.9.x will become soon the `latest` and the 3.x the `next`.

**Comment by deepakjsr7979** [comment]
> @deepakjsr7979 All the links where working when i gave them to you, but now the don't as i move the refactor branch of the plugin to branch 2.9.x since i have published the beta using the capacitor3 in the master. so they are now
> 
> * https://github.com/capacitor-community/sqlite/blob/2.9.x/docs/APIConnection.md
> * https://github.com/capacitor-community/sqlite/blob/2.9.x/docs/APIDBConnection.md
> * https://github.com/capacitor-community/sqlite/blob/2.9.x/docs/ImportExportJson.md
> * https://github.com/capacitor-community/sqlite/blob/2.9.x/docs/Ionic-Angular-Usage.md
>   and so on... replace refactor by 2.9.x in the previous link
> 
> ```
> {
>   ...
>   ...
>   tables: [
>     {
>       name: 'FingerTemplateM',
>       schema: [
>         ....
>         ....
>       ],
>       indexes: [
>         {
>           name: 'EmpIDIndex',
>           value: 'EmployeeId ASC, FingerIndex ASC',
>           mode: 'UNIQUE',
>         },
>       ],
>     }
>   ]
> }
> ```
> 
> Yes you have to change your code, the 2.4.x release is not going to be maintained, so the 2.9.x will become soon the `latest` and the 3.x the `next`

#thanks man
Really appreciate your contribution to ionic community..

Bro as u r using your own oh JSON import structure to create tables and import data , but if export from tools like DB browser for sqlite or sqlite studios it has a different SQL skema na data , if ther way to map bother the json system generated according to your JSON import structure , because if you have database created in SQL tools db browser or studios we have to manually create the skemas and all thes take lots of time to do it in currently .. if we can generate it systematic it we'll be more fun and less debugging ... Hope u understand my point ?

**Comment by deepakjsr7979** [comment]
> value: 'EmployeeId ASC, FingerIndex ASC',
>           mode: 'UNIQUE',

i have now updated my 2.4 to 
` "@capacitor-community/sqlite": "^2.9.6",`
now i m gating error 
{"result":false,"message":"isJsonValid command failed : Stringify Json Object not Valid"}
same json was working on perfectly on 2.4 ver.
at list message will say why its not valid..? i have added  "version": 1, -- but stell has that error.

**Comment by jepiqueau** [comment]
@deepakjsr7979  look at https://github.com/jepiqueau/angular-sqlite-app-starter/tree/refactor it will help you to see what should be the impact in your code of moving from 2.4 to 2.9.6. You will see that the plugin initialization has changed. See the new service below
```
import { Injectable } from '@angular/core';

import { Plugins, Capacitor } from '@capacitor/core';
import '@capacitor-community/sqlite';
import { SQLiteDBConnection, SQLiteConnection, capSQLiteSet,
         capSQLiteChanges, capEchoResult, capSQLiteResult 
        } from '@capacitor-community/sqlite';
const { CapacitorSQLite } = Plugins;

@Injectable()

export class SQLiteService {
    sqlite: SQLiteConnection;
    isService: boolean = false;
    platform: string;

    constructor() {
    }
    /**
     * Plugin Initialization
     */
    initializePlugin(): Promise<boolean> {
        return new Promise (resolve => {
            this.platform = Capacitor.platform;
            console.log("*** platform " + this.platform)
            const sqlitePlugin: any = CapacitorSQLite;
            this.sqlite = new SQLiteConnection(sqlitePlugin);
            this.isService = true;
            console.log("$$$ in service this.isService " + this.isService + " $$$")
            resolve(true);
        });
    }
    /**
     * Echo a value
     * @param value 
     */
    async echo(value: string): Promise<capEchoResult> {
        console.log("&&&& in echo this.sqlite " + this.sqlite + " &&&&")
        if(this.sqlite != null) {
            return await this.sqlite.echo(value);
        } else {
            return null;
        }
    }
    /**
     * addUpgradeStatement
     * @param database 
     * @param fromVersion 
     * @param toVersion 
     * @param statement 
     * @param set 
     */
    async addUpgradeStatement(database:string, fromVersion: number,
                              toVersion: number, statement: string,
                              set?: capSQLiteSet[])
                                        : Promise<capSQLiteResult> {
        if(this.sqlite != null) {
            return await this.sqlite.addUpgradeStatement(database,
                fromVersion, toVersion, statement, set ? set : []);
        } else {
            return null;
        }                             
    }
    /**
     * Create a connection to a database
     * @param database 
     * @param encrypted 
     * @param mode 
     * @param version 
     */
    async createConnection(database:string, encrypted: boolean,
                           mode: string, version: number
                           ): Promise<SQLiteDBConnection | null> {
        if(this.sqlite != null) {
            const db: SQLiteDBConnection = await this.sqlite.createConnection(
                                database, encrypted, mode, version);
            if (db != null) {
                return db;
            } else {
                return null
            }
        } else {
            return null;
        }
    }
    /**
     * Close a connection to a database
     * @param database 
     */
    async closeConnection(database:string): Promise<capSQLiteResult> {
        if(this.sqlite != null) {
            return await this.sqlite.closeConnection(database);
        } else {
            return null;
        }
    }
    /**
     * Retrieve an existing connection to a database
     * @param database 
     */
    async retrieveConnection(database:string): 
            Promise<SQLiteDBConnection | null | undefined> {
        if(this.sqlite != null) {
            return await this.sqlite.retrieveConnection(database);
        } else {
            return null;
        }
    }
    /**
     * Retrieve all existing connections
     */
    async retrieveAllConnections(): 
                    Promise<Map<string, SQLiteDBConnection>> {
        if(this.sqlite != null) {
            const myConns =  await this.sqlite.retrieveAllConnections();
            let keys = [...myConns.keys()];
            keys.forEach( (value) => {
                console.log("Connection: " + value);
              }); 
              return myConns;
        } else {
            return null;
        }               
    }
    /**
     * Close all existing connections
     */
    async closeAllConnections(): Promise<capSQLiteResult> {
        if(this.sqlite != null) {
            return await this.sqlite.closeAllConnections();
        } else {
            return null;
        }
    }
    /**
     * Import from a Json Object
     * @param jsonstring 
     */
    async importFromJson(jsonstring:string): Promise<capSQLiteChanges> {
        if(this.sqlite != null) {
            return await this.sqlite
                                .importFromJson(jsonstring);
        } else {
            return null;
        }
                    
    }
    /**
     * Is Json Object Valid
     * @param jsonstring Check the validity of a given Json Object
     */
    async isJsonValid(jsonstring:string): Promise<capSQLiteResult> {
        if(this.sqlite != null) {
            return await this.sqlite.isJsonValid(jsonstring);
        } else {
            return null;
        }

    }
    /**
     * Copy databases from public/assets/databases folder to application databases folder
     */
    async copyFromAssets(): Promise<capSQLiteResult> { 
        if (this.sqlite != null) {
          return await this.sqlite.copyFromAssets();
        } else {
          return null;
        }
      }
    
}

```

You can also share your code on github so i may have a look

**Comment by deepakjsr7979** [comment]
> are your code on github so i may have a look

retrieveAllConnections return Null;

if i put database: this.dbName in every method its working is it recommended to do so?
 
```
  await CapacitorSQLite.createConnection({ database: this.dbName, encrypted: false, mode: 'full', version: 1  });
        await CapacitorSQLite.open({ database: this.dbName });
        if (!update) {
          await CapacitorSQLite.createSyncTable({ database: this.dbName});
        } else {
          await CapacitorSQLite.setSyncDate({ syncdate: '' + new Date().getTime(), database: this.dbName });
        }

 getListAll(quryList: string) {
    console.log(this.dbReady);
    return this.dbReady.pipe(
      switchMap(isReady => {
        if (!isReady) {
          return of({ values: [] });
        } else {
          // const statement = 'SELECT * FROM products;';
          const statement = quryList;
          return from(CapacitorSQLite.query({ statement, values: [] , database: this.dbName}));
        }
      })
    );
  }

  async getById(id) {
    const statement = `SELECT * FROM products LEFT JOIN vendors ON vendors.id=products.vendorid WHERE products.id=${id} ;`;
    return (await CapacitorSQLite.query({ statement, values: [], database: this.dbName })).values[0];
  }
```

**Comment by deepakjsr7979** [comment]
> #thanks man
> Really appreciate your contribution to ionic community..
> 
> Bro as u r using your own oh JSON import structure to create tables and import data , but if export from tools like DB browser for sqlite or sqlite studios it has a different SQL skema of json , if there is a way to map both the json, system generated json file according to your JSON import structure, because if you have database created using SQL tools db browser or studios we have to manually create the skema and all thes take lots of time to do it in currently .. if we can generate it systematic it we'll be more fun and less debugging ... Hope u understand my point ?
> 
> Or is there any tool where I can upload my database file it will generate JSON skema according to your JSON import structure ? So that we don't have to create table skema and import data manually?

Bro can You please  reply on this as well?

**Comment by jepiqueau** [comment]
@deepakjsr7979 As already mentioned the code is there https://github.com/jepiqueau/angular-sqlite-app-starter/tree/refactor . Clone it and make it working. When you will have understood modify your code accordingly and it will work. For what i saw from DBBrowser if can exported the SQL statements or the table data in json but not the shemas or indexes. So if you want to import a database exported by DBBrowser in SQL Statements it is straightforward. take the file generated by DBBrowser read it and create a string  and do a db.execute of that string and you will have your db loaded. So i do not thing there is a need for modyfing the json format
