### ISSUE TITLE
importFromJson file dont Suppoet data type BOOLEAN and DATETIME

### ISSUE THREAD

**Issue by deepakjsr7979** [capacitor-community/sqlite#65]
```
	{ "column": "DataSync", "value": "BOOLEAN DEFAULT (0) NOT NULL" },
	{ "column": "CreatedOn", "value": "DATETIME  DEFAULT (datetime(CURRENT_TIMESTAMP, 'localtime')) NOT NULL" }
```
current JSON import don't support above data set and conditions. like cant have date-time function , can't set date time according to local-time zone, BOOLEAN  Type not support in importing and exporting data to the table,

**I capacitor community to look into this and enhance the plugin features.**

**Comment by jepiqueau** [comment]
@deepakjsr7979 First thanks for using the plugin, BOOLEAN and DATETIME or not supported types from SQLite see doc `https://www.sqlite.org/datatype3.html` This is the reason why this type are not implemented in importFromJson. 

```
2. Storage Classes and Datatypes
Each value stored in an SQLite database (or manipulated by the database engine) has one of the following storage classes:

NULL. The value is a NULL value.

INTEGER. The value is a signed integer, stored in 1, 2, 3, 4, 6, or 8 bytes depending on the magnitude of the value.

REAL. The value is a floating point value, stored as an 8-byte IEEE floating point number.

TEXT. The value is a text string, stored using the database encoding (UTF-8, UTF-16BE or UTF-16LE).

BLOB. The value is a blob of data, stored exactly as it was input.

A storage class is more general than a datatype. The INTEGER storage class, for example, includes 6 different integer datatypes of different lengths. This makes a difference on disk. But as soon as INTEGER values are read off of disk and into memory for processing, they are converted to the most general datatype (8-byte signed integer). And so for the most part, "storage class" is indistinguishable from "datatype" and the two terms can be used interchangeably.

Any column in an SQLite version 3 database, except an INTEGER PRIMARY KEY column, may be used to store a value of any storage class.

All values in SQL statements, whether they are literals embedded in SQL statement text or parameters bound to precompiled SQL statements have an implicit storage class. Under circumstances described below, the database engine may convert values between numeric storage classes (INTEGER and REAL) and TEXT during query execution.

2.1. Boolean Datatype
SQLite does not have a separate Boolean storage class. Instead, Boolean values are stored as integers 0 (false) and 1 (true).

2.2. Date and Time Datatype
SQLite does not have a storage class set aside for storing dates and/or times. Instead, the built-in Date And Time Functions of SQLite are capable of storing dates and times as TEXT, REAL, or INTEGER values:

TEXT as ISO8601 strings ("YYYY-MM-DD HH:MM:SS.SSS").
REAL as Julian day numbers, the number of days since noon in Greenwich on November 24, 4714 B.C. according to the proleptic Gregorian calendar.
INTEGER as Unix Time, the number of seconds since 1970-01-01 00:00:00 UTC.
Applications can chose to store dates and times in any of these formats and freely convert between formats using the built-in date and time functions.


```

**Comment by deepakjsr7979** [comment]
> formats using the built-in date and time functions

Thanks for your descriptive reply
 **relay informative , thanks man** 👍 .

**Comment by deepakjsr7979** [comment]
One more thing i want to ask 
if i am evacuating any CapacitorSQLite.query({ statement, values: [] })) 
how to get **SQL error statement** if query fails, as error message ?

**Comment by deepakjsr7979** [comment]
> `https://www.sqlite.org/datatype3.html`

![image](https://user-images.githubusercontent.com/56829932/104810730-a8d82c00-581c-11eb-831a-090ae70553e6.png)
actually it gives so many data type options that is way i got confuse .

**Comment by jepiqueau** [comment]
@deepakjsr7979 i understand your confusion but it seems that SQLiteStudio is not compliant if you take DB Browser for SQLite you will only see the 5 types described in the doc mentioned above. If you are using `refactor` release of the plugin, the result of a query return a Promise<capSQLiteValues> where

```
#### capSQLiteValues

| Prop          | Type                | Description                      |
| ------------- | ------------------- | -------------------------------- |
| **`values`**  | <code>any[]</code>  | the data values list as an Array |
| **`message`** | <code>string</code> | a returned message               |
```

**Comment by deepakjsr7979** [comment]
> @deepakjsr7979 i understand your confusion but it seems that SQLiteStudio is not compliant if you take DB Browser for SQLite you will only see the 5 types described in the doc mentioned above. If you are using `refactor` release of the plugin, the result of a query return a Promise where
> 
> ```
> #### capSQLiteValues
> 
> | Prop          | Type                | Description                      |
> | ------------- | ------------------- | -------------------------------- |
> | **`values`**  | <code>any[]</code>  | the data values list as an Array |
> | **`message`** | <code>string</code> | a returned message               |
> ```

thanks for your reply ,
message does't return the SQL query error only say  **Query command failed** not shows reason behind that failure 
like SQL shows the message why the query got failed ?
not shows that.

**Comment by jepiqueau** [comment]
@deepakjsr7979 on which platform? i think in the refactor it must return the message, if not tell me as it was also part of the scope of the refactor to better handle the error message

**Comment by deepakjsr7979** [comment]
> @deepakjsr7979 on which platform? i think in the refactor it must return the message, if not tell me as it was also part of the scope of the refactor to better handle the error message

In Android platform , It only shows **Query command failed**  and changes -1 .

**Comment by jepiqueau** [comment]
@deepakjsr7979 Did you move your app to the refactor release of the plugin and if so do you still have the issue on the Error message?
