### ISSUE TITLE
exportToJson command failed : return Obj is not a JsonSQLite Obj

### ISSUE THREAD

**Issue by najmulansari** [capacitor-community/sqlite#67]
I am getting "exportToJson command failed : return Obj is not a JsonSQLite Obj" error whenever I do partial export. Full export always works. I have just 3 tables. I added just 2 entries still gives this error.

I am using the below plugins.
 "@capacitor-community/sqlite": "^2.9.5",
 "@capacitor/android": "^2.4.6",
 "@capacitor/core": "2.4.6"

Please help as I am stuck with this since long.

**Comment by jepiqueau** [comment]
@najmulansari first thanks for using the refactor release it help to sort out all the bugs. I am ready to help but for this i need more data from you. The schema of your database , the stored synchronization date before the partial export, the 2 entries that you added was it from a partial importFromJson or from a normal  use (execute, executeSet or run). Can i see partially the code where you do these operations. Which framework are you using Ionic, React, Vue. i updated yesterday the Ionic/Vue starter App and it is working fine but there is something that i may overlook

**Comment by jepiqueau** [comment]
@najmulansari Are you using the Electron platform?

**Comment by najmulansari** [comment]
Hi @jepiqueau,
Below are the details.

DB Schema.
--------------
export const tableSchema: string = `CREATE TABLE IF NOT EXISTS class (id INTEGER PRIMARY KEY NOT NULL,userId INTEGER,className TEXT,description TEXT,last_modified INTEGER  DEFAULT (strftime('%s', 'now')));
CREATE TABLE IF NOT EXISTS section (id INTEGER PRIMARY KEY NOT NULL,userid  INTEGER  ,classId  INTEGER  ,sectionName  TEXT NOT NULL  ,description  TEXT ,last_modified INTEGER  DEFAULT (strftime('%s', 'now')) );
CREATE TABLE IF NOT EXISTS student ( id INTEGER PRIMARY KEY NOT NULL, userId INTEGER , classId INTEGER , sectionId INTEGER , studentName TEXT , address TEXT , gender TEXT , contact1 TEXT , contact2 TEXT , email TEXT ,
 guardian TEXT , guardiancontact TEXT , schoolcollege TEXT , startdate TEXT , dob TEXT , fees INTEGER , discount INTEGER , profilePic TEXT , last_modified INTEGER  DEFAULT (strftime('%s', 'now')) );
CREATE TRIGGER IF NOT EXISTS class_trigger_last_modified
AFTER UPDATE ON class
FOR EACH ROW WHEN NEW.last_modified <= OLD.last_modified
BEGIN
UPDATE class SET last_modified= (strftime('%s', 'now')) WHERE id=OLD.id;
END;
CREATE TRIGGER IF NOT EXISTS section_trigger_last_modified
AFTER UPDATE ON section
FOR EACH ROW WHEN NEW.last_modified <= OLD.last_modified
BEGIN
UPDATE section SET last_modified= (strftime('%s', 'now')) WHERE id=OLD.id;
END;
CREATE TRIGGER IF NOT EXISTS student_trigger_last_modified
AFTER UPDATE ON student
FOR EACH ROW WHEN NEW.last_modified <= OLD.last_modified
BEGIN
UPDATE student SET last_modified= (strftime('%s', 'now')) WHERE id=OLD.id;
END;
PRAGMA user_version = 1;`

-----

private async createDB() {
    var exists = (await Storage.get({ key: this.dbName })).value;
    if (!exists) {
      await this.DBConnection.execute(tableSchema);
      await this.DBConnection.setSyncDate('' + (new Date()).toISOString())
      await Storage.set({ key: this.dbName, value: '1' });
    }
  }


  public async addClass(userId,className,description) {
    var values = [userId,className,description];
    let sqlcmd: string = "INSERT INTO Class(userId,className,description) VALUES (?,?,?);";

    var result = await this.db.run(sqlcmd, values);
    return result.changes;
  }

  public async addSection(userid,classId,sectionName,description) {
    var values = [userid,classId,sectionName,description];
    let sqlcmd: string = "INSERT INTO Section(userid,classId,sectionName,description); VALUES (?,?,?,?);";

    var result = await this.db.run(sqlcmd, values);
    return result.changes;
  }


 await this.addClass(1,"MA","Master of Atrs");

 await this.addClass(1,1,"Morning","Morning - From 8AM to 9AM");


  public async getDatabaseExport() {
    let result = await this.db.exportToJson('partial');
    console.log(JSON.stringify(result.export));

    var date = (new Date()).toISOString();
    await this.db.setSyncDate(date);
  }

I am using Ionic/Angular/Capacitor. Below are installed plugins.

"dependencies": {
    "@angular/common": "~11.1.0",
    "@angular/core": "~11.1.0",
    "@angular/forms": "~11.1.0",
    "@angular/platform-browser": "~11.1.0",
    "@angular/platform-browser-dynamic": "~11.1.0",
    "@angular/router": "~11.1.0",
    "@capacitor-community/sqlite": "^2.9.5",
    "@capacitor/android": "^2.4.6",
    "@capacitor/core": "2.4.6",
    "@ionic-native/call-number": "^5.30.0",
    "@ionic-native/core": "^5.30.0",
    "@ionic-native/file-opener": "^5.30.0",
    "@ionic-native/splash-screen": "^5.30.0",
    "@ionic-native/status-bar": "^5.30.0",
    "@ionic/angular": "^5.5.2",
    "call-number": "^1.0.1",
    "cordova-plugin-androidx": "^3.0.0",
    "cordova-plugin-androidx-adapter": "^1.1.3",
    "cordova-plugin-file-opener2": "^3.0.5",
    "jetifier": "^1.6.6",
    "moment": "^2.29.1",
    "npm-check-updates": "^11.0.0",
    "rxjs": "~6.6.3",
    "tslib": "^2.1.0",
    "zone.js": "~0.11.3"
  },

**Comment by jepiqueau** [comment]
@najmulansari Which platform are you testing Android, iOS, Electron

**Comment by najmulansari** [comment]
@jepiqueau Android, OS 7/10

**Comment by jepiqueau** [comment]
@najmulansari Ok i did reproduce the issue, so i have to figure out this thanks for your patience

**Comment by jepiqueau** [comment]
@najmulansari the syncDate and the date of the insert users are the same so there is no object returned
so define your initial syncDate as date - 2 hours
```
    // set the synchronization date
    let date = new Date();
    date.setHours(date.getHours() - 2);
    let syncDate: string = date.toISOString();
    console.log(`$$$ syncDate ${syncDate}`)
    ret = await db.setSyncDate(syncDate);
    if(!ret.result) return false;
    result = await db.getSyncDate();
    if(result.syncDate === 0) return false;
    console.log("$$ initial syncDate " + result.syncDate);
```
after do your insert
do your export
this should work

**Comment by najmulansari** [comment]
@jepiqueau - After making changes as per your suggestion, Now I am getting "SetSyncDate command failed".

  public async getDatabaseExport() {
    var result = await this.db.getSyncDate();
    if (result.syncDate === 0) {
      let date = new Date();
      date.setHours(date.getHours() - 2);
      let syncDate: string = date.toISOString();
      await this.db.setSyncDate(syncDate);
      return;
    }

    console.log("$$ initial syncDate " + result.syncDate);
    var exportResult = await this.db.exportToJson('partial');
    console.log(JSON.stringify(exportResult.export));

    var date = (new Date()).toISOString();
    await this.db.setSyncDate(date);
  }

See output below from chrome debugger console.

native:
Object
callbackId: "134016820"
methodName: "setSyncDate"
options: {database: "myfavcoachingdb", syncdate: "2021-01-22T01:10:08.372Z"}
pluginId: "CapacitorSQLite"

result:
Object
message: "SetSyncDate command failed"
result: false

**Comment by jepiqueau** [comment]
@najmulansari this has been implemented in ` https://github.com/jepiqueau/angular-sqlite-app-refactor` and works well but it was to explained the reason of failure more than thing you should do. For me, there is no reason to do a partial export just after creating a database. Usually the process flow of synchronization is

- get the database schemas, indexes and table's data from a server
- create a json object from these data
- use `importFromJson` with '**full**' mode to implement the database in your  device
- create the connection to the database with `createConnection` which returned the db connector
- open the database with `db.open`
- create the synchronization table with `db.createSyncTable`, the synchronization date is automatically created and stored as a number
- you can check the initial synchronization date with `db.getSyncDate`
- now you can start using the database locally and make some `db.run, db.query, ...` 
- after a while you decide to synchronize back the local database to the remote database on the server
- use `exportToJson` with '**partial**' mode to export only the modifications since the 'initial' or the 'last' synchronization date
- create from the json object the data to be send to the server
- upload the remote server database
- set a new synchronization date to the local database. the format is `2021-01-20T18:42:15.000Z` 

You could also decide to erase the remote server database so for this you may use the `exportToJson with the '**full**' mode

hope this clarify the process
I encourage you to look at `https://github.com/jepiqueau/angular-sqlite-app-refactor` which demonstrate the use of the plugin in `testimportjson, testexportjson` and also show your case implemented in `testexportjson67`

**Comment by najmulansari** [comment]
Thank you so much for your help, I really appreciate it. I think setSyncDate was the issue. On setting 2 hours earlier it solved the problem. A big thumbs up for you.

**Comment by jepiqueau** [comment]
@najmulansari you are welcome
