### ISSUE TITLE
Import with foreign keys defined

### ISSUE THREAD

**Issue by dinosaadeh** [capacitor-community/sqlite#70]
I noticed that when I do an import and that there are foreign keys, the child table doesn't import and I think it is part of a transaction logic.. Importing the child while the parent table import didn't commit is causing the whole transaction to abort.

**Comment by jepiqueau** [comment]
@dinosaadeh hi, thanks to bring this on github. I never test it, thinking about it  and before i bring a solution i suggest the following workaround. make a first import 'full' containing all the table's (schema, indexes) and the parent table's data and when it is executed successfully make a second 'partial' import containing all the child table's data. I didn't test it but i think it should work. come ba k to me if not

**Comment by viniciusmaran** [comment]
Same issue here, even using pragma foreign_keys = OFF the import fails.

**Comment by jepiqueau** [comment]
@dinosaadeh @viniciusmaran I come back to both of you. Is still an issue with the release 3.2.0-10 of the `@capacitor-community/sqlite` plugin. If it i still the case can you give an example of the json object that you want to import. If i do not have news from you i will close the issue.

**Comment by dinosaadeh** [comment]
Hello,

I didn't upgrade to this version yet. Would upgrading cause any issues?
This is the one I'm currently using ***@***.***/sqlite":
"^2.4.3-1". Either way, close the issue and will let you know of anything
that comes up. Thanks for reaching out.

Regards, *Dino SAADEH*

**Comment by jepiqueau** [comment]
@dinosaadeh  thanks for replying, yah it's a long way, before to upgrade make sure that you do not use any other plugins which have not being converted to `@capacitor/core@3.2.0` the version 3 of the `@capacitor-community/sqlite` use try...catch to retrieve all the error and have new methods for securing the passphrase for encryption. May be the best is that you give me an example of json object which fails importing in your version so i can test it myself on the new version.

**Comment by jepiqueau** [comment]
@dinosaadeh Without getting info from your side, i will close the issue in 2 days
