### ISSUE TITLE
com.getcapacitor.community.database.sqlite.CapacitorSQLitePlugin cannot find symbol

### ISSUE THREAD

**Issue by vorkapps** [capacitor-community/sqlite#72]
I was using the 2.4.4 version of the plugin which presented random problems with the permissions, so I thought to use the 2.9.6 version and modified my code to use the new methods.
However while trying to build the Android native application, Android Studio cannot find the com.getcapacitor.community.database.sqlite.CapacitorSQLitePlugin import

I've tried everything, removing and re-installing the plugin, doing an npx cap sync again etc, but nothing helps.

Any idea where I'm doing things wrong ?
Many thanks

**Comment by vorkapps** [comment]
it finds com.getcapacitor.community.database.sqlite.CapacitorSQLite but not com.getcapacitor.community.database.sqlite.CapacitorSQLitePlugin, as if it's finding the old version of the plugin

**Comment by vorkapps** [comment]
Ok it seems that on the main README.md it says that you need to use:
import com.getcapacitor.community.database.sqlite.CapacitorSQLitePlugin;

public class MainActivity extends BridgeActivity {
    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        registerPlugin(CapacitorSQLitePlugin.class);

    }

But when you look on the README.md in the NODE_MODULES folder it says:
import com.getcapacitor.community.database.sqlite.CapacitorSQLite;

public class MainActivity extends BridgeActivity {
    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        registerPlugin(CapacitorSQLite.class);

    }

So it seems it's a typo on the README.md on github.

Issue closed, but maybe you need to fix the readme here :)

Many thanks

**Comment by jepiqueau** [comment]
@vorkapps hi, thanks for using the plugin and to migrate to 2.9.6. If you use the 2.9.6 `(latest)` , you have to look on github to the readme of the branch 2.9.x to get the instructions. The instructions that you are talking about are on the master branch which are corresponding to the `next` release which are using Capacitor3. if you look also at `https://www.npmjs.com/package/@capacitor-community/sqlite`you get also the right instructions. The `next` version is based on Capacitor3 which is still in `beta` but also better handle the errors through the try...catch which allow you to get the proper error message to typescript. Happy that you find your way. Do not hesitate to contact me if your find issues or enhancements required

**Comment by vorkapps** [comment]
@jepiqueau hi and thanks for replying :) My bad then! :) I look forward to using your plugin when v3 is out 
Many thanks!

**Comment by jepiqueau** [comment]
@vorkapps Ok so for the v3 look at the master, in fact for Android you will not have to add something in the mainActivity.java i will updated the readme i have tested it for Ionic/Vue and Ionic/React and it works so i will also update for Ionic/angular. thanks again for using the plugin
