### ISSUE TITLE
No permission to write to db

### ISSUE THREAD

**Issue by vorkapps** [capacitor-community/sqlite#73]
Hi, I'm using 2.9.6 (latest)

I'm having real troubles identifying what's going on... On some devices the sqldb is create, opened and populated fine, without any issues. On others it does not get created...

No permission is requested from the user on either of the above. I assume it is "obtained" by default, as it is not requested even for the devices it functions correctly.

Code fragment:

sqlite: SQLiteConnection;
sqldb: SQLiteDBConnection;

initializePlugin() {
  return new Promise (resolve => {
    const sqlitePlugin: any = CapacitorSQLite;
    this.sqlite = new SQLiteConnection(sqlitePlugin);
    resolve(true);
  });
}

this.initializePlugin().then(() => {
  this.sqldb = null;
  if (this.sqlite != null) {
    const db: SQLiteDBConnection = await this.sqlite.createConnection(database, encrypted, mode, version);
    this.sqldb = db;
  }
  if (this.sqldb != null) {
    await this.sqldb.open().then(async opRes => {
      // if (opRes.result)  // I first tried check the opRes.result boolean but it wasn't getting a true value on either of the devices, so I commented it out
     await this.sqldb.execute('CREATE TABLE xx blah blah');
  }
}

Please help as the app is already on the appstore as it was working properly on all devices tested priot to launch

Many thanks

**Comment by jepiqueau** [comment]
@vorkapps Have you identified on which device it does not work? It is difficult to say. I only test on Apple simulators as i do not have any Apple real device. Normally, there is no need for permissions as far as i know on Apple.
I do not understand in your code why you are missing `await` and `.then` which may cause an issue
```
await this.sqldb.open().then(async opRes => {
```
i think it should be either
```
const res = await this.sqldb.open();
if(res.result  {
  ...
} else {
  ...
}
```
or 
```
this.sqldb.open().then( async opRes => {
  if(opRes.result) {
    ...
  } else {
    ...
  }
});
```
Which framework are you using Ionic/Angular, Ionic/React, Ionic/Vue, others... ?

**Comment by vorkapps** [comment]
I'm using Ionic/Angular
When I had the "if" statement to check the .result value it was never getting a true value for some reason
I have an "await" before the this.sqldb.open()..... because I want to execute the open asynchronously and move to the next statement only after the open() executes (either successfully or not). Is this wrong? But why should it interfere?

**Comment by vorkapps** [comment]
The problem occurs on ANDROID, not sure about apple, but I think it does there too, but not on all devices

**Comment by vorkapps** [comment]
Hi again, dont spend any time on this, I think there might be a logic error in the app, under certain conditions and it might not be a problem with the plugin. I will let you know soon. Thanks ! :)

**Comment by jepiqueau** [comment]
@vorkapps Ok, tell me when you fix your app and close the issue

**Comment by vorkapps** [comment]
Indeed it was a logic error which never occured when an existing "beta" tester was launching the app, even if it was newly installed... It never happened before, because all users were beta-testers, but now that the app is out in the open, it happens to all new users...
Sorry for troubling you, and thank you for an excellent plugin
Question (if I may get your feedback on it):  what is better on new installs with a pre-populated db:
  1. create a new db and have an sql-set included in the bundle and populate it on first-run by running .execute() ?
  or
  2. include a pre-populated sqlite.db and use the "copyFromAsset()" method ?

**Comment by jepiqueau** [comment]
@vorkapps you can choose both options. you have to balance between the "dead-weight" of the pre-populated database which will be used only once and the time to execute the sql-set the first time which can be painful for the user and discourage them to use the app. i will certainly opt for the solution 1 for application size(kilobytes) reason, but it is up to you to evaluate this. i close this issue now
