### ISSUE TITLE
getSyncDate() bogus output

### ISSUE THREAD

**Issue by CosminCraciun** [capacitor-community/sqlite#74]
getSyncDate doesn't work as expected.

I used the provided [Ionic/Angular app](https://github.com/jepiqueau/angular-sqlite-app-starter) from the repo.
I modified the 2 databases test so that after setting the syncDate, I also retrieve it to see how it looks like: 

> test2dbs.page.ts line 76

```
// set the synchronization date
const syncDate: string = "2020-11-25T08:30:25.000Z";
await db.setSyncDate(syncDate);
const sy = await db.getSyncDate();
alert(sy.syncDate);
```

The retrieved sync date is `1606293025`. I expected to see the same syncDate I inserted "2020-11-25T08:30:25.000Z".
Note that the end of the retrieve date ...3025 is not consistently the minutes and seconds. A different insert will give a more random result.
Inserting `2020-11-25T08:33:28.000Z` gets the `1606293208`

Ran the tests on an android emulator: Pixel 2 with API 29.

**Comment by jepiqueau** [comment]
@CosminCraciun Thanks for using the plugin, the date which is returned is a number corresponding to the `unix epoch` of the date you have entered which is stored in the database. so if you do 
```
c= new Date(1606293025*1000)

```
you will get `c = 2020-11-25T08:30:25.000Z` which is the one you have given
Hope this clarify

**Comment by CosminCraciun** [comment]
Yeah, thanks! 
Initially I didn't multiply with 1 000. I didn't catch this in the documentation, but it's possible that I missed it. 
Great work, though!
