### ISSUE TITLE
Data import where the ID is a UUID

### ISSUE THREAD

**Issue by dinosaadeh** [capacitor-community/sqlite#75]
I opted for a table (as a first step before changing the rest) to have a UUID. On import it failed. The reason being is that in UtilsJson.java, the method isIdExists is throwing an exception that was not caught. The key is passed and the dashes  in SQL represented unknown tokens. So I added the following which works both for numeric IDs and UUID (string):

```
        query = new StringBuilder("SELECT ")
            .append(firstColumnName)
            .append(" FROM ")
            .append(tableName)
            .append(" WHERE ")
            .append(firstColumnName)
            .append(" = '")
            .append(key)
            .append("';")
            .toString();
```

This solved my issue. Please advise if you have any comments.

**Comment by jepiqueau** [comment]
@dinosaadeh Thank for that bug for Android and Electron. It was well written for iOS. it will come in the next release as:
```
        StringBuilder sbQuery = new StringBuilder("SELECT ")
            .append(firstColumnName)
            .append(" FROM ")
            .append(tableName)
            .append(" WHERE ")
            .append(firstColumnName);
        if(key instanceof Integer) sbQuery
            .append(" = ")
            .append(key)
            .append(";");
        if(key instanceof String) sbQuery
            .append(" = '")
            .append(key)
            .append("';");
        String query = sbQuery.toString();

```
Which version are you working with ?

**Comment by dinosaadeh** [comment]
"@capacitor-community/sqlite": "^2.4.3-1",

**Comment by jepiqueau** [comment]
@dinosaadeh this has been fix in 2.9.8

**Comment by jepiqueau** [comment]
@dinosaadeh see example in the doc https://github.com/capacitor-community/sqlite/blob/2.9.x/docs/ImportExportJson.md#full-mode-with-triggers-and-uuid , so i close the issue

**Comment by maxsoftware** [comment]
Import also fails when sql_deleted = 1 and ID is a UUID. The affected lines in ImportFromJson.java are 551 - DELETE FROM command.
