### ISSUE TITLE
Can't create my own DB Trigger

### ISSUE THREAD

**Issue by deepakjsr7979** [capacitor-community/sqlite#76]
Can't create my table base own trigger according to my use , can't import export as well.. can we accept this to be done ✅ in future?

**Comment by jepiqueau** [comment]
@danielprrazevedo  Hi, yes i know that we cannot import/export trigger yet. It was on the list of ToDos, but i decided as know one where asking to prioritize the move to Capacitor3 which took me much more time that foreseen. that will be the first on the list except if there are other bugs requiring my attention. Is it something blocking for you?

can you more descriptif on `Can't create my table base own trigger according to my use`, do you mean with standard sql statements and execute or just import/export?

**Comment by deepakjsr7979** [comment]
> @danielprrazevedo Hi, yes i know that we cannot import/export trigger yet. It was on the list of ToDos, but i decided as know one where asking to prioritize the move to Capacitor3 which took me much more time that foreseen. that will be the first on the list except if there are other bugs requiring my attention. Is it something blocking for you?
> 
> can you more descriptif on `Can't create my table base own trigger according to my use`, do you mean with standard sql statements and execute or just import/export?

Thank's for your reply...

I mean to say that I have created my project  required own trigger , its working fine in my DB sqlite , but i don't know how to add that trigger to specific table , as u have it for last_modified

**Comment by jepiqueau** [comment]
@deepakjsr7979 ok so you do not know how to add it to a specific table in the json object to import i assume

**Comment by jepiqueau** [comment]
@deepakjsr7979  Which release of the plugin are you using?

**Comment by deepakjsr7979** [comment]
I m using 2.9.6

**Comment by jepiqueau** [comment]
@deepakjsr7979 i am working on it, it will be on the next release

**Comment by deepakjsr7979** [comment]
> @deepakjsr7979 i am working on it, it will be on the next release

Thanks man☺️ really appreciate your effort..

**Comment by jepiqueau** [comment]
@deepakjsr7979 this has been fixed in 2.9.8

**Comment by jepiqueau** [comment]
@deepakjsr7979 There were a small issue for  `Android export 'Partial' triggers` which is fixed in 2.9.9

**Comment by deepakjsr7979** [comment]
> @deepakjsr7979 There were a small issue for `Android export 'Partial' triggers` which is fixed in 2.9.9

Great 👌 I will check it and reply you soon 🙂.

**Comment by deepakjsr7979** [comment]
> @deepakjsr7979 There were a small issue for `Android export 'Partial' triggers` which is fixed in 2.9.9

Can you please give  an example of Json structure  to create UUID and trigger ?

**Comment by jepiqueau** [comment]
@deepakjsr7979 The doc was updated so look at https://github.com/capacitor-community/sqlite/blob/2.9.x/docs/ImportExportJson.md#full-mode-with-triggers-and-uuid
