### ISSUE TITLE
Copy db from storage

### ISSUE THREAD

**Issue by enginarmutcu** [capacitor-community/sqlite#77]
Hello,

I want to use my existing prepared database, I download from my server but I can not copy into assets folder so I can not use copyFromAssets function.Is there a way to use existing database in external folder or data folder?

Thanks.

**Comment by jepiqueau** [comment]
@enginarmutcu On which platform have you download from your server (iOS, Android, Windows, MacOs) ?. Is it a sqlite db? why you cannot copy it to the asset folder?

**Comment by enginarmutcu** [comment]
Hi,

I use Ionic 5 - capacitor and trying with android.I use sqlite db. While the app is running, I download sqllite db from web and the downloaded sqllite db stored in application data folder as you can see.
![image](https://user-images.githubusercontent.com/67257016/107122571-75337380-68a9-11eb-95ae-c3204e90036b.png)

As far as I understand, copyFromAssets function is not applicable to this folder.

Thanks for your help.

**Comment by jepiqueau** [comment]
@enginarmutcu Ok, so just create a `databases` folder under io.ionic.starter, not under files folder and move the `transactiondb.db`  and rename the database as `transactionSQLite.db` then you can access it in your app by giving `transaction` as  database name 
```
db = await sqlite.createConnection(transaction)
```
like this it should work.

**Comment by jepiqueau** [comment]
@enginarmutcu Have you succeed to rename the file. see my answer to #79

**Comment by enginarmutcu** [comment]
Hello,
I can create _databases_ folder manually by android studio file explorer.But I need to do this programmatically.Capacitor filesystem plugins could not be create this folder or I can not do it.

**Comment by jepiqueau** [comment]
@enginarmutcu fix in 2.9.10, use `addSQLiteSuffix` and `deleteOldDatabases`methods see https://github.com/capacitor-community/sqlite/blob/2.9.x/docs/MigratingCordovaDatabases.md for explanations
