### ISSUE TITLE
I am trying to use Database Inspector in Android Studio. always showing my application database (highlighted in the image) as "closed".

### ISSUE THREAD

**Issue by deepakjsr7979** [capacitor-community/sqlite#78]
![image](https://user-images.githubusercontent.com/56829932/107147239-f0ad2780-6972-11eb-835d-d5e791a39d35.png)

Any word on this issue?

**Comment by jepiqueau** [comment]
@deepakjsr7979 No idea, i tried on one of my App running on an Emulator `Pixel 3a XL API29` and when i opened the Database Inspector, i could not see any of the databases, i got `Nothing to show`. I am running Android Studio 4.1.2. i look at other apps ie com.google.android.calendar , there i can see the all the dbs. Looking at the `Device File Explorer` the only difference i can see it that the permissions for the databases for the com.google.android.calendar are `-rw-rw----` where for my dbs the permissions are `-rw-------` Can you check on yours and tell me.

**Comment by jepiqueau** [comment]
@deepakjsr7979  I changed the permissions of my dbs to `-rw-rw----` but it does not change anything i still cannot see the databases in the `Database Inspector` So i cannot help more on this, sorry for this.

**Comment by deepakjsr7979** [comment]
> @deepakjsr7979 I changed the permissions of my dbs to `-rw-rw----` but it does not change anything i still cannot see the databases in the `Database Inspector` So i cannot help more on this, sorry for this.
Have you seen the answer there ? Or can suggest any thing from this link

https://stackoverflow.com/questions/65058335/android-studio-database-inspector-always-showing-database-as-closed

**Comment by jepiqueau** [comment]
@deepakjsr7979 I had a look but it does not change anything from my side. I do not see the databases even when i start in the debug mode. Did you do something to see them any preferences ? I am running the emulator in Android Studio.

**Comment by deepakjsr7979** [comment]
> @deepakjsr7979 I had a look but it does not change anything from my side. I do not see the databases even when i start in the debug mode. Did you do something to see them any preferences ? I am running the emulator in Android Studio.

i am ruining on android device.  and if  device android ver > 26 then u can see all the data base in android studio.

**Comment by jepiqueau** [comment]
@deepakjsr7979 I am running API 29 and I cannot see them. Why do you not use DB Browser to look at your DB's. It is free and works. You can also address this point to Android Studio.

**Comment by deepakjsr7979** [comment]
> @deepakjsr7979 I am running API 29 and I cannot see them. Why do you not use DB Browser to look at your DB's. It is free and works. You can also address this point to Android Studio.

I don't know if db browser will so live device database change .. as android studio will so

**Comment by jepiqueau** [comment]
@deepakjsr7979 As i cannot do too much i close the issue

**Comment by jjkavalam** [comment]
Is there any new info on this issue (asking just in case someone has any updates) ?

**Comment by jepiqueau** [comment]
@jjkavalam 
Click on your close database icon
Enable (keep open) by clicking on the icon surrounded by the black rectangle  see picture
<img width="334" alt="AndroidStudio Database Inspector" src="https://github.com/capacitor-community/sqlite/assets/16580653/4d19ecb1-a20e-470b-8a61-4e86d60de77a">

Now you should see your database

**Comment by jepiqueau** [comment]
@jjkavalam it seems that you can access them only when the app is not running and not during the debugging process but i could not find the reason for it

**Comment by khwong-c** [comment]
I faced a similar issue when I was working with `Room`, the latest SQLite-based DB.

I solved this by adding the following to the Manifest
```
<uses-permission android:name="android.permission.INTERNET" />
```

It makes sense to me as the application may need internet access to reach the Inspector.

**Comment by Jhansi-1234** [comment]
how to open the database in andoid studio koala version using java
![Screenshot 2024-08-20 165036](https://github.com/user-attachments/assets/97c58e2d-05be-4933-8993-b70135c43ea3)
