### ISSUE TITLE
Is there a way to connect to a db file, that not has the prefix SQLite.db

### ISSUE THREAD

**Issue by tfuetterer** [capacitor-community/sqlite#79]
Hi, 

I want to migrate from Cordova to Capacitor and have an existing Andoid app. But the db file does not have the SQLite.db extension, so I cannot connect to this with your plugin. Is there a way to do so?

Thanks in Advance

**Comment by jepiqueau** [comment]
hi, thanks for using the plugin. Well can't you rename your db to have the suffix SQLite.db and after that it will works. In a mean time, i will put this on my list of improvements, i will add a command to rename all the dbs in the database folders for iOS and Android. I will do this a bit later so in a meantime tell me if you do not succeed to rename your file

**Comment by tfuetterer** [comment]
Hi, thanks for the quick reply. I tried to copy the file, but with the capacitor FileSystem API, I was not able to access the databases folder in any way and I spend a whole day on this. Mayby you have expierience with this?

Maybe, instead of renaming the files, it would be better if you implement to copy the files, because then you have a backup of the db, just in case anything goes wrong =)

**Comment by jepiqueau** [comment]
@tfuetterer In which folder are your databases created with the cordova-plugin.? the process should be to copy the file from that folder to the database folder and rename them by adding the suffix SQLite. Up to you to manage the delete of the "cordova plugin" files later. Is that right?

**Comment by tfuetterer** [comment]
The database is actually in the same folder ("databases")

**Comment by jepiqueau** [comment]
@tfuetterer fix in 2.9.10 use new method `addSQLiteSuffix` and `deleteOldDatabases`

**Comment by jepiqueau** [comment]
@tfuetterer see https://github.com/capacitor-community/sqlite/blob/2.9.x/docs/MigratingCordovaDatabases.md for explanations

**Comment by tfuetterer** [comment]
Thank you very much for the help. I will try it as soon as possible.

**Comment by jepiqueau** [comment]
@tfuetterer Hi, i will close that issue to morrow if no news

**Comment by jepiqueau** [comment]
@tfuetterer Hi, i will close that issue to morrow if no news
