### ISSUE TITLE
Can this plugin used with ionic-storage?

### ISSUE THREAD

**Issue by ryaa** [capacitor-community/sqlite#80]
**Is your feature request related to a problem? Please describe.**
Ionic Storage (https://github.com/ionic-team/ionic-storage) can use cordova sqlite (https://github.com/storesafe/cordova-sqlite-storage) as a storage medium. Can this plugin replace cordova sqlite for usage with ionic storage?

**Describe the solution you'd like**
Use this plugin with ionic storage.

**Describe alternatives you've considered**
Cordova sqlite plugin https://github.com/storesafe/cordova-sqlite-storage

**Additional context**
N/A

**Comment by jepiqueau** [comment]
@ryaa  Ionic Storage is a  simple key-value Storage module. so you can use the capacitor-data-storage-sqlite `https://www.npmjs.com/package/capacitor-data-storage-sqlite` which i have developed for key-value storage. This one is more for a general database purpose. Thanks for looking to those plugins

**Comment by NLueg** [comment]
@jepiqueau I don't think that you got the main point of the question as I think I have the same question.
Ionic Storage use  `cordova-sqlite-storage` directly out of the box if the plugin is installed. 
Is this the same with this plugin? Does ionic-storage use this plugin out of the box if it is installed?

**Comment by jepiqueau** [comment]
@ryaa  @NLueg The answer is no better talk to the Ionic team. I am not from Ionic. Sorry for this
