### ISSUE TITLE
sqlite undefined. retrieveConnection not working | Ionic Vue | function call

### ISSUE THREAD

**Issue by Snogo** [capacitor-community/sqlite#81]
first of all thank you very much for the package. I can successfully create my sqlite database and insert rows and access them and load them all into a page (ion-list). this works perfect. now however I want to implement a filter functionality. with a selection of an ion-select the data should be filtered via an WHERE query. when I try to do that I get the following error:

**Uncaught (in promise) TypeError: Cannot read property 'retrieveConnection' of undefined**

this happens when I call the same file (same function. different parameter) as the one in which I create the connection but also happens when I put it in a separate file. I have all the proper lines in my main.ts (described at https://github.com/jepiqueau/vue-sqlite-app-starter ) and I use the lines 
```
const app = getCurrentInstance();
const sqlite = app?.appContext.config.globalProperties.$sqlite;
```
does it has to be in a component or page or can it also be in a function only Typescript file? 
the following shortened code looks like this:

```
import { ref, onMounted, getCurrentInstance } from 'vue';
import { createTablesNoEncryption, importAllAnimals } from '@/utils/utils-init-db';
import { deleteDatabase } from '@/utils/utils-delete-db';

export function getAllAnimals(filterSize?: any) {

    const animals= ref<Animal[]>();
    const app = getCurrentInstance()
    const sqlite = app?.appContext.config.globalProperties.$sqlite;

    const initVDB = async () => {

        // initialize the connection
        const db = await sqlite
            .createConnection("vdb", false, "no-encryption", 1);

        // open db testNew
        let ret = await db.open();
        if (!ret.result) {
            return false;
        }

        // create tables in db
        ret = await db.execute(createTablesNoEncryption);
        if (ret.changes.changes < 0) {
            return false;
        }

        // add two users in db
        ret = await db.execute(importAllAnimals);
        if (ret.changes.changes < 0) {
            return false;
        }
        app?.appContext.config.globalProperties.$existingConn.setExistConn(true);
        return true;
    }
   
    const loadAnimals = async () => {

         // initialize the connection
         const db = await sqlite
         .createConnection("vdb", false, "no-encryption", 1);

         let ret: any = await deleteDatabase(db); //TODO: remove Line when RELEASE

         ret = await db.open();
            if (!ret.result) {
                console.log("error opening DB");
                return false;
            }
        
        ret = await db.query("SELECT * FROM animal");
    
        if(ret.values.length !== 33) { 
            await initVDB(); 
            ret = await db.query("SELECT * FROM animal");
            if(ret.values.length == 33) { 
                animals.value = ret.values;
                console.log("animals loaded");
            }else{
                console.log("error loading animals")
            }
        } else {
            animals .value = ret.values;
            console.log("animals loaded");
        }

      }

      const filterAnimal= async () => {

        //const animals= ref<Animal[]>();
        //const app = getCurrentInstance()
        //const sqlite = app?.appContext.config.globalProperties.$sqlite;

        // initialize the connection
        console.log("before connection");
        const db =  await sqlite.retrieveConnection("vdb");
        console.log("retrieved connection");

        let ret = await db.open();
        if (!ret.result) {
            console.log("error opening DB");
            //return false;
        }
       console.log("db for filtering opened");

       let where = " WHERE size>20";

       ret = await db.query("SELECT * FROM animal" + where);
       if(ret.values.length >= 0) {
           animals.value = ret.values;
           console.log("animals loaded");
       }
   }

    onMounted(async () => {
        if(filterSize == undefined){
          loadAnimals();
        }
    });

    if(filterSize != undefined){
        filterAnimal();
    }

    return animals;
}
```

Windows10. "@capacitor-community/sqlite": "^2.9.9". "vue-sqlite-hook": "^1.0.0". "@ionic/vue": "^5.4.0"
Samsung Galax S7. Android

**Comment by jepiqueau** [comment]
@Snogo I only test it from a component call by a view where i encapsulate the component into a Suspense for dealing with asynchroneous functions like this for the component `ExistingConnTest`
```
          <Suspense>
            <template #default>
              <ExistingConnTest />
            </template>
            <template #feedback>
              <div> Loading ... </div>
            </template>
          </Suspense>

```
I never test it like you do. Can you show how this function is called

**Comment by Snogo** [comment]
I see. here are the two code snippets of interest:

```
 <ion-select multiple="false" cancel-text="back" ok-text="ok" v-model="filterSize" @ionChange="onChange($event, filterSize)">
          <ion-select-option value="0">small</ion-select-option>
          <ion-select-option value="1">medium</ion-select-option>
          <ion-select-option value="2">large</ion-select-option>
        </ion-select>
 <ion-list>

...

         <Suspense>
         <ion-item :key="animal.id" v-for="animal in animals">
           <ion-label>
                <h2>{{ animal.name_dt }}</h2> 
              </ion-label>
         </ion-item>
         </Suspense>
        </ion-list>
```
and

```
 setup() {
    console.log("Animals setup");
    let animals = getAllAnimals();
    const filterSize = ref([]);
    const onChange = async (e: any, filter: any) => {
      filter = e.target.value;
      filterSize.value = filter;
      console.log(JSON.stringify(filterSize.value));
      animals = getAllAnimals(filterSize.value);
    }
     return { animals, filterSize, onChange }
  }, 
```

**Comment by jepiqueau** [comment]
@Snogo can you also share createTablesNoEncryption, importAllAnimals so i can try to reproduce. Would be in fact better if you can share the whole code on github

**Comment by jepiqueau** [comment]
@Snogo i do not see where you call initVDB, Would changing 
```
    if(filterSize != undefined){
        filterAnimal();
    }
```
by 
```
    if(filterSize != undefined){
       async () => {        
          filterAnimal();
      }
    }
```
make a difference

**Comment by Snogo** [comment]
you are right. should put it in `async `but then somehow filterAnimal is not called anymore (not console outputs)

and `initVDB `is called inside `loadAnimal ` if there is no data in the sqlite database
I send you an invitation to the GitHub

**Comment by jepiqueau** [comment]
@Snogo ok thanks

**Comment by jepiqueau** [comment]
@Snogo yes i did not saw it in a first look

if you do this can it solved
```
    onMounted(async () => {
        if(filterSize == undefined){
          loadAnimals();
        } else {
          filterAnimal()
        }
    });
```

**Comment by Snogo** [comment]
true. this is actually how I wanted it to be - but again `filterAnimal()` seems to be mysteriously not called anymore
maybe in the second function call in the same file in the LifeCycle `onMounted ` is not fired anymore (?)

**Comment by jepiqueau** [comment]
@Snogo Can you try this filterSize is a ref so

```
    onMounted(async () => {
        if(filterSize.value != undefined){
          filterAnimal(); 
        } else {
          loadAnimals();
        }
    });
```

**Comment by jepiqueau** [comment]
@Snogo i have try to implement your stuff in my app but it seems that the ion-select ionChange is not triggered so it never calls the filterAnimal

**Comment by Snogo** [comment]
> 
> 
> @Snogo Can you try this filterSize is a ref so
> 
> ```
>     onMounted(async () => {
>         if(filterSize.value != undefined){
>           filterAnimal(); 
>         } else {
>           loadAnimals();
>         }
>     });
> ```

I did but actually I give over `filterSize.value` in the parameter. thus it shouldn't be a ref anymore. I will also get a runtime error if I put that in the onMounted event for the first call of the function (loadAnimals)

> 
> 
> @Snogo i have try to implement your stuff in my app but it seems that the ion-select ionChange is not triggered so it never calls the filterAnimal

`ionChange `is triggered. it actually tells me the correctly selected value of the ion-select in the console - however the onMounted event is not triggered again (a second time after loading the data). this is strange

and I don't think I can code a different component based solution because inter alia of the nature of separation of ion-list and ion-select. do you have another idea? I guess I am using the Typescript function call wrongly (with onMounted) and then somehow the sqlite reference is not ready

**Comment by Snogo** [comment]
about the `onMounted `not firing. it makes sense according to the [Ionic Docs ](https://ionicframework.com/docs/vue/lifecycle): 

> Ionic Vue manages the lifetime of a page, certain events might not fire when you expect them to. For instance, mounted fires the first time a page is displayed, but if you navigate away from the page Ionic Framework might keep the page around in the DOM, and a subsequent visit to the page might not call mounted again. 

I now tried to close the sqlite connection everytime I finish doing something with the database before calling `filterAnimal` with no effect unfortunately. also the line `app?.appContext.config.globalProperties.$existingConn.setExistConn(true);` when trying to retrieve the connection also didn't make a change. everytime `filterAnimal ` gets called I get  **Uncaught (in promise) TypeError: Cannot read property 'createConnection' of undefined** because `sqlite `is undefined

**Comment by Snogo** [comment]
@jepiqueau I put it now all in the .vue file in it works! the file gets huge and its against the project structure but at least it works now. file this as solved for now. don't know why the function calls don't work

**Comment by jepiqueau** [comment]
@Snogo i finally got it look at https://github.com/jepiqueau/vue-sqlite-app-starter/tree/refactor/src/components/Animals it works wit a new version of the plugin 2.9.12 and a new version of the vue-sqlite-hook 1.0.1 Tell me if you like it

**Comment by Snogo** [comment]
@jepiqueau thank you very much
however i just tried to use your new code with mine but get this error
`Property 'isDBOpen' does not exist on type 'SQLiteDBConnection'`
I have updated to the new packages  plugin 2.9.12 and vue-sqlite-hook 1.0.1

**Comment by jepiqueau** [comment]
@Snogo Can you close the issue if everything work fine or i will close it to morrow

**Comment by Snogo** [comment]
I didn't use the same code structure as before for now but got no problems anymore with getting the SQLconnection so far with your fix. thus I will close this issue
