### ISSUE TITLE
sqlite undefined in async method | Ionic Vue

### ISSUE THREAD

**Issue by Snogo** [capacitor-community/sqlite#86]
maybe related to issue #81 

in any async method inside the method block of the composition api `sqlite ` seems `undefined ` like here :

```
methods: {
 async getDBReady(): Promise<SQLiteDBConnection | null>{
           const app = getCurrentInstance();
          const sqlite = app?.appContext.config.globalProperties.$sqlite;  //always gets undefined
            const db = await sqlite.createConnection("vdb");
            const ret = await db.open();
            if (!ret.result) {
                return null;
            }   
        return db;
      }
}
```
Windows10. "@capacitor-community/sqlite": "^2.9.13". "vue-sqlite-hook": "^1.0.1". "@ionic/vue": "^5.5.4"
Samsung Galax S7. Android

**Comment by Snogo** [comment]
solved this by using the `sqlite` from the `setup`. so like 
` const db = await **this**.sqlite.createConnection("vdb");`
which is actually the better and probably propper way to do it. thus I don't know if it's an isssue

**Comment by jepiqueau** [comment]
@Snogo i think the problem is with `const sqlite= ... ` that should be in the setup() method and you can pass it as argument of your methods

**Comment by Snogo** [comment]
@jepiqueau true. I will close this issue
