### ISSUE TITLE
executeSet on android not accept null values

### ISSUE THREAD

**Issue by danielprrazevedo** [capacitor-community/sqlite#89]
**Describe the bug**
When I try to insert a null value in a field that should accept null by executeSet, it tells me that it is not supported. (in the list of accepted values, null appears as a possible value)

**To Reproduce**
After creating your table in a field marked as null, try inserting, via executeSet, a null value in a field that should accept nulls

In Android Studio
```Error executeSet: Cannot bind null at index 16 Supported types: null, byte[], float, double, long, int, short, byte, string```

**Expected behavior**
The same behavior as the run method, if I get the same value passing through run, it runs without problems

**Screenshots**
![image](https://user-images.githubusercontent.com/20153661/109972120-bd418c80-7cd5-11eb-801a-9172c5ad83b0.png)

**Smartphone (please complete the following information):**

- Device: Pixel 3 (emulator)
- OS: Android 10
- Browser Webview (Capacitor)

**Additional context**
I'm using version 2.9. * And I didn't get to test it in 3. * - beta

**Comment by jepiqueau** [comment]
@danielprrazevedo Can you share the table schema and the executeSet statement so i can test it easily as i am quite busy on something else right now

**Comment by jepiqueau** [comment]
@danielprrazevedo I did reproduce it so i will fix it in the next release

**Comment by jepiqueau** [comment]
@danielprrazevedo  this is fixed in release 3.0.0-beta.5

**Comment by danielprrazevedo** [comment]
@jepiqueau 
Sorry for my delay
will versions 2.9. * not receive any more updates?

**Comment by jepiqueau** [comment]
@danielprrazevedo I will provide one more update for fixing this issue may be to morrow as i do not have time to work to day

**Comment by jepiqueau** [comment]
@danielprrazevedo Can you show me your set statement and value In fact i can make it in Android by having `,,` or `,null,` in the set values but this does not work in iOS. So why did you put this field in the set statement if you do not want to give a value. If you do not define it in the statement the store value for the fields which are not given is NULL

**Comment by jepiqueau** [comment]
@danielprrazevedo this is fixed in 2.9.14
