### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by candreapps** [capacitor-community/sqlite#92]
**Is your feature request related to a problem? Please describe.**
Browser is not supported.

**Describe the solution you'd like**
I would like to open my App in Browser and have the same behavior as on Mobile.

**Describe alternatives you've considered**
For Cordova Browser support seems to work https://github.com/storesafe/cordova-sqlite-storage

**Comment by jepiqueau** [comment]
@candreapps Thanks for looking at the plugin. i already mentioned several times that i will not develop the browser support. The developer can use the Electron plugin part for this and then the database will be stored on disk. It will ask  a lot of work for storing a database in memory; `sql.js` uses a virtual database file stored in memory. So i do not really see the point of doing all this effort.

**Comment by candreapps** [comment]
Thank you for your quick reply. I found your statement on that in issue #2. Sorry for any inconvenience.

**Comment by jepiqueau** [comment]
@candreapps No problem, You are welcome May be you would like to contribute and develop it yourself for the benefit of the capacitor community. Many developers asked for it, In that case make a PR and i will have a look.

**Comment by candreapps** [comment]
Unfortunately I'm not that good at programming yet :)
