### ISSUE TITLE
Db export fails to export column of type 'REAL'

### ISSUE THREAD

**Issue by accron-1** [capacitor-community/sqlite#94]
**Describe the bug**
Exporting the db with `exportToJson({jsonexportmode:'full'})` fails to export column of type `REAL`.

**To Reproduce**
Create a db with a table that has a column type of `REAL`, and export the data.

**Expected behavior**
The exported data should also contain the data from column of type `REAL`.

**Screenshots**
Given the schema:
![db_schema](https://user-images.githubusercontent.com/14213307/110961826-83652b80-8350-11eb-80f7-6f23bcd43244.png)

And the following table rows:
![table_content](https://user-images.githubusercontent.com/14213307/110961864-8cee9380-8350-11eb-8e16-8cdabb7c62be.png)

This is what is exported:
![table_exported](https://user-images.githubusercontent.com/14213307/110961888-911ab100-8350-11eb-9178-a517f5e24a95.png)

Note that the `weight` column data is missing in the last picture (the values, `11`, `12`, `13` from picture 2).

**Desktop (please complete the following information):**
- OS: Ubuntu

**Smartphone (please complete the following information):**
Android Emulator

**Additional context**
I'm assuming that it has to do with the column being of type `REAL`, as it's the only difference compared to the other columns.

This used to work in a previous version of the plugin, but there seems to have occurred a regression at some point.

Plugin version: 2.9.13

**Comment by jepiqueau** [comment]
@accron-1 I will have a look

**Comment by jepiqueau** [comment]
@accron-1 Well it is working fine.
your entry for the import should be :
```
  export const dataToImport94: any = {
    database : "db-from-json94",
    version : 1,
    encrypted : false,
    mode : "full",
    tables :[
        {
            name: "reps",
            schema: [
                {column:"id", value: "INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE"},
                {column:"fk_workoutexercices", value:"INTEGER NOT NULL"},
                {column:"weight", value:"REAL NOT NULL"},
                {column:"reps", value:"INTEGER NOT NULL"},
                {column:"rest", value:"INTEGER NOT NULL"},
                {column:"note", value:"TEXT"},
            ],
            values: [
                [1,1,11,21,31,"NULL"],
                [2,1,12,22,32,"NULL"],
                [3,1,13,23,33,"NULL"],
            ]
        },
    ]
  };

```

**Comment by jepiqueau** [comment]
@accron-1 you can see it working in `https://github.com/jepiqueau/angular-sqlite-app-starter/tree/refactor`

**Comment by accron-1** [comment]
Thanks for looking into it!
However, that's not the output I get:
```javascript
{
  "database": "gymrat",
  "encrypted": false,
  "mode": "full",
  "tables": [{
	  "name": "reps",
	  "schema": [
		{"column": "id","value": "INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE"},
		{"column": "fk_workoutexercises","value": "INTEGER NOT NULL"},
		{"column": "weight","value": "REAL NOT NULL"},
		{"column": "reps","value": "INTEGER NOT NULL"},
		{"column": "rest","value": "INTEGER NOT NULL"},
		{"column": "note","value": "TEXT"},
		{"value": "REFERENCES workoutexercises(id) ON DELETE CASCADE ","foreignkey": "fk_workoutexercises"}
	  ],
	  "values": [
		[1,1,21,31,"NULL"],
		[2,1,22,32,"NULL"],
		[3,1,23,33,"NULL"],
	  ]
	},]
};
```
So there seems to be something else at play here.

My overall db schema is more complex of course:
![schema](https://user-images.githubusercontent.com/14213307/111062528-a1926f00-84a9-11eb-854e-08c0dfaaa693.png)



Also, this was one of the first features that I added and tested in my app, about a year ago, and it did work with an older version of the plugin.
I didn't try it since then, but as I have just upgraded my app from Vue2 -> Vue3 I re-tested everything to make sure nothing is broken in the Vue code, and this is how I discovered it.

**Comment by accron-1** [comment]
I just tried changing `REAL` to `INTEGER` for the table schema, to see if it makes a difference, and sure enough everything works as expected:

![export_integer](https://user-images.githubusercontent.com/14213307/111063707-85de9700-84b0-11eb-937f-7dca62cd39ae.png)

So it definitely has something to do with the col type being `REAL`.

**Comment by accron-1** [comment]
> I didn't try it since then, but as I have just upgraded my app from Vue2 -> Vue3 I re-tested everything to make sure nothing is broken in the Vue code, and this is how I discovered it.

To clarify: between the first implementation, when it worked, and now, I have upgraded the plugin on a few occasions, but I never tried the export-feature between upgrades. Therefore I can't say at what version it stopped working.

**Comment by jepiqueau** [comment]
@accron-1 If you can make a small replicate of the app showing the problem and share it on github i could have a look otherwise it would be difficult for me to grab what is wrong as i could not replicate it

**Comment by accron-1** [comment]
I'm not sure if I can break down the app to anything smaller.
But in the meantime I've come up with another test: I set the col type to `INTEGER` (which we've seen seems to work), but insert a float instead (Sqlite doesn't enforce types, so it's no problem). Thus:

These values (note that `Weight` is now a decimal number):
![img1](https://user-images.githubusercontent.com/14213307/111069209-50e03d80-84cc-11eb-87ea-9478699d8b47.png)

are represented as this in the JS and app:
![img2](https://user-images.githubusercontent.com/14213307/111069239-6f463900-84cc-11eb-8296-1cdfeea22a8e.png)

Note that the db and app work fine with the decimal numbers.

However, the export still fails to include the `weight` column:
![img3](https://user-images.githubusercontent.com/14213307/111069254-7ff6af00-84cc-11eb-93e5-fa6fa4e460d8.png)

So it's not only an issue of the col being defined as `REAL`, but it also seems to be a problem that the value is a float.

Maybe this can give you some clue as to what the problem might be.

**Comment by jepiqueau** [comment]
@accron-1 I tested it on android and ios in an angular app using the @capacitor-community/sqlite@latest which is the 2.9.13 .
i bound the value according to the type which can be TEXT, REAL, INTEGER, BLOB and that is it so FLOAT is not a sqlite3 type.
if you cannot split the application in a small one and share it i could not really help as it works with my test app.

**Comment by jepiqueau** [comment]
@accron-1 look at `https://www.sqlite.org/datatype3.html` for the supported types

**Comment by accron-1** [comment]
I'm aware that a `FLOAT` type doesn't exist in Sqlite, I was merely illustrating another potential issue.

What test can I do that will give you more info regarding this issue?

**Comment by accron-1** [comment]
Another difference between your export and mine is that yours contains the version number: `version : 1`
My export doesn't have that, as you can see above.
I noticed that from the start, but thought that I hadn't defined the version in my db script. I checked now and I do have it:
`PRAGMA user_version = 1;`
It's more evidence that our versions don't behave the same.

**Comment by jepiqueau** [comment]
@accron-1  ok show me your package.json file

Did you run `npx cap sync` before building your app.
Show me your `MainActivity.java` file 
Was your database created with an `importFromJson` process or through standard use of SQLite statements (Execute, ExecuteSet, Run ...)
if `importFromJson` give me the json object  as you enter it 
otherwise show me the statements.

Can run this statement with query and give me the result in the sql field
```
SELECT name,sql FROM sqlite_master WHERE type = 'table' AND name='reps';
```
Can you run this statement  with execute or run and give me the result
```
PRAGMA table_info("users");
```

**Comment by jepiqueau** [comment]
@accron-1 In android studio, can you open your app
open the folder `capacitor-community-sqlite`
open the folder java and the subfolder `com.getcapacitor.community.database.sqlite.SQLite.ImportExportJson` 
open the file `UtilsJson.java`
go to line 158
`            if (type.equals("REAL") && (value instanceof Double || value instanceof Integer)) ret = true;`
change it with 
`            if (type.equals("REAL") && (value instanceof Double || value instanceof Float || value instanceof Integer)) ret = true;`

clean the project and rebuild it
tell me if it does change something and give you the right result

**Comment by accron-1** [comment]
When I did `npx cap sync` I saw that I was actually still stuck on v. 2.4: I had updated the `package.json` but had failed to run npx. I have now upgraded to 2.9.13 (according to `npx cap ls`).

That certainly explains the different output for you and me, but I haven't been able to verify it yet.

To request storage permission we used to do:
```javascript
const handlerPermissions = CapacitorSQLite.addListener(
        'androidPermissionsRequest', async (data) => {
          if(data.permissionGranted === 1) {
            ....
          }
      });
      CapacitorSQLite.requestPermissions();
```
But not anymore it seems. What's the new way of doing this? I couldn't find anything in the docs.

**Comment by jepiqueau** [comment]
@accron-1 this i not required so it has been removed on the request of some developers. Yes it is important that you `npx cap sync` each time you change the version of the plugin and also when you upgrade capacitor/core ...
Now is it working?

**Comment by accron-1** [comment]
I had to adapt all my db calls to the new api, so it took a while.

The exported data now contains the `REAL` field, so the export and import finally works as expected! Thanks for mentioning the `npx sync`.

Question: will the api's change again in the upcoming v.3?

**Comment by jepiqueau** [comment]
@accron-1 The API will not change except that the call to db method will have to be done through a try...catch to get back the error messages which was requested by a lot of developers. You can see it in `https://github.com/capacitor-community/sqlite/blob/master/docs/Ionic-Vue-Usage.md` . I know that it can be a bit frustrating but i just make changes when developers ask for it and there is a value for the capacitor community. But everything is clearly documented and demonstrated in app starters depending on the framework. Hope this clarify. i wish you all the best for your app. The 2.9.x series will be stopped to be maintained as soon as Capacitor 3 will be released. To day it is in Release Candidate.

**Comment by jepiqueau** [comment]
Can you close the issue when everything has been finally tested on your site
