### ISSUE TITLE
Max size of .db file , this plugin can handle ??

### ISSUE THREAD

**Issue by pratiksan45** [capacitor-community/sqlite#96]

**Comment by jepiqueau** [comment]
@pratiksan45 see sqlite3 doc `https://www.sqlite.org/limits.html`

**Comment by jepiqueau** [comment]
@pratiksan45 Any news ? Did you have an issue or was it just a question? If no answer from you in the two coming days, I will close the issue.

**Comment by pratiksan45** [comment]
Hi @jepiqueau  ! yes , It was a question and I got clarified from the link you provided .   
Thanks .
