### ISSUE TITLE
3.0.0-beta.4 - ImportFromJson fails when importing JSON created using the exportToJson

### ISSUE THREAD

**Issue by mpat8121** [capacitor-community/sqlite#97]
**Describe the bug**
SQLite Plugin Version: 3.0.0-beta.4.
When utilising the importFromJson method to import a JSON file that has been previously exported from the same app/database, the import fails due to the trigger construction.

**To Reproduce**
Steps to reproduce the behaviour:

1. Run an app that initialises a database
2. Run the exportToJson method to export the database to a file
3. Run the importToJson method to import the file created in 2.
4. The import fails with a standard error message

**Expected behaviour**
The import of an export created inside the app should succeed

**Smartphone (please complete the following information):**

- Device: Android Emulator & iOS Simulator
- OS: iOS 14.4, Android 11.0

**Additional context**
The createTableTriggers method in ImportFromJson.java & ImportFromJson.swift build the CREATE TRIGGER statement for the ON UPDATE last_modified column trigger, but the triggerTimeevent already contains the "ON" SQL command so it does not need to be appended a second time. This causes a SQL syntax error and the import fails.
Replace the "ON" with an empty space " " resolves the issue:
JAVA: [Line 261](https://github.com/capacitor-community/sqlite/blob/9c81325eb86517f78ab3557c65144cebe4da1152/android/src/main/java/com/getcapacitor/community/database/sqlite/SQLite/ImportExportJson/ImportFromJson.java#L261) -> .append(" ON ") becomes .append(" ")
SWIFT: [Line 253](https://github.com/capacitor-community/sqlite/blob/9c81325eb86517f78ab3557c65144cebe4da1152/ios/Plugin/ImportExportJson/ImportFromJson.swift#L253) stmt.append(" ON ") becomes stmt.append(" ")
I am unsure if this change has other implications during database initialisation elsewhere.

**Comment by jepiqueau** [comment]
@mpat8121 I know, i have to implement all the fixes to issues from 2.9.9 to 2.9.13 into 3.0.0. I will work on this now and implement also capacitor3.0-rc. So be patient it will come.

**Comment by mpat8121** [comment]
@jepiqueau Ok. There is no rush on a fix/update as we have the import temporarily working with the change mentioned above.

**Comment by jepiqueau** [comment]
@mpat8121 Many thanks for your understanding and patience. it will come i am working on.

**Comment by jepiqueau** [comment]
@mpat8121 In fact it is not the importFromJson createTableTriggers which is wrong the `.append(" ON ")`should stay. It is the ExportToJson which is wrong in the getTriggers the timeEvent should not contains the " ON" so just before
```
                        jsonRow.setName(name);
                        jsonRow.setTimeevent(timeEvent);
```
you must include 
```
                        if(timeEvent.toUpperCase().endsWith(" ON")) {
                            timeEvent = timeEvent.substring(0, timeEvent.length() - 3);
                        }

```
this is for the Android plugin

**Comment by mpat8121** [comment]
@jepiqueau That does resolve the issue when importing a new export (generated after the above fix), but anything that has been exported prior to this fix is unable to be imported. Should there be a way to import previous exports?

**Comment by jepiqueau** [comment]
@mpat8121 Are you storing your successive exports? What are the reason for if i may. It seems that you are using the import/export json object in a way i never thought about it so i am interested to know. I think in previous exports to be able to use them you need to loop through and remove the ` ON` from the timeEvent. In fact it was a mistake to have it on the timeEvent string

**Comment by jepiqueau** [comment]
@mpat8121 i will make the following changes in ImportFromJson for compatibility on top of the one done in the exportToJson
```
    private ArrayList<String> createTableTriggers(ArrayList<JsonTrigger> mTriggers, String tableName) {
        ArrayList<String> statements = new ArrayList<>();
        for (int j = 0; j < mTriggers.size(); j++) {
            String timeEvent = mTriggers.get(j).getTimeevent();
            if(timeEvent.toUpperCase().endsWith(" ON")) {
                timeEvent = timeEvent.substring(0, timeEvent.length() - 3);
            }

            StringBuilder sBuilder = new StringBuilder("CREATE TRIGGER IF NOT EXISTS ")
                .append(mTriggers.get(j).getName())
                .append(" ")
                .append(timeEvent)
                .append(" ON ")
                .append(tableName)
                .append(" ");
            if (mTriggers.get(j).getCondition() != null) {
                sBuilder.append(mTriggers.get(j).getCondition()).append(" ");
            }
            sBuilder.append(mTriggers.get(j).getLogic());
            String stmt = sBuilder.toString();
            statements.add(stmt);
        }
        return statements;
    }
```
The same modifications to the `exportToJson` and `importToJson` will be done for iOS and Electron.

**Comment by jepiqueau** [comment]
@mpat8121 this is fixed in release 3.0.0-beta.5

**Comment by mpat8121** [comment]
@jepiqueau The use case is to allow a user of the app to back-up their data from the device to a file (saved to another app or onto their device) and then to be able to restore the app to that state by importing the file.
It does mean that we relinquish control of which version of both the app itself and this plugin that the data export is generated from so backward/forward compatibility is required. The app handles as much of the data transformation as possible.

That being said, the changes you have made in beta.5 have improved this significantly so I will close this issue.
As always, thanks for your efforts!

**Comment by jepiqueau** [comment]
@mpat8121 Thanks for the sharing and do not hesitate if you find something else, it will help to improve the product and be a benefit for the capacitor-community developers
