### ISSUE TITLE
query a database via a search bar

### ISSUE THREAD

**Issue by candreapps** [capacitor-community/sqlite#98]
**Is your feature request related to a problem? Please describe.**
Missing documentation.

**Describe the solution you'd like**
A simple example of using this plugin to query a database via a search bar.

**Comment by jepiqueau** [comment]
@candreapps Your question is not related to plugin features but more on the application site. Yes it would be nice to have that but it is depending on the framework used. I am to busy on maintaining my plugins for the time being with the move to Capacitor 3 imminent to spend time on this. You may look at this `https://jsmobiledev.com/article/searchbar-firebase` and replace firebase by call to the plugin.

**Comment by jepiqueau** [comment]
@candreapps Did you find a solution ? if yes can you close this issue

**Comment by candreapps** [comment]
yes, my solution was to use json files instead.
