### ISSUE TITLE
To where copyFromAssets() copy db files

### ISSUE THREAD

**Issue by ncham** [capacitor-community/sqlite#99]
Inside copyFromAssets() method, to which location db files are copied in Android and iOS?
Is it possible to access(open) that db file by using _ionic-native/sqlite_ also?

**Comment by jepiqueau** [comment]
@ncham as mentioned in the doc 
```
### Android

- **data/data/YOUR_PACKAGE/databases**

### IOS

- **in the Document folder of YOUR_APPLICATION**
```
No idea if it is compatible with ` ionic-native/sqlite`

**Comment by jepiqueau** [comment]
@ncham having look at `https://www.positronx.io/ionic-sqlite-database-crud-app-example-tutorial/` and convert it to the use of capacitor, the database location are if you use the `default` location
```
### Android
 - data/data/YOUR_PACKAGE/databases
 so it is the same location

### IOS
 - Library/LocalDatabase folder of YOUR_APPLICATION
 so it is not the same location

I will have  to modify the `addSQLiteSuffix` method to allow for this location

**Comment by ncham** [comment]
@jepiqueau When copying using copyFromAssets(), does the database is suffixed with SQLite?
ex: my_db_name.db -> my_db_nameSQLite.db

**Comment by jepiqueau** [comment]
@ncham Yes in order to be compatible with the plugin
on iOS the "default" location is Documents under the application
on Android the "default" location is databases under the application
on Electron the "default" location is Databases/YOUR_APPLICATION_NAMEin the Home directory

**Comment by jepiqueau** [comment]
@ncham Any news? Did you finally make it working ? if yes can you close the issue

**Comment by ncham** [comment]
> on iOS the "default" location is Documents under the application
Since the .db file is in Documents folder, is it visible to iTunes or backed up by iCloud?

**Comment by jepiqueau** [comment]
@ncham i could not answer i do not have an iOS device. i just test the plugin on simulator. test it on your side

**Comment by jepiqueau** [comment]
@ncham Any news from your side or i will close the issue
